# Mô hình 3 - LSTM Sequence-to-Vector t+1 đến t+24

LSTM nhận chuỗi quan sát 72 giờ gần nhất và trả về đồng thời vector 24 giá trị PM2.5
tương lai. Khác với 24 XGBoost độc lập, kiến trúc này chia sẻ biểu diễn giữa các
horizon nên có khả năng học quan hệ của cả quỹ đạo dự báo.

Mô hình dùng MSE làm loss, Adam làm optimizer, theo dõi RMSE và MAE trên Train và
Validation, có Early Stopping, ReduceLROnPlateau, Dropout và L2 regularization.

In [1]:
from pathlib import Path
import json
import random
from typing import Any

import joblib
import matplotlib.pyplot as plt
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "mathtext.fontset": "dejavusans",
    "axes.unicode_minus": False,
})
import numpy as np
import pandas as pd
from IPython.display import Markdown, display
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# Nhận diện project bằng cấu trúc, không phụ thuộc tên thư mục tạm của project.
CURRENT_DIR = Path.cwd().resolve()
SEARCH_DIRS = [CURRENT_DIR, CURRENT_DIR.parent]
SEARCH_DIRS.extend(path for path in CURRENT_DIR.iterdir() if path.is_dir())
PROJECT_CANDIDATES = []
for candidate in SEARCH_DIRS:
    data_file = candidate / "data" / "processed" / "pm25_training_data_enriched.csv"
    notebook_marker = candidate / "model" / "0_multihorizon_data_preparation.ipynb"
    if notebook_marker.exists() and data_file.exists():
        resolved = candidate.resolve()
        if resolved not in PROJECT_CANDIDATES:
            PROJECT_CANDIDATES.append(resolved)

if len(PROJECT_CANDIDATES) == 1:
    PROJECT_ROOT = PROJECT_CANDIDATES[0]
elif not PROJECT_CANDIDATES:
    raise FileNotFoundError(
        "Không tìm thấy project chứa đồng thời model và "
        "data/processed/pm25_training_data_enriched.csv."
    )
else:
    raise RuntimeError(
        "Có nhiều project phù hợp; hãy mở Jupyter tại đúng thư mục gốc cần chạy: "
        + ", ".join(str(path) for path in PROJECT_CANDIDATES)
    )

MODEL_DIR = PROJECT_ROOT / "model"
RESULTS_DIR = MODEL_DIR / "results"
CANDIDATES_DIR = MODEL_DIR / "candidates"
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "pm25_training_data_enriched.csv"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
CANDIDATES_DIR.mkdir(parents=True, exist_ok=True)

HORIZONS = np.arange(1, 25, dtype=int)
TARGET_COLUMNS = [f"target_pm25_t_plus_{h}" for h in HORIZONS]
MAX_HORIZON = int(HORIZONS.max())

POLLUTANT_FEATURES = ["pm25", "pm10", "o3", "no2", "so2", "co"]
WEATHER_FEATURES = [
    "temp", "humidity", "wind_speed", "wind_dir", "precip", "pressure", "cloud_cover"
]
TEMPORAL_FEATURES = ["hour", "day_of_week", "month", "is_weekend", "day_of_year"]
HISTORY_FEATURES = [
    "pm25_lag_1h", "pm25_lag_3h", "pm25_lag_6h", "pm25_lag_12h",
    "pm25_lag_24h", "pm25_lag_48h", "pm25_lag_72h", "pm25_lag_96h",
    "pm25_lag_120h", "pm25_lag_144h", "pm25_lag_168h",
    "pm25_roll_6h", "pm25_roll_12h", "pm25_roll_24h", "pm25_roll_72h",
    "pm25_roll_168h", "pm25_std_6h", "pm25_std_12h", "pm25_std_24h",
    "pm25_std_72h", "pm25_std_168h", "pm25_min_24h", "pm25_max_24h",
    "pm25_delta_1h", "pm25_delta_3h", "pm25_delta_24h",
    "pm25_roll_ratio_6h_24h", "pm25_roll_ratio_24h_72h",
    "pm25_same_hour_mean_7d", "pm25_same_hour_median_7d",
    "pm25_same_hour_std_7d", "pm25_same_hour_min_7d",
    "pm25_same_hour_max_7d", "pm25_same_hour_ratio_7d", "pm25_weekly_delta",
]
ENGINEERED_FEATURES = [
    "ventilation_index", "humid_stagnation", "rain_flag", "calm_wind",
    "high_humidity", "wind_x", "wind_y", "hour_sin", "hour_cos",
    "day_sin", "day_cos", "month_sin", "month_cos", "pm25_pm10_ratio",
    "no2_co_ratio",
]
NUMERIC_FEATURES = (
    POLLUTANT_FEATURES + WEATHER_FEATURES + TEMPORAL_FEATURES
    + HISTORY_FEATURES + ENGINEERED_FEATURES
)
CATEGORICAL_FEATURES = ["city", "season"]

print(f"Project root: {PROJECT_ROOT}")
print(f"Data: {DATA_PATH}")

Project root: D:\Project123456\aqi-vietnam\aqi-vietnam4
Data: D:\Project123456\aqi-vietnam\aqi-vietnam4\data\processed\pm25_training_data_enriched.csv

In [2]:
def make_multihorizon_frame(data: pd.DataFrame) -> pd.DataFrame:
    """Ghép chính xác PM2.5 tại t+1,...,t+24 theo city và timestamp."""
    frame = data.copy()
    frame["datetime"] = pd.to_datetime(frame["datetime"])
    frame = frame.sort_values(["city", "datetime"]).reset_index(drop=True)
    if frame.duplicated(["city", "datetime"]).any():
        raise ValueError("Dữ liệu có city/datetime trùng, không thể ghép target chính xác.")

    lookup = frame.set_index(["city", "datetime"])["pm25"]
    for horizon, column in zip(HORIZONS, TARGET_COLUMNS):
        keys = pd.MultiIndex.from_arrays(
            [frame["city"], frame["datetime"] + pd.to_timedelta(horizon, unit="h")],
            names=["city", "datetime"],
        )
        frame[column] = lookup.reindex(keys).to_numpy(dtype=float)
    frame["forecast_end"] = frame["datetime"] + pd.Timedelta(hours=MAX_HORIZON)
    return frame


def make_temporal_split(
    frame: pd.DataFrame,
    train_fraction: float = 0.70,
    validation_fraction: float = 0.15,
    purge_hours: int = MAX_HORIZON,
) -> dict[str, Any]:
    """Chia theo forecast_end để không có cửa sổ target giao nhau giữa các tập."""
    unique_ends = pd.Series(frame["forecast_end"].dropna().sort_values().unique())
    train_cut = pd.Timestamp(unique_ends.iloc[int(len(unique_ends) * train_fraction)])
    val_cut = pd.Timestamp(
        unique_ends.iloc[int(len(unique_ends) * (train_fraction + validation_fraction))]
    )
    purge = pd.Timedelta(hours=purge_hours)
    forecast_end = pd.to_datetime(frame["forecast_end"])
    masks = {
        "train": forecast_end < train_cut,
        "validation": (forecast_end >= train_cut + purge) & (forecast_end < val_cut),
        "test": forecast_end >= val_cut + purge,
    }
    if any(not mask.any() for mask in masks.values()):
        raise ValueError("Temporal split tạo ra ít nhất một tập rỗng.")
    return {
        "masks": masks,
        "train_cut": train_cut,
        "val_cut": val_cut,
        "purge_hours": purge_hours,
    }


def split_summary(frame: pd.DataFrame, split: dict[str, Any]) -> dict[str, Any]:
    summary: dict[str, Any] = {
        "strategy": "global chronological 70/15/15 by forecast_end with 24-hour purge gaps",
        "train_cut": split["train_cut"].isoformat(),
        "validation_cut": split["val_cut"].isoformat(),
        "purge_hours": int(split["purge_hours"]),
        "horizons": HORIZONS.tolist(),
    }
    for name, mask in split["masks"].items():
        part = frame.loc[mask]
        summary[name] = {
            "rows": int(len(part)),
            "source_start": part["datetime"].min().isoformat(),
            "source_end": part["datetime"].max().isoformat(),
            "forecast_end_start": part["forecast_end"].min().isoformat(),
            "forecast_end_end": part["forecast_end"].max().isoformat(),
        }
    return summary


def load_model_frame() -> tuple[pd.DataFrame, dict[str, Any], pd.DataFrame]:
    raw = pd.read_csv(DATA_PATH, low_memory=False)
    raw["datetime"] = pd.to_datetime(raw["datetime"])
    supervised = make_multihorizon_frame(raw)
    required = NUMERIC_FEATURES + CATEGORICAL_FEATURES + TARGET_COLUMNS
    missing_columns = sorted(set(required) - set(supervised.columns))
    if missing_columns:
        raise KeyError(f"Thiếu cột cần thiết: {missing_columns}")
    frame = supervised.dropna(subset=required).copy().reset_index(drop=True)
    split = make_temporal_split(frame)
    manifest = split_summary(frame, split)
    (RESULTS_DIR / "multihorizon_temporal_split.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return frame, split, raw


def build_feature_matrix(
    frame: pd.DataFrame,
    feature_columns: list[str] | None = None,
) -> pd.DataFrame:
    matrix = pd.get_dummies(
        frame[NUMERIC_FEATURES + CATEGORICAL_FEATURES],
        columns=CATEGORICAL_FEATURES,
        drop_first=False,
        dtype=float,
    )
    if feature_columns is None:
        return matrix.astype(np.float32)
    for column in feature_columns:
        if column not in matrix:
            matrix[column] = 0.0
    return matrix.reindex(columns=feature_columns, fill_value=0.0).astype(np.float32)


def regression_metrics(actual: Any, predicted: Any) -> dict[str, float]:
    y_true = np.asarray(actual, dtype=float)
    y_pred = np.clip(np.asarray(predicted, dtype=float), 0.0, None)
    return {
        "rmse_ug_m3": float(np.sqrt(mean_squared_error(y_true, y_pred))),
        "mae_ug_m3": float(mean_absolute_error(y_true, y_pred)),
        "r2": float(r2_score(y_true, y_pred)),
        "bias_ug_m3": float(np.mean(y_pred - y_true)),
    }


def prediction_frame(
    frame: pd.DataFrame,
    mask: pd.Series,
    predictions: np.ndarray,
    model_name: str,
    split_name: str,
) -> pd.DataFrame:
    part = frame.loc[mask].reset_index(drop=True)
    actual = part[TARGET_COLUMNS].to_numpy(dtype=float)
    predicted = np.clip(np.asarray(predictions, dtype=float), 0.0, None)
    if predicted.shape != actual.shape:
        raise ValueError(f"Prediction shape {predicted.shape} khác target shape {actual.shape}.")
    rows = len(part)
    output = pd.DataFrame({
        "model": model_name,
        "split": split_name,
        "city": np.repeat(part["city"].to_numpy(), len(HORIZONS)),
        "source_time": np.repeat(part["datetime"].to_numpy(), len(HORIZONS)),
        "horizon": np.tile(HORIZONS, rows),
        "actual_pm25": actual.reshape(-1),
        "predicted_pm25": predicted.reshape(-1),
    })
    output["target_time"] = pd.to_datetime(output["source_time"]) + pd.to_timedelta(
        output["horizon"], unit="h"
    )
    output["abs_error_ug_m3"] = np.abs(output["actual_pm25"] - output["predicted_pm25"])
    return output


def metric_tables(predictions: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    horizon_rows = []
    for (model, split_name, horizon), part in predictions.groupby(
        ["model", "split", "horizon"], sort=True
    ):
        horizon_rows.append({
            "model": model,
            "split": split_name,
            "horizon": int(horizon),
            "rows": int(len(part)),
            **regression_metrics(part["actual_pm25"], part["predicted_pm25"]),
        })
    by_horizon = pd.DataFrame(horizon_rows)

    city_rows = []
    for (model, split_name, city), part in predictions.groupby(
        ["model", "split", "city"], sort=True
    ):
        city_rows.append({
            "model": model,
            "split": split_name,
            "city": city,
            "rows": int(len(part)),
            **regression_metrics(part["actual_pm25"], part["predicted_pm25"]),
        })
    by_city = pd.DataFrame(city_rows)

    summary_rows = []
    for (model, split_name), part in predictions.groupby(["model", "split"], sort=True):
        horizon_part = by_horizon.loc[
            by_horizon["model"].eq(model) & by_horizon["split"].eq(split_name)
        ]
        summary_rows.append({
            "model": model,
            "split": split_name,
            "rows": int(len(part)),
            "mean_horizon_rmse_ug_m3": float(horizon_part["rmse_ug_m3"].mean()),
            "mean_horizon_mae_ug_m3": float(horizon_part["mae_ug_m3"].mean()),
            **{f"global_{key}": value for key, value in regression_metrics(
                part["actual_pm25"], part["predicted_pm25"]
            ).items()},
        })
    return by_horizon, by_city, pd.DataFrame(summary_rows)


def save_evaluation(model_slug: str, predictions: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    by_horizon, by_city, summary = metric_tables(predictions)
    predictions.to_csv(
        RESULTS_DIR / f"{model_slug}_multihorizon_predictions.csv",
        index=False,
        encoding="utf-8-sig",
    )
    by_horizon.to_csv(
        RESULTS_DIR / f"{model_slug}_multihorizon_by_horizon.csv",
        index=False,
        encoding="utf-8-sig",
    )
    by_city.to_csv(
        RESULTS_DIR / f"{model_slug}_multihorizon_by_city.csv",
        index=False,
        encoding="utf-8-sig",
    )
    summary.to_csv(
        RESULTS_DIR / f"{model_slug}_multihorizon_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )
    return by_horizon, by_city, summary

In [3]:
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import tensorflow as tf
from sklearn.preprocessing import StandardScaler

tf.keras.utils.set_random_seed(SEED)
try:
    tf.config.experimental.enable_op_determinism()
except Exception:
    pass

MODEL_NAME = "LSTM"
MODEL_SLUG = "lstm"
SEQUENCE_LENGTH = 72
BATCH_SIZE = 256
MAX_EPOCHS = 60
LSTM_FEATURES = [
    "pm25", "pm10", "o3", "no2", "temp", "humidity", "wind_speed",
    "pressure", "precip", "hour_sin", "hour_cos", "day_sin", "day_cos",
]

In [4]:
def make_lstm_sequences(
    frame: pd.DataFrame,
    scaled_features: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    windows = []
    targets = []
    endpoint_positions = []
    all_targets = frame[TARGET_COLUMNS].to_numpy(dtype=np.float32)

    for _, city_frame in frame.groupby("city", sort=False):
        positions = city_frame.index.to_numpy(dtype=int)
        values = scaled_features[positions]
        times = city_frame["datetime"].to_numpy(dtype="datetime64[h]")
        if len(city_frame) < SEQUENCE_LENGTH:
            continue
        city_windows = np.lib.stride_tricks.sliding_window_view(
            values, window_shape=SEQUENCE_LENGTH, axis=0
        ).transpose(0, 2, 1)
        ends = np.arange(SEQUENCE_LENGTH - 1, len(city_frame))
        starts = ends - SEQUENCE_LENGTH + 1
        continuous = (times[ends] - times[starts]) == np.timedelta64(SEQUENCE_LENGTH - 1, "h")
        valid_ends = ends[continuous]
        windows.append(city_windows[continuous])
        endpoint_positions.append(positions[valid_ends])
        targets.append(all_targets[positions[valid_ends]])

    return (
        np.concatenate(windows).astype(np.float32),
        np.concatenate(targets).astype(np.float32),
        np.concatenate(endpoint_positions).astype(int),
    )

In [5]:
model_frame, split, raw_data = load_model_frame()
encoded_city = pd.get_dummies(model_frame["city"], prefix="city", dtype=float)
feature_frame = pd.concat([model_frame[LSTM_FEATURES], encoded_city], axis=1)
lstm_feature_columns = feature_frame.columns.tolist()

train_row_mask = split["masks"]["train"].to_numpy()
feature_scaler = StandardScaler()
feature_scaler.fit(feature_frame.loc[train_row_mask])
scaled_features = feature_scaler.transform(feature_frame).astype(np.float32)

sequences, sequence_targets, endpoint_positions = make_lstm_sequences(
    model_frame, scaled_features
)
endpoint_split_masks = {
    name: mask.to_numpy()[endpoint_positions]
    for name, mask in split["masks"].items()
}

target_scaler = StandardScaler()
target_scaler.fit(sequence_targets[endpoint_split_masks["train"]].reshape(-1, 1))
scaled_targets = target_scaler.transform(sequence_targets.reshape(-1, 1)).reshape(
    sequence_targets.shape
).astype(np.float32)

x_train = sequences[endpoint_split_masks["train"]]
y_train = scaled_targets[endpoint_split_masks["train"]]
x_validation = sequences[endpoint_split_masks["validation"]]
y_validation = scaled_targets[endpoint_split_masks["validation"]]
x_test = sequences[endpoint_split_masks["test"]]
y_test = scaled_targets[endpoint_split_masks["test"]]
print(x_train.shape, x_validation.shape, x_test.shape)

(68616, 72, 16) (14679, 72, 16) (14679, 72, 16)

In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(SEQUENCE_LENGTH, x_train.shape[-1])),
    tf.keras.layers.LSTM(96, return_sequences=True, dropout=0.15),
    tf.keras.layers.LSTM(48, dropout=0.15),
    tf.keras.layers.Dense(
        64,
        activation="relu",
        kernel_regularizer=tf.keras.regularizers.l2(1e-4),
    ),
    tf.keras.layers.Dropout(0.20),
    tf.keras.layers.Dense(len(HORIZONS), activation="linear"),
], name="pm25_multihorizon_lstm")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="mse",
    metrics=[
        tf.keras.metrics.RootMeanSquaredError(name="rmse"),
        tf.keras.metrics.MeanAbsoluteError(name="mae"),
    ],
)
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "pm25_multihorizon_lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 72, 96)         │        43,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 48)             │        27,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         3,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 24)             │         1,560 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 75,928 (296.59 KB)

 Trainable params: 75,928 (296.59 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=10, restore_best_weights=True, min_delta=1e-4
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss", factor=0.5, patience=5, min_lr=1e-5, verbose=1
    ),
    tf.keras.callbacks.ModelCheckpoint(
        str(CANDIDATES_DIR / "lstm_multihorizon.keras"),
        monitor="val_loss",
        save_best_only=True,
    ),
]

history = model.fit(
    x_train,
    y_train,
    validation_data=(x_validation, y_validation),
    epochs=MAX_EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks,
    shuffle=False,
    verbose=1,
)
history_frame = pd.DataFrame(history.history)
history_frame.insert(0, "epoch", np.arange(1, len(history_frame) + 1))
history_frame.to_csv(
    RESULTS_DIR / "lstm_multihorizon_learning_curve.csv",
    index=False,
    encoding="utf-8-sig",
)

Epoch 1/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 41:46 9s/step - loss: 1.5130 - mae: 0.8199 - rmse: 1.2278

  2/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 538ms/step - loss: 1.3345 - mae: 0.7770 - rmse: 1.1502

  3/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 466ms/step - loss: 1.4575 - mae: 0.8169 - rmse: 1.2012

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 436ms/step - loss: 1.5033 - mae: 0.8366 - rmse: 1.2206

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 430ms/step - loss: 1.4963 - mae: 0.8402 - rmse: 1.2183

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 414ms/step - loss: 1.4756 - mae: 0.8367 - rmse: 1.2101

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 405ms/step - loss: 1.4791 - mae: 0.8379 - rmse: 1.2119

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 396ms/step - loss: 1.5250 - mae: 0.8501 - rmse: 1.2300

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 395ms/step - loss: 1.5476 - mae: 0.8562 - rmse: 1.2392

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 392ms/step - loss: 1.5550 - mae: 0.8585 - rmse: 1.2424

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 386ms/step - loss: 1.5519 - mae: 0.8579 - rmse: 1.2414

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 383ms/step - loss: 1.5525 - mae: 0.8593 - rmse: 1.2418

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 383ms/step - loss: 1.5660 - mae: 0.8618 - rmse: 1.2472

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 383ms/step - loss: 1.6024 - mae: 0.8693 - rmse: 1.2609

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 382ms/step - loss: 1.6311 - mae: 0.8755 - rmse: 1.2718

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 381ms/step - loss: 1.6598 - mae: 0.8817 - rmse: 1.2825

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 377ms/step - loss: 1.6894 - mae: 0.8880 - rmse: 1.2935

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 373ms/step - loss: 1.7132 - mae: 0.8929 - rmse: 1.3024

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 373ms/step - loss: 1.7368 - mae: 0.8978 - rmse: 1.3111

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 372ms/step - loss: 1.7564 - mae: 0.9018 - rmse: 1.3184

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 373ms/step - loss: 1.7712 - mae: 0.9049 - rmse: 1.3240

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 372ms/step - loss: 1.7838 - mae: 0.9078 - rmse: 1.3288

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 369ms/step - loss: 1.7952 - mae: 0.9107 - rmse: 1.3331

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 368ms/step - loss: 1.8046 - mae: 0.9134 - rmse: 1.3367

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 369ms/step - loss: 1.8117 - mae: 0.9156 - rmse: 1.3395

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 367ms/step - loss: 1.8178 - mae: 0.9175 - rmse: 1.3419

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 365ms/step - loss: 1.8216 - mae: 0.9188 - rmse: 1.3434

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 364ms/step - loss: 1.8236 - mae: 0.9197 - rmse: 1.3443

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 362ms/step - loss: 1.8248 - mae: 0.9204 - rmse: 1.3449

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 360ms/step - loss: 1.8243 - mae: 0.9206 - rmse: 1.3449

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 358ms/step - loss: 1.8224 - mae: 0.9204 - rmse: 1.3443

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 357ms/step - loss: 1.8198 - mae: 0.9200 - rmse: 1.3434

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 357ms/step - loss: 1.8167 - mae: 0.9195 - rmse: 1.3423

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 356ms/step - loss: 1.8130 - mae: 0.9189 - rmse: 1.3411

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 355ms/step - loss: 1.8095 - mae: 0.9184 - rmse: 1.3398

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 354ms/step - loss: 1.8053 - mae: 0.9178 - rmse: 1.3383

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 352ms/step - loss: 1.8010 - mae: 0.9171 - rmse: 1.3368

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 350ms/step - loss: 1.7962 - mae: 0.9162 - rmse: 1.3350

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 349ms/step - loss: 1.7911 - mae: 0.9153 - rmse: 1.3331

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 349ms/step - loss: 1.7857 - mae: 0.9144 - rmse: 1.3311

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 350ms/step - loss: 1.7807 - mae: 0.9136 - rmse: 1.3293

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 350ms/step - loss: 1.7754 - mae: 0.9128 - rmse: 1.3273

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 350ms/step - loss: 1.7700 - mae: 0.9119 - rmse: 1.3253

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 351ms/step - loss: 1.7651 - mae: 0.9112 - rmse: 1.3234

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 351ms/step - loss: 1.7600 - mae: 0.9105 - rmse: 1.3215

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 351ms/step - loss: 1.7546 - mae: 0.9096 - rmse: 1.3195

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 353ms/step - loss: 1.7497 - mae: 0.9088 - rmse: 1.3176

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 354ms/step - loss: 1.7444 - mae: 0.9079 - rmse: 1.3156

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 357ms/step - loss: 1.7388 - mae: 0.9068 - rmse: 1.3134

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 357ms/step - loss: 1.7331 - mae: 0.9057 - rmse: 1.3112

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 357ms/step - loss: 1.7274 - mae: 0.9045 - rmse: 1.3090

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 356ms/step - loss: 1.7215 - mae: 0.9033 - rmse: 1.3067

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 354ms/step - loss: 1.7156 - mae: 0.9020 - rmse: 1.3044

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 353ms/step - loss: 1.7101 - mae: 0.9009 - rmse: 1.3023

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 352ms/step - loss: 1.7045 - mae: 0.8997 - rmse: 1.3001

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 352ms/step - loss: 1.6991 - mae: 0.8985 - rmse: 1.2980

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 352ms/step - loss: 1.6937 - mae: 0.8972 - rmse: 1.2959

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 351ms/step - loss: 1.6883 - mae: 0.8960 - rmse: 1.2937

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 350ms/step - loss: 1.6832 - mae: 0.8949 - rmse: 1.2917

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 349ms/step - loss: 1.6780 - mae: 0.8937 - rmse: 1.2897

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 348ms/step - loss: 1.6730 - mae: 0.8926 - rmse: 1.2877

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 346ms/step - loss: 1.6680 - mae: 0.8915 - rmse: 1.2857

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 345ms/step - loss: 1.6630 - mae: 0.8904 - rmse: 1.2837

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 344ms/step - loss: 1.6579 - mae: 0.8892 - rmse: 1.2817

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 343ms/step - loss: 1.6527 - mae: 0.8880 - rmse: 1.2796

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 342ms/step - loss: 1.6474 - mae: 0.8868 - rmse: 1.2775

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 341ms/step - loss: 1.6422 - mae: 0.8855 - rmse: 1.2754

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 340ms/step - loss: 1.6369 - mae: 0.8843 - rmse: 1.2733

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 339ms/step - loss: 1.6318 - mae: 0.8830 - rmse: 1.2712

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 337ms/step - loss: 1.6268 - mae: 0.8819 - rmse: 1.2692

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 337ms/step - loss: 1.6220 - mae: 0.8807 - rmse: 1.2673

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 336ms/step - loss: 1.6173 - mae: 0.8796 - rmse: 1.2654

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 335ms/step - loss: 1.6126 - mae: 0.8785 - rmse: 1.2635

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 334ms/step - loss: 1.6082 - mae: 0.8775 - rmse: 1.2617

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 333ms/step - loss: 1.6039 - mae: 0.8765 - rmse: 1.2599

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 332ms/step - loss: 1.5997 - mae: 0.8756 - rmse: 1.2582

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 332ms/step - loss: 1.5957 - mae: 0.8747 - rmse: 1.2566

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 331ms/step - loss: 1.5917 - mae: 0.8738 - rmse: 1.2550

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 331ms/step - loss: 1.5879 - mae: 0.8730 - rmse: 1.2535

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 330ms/step - loss: 1.5840 - mae: 0.8722 - rmse: 1.2519

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 330ms/step - loss: 1.5808 - mae: 0.8715 - rmse: 1.2506

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 329ms/step - loss: 1.5782 - mae: 0.8710 - rmse: 1.2496

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 329ms/step - loss: 1.5759 - mae: 0.8705 - rmse: 1.2487

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 328ms/step - loss: 1.5739 - mae: 0.8701 - rmse: 1.2479

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 328ms/step - loss: 1.5721 - mae: 0.8698 - rmse: 1.2472

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 328ms/step - loss: 1.5704 - mae: 0.8695 - rmse: 1.2466

 87/269 ━━━━━━━━━━━━━━━━━━━━ 59s 328ms/step - loss: 1.5689 - mae: 0.8693 - rmse: 1.2460

 88/269 ━━━━━━━━━━━━━━━━━━━━ 59s 329ms/step - loss: 1.5673 - mae: 0.8690 - rmse: 1.2454

 89/269 ━━━━━━━━━━━━━━━━━━━━ 59s 330ms/step - loss: 1.5658 - mae: 0.8688 - rmse: 1.2449

 90/269 ━━━━━━━━━━━━━━━━━━━━ 59s 330ms/step - loss: 1.5643 - mae: 0.8686 - rmse: 1.2443

 91/269 ━━━━━━━━━━━━━━━━━━━━ 58s 331ms/step - loss: 1.5627 - mae: 0.8684 - rmse: 1.2437

 92/269 ━━━━━━━━━━━━━━━━━━━━ 58s 331ms/step - loss: 1.5610 - mae: 0.8681 - rmse: 1.2431

 93/269 ━━━━━━━━━━━━━━━━━━━━ 58s 331ms/step - loss: 1.5593 - mae: 0.8678 - rmse: 1.2424

 94/269 ━━━━━━━━━━━━━━━━━━━━ 57s 331ms/step - loss: 1.5575 - mae: 0.8674 - rmse: 1.2417

 95/269 ━━━━━━━━━━━━━━━━━━━━ 57s 331ms/step - loss: 1.5556 - mae: 0.8671 - rmse: 1.2409

 96/269 ━━━━━━━━━━━━━━━━━━━━ 57s 332ms/step - loss: 1.5536 - mae: 0.8667 - rmse: 1.2402

 97/269 ━━━━━━━━━━━━━━━━━━━━ 56s 331ms/step - loss: 1.5516 - mae: 0.8663 - rmse: 1.2394

 98/269 ━━━━━━━━━━━━━━━━━━━━ 56s 331ms/step - loss: 1.5495 - mae: 0.8658 - rmse: 1.2386

 99/269 ━━━━━━━━━━━━━━━━━━━━ 56s 330ms/step - loss: 1.5474 - mae: 0.8654 - rmse: 1.2377

100/269 ━━━━━━━━━━━━━━━━━━━━ 55s 329ms/step - loss: 1.5452 - mae: 0.8649 - rmse: 1.2369

101/269 ━━━━━━━━━━━━━━━━━━━━ 55s 328ms/step - loss: 1.5431 - mae: 0.8644 - rmse: 1.2360

102/269 ━━━━━━━━━━━━━━━━━━━━ 54s 328ms/step - loss: 1.5409 - mae: 0.8639 - rmse: 1.2351

103/269 ━━━━━━━━━━━━━━━━━━━━ 54s 327ms/step - loss: 1.5387 - mae: 0.8634 - rmse: 1.2342

104/269 ━━━━━━━━━━━━━━━━━━━━ 53s 327ms/step - loss: 1.5365 - mae: 0.8630 - rmse: 1.2334

105/269 ━━━━━━━━━━━━━━━━━━━━ 53s 326ms/step - loss: 1.5343 - mae: 0.8625 - rmse: 1.2325

106/269 ━━━━━━━━━━━━━━━━━━━━ 53s 326ms/step - loss: 1.5321 - mae: 0.8620 - rmse: 1.2316

107/269 ━━━━━━━━━━━━━━━━━━━━ 52s 325ms/step - loss: 1.5298 - mae: 0.8615 - rmse: 1.2306

108/269 ━━━━━━━━━━━━━━━━━━━━ 52s 324ms/step - loss: 1.5275 - mae: 0.8609 - rmse: 1.2297

109/269 ━━━━━━━━━━━━━━━━━━━━ 51s 324ms/step - loss: 1.5251 - mae: 0.8604 - rmse: 1.2287

110/269 ━━━━━━━━━━━━━━━━━━━━ 51s 323ms/step - loss: 1.5227 - mae: 0.8598 - rmse: 1.2277

111/269 ━━━━━━━━━━━━━━━━━━━━ 50s 323ms/step - loss: 1.5203 - mae: 0.8593 - rmse: 1.2268

112/269 ━━━━━━━━━━━━━━━━━━━━ 50s 322ms/step - loss: 1.5179 - mae: 0.8587 - rmse: 1.2258

113/269 ━━━━━━━━━━━━━━━━━━━━ 50s 322ms/step - loss: 1.5154 - mae: 0.8581 - rmse: 1.2247

114/269 ━━━━━━━━━━━━━━━━━━━━ 49s 321ms/step - loss: 1.5129 - mae: 0.8575 - rmse: 1.2237

115/269 ━━━━━━━━━━━━━━━━━━━━ 49s 321ms/step - loss: 1.5104 - mae: 0.8568 - rmse: 1.2226

116/269 ━━━━━━━━━━━━━━━━━━━━ 48s 320ms/step - loss: 1.5078 - mae: 0.8562 - rmse: 1.2216

117/269 ━━━━━━━━━━━━━━━━━━━━ 48s 320ms/step - loss: 1.5052 - mae: 0.8555 - rmse: 1.2205

118/269 ━━━━━━━━━━━━━━━━━━━━ 48s 319ms/step - loss: 1.5026 - mae: 0.8548 - rmse: 1.2194

119/269 ━━━━━━━━━━━━━━━━━━━━ 47s 318ms/step - loss: 1.5000 - mae: 0.8541 - rmse: 1.2183

120/269 ━━━━━━━━━━━━━━━━━━━━ 47s 318ms/step - loss: 1.4973 - mae: 0.8534 - rmse: 1.2172

121/269 ━━━━━━━━━━━━━━━━━━━━ 47s 318ms/step - loss: 1.4947 - mae: 0.8527 - rmse: 1.2161

122/269 ━━━━━━━━━━━━━━━━━━━━ 46s 317ms/step - loss: 1.4920 - mae: 0.8519 - rmse: 1.2149

123/269 ━━━━━━━━━━━━━━━━━━━━ 46s 317ms/step - loss: 1.4893 - mae: 0.8512 - rmse: 1.2138

124/269 ━━━━━━━━━━━━━━━━━━━━ 45s 317ms/step - loss: 1.4866 - mae: 0.8504 - rmse: 1.2127

125/269 ━━━━━━━━━━━━━━━━━━━━ 45s 316ms/step - loss: 1.4838 - mae: 0.8496 - rmse: 1.2115

126/269 ━━━━━━━━━━━━━━━━━━━━ 45s 316ms/step - loss: 1.4811 - mae: 0.8488 - rmse: 1.2103

127/269 ━━━━━━━━━━━━━━━━━━━━ 44s 316ms/step - loss: 1.4783 - mae: 0.8480 - rmse: 1.2091

128/269 ━━━━━━━━━━━━━━━━━━━━ 44s 316ms/step - loss: 1.4756 - mae: 0.8472 - rmse: 1.2080

129/269 ━━━━━━━━━━━━━━━━━━━━ 44s 316ms/step - loss: 1.4728 - mae: 0.8464 - rmse: 1.2068

130/269 ━━━━━━━━━━━━━━━━━━━━ 43s 316ms/step - loss: 1.4700 - mae: 0.8456 - rmse: 1.2056

131/269 ━━━━━━━━━━━━━━━━━━━━ 43s 316ms/step - loss: 1.4672 - mae: 0.8447 - rmse: 1.2044

132/269 ━━━━━━━━━━━━━━━━━━━━ 43s 315ms/step - loss: 1.4644 - mae: 0.8439 - rmse: 1.2032

133/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 1.4616 - mae: 0.8431 - rmse: 1.2020

134/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 1.4588 - mae: 0.8422 - rmse: 1.2008

135/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 1.4561 - mae: 0.8414 - rmse: 1.1996

136/269 ━━━━━━━━━━━━━━━━━━━━ 42s 316ms/step - loss: 1.4533 - mae: 0.8406 - rmse: 1.1983

137/269 ━━━━━━━━━━━━━━━━━━━━ 41s 316ms/step - loss: 1.4505 - mae: 0.8397 - rmse: 1.1971

138/269 ━━━━━━━━━━━━━━━━━━━━ 41s 316ms/step - loss: 1.4477 - mae: 0.8389 - rmse: 1.1959

139/269 ━━━━━━━━━━━━━━━━━━━━ 41s 317ms/step - loss: 1.4449 - mae: 0.8380 - rmse: 1.1947

140/269 ━━━━━━━━━━━━━━━━━━━━ 41s 318ms/step - loss: 1.4421 - mae: 0.8371 - rmse: 1.1935

141/269 ━━━━━━━━━━━━━━━━━━━━ 40s 319ms/step - loss: 1.4393 - mae: 0.8363 - rmse: 1.1923

142/269 ━━━━━━━━━━━━━━━━━━━━ 40s 320ms/step - loss: 1.4366 - mae: 0.8354 - rmse: 1.1911

143/269 ━━━━━━━━━━━━━━━━━━━━ 40s 322ms/step - loss: 1.4338 - mae: 0.8346 - rmse: 1.1898

144/269 ━━━━━━━━━━━━━━━━━━━━ 40s 322ms/step - loss: 1.4310 - mae: 0.8337 - rmse: 1.1886

145/269 ━━━━━━━━━━━━━━━━━━━━ 40s 324ms/step - loss: 1.4282 - mae: 0.8328 - rmse: 1.1874

146/269 ━━━━━━━━━━━━━━━━━━━━ 39s 324ms/step - loss: 1.4254 - mae: 0.8319 - rmse: 1.1861

147/269 ━━━━━━━━━━━━━━━━━━━━ 39s 325ms/step - loss: 1.4226 - mae: 0.8310 - rmse: 1.1849

148/269 ━━━━━━━━━━━━━━━━━━━━ 39s 327ms/step - loss: 1.4197 - mae: 0.8301 - rmse: 1.1836

149/269 ━━━━━━━━━━━━━━━━━━━━ 39s 329ms/step - loss: 1.4169 - mae: 0.8292 - rmse: 1.1824

150/269 ━━━━━━━━━━━━━━━━━━━━ 39s 331ms/step - loss: 1.4141 - mae: 0.8283 - rmse: 1.1811

151/269 ━━━━━━━━━━━━━━━━━━━━ 39s 333ms/step - loss: 1.4113 - mae: 0.8273 - rmse: 1.1799

152/269 ━━━━━━━━━━━━━━━━━━━━ 39s 334ms/step - loss: 1.4085 - mae: 0.8264 - rmse: 1.1787

153/269 ━━━━━━━━━━━━━━━━━━━━ 38s 334ms/step - loss: 1.4058 - mae: 0.8255 - rmse: 1.1774

154/269 ━━━━━━━━━━━━━━━━━━━━ 38s 337ms/step - loss: 1.4030 - mae: 0.8246 - rmse: 1.1762

155/269 ━━━━━━━━━━━━━━━━━━━━ 38s 338ms/step - loss: 1.4002 - mae: 0.8237 - rmse: 1.1749

156/269 ━━━━━━━━━━━━━━━━━━━━ 38s 341ms/step - loss: 1.3974 - mae: 0.8228 - rmse: 1.1737

157/269 ━━━━━━━━━━━━━━━━━━━━ 38s 342ms/step - loss: 1.3947 - mae: 0.8218 - rmse: 1.1724

158/269 ━━━━━━━━━━━━━━━━━━━━ 38s 343ms/step - loss: 1.3919 - mae: 0.8209 - rmse: 1.1712

159/269 ━━━━━━━━━━━━━━━━━━━━ 37s 345ms/step - loss: 1.3891 - mae: 0.8200 - rmse: 1.1699

160/269 ━━━━━━━━━━━━━━━━━━━━ 37s 344ms/step - loss: 1.3863 - mae: 0.8190 - rmse: 1.1687

161/269 ━━━━━━━━━━━━━━━━━━━━ 37s 345ms/step - loss: 1.3836 - mae: 0.8181 - rmse: 1.1674

162/269 ━━━━━━━━━━━━━━━━━━━━ 36s 345ms/step - loss: 1.3808 - mae: 0.8172 - rmse: 1.1662

163/269 ━━━━━━━━━━━━━━━━━━━━ 36s 345ms/step - loss: 1.3781 - mae: 0.8163 - rmse: 1.1650

164/269 ━━━━━━━━━━━━━━━━━━━━ 36s 346ms/step - loss: 1.3754 - mae: 0.8153 - rmse: 1.1637

165/269 ━━━━━━━━━━━━━━━━━━━━ 36s 347ms/step - loss: 1.3726 - mae: 0.8144 - rmse: 1.1625

166/269 ━━━━━━━━━━━━━━━━━━━━ 35s 348ms/step - loss: 1.3699 - mae: 0.8135 - rmse: 1.1613

167/269 ━━━━━━━━━━━━━━━━━━━━ 35s 348ms/step - loss: 1.3672 - mae: 0.8126 - rmse: 1.1600

168/269 ━━━━━━━━━━━━━━━━━━━━ 35s 349ms/step - loss: 1.3646 - mae: 0.8117 - rmse: 1.1588

169/269 ━━━━━━━━━━━━━━━━━━━━ 35s 350ms/step - loss: 1.3619 - mae: 0.8108 - rmse: 1.1576

170/269 ━━━━━━━━━━━━━━━━━━━━ 34s 352ms/step - loss: 1.3593 - mae: 0.8099 - rmse: 1.1564

171/269 ━━━━━━━━━━━━━━━━━━━━ 35s 358ms/step - loss: 1.3567 - mae: 0.8090 - rmse: 1.1552

172/269 ━━━━━━━━━━━━━━━━━━━━ 35s 362ms/step - loss: 1.3541 - mae: 0.8081 - rmse: 1.1540

173/269 ━━━━━━━━━━━━━━━━━━━━ 34s 364ms/step - loss: 1.3515 - mae: 0.8072 - rmse: 1.1529

174/269 ━━━━━━━━━━━━━━━━━━━━ 34s 365ms/step - loss: 1.3490 - mae: 0.8064 - rmse: 1.1517

175/269 ━━━━━━━━━━━━━━━━━━━━ 34s 365ms/step - loss: 1.3464 - mae: 0.8055 - rmse: 1.1505

176/269 ━━━━━━━━━━━━━━━━━━━━ 34s 368ms/step - loss: 1.3439 - mae: 0.8047 - rmse: 1.1494

177/269 ━━━━━━━━━━━━━━━━━━━━ 33s 369ms/step - loss: 1.3414 - mae: 0.8038 - rmse: 1.1482

178/269 ━━━━━━━━━━━━━━━━━━━━ 33s 372ms/step - loss: 1.3389 - mae: 0.8029 - rmse: 1.1470

179/269 ━━━━━━━━━━━━━━━━━━━━ 33s 373ms/step - loss: 1.3364 - mae: 0.8021 - rmse: 1.1459

180/269 ━━━━━━━━━━━━━━━━━━━━ 33s 374ms/step - loss: 1.3339 - mae: 0.8013 - rmse: 1.1447

181/269 ━━━━━━━━━━━━━━━━━━━━ 32s 374ms/step - loss: 1.3314 - mae: 0.8004 - rmse: 1.1436

182/269 ━━━━━━━━━━━━━━━━━━━━ 32s 374ms/step - loss: 1.3289 - mae: 0.7996 - rmse: 1.1425

183/269 ━━━━━━━━━━━━━━━━━━━━ 32s 374ms/step - loss: 1.3264 - mae: 0.7987 - rmse: 1.1413

184/269 ━━━━━━━━━━━━━━━━━━━━ 31s 374ms/step - loss: 1.3240 - mae: 0.7979 - rmse: 1.1402

185/269 ━━━━━━━━━━━━━━━━━━━━ 31s 374ms/step - loss: 1.3215 - mae: 0.7971 - rmse: 1.1390

186/269 ━━━━━━━━━━━━━━━━━━━━ 31s 374ms/step - loss: 1.3191 - mae: 0.7963 - rmse: 1.1379

187/269 ━━━━━━━━━━━━━━━━━━━━ 30s 374ms/step - loss: 1.3166 - mae: 0.7954 - rmse: 1.1368

188/269 ━━━━━━━━━━━━━━━━━━━━ 30s 374ms/step - loss: 1.3142 - mae: 0.7946 - rmse: 1.1356

189/269 ━━━━━━━━━━━━━━━━━━━━ 29s 374ms/step - loss: 1.3118 - mae: 0.7938 - rmse: 1.1345

190/269 ━━━━━━━━━━━━━━━━━━━━ 29s 375ms/step - loss: 1.3094 - mae: 0.7929 - rmse: 1.1334

191/269 ━━━━━━━━━━━━━━━━━━━━ 29s 375ms/step - loss: 1.3070 - mae: 0.7921 - rmse: 1.1323

192/269 ━━━━━━━━━━━━━━━━━━━━ 28s 374ms/step - loss: 1.3046 - mae: 0.7913 - rmse: 1.1311

193/269 ━━━━━━━━━━━━━━━━━━━━ 28s 374ms/step - loss: 1.3022 - mae: 0.7905 - rmse: 1.1300

194/269 ━━━━━━━━━━━━━━━━━━━━ 28s 374ms/step - loss: 1.2998 - mae: 0.7896 - rmse: 1.1289

195/269 ━━━━━━━━━━━━━━━━━━━━ 27s 374ms/step - loss: 1.2974 - mae: 0.7888 - rmse: 1.1278

196/269 ━━━━━━━━━━━━━━━━━━━━ 27s 374ms/step - loss: 1.2951 - mae: 0.7880 - rmse: 1.1267

197/269 ━━━━━━━━━━━━━━━━━━━━ 26s 373ms/step - loss: 1.2927 - mae: 0.7872 - rmse: 1.1256

198/269 ━━━━━━━━━━━━━━━━━━━━ 26s 373ms/step - loss: 1.2904 - mae: 0.7864 - rmse: 1.1245

199/269 ━━━━━━━━━━━━━━━━━━━━ 26s 373ms/step - loss: 1.2880 - mae: 0.7856 - rmse: 1.1234

200/269 ━━━━━━━━━━━━━━━━━━━━ 25s 373ms/step - loss: 1.2857 - mae: 0.7848 - rmse: 1.1223

201/269 ━━━━━━━━━━━━━━━━━━━━ 25s 373ms/step - loss: 1.2834 - mae: 0.7840 - rmse: 1.1212

202/269 ━━━━━━━━━━━━━━━━━━━━ 24s 373ms/step - loss: 1.2811 - mae: 0.7832 - rmse: 1.1201

203/269 ━━━━━━━━━━━━━━━━━━━━ 24s 372ms/step - loss: 1.2788 - mae: 0.7824 - rmse: 1.1190

204/269 ━━━━━━━━━━━━━━━━━━━━ 24s 372ms/step - loss: 1.2766 - mae: 0.7816 - rmse: 1.1180

205/269 ━━━━━━━━━━━━━━━━━━━━ 23s 371ms/step - loss: 1.2744 - mae: 0.7808 - rmse: 1.1169

206/269 ━━━━━━━━━━━━━━━━━━━━ 23s 371ms/step - loss: 1.2721 - mae: 0.7800 - rmse: 1.1159

207/269 ━━━━━━━━━━━━━━━━━━━━ 22s 370ms/step - loss: 1.2699 - mae: 0.7793 - rmse: 1.1148

208/269 ━━━━━━━━━━━━━━━━━━━━ 22s 370ms/step - loss: 1.2677 - mae: 0.7785 - rmse: 1.1138

209/269 ━━━━━━━━━━━━━━━━━━━━ 22s 369ms/step - loss: 1.2655 - mae: 0.7777 - rmse: 1.1128

210/269 ━━━━━━━━━━━━━━━━━━━━ 21s 369ms/step - loss: 1.2633 - mae: 0.7769 - rmse: 1.1117

211/269 ━━━━━━━━━━━━━━━━━━━━ 21s 369ms/step - loss: 1.2611 - mae: 0.7762 - rmse: 1.1107

212/269 ━━━━━━━━━━━━━━━━━━━━ 20s 368ms/step - loss: 1.2590 - mae: 0.7754 - rmse: 1.1096

213/269 ━━━━━━━━━━━━━━━━━━━━ 20s 368ms/step - loss: 1.2568 - mae: 0.7746 - rmse: 1.1086

214/269 ━━━━━━━━━━━━━━━━━━━━ 20s 367ms/step - loss: 1.2546 - mae: 0.7738 - rmse: 1.1076

215/269 ━━━━━━━━━━━━━━━━━━━━ 19s 367ms/step - loss: 1.2525 - mae: 0.7731 - rmse: 1.1066

216/269 ━━━━━━━━━━━━━━━━━━━━ 19s 367ms/step - loss: 1.2503 - mae: 0.7723 - rmse: 1.1055

217/269 ━━━━━━━━━━━━━━━━━━━━ 19s 366ms/step - loss: 1.2482 - mae: 0.7716 - rmse: 1.1045

218/269 ━━━━━━━━━━━━━━━━━━━━ 18s 366ms/step - loss: 1.2461 - mae: 0.7708 - rmse: 1.1035

219/269 ━━━━━━━━━━━━━━━━━━━━ 18s 366ms/step - loss: 1.2439 - mae: 0.7700 - rmse: 1.1025

220/269 ━━━━━━━━━━━━━━━━━━━━ 17s 365ms/step - loss: 1.2418 - mae: 0.7693 - rmse: 1.1014

221/269 ━━━━━━━━━━━━━━━━━━━━ 17s 365ms/step - loss: 1.2397 - mae: 0.7685 - rmse: 1.1004

222/269 ━━━━━━━━━━━━━━━━━━━━ 17s 364ms/step - loss: 1.2376 - mae: 0.7678 - rmse: 1.0994

223/269 ━━━━━━━━━━━━━━━━━━━━ 16s 364ms/step - loss: 1.2355 - mae: 0.7670 - rmse: 1.0984

224/269 ━━━━━━━━━━━━━━━━━━━━ 16s 363ms/step - loss: 1.2334 - mae: 0.7663 - rmse: 1.0974

225/269 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - loss: 1.2313 - mae: 0.7655 - rmse: 1.0964

226/269 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - loss: 1.2292 - mae: 0.7648 - rmse: 1.0954

227/269 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - loss: 1.2272 - mae: 0.7640 - rmse: 1.0944

228/269 ━━━━━━━━━━━━━━━━━━━━ 14s 363ms/step - loss: 1.2251 - mae: 0.7633 - rmse: 1.0934

229/269 ━━━━━━━━━━━━━━━━━━━━ 14s 362ms/step - loss: 1.2230 - mae: 0.7625 - rmse: 1.0924

230/269 ━━━━━━━━━━━━━━━━━━━━ 14s 362ms/step - loss: 1.2210 - mae: 0.7618 - rmse: 1.0914

231/269 ━━━━━━━━━━━━━━━━━━━━ 13s 362ms/step - loss: 1.2189 - mae: 0.7610 - rmse: 1.0904

232/269 ━━━━━━━━━━━━━━━━━━━━ 13s 362ms/step - loss: 1.2169 - mae: 0.7603 - rmse: 1.0894

233/269 ━━━━━━━━━━━━━━━━━━━━ 13s 362ms/step - loss: 1.2148 - mae: 0.7595 - rmse: 1.0884

234/269 ━━━━━━━━━━━━━━━━━━━━ 12s 362ms/step - loss: 1.2128 - mae: 0.7588 - rmse: 1.0874

235/269 ━━━━━━━━━━━━━━━━━━━━ 12s 362ms/step - loss: 1.2108 - mae: 0.7580 - rmse: 1.0864

236/269 ━━━━━━━━━━━━━━━━━━━━ 11s 362ms/step - loss: 1.2087 - mae: 0.7573 - rmse: 1.0854

237/269 ━━━━━━━━━━━━━━━━━━━━ 11s 362ms/step - loss: 1.2067 - mae: 0.7565 - rmse: 1.0845

238/269 ━━━━━━━━━━━━━━━━━━━━ 11s 361ms/step - loss: 1.2047 - mae: 0.7558 - rmse: 1.0835

239/269 ━━━━━━━━━━━━━━━━━━━━ 10s 361ms/step - loss: 1.2027 - mae: 0.7550 - rmse: 1.0825

240/269 ━━━━━━━━━━━━━━━━━━━━ 10s 361ms/step - loss: 1.2008 - mae: 0.7543 - rmse: 1.0815

241/269 ━━━━━━━━━━━━━━━━━━━━ 10s 361ms/step - loss: 1.1988 - mae: 0.7536 - rmse: 1.0806

242/269 ━━━━━━━━━━━━━━━━━━━━ 9s 361ms/step - loss: 1.1968 - mae: 0.7528 - rmse: 1.0796

243/269 ━━━━━━━━━━━━━━━━━━━━ 9s 361ms/step - loss: 1.1948 - mae: 0.7521 - rmse: 1.0786

244/269 ━━━━━━━━━━━━━━━━━━━━ 9s 361ms/step - loss: 1.1929 - mae: 0.7514 - rmse: 1.0777

245/269 ━━━━━━━━━━━━━━━━━━━━ 8s 361ms/step - loss: 1.1909 - mae: 0.7507 - rmse: 1.0767

246/269 ━━━━━━━━━━━━━━━━━━━━ 8s 360ms/step - loss: 1.1890 - mae: 0.7499 - rmse: 1.0757

247/269 ━━━━━━━━━━━━━━━━━━━━ 7s 360ms/step - loss: 1.1871 - mae: 0.7492 - rmse: 1.0748

248/269 ━━━━━━━━━━━━━━━━━━━━ 7s 360ms/step - loss: 1.1851 - mae: 0.7485 - rmse: 1.0738

249/269 ━━━━━━━━━━━━━━━━━━━━ 7s 360ms/step - loss: 1.1832 - mae: 0.7478 - rmse: 1.0729

250/269 ━━━━━━━━━━━━━━━━━━━━ 6s 360ms/step - loss: 1.1813 - mae: 0.7471 - rmse: 1.0719

251/269 ━━━━━━━━━━━━━━━━━━━━ 6s 359ms/step - loss: 1.1794 - mae: 0.7464 - rmse: 1.0710

252/269 ━━━━━━━━━━━━━━━━━━━━ 6s 359ms/step - loss: 1.1775 - mae: 0.7457 - rmse: 1.0701

253/269 ━━━━━━━━━━━━━━━━━━━━ 5s 359ms/step - loss: 1.1756 - mae: 0.7449 - rmse: 1.0691

254/269 ━━━━━━━━━━━━━━━━━━━━ 5s 358ms/step - loss: 1.1737 - mae: 0.7442 - rmse: 1.0682

255/269 ━━━━━━━━━━━━━━━━━━━━ 5s 358ms/step - loss: 1.1718 - mae: 0.7435 - rmse: 1.0673

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 357ms/step - loss: 1.1700 - mae: 0.7428 - rmse: 1.0663

257/269 ━━━━━━━━━━━━━━━━━━━━ 4s 357ms/step - loss: 1.1681 - mae: 0.7421 - rmse: 1.0654

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 357ms/step - loss: 1.1662 - mae: 0.7414 - rmse: 1.0645

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 356ms/step - loss: 1.1644 - mae: 0.7407 - rmse: 1.0635

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 356ms/step - loss: 1.1625 - mae: 0.7400 - rmse: 1.0626

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 356ms/step - loss: 1.1607 - mae: 0.7393 - rmse: 1.0617

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 355ms/step - loss: 1.1589 - mae: 0.7386 - rmse: 1.0608

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 355ms/step - loss: 1.1570 - mae: 0.7379 - rmse: 1.0599

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 355ms/step - loss: 1.1552 - mae: 0.7373 - rmse: 1.0589

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 354ms/step - loss: 1.1534 - mae: 0.7366 - rmse: 1.0580

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 354ms/step - loss: 1.1516 - mae: 0.7359 - rmse: 1.0571

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - loss: 1.1498 - mae: 0.7352 - rmse: 1.0562

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 353ms/step - loss: 1.1480 - mae: 0.7345 - rmse: 1.0553

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - loss: 1.1462 - mae: 0.7338 - rmse: 1.0544

269/269 ━━━━━━━━━━━━━━━━━━━━ 119s 410ms/step - loss: 0.6684 - mae: 0.5519 - rmse: 0.8143 - val_loss: 1.1244 - val_mae: 0.6439 - val_rmse: 1.0579 - learning_rate: 0.0010

Epoch 2/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 376ms/step - loss: 1.1947 - mae: 0.7214 - rmse: 1.0906

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 408ms/step - loss: 1.0819 - mae: 0.6986 - rmse: 1.0362

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 398ms/step - loss: 1.1456 - mae: 0.7289 - rmse: 1.0662

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 438ms/step - loss: 1.1646 - mae: 0.7414 - rmse: 1.0754

  5/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 465ms/step - loss: 1.1469 - mae: 0.7392 - rmse: 1.0672

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 449ms/step - loss: 1.1247 - mae: 0.7344 - rmse: 1.0568

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 427ms/step - loss: 1.1180 - mae: 0.7334 - rmse: 1.0537

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 413ms/step - loss: 1.1370 - mae: 0.7405 - rmse: 1.0626

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 407ms/step - loss: 1.1446 - mae: 0.7445 - rmse: 1.0663

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 398ms/step - loss: 1.1444 - mae: 0.7460 - rmse: 1.0663

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 400ms/step - loss: 1.1391 - mae: 0.7456 - rmse: 1.0639

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 396ms/step - loss: 1.1388 - mae: 0.7472 - rmse: 1.0638

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 402ms/step - loss: 1.1468 - mae: 0.7500 - rmse: 1.0675

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 411ms/step - loss: 1.1685 - mae: 0.7567 - rmse: 1.0772

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 411ms/step - loss: 1.1856 - mae: 0.7621 - rmse: 1.0848

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 408ms/step - loss: 1.2028 - mae: 0.7675 - rmse: 1.0924

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 412ms/step - loss: 1.2206 - mae: 0.7727 - rmse: 1.1002

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 407ms/step - loss: 1.2354 - mae: 0.7771 - rmse: 1.1067

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 405ms/step - loss: 1.2512 - mae: 0.7817 - rmse: 1.1136

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 405ms/step - loss: 1.2653 - mae: 0.7860 - rmse: 1.1197

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 403ms/step - loss: 1.2758 - mae: 0.7892 - rmse: 1.1243

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 413ms/step - loss: 1.2851 - mae: 0.7923 - rmse: 1.1284

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 418ms/step - loss: 1.2937 - mae: 0.7952 - rmse: 1.1322

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 421ms/step - loss: 1.3009 - mae: 0.7979 - rmse: 1.1354

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 433ms/step - loss: 1.3067 - mae: 0.8001 - rmse: 1.1380

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 433ms/step - loss: 1.3119 - mae: 0.8021 - rmse: 1.1403

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 428ms/step - loss: 1.3156 - mae: 0.8036 - rmse: 1.1420

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 426ms/step - loss: 1.3182 - mae: 0.8049 - rmse: 1.1433

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 421ms/step - loss: 1.3203 - mae: 0.8060 - rmse: 1.1442

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 419ms/step - loss: 1.3212 - mae: 0.8067 - rmse: 1.1447

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 416ms/step - loss: 1.3212 - mae: 0.8072 - rmse: 1.1448

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 414ms/step - loss: 1.3207 - mae: 0.8074 - rmse: 1.1446

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 415ms/step - loss: 1.3197 - mae: 0.8076 - rmse: 1.1443

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 413ms/step - loss: 1.3184 - mae: 0.8076 - rmse: 1.1438

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 410ms/step - loss: 1.3172 - mae: 0.8078 - rmse: 1.1433

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 407ms/step - loss: 1.3156 - mae: 0.8077 - rmse: 1.1426

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 404ms/step - loss: 1.3138 - mae: 0.8076 - rmse: 1.1419

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 400ms/step - loss: 1.3115 - mae: 0.8073 - rmse: 1.1409

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 397ms/step - loss: 1.3090 - mae: 0.8069 - rmse: 1.1399

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 396ms/step - loss: 1.3062 - mae: 0.8063 - rmse: 1.1387

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 398ms/step - loss: 1.3036 - mae: 0.8059 - rmse: 1.1376

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 395ms/step - loss: 1.3007 - mae: 0.8053 - rmse: 1.1363

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 392ms/step - loss: 1.2978 - mae: 0.8047 - rmse: 1.1350

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 388ms/step - loss: 1.2952 - mae: 0.8043 - rmse: 1.1339

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 387ms/step - loss: 1.2926 - mae: 0.8038 - rmse: 1.1328

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 386ms/step - loss: 1.2897 - mae: 0.8032 - rmse: 1.1315

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 384ms/step - loss: 1.2871 - mae: 0.8028 - rmse: 1.1304

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 385ms/step - loss: 1.2843 - mae: 0.8022 - rmse: 1.1292

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 383ms/step - loss: 1.2813 - mae: 0.8015 - rmse: 1.1278

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 380ms/step - loss: 1.2781 - mae: 0.8007 - rmse: 1.1264

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 378ms/step - loss: 1.2748 - mae: 0.7998 - rmse: 1.1249

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 376ms/step - loss: 1.2714 - mae: 0.7989 - rmse: 1.1234

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 374ms/step - loss: 1.2679 - mae: 0.7980 - rmse: 1.1218

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 371ms/step - loss: 1.2647 - mae: 0.7972 - rmse: 1.1204

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 370ms/step - loss: 1.2615 - mae: 0.7963 - rmse: 1.1189

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 368ms/step - loss: 1.2584 - mae: 0.7954 - rmse: 1.1175

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 366ms/step - loss: 1.2553 - mae: 0.7946 - rmse: 1.1161

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 364ms/step - loss: 1.2522 - mae: 0.7937 - rmse: 1.1147

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 363ms/step - loss: 1.2494 - mae: 0.7929 - rmse: 1.1134

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 362ms/step - loss: 1.2465 - mae: 0.7921 - rmse: 1.1121

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 361ms/step - loss: 1.2437 - mae: 0.7914 - rmse: 1.1109

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 360ms/step - loss: 1.2410 - mae: 0.7907 - rmse: 1.1096

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 359ms/step - loss: 1.2382 - mae: 0.7899 - rmse: 1.1084

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 358ms/step - loss: 1.2353 - mae: 0.7891 - rmse: 1.1070

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 357ms/step - loss: 1.2324 - mae: 0.7883 - rmse: 1.1057

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 356ms/step - loss: 1.2293 - mae: 0.7874 - rmse: 1.1043

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 356ms/step - loss: 1.2263 - mae: 0.7866 - rmse: 1.1029

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 355ms/step - loss: 1.2232 - mae: 0.7857 - rmse: 1.1015

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 355ms/step - loss: 1.2202 - mae: 0.7848 - rmse: 1.1001

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 355ms/step - loss: 1.2172 - mae: 0.7840 - rmse: 1.0987

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 354ms/step - loss: 1.2145 - mae: 0.7832 - rmse: 1.0974

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 353ms/step - loss: 1.2117 - mae: 0.7824 - rmse: 1.0961

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 352ms/step - loss: 1.2090 - mae: 0.7816 - rmse: 1.0949

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 352ms/step - loss: 1.2064 - mae: 0.7809 - rmse: 1.0937

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 350ms/step - loss: 1.2040 - mae: 0.7802 - rmse: 1.0925

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 349ms/step - loss: 1.2016 - mae: 0.7795 - rmse: 1.0914

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 349ms/step - loss: 1.1993 - mae: 0.7789 - rmse: 1.0904

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 348ms/step - loss: 1.1971 - mae: 0.7783 - rmse: 1.0894

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 347ms/step - loss: 1.1950 - mae: 0.7777 - rmse: 1.0884

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 346ms/step - loss: 1.1929 - mae: 0.7771 - rmse: 1.0874

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 346ms/step - loss: 1.1912 - mae: 0.7767 - rmse: 1.0867

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 345ms/step - loss: 1.1902 - mae: 0.7764 - rmse: 1.0862

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 345ms/step - loss: 1.1893 - mae: 0.7761 - rmse: 1.0858

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 344ms/step - loss: 1.1887 - mae: 0.7759 - rmse: 1.0856

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 344ms/step - loss: 1.1881 - mae: 0.7758 - rmse: 1.0853

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 345ms/step - loss: 1.1878 - mae: 0.7757 - rmse: 1.0852

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 345ms/step - loss: 1.1876 - mae: 0.7757 - rmse: 1.0851

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 346ms/step - loss: 1.1873 - mae: 0.7756 - rmse: 1.0850

 89/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 346ms/step - loss: 1.1870 - mae: 0.7756 - rmse: 1.0849

 90/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 347ms/step - loss: 1.1868 - mae: 0.7756 - rmse: 1.0848

 91/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 346ms/step - loss: 1.1865 - mae: 0.7755 - rmse: 1.0847

 92/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 345ms/step - loss: 1.1860 - mae: 0.7754 - rmse: 1.0845

 93/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 344ms/step - loss: 1.1856 - mae: 0.7753 - rmse: 1.0843

 94/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 344ms/step - loss: 1.1850 - mae: 0.7751 - rmse: 1.0841

 95/269 ━━━━━━━━━━━━━━━━━━━━ 59s 343ms/step - loss: 1.1843 - mae: 0.7749 - rmse: 1.0838

 96/269 ━━━━━━━━━━━━━━━━━━━━ 59s 342ms/step - loss: 1.1836 - mae: 0.7747 - rmse: 1.0835

 97/269 ━━━━━━━━━━━━━━━━━━━━ 58s 342ms/step - loss: 1.1828 - mae: 0.7745 - rmse: 1.0832

 98/269 ━━━━━━━━━━━━━━━━━━━━ 58s 342ms/step - loss: 1.1820 - mae: 0.7742 - rmse: 1.0828

 99/269 ━━━━━━━━━━━━━━━━━━━━ 58s 342ms/step - loss: 1.1811 - mae: 0.7739 - rmse: 1.0824

100/269 ━━━━━━━━━━━━━━━━━━━━ 57s 341ms/step - loss: 1.1802 - mae: 0.7736 - rmse: 1.0820

101/269 ━━━━━━━━━━━━━━━━━━━━ 57s 340ms/step - loss: 1.1792 - mae: 0.7733 - rmse: 1.0816

102/269 ━━━━━━━━━━━━━━━━━━━━ 56s 339ms/step - loss: 1.1783 - mae: 0.7730 - rmse: 1.0811

103/269 ━━━━━━━━━━━━━━━━━━━━ 56s 339ms/step - loss: 1.1773 - mae: 0.7727 - rmse: 1.0807

104/269 ━━━━━━━━━━━━━━━━━━━━ 55s 338ms/step - loss: 1.1763 - mae: 0.7724 - rmse: 1.0802

105/269 ━━━━━━━━━━━━━━━━━━━━ 55s 338ms/step - loss: 1.1752 - mae: 0.7720 - rmse: 1.0797

106/269 ━━━━━━━━━━━━━━━━━━━━ 54s 337ms/step - loss: 1.1742 - mae: 0.7717 - rmse: 1.0792

107/269 ━━━━━━━━━━━━━━━━━━━━ 54s 337ms/step - loss: 1.1730 - mae: 0.7713 - rmse: 1.0787

108/269 ━━━━━━━━━━━━━━━━━━━━ 54s 336ms/step - loss: 1.1719 - mae: 0.7709 - rmse: 1.0782

109/269 ━━━━━━━━━━━━━━━━━━━━ 53s 336ms/step - loss: 1.1706 - mae: 0.7705 - rmse: 1.0776

110/269 ━━━━━━━━━━━━━━━━━━━━ 53s 336ms/step - loss: 1.1694 - mae: 0.7701 - rmse: 1.0770

111/269 ━━━━━━━━━━━━━━━━━━━━ 52s 335ms/step - loss: 1.1680 - mae: 0.7696 - rmse: 1.0764

112/269 ━━━━━━━━━━━━━━━━━━━━ 52s 335ms/step - loss: 1.1667 - mae: 0.7691 - rmse: 1.0758

113/269 ━━━━━━━━━━━━━━━━━━━━ 52s 334ms/step - loss: 1.1653 - mae: 0.7687 - rmse: 1.0751

114/269 ━━━━━━━━━━━━━━━━━━━━ 51s 334ms/step - loss: 1.1639 - mae: 0.7681 - rmse: 1.0745

115/269 ━━━━━━━━━━━━━━━━━━━━ 51s 333ms/step - loss: 1.1624 - mae: 0.7676 - rmse: 1.0738

116/269 ━━━━━━━━━━━━━━━━━━━━ 50s 333ms/step - loss: 1.1609 - mae: 0.7671 - rmse: 1.0731

117/269 ━━━━━━━━━━━━━━━━━━━━ 50s 332ms/step - loss: 1.1594 - mae: 0.7665 - rmse: 1.0723

118/269 ━━━━━━━━━━━━━━━━━━━━ 50s 331ms/step - loss: 1.1578 - mae: 0.7659 - rmse: 1.0716

119/269 ━━━━━━━━━━━━━━━━━━━━ 49s 331ms/step - loss: 1.1563 - mae: 0.7654 - rmse: 1.0709

120/269 ━━━━━━━━━━━━━━━━━━━━ 49s 330ms/step - loss: 1.1547 - mae: 0.7648 - rmse: 1.0701

121/269 ━━━━━━━━━━━━━━━━━━━━ 48s 330ms/step - loss: 1.1531 - mae: 0.7642 - rmse: 1.0693

122/269 ━━━━━━━━━━━━━━━━━━━━ 48s 329ms/step - loss: 1.1514 - mae: 0.7635 - rmse: 1.0685

123/269 ━━━━━━━━━━━━━━━━━━━━ 47s 329ms/step - loss: 1.1498 - mae: 0.7629 - rmse: 1.0677

124/269 ━━━━━━━━━━━━━━━━━━━━ 47s 328ms/step - loss: 1.1481 - mae: 0.7622 - rmse: 1.0669

125/269 ━━━━━━━━━━━━━━━━━━━━ 47s 328ms/step - loss: 1.1463 - mae: 0.7616 - rmse: 1.0661

126/269 ━━━━━━━━━━━━━━━━━━━━ 46s 327ms/step - loss: 1.1446 - mae: 0.7609 - rmse: 1.0653

127/269 ━━━━━━━━━━━━━━━━━━━━ 46s 327ms/step - loss: 1.1428 - mae: 0.7602 - rmse: 1.0644

128/269 ━━━━━━━━━━━━━━━━━━━━ 46s 327ms/step - loss: 1.1411 - mae: 0.7595 - rmse: 1.0635

129/269 ━━━━━━━━━━━━━━━━━━━━ 45s 327ms/step - loss: 1.1393 - mae: 0.7588 - rmse: 1.0627

130/269 ━━━━━━━━━━━━━━━━━━━━ 45s 327ms/step - loss: 1.1375 - mae: 0.7580 - rmse: 1.0618

131/269 ━━━━━━━━━━━━━━━━━━━━ 45s 326ms/step - loss: 1.1357 - mae: 0.7573 - rmse: 1.0609

132/269 ━━━━━━━━━━━━━━━━━━━━ 44s 326ms/step - loss: 1.1338 - mae: 0.7566 - rmse: 1.0600

133/269 ━━━━━━━━━━━━━━━━━━━━ 44s 325ms/step - loss: 1.1320 - mae: 0.7559 - rmse: 1.0591

134/269 ━━━━━━━━━━━━━━━━━━━━ 43s 325ms/step - loss: 1.1302 - mae: 0.7551 - rmse: 1.0582

135/269 ━━━━━━━━━━━━━━━━━━━━ 43s 324ms/step - loss: 1.1284 - mae: 0.7544 - rmse: 1.0574

136/269 ━━━━━━━━━━━━━━━━━━━━ 43s 324ms/step - loss: 1.1266 - mae: 0.7537 - rmse: 1.0565

137/269 ━━━━━━━━━━━━━━━━━━━━ 42s 324ms/step - loss: 1.1247 - mae: 0.7529 - rmse: 1.0556

138/269 ━━━━━━━━━━━━━━━━━━━━ 42s 324ms/step - loss: 1.1229 - mae: 0.7522 - rmse: 1.0546

139/269 ━━━━━━━━━━━━━━━━━━━━ 42s 324ms/step - loss: 1.1210 - mae: 0.7515 - rmse: 1.0537

140/269 ━━━━━━━━━━━━━━━━━━━━ 41s 323ms/step - loss: 1.1192 - mae: 0.7507 - rmse: 1.0528

141/269 ━━━━━━━━━━━━━━━━━━━━ 41s 323ms/step - loss: 1.1173 - mae: 0.7500 - rmse: 1.0519

142/269 ━━━━━━━━━━━━━━━━━━━━ 41s 323ms/step - loss: 1.1155 - mae: 0.7492 - rmse: 1.0510

143/269 ━━━━━━━━━━━━━━━━━━━━ 40s 323ms/step - loss: 1.1136 - mae: 0.7485 - rmse: 1.0500

144/269 ━━━━━━━━━━━━━━━━━━━━ 40s 323ms/step - loss: 1.1117 - mae: 0.7477 - rmse: 1.0491

145/269 ━━━━━━━━━━━━━━━━━━━━ 40s 323ms/step - loss: 1.1098 - mae: 0.7470 - rmse: 1.0482

146/269 ━━━━━━━━━━━━━━━━━━━━ 39s 323ms/step - loss: 1.1079 - mae: 0.7462 - rmse: 1.0472

147/269 ━━━━━━━━━━━━━━━━━━━━ 39s 322ms/step - loss: 1.1060 - mae: 0.7454 - rmse: 1.0463

148/269 ━━━━━━━━━━━━━━━━━━━━ 38s 322ms/step - loss: 1.1041 - mae: 0.7446 - rmse: 1.0453

149/269 ━━━━━━━━━━━━━━━━━━━━ 38s 322ms/step - loss: 1.1022 - mae: 0.7438 - rmse: 1.0443

150/269 ━━━━━━━━━━━━━━━━━━━━ 38s 322ms/step - loss: 1.1002 - mae: 0.7430 - rmse: 1.0434

151/269 ━━━━━━━━━━━━━━━━━━━━ 37s 322ms/step - loss: 1.0983 - mae: 0.7422 - rmse: 1.0424

152/269 ━━━━━━━━━━━━━━━━━━━━ 37s 322ms/step - loss: 1.0964 - mae: 0.7414 - rmse: 1.0414

153/269 ━━━━━━━━━━━━━━━━━━━━ 37s 322ms/step - loss: 1.0945 - mae: 0.7406 - rmse: 1.0404

154/269 ━━━━━━━━━━━━━━━━━━━━ 37s 322ms/step - loss: 1.0926 - mae: 0.7398 - rmse: 1.0395

155/269 ━━━━━━━━━━━━━━━━━━━━ 36s 322ms/step - loss: 1.0906 - mae: 0.7390 - rmse: 1.0385

156/269 ━━━━━━━━━━━━━━━━━━━━ 36s 323ms/step - loss: 1.0887 - mae: 0.7382 - rmse: 1.0375

157/269 ━━━━━━━━━━━━━━━━━━━━ 36s 322ms/step - loss: 1.0868 - mae: 0.7374 - rmse: 1.0365

158/269 ━━━━━━━━━━━━━━━━━━━━ 35s 322ms/step - loss: 1.0848 - mae: 0.7366 - rmse: 1.0356

159/269 ━━━━━━━━━━━━━━━━━━━━ 35s 322ms/step - loss: 1.0829 - mae: 0.7357 - rmse: 1.0346

160/269 ━━━━━━━━━━━━━━━━━━━━ 35s 322ms/step - loss: 1.0810 - mae: 0.7349 - rmse: 1.0336

161/269 ━━━━━━━━━━━━━━━━━━━━ 34s 322ms/step - loss: 1.0791 - mae: 0.7341 - rmse: 1.0326

162/269 ━━━━━━━━━━━━━━━━━━━━ 34s 322ms/step - loss: 1.0771 - mae: 0.7333 - rmse: 1.0316

163/269 ━━━━━━━━━━━━━━━━━━━━ 34s 322ms/step - loss: 1.0752 - mae: 0.7325 - rmse: 1.0306

164/269 ━━━━━━━━━━━━━━━━━━━━ 33s 322ms/step - loss: 1.0733 - mae: 0.7317 - rmse: 1.0296

165/269 ━━━━━━━━━━━━━━━━━━━━ 33s 321ms/step - loss: 1.0714 - mae: 0.7308 - rmse: 1.0287

166/269 ━━━━━━━━━━━━━━━━━━━━ 33s 321ms/step - loss: 1.0695 - mae: 0.7300 - rmse: 1.0277

167/269 ━━━━━━━━━━━━━━━━━━━━ 32s 321ms/step - loss: 1.0676 - mae: 0.7292 - rmse: 1.0267

168/269 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 1.0657 - mae: 0.7284 - rmse: 1.0257

169/269 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 1.0638 - mae: 0.7277 - rmse: 1.0248

170/269 ━━━━━━━━━━━━━━━━━━━━ 31s 320ms/step - loss: 1.0620 - mae: 0.7269 - rmse: 1.0238

171/269 ━━━━━━━━━━━━━━━━━━━━ 31s 320ms/step - loss: 1.0602 - mae: 0.7261 - rmse: 1.0229

172/269 ━━━━━━━━━━━━━━━━━━━━ 30s 319ms/step - loss: 1.0584 - mae: 0.7254 - rmse: 1.0220

173/269 ━━━━━━━━━━━━━━━━━━━━ 30s 319ms/step - loss: 1.0566 - mae: 0.7246 - rmse: 1.0210

174/269 ━━━━━━━━━━━━━━━━━━━━ 30s 319ms/step - loss: 1.0548 - mae: 0.7239 - rmse: 1.0201

175/269 ━━━━━━━━━━━━━━━━━━━━ 29s 318ms/step - loss: 1.0530 - mae: 0.7231 - rmse: 1.0192

176/269 ━━━━━━━━━━━━━━━━━━━━ 29s 318ms/step - loss: 1.0513 - mae: 0.7224 - rmse: 1.0183

177/269 ━━━━━━━━━━━━━━━━━━━━ 29s 318ms/step - loss: 1.0495 - mae: 0.7217 - rmse: 1.0174

178/269 ━━━━━━━━━━━━━━━━━━━━ 28s 317ms/step - loss: 1.0477 - mae: 0.7209 - rmse: 1.0165

179/269 ━━━━━━━━━━━━━━━━━━━━ 28s 317ms/step - loss: 1.0460 - mae: 0.7202 - rmse: 1.0155

180/269 ━━━━━━━━━━━━━━━━━━━━ 28s 317ms/step - loss: 1.0442 - mae: 0.7195 - rmse: 1.0146

181/269 ━━━━━━━━━━━━━━━━━━━━ 27s 317ms/step - loss: 1.0425 - mae: 0.7188 - rmse: 1.0137

182/269 ━━━━━━━━━━━━━━━━━━━━ 27s 316ms/step - loss: 1.0407 - mae: 0.7180 - rmse: 1.0128

183/269 ━━━━━━━━━━━━━━━━━━━━ 27s 316ms/step - loss: 1.0390 - mae: 0.7173 - rmse: 1.0119

184/269 ━━━━━━━━━━━━━━━━━━━━ 26s 316ms/step - loss: 1.0372 - mae: 0.7166 - rmse: 1.0110

185/269 ━━━━━━━━━━━━━━━━━━━━ 26s 316ms/step - loss: 1.0355 - mae: 0.7159 - rmse: 1.0101

186/269 ━━━━━━━━━━━━━━━━━━━━ 26s 315ms/step - loss: 1.0338 - mae: 0.7151 - rmse: 1.0092

187/269 ━━━━━━━━━━━━━━━━━━━━ 25s 315ms/step - loss: 1.0320 - mae: 0.7144 - rmse: 1.0083

188/269 ━━━━━━━━━━━━━━━━━━━━ 25s 315ms/step - loss: 1.0303 - mae: 0.7137 - rmse: 1.0074

189/269 ━━━━━━━━━━━━━━━━━━━━ 25s 315ms/step - loss: 1.0286 - mae: 0.7130 - rmse: 1.0065

190/269 ━━━━━━━━━━━━━━━━━━━━ 24s 314ms/step - loss: 1.0269 - mae: 0.7123 - rmse: 1.0056

191/269 ━━━━━━━━━━━━━━━━━━━━ 24s 314ms/step - loss: 1.0251 - mae: 0.7115 - rmse: 1.0047

192/269 ━━━━━━━━━━━━━━━━━━━━ 24s 314ms/step - loss: 1.0234 - mae: 0.7108 - rmse: 1.0038

193/269 ━━━━━━━━━━━━━━━━━━━━ 23s 314ms/step - loss: 1.0217 - mae: 0.7101 - rmse: 1.0029

194/269 ━━━━━━━━━━━━━━━━━━━━ 23s 314ms/step - loss: 1.0200 - mae: 0.7094 - rmse: 1.0020

195/269 ━━━━━━━━━━━━━━━━━━━━ 23s 314ms/step - loss: 1.0183 - mae: 0.7087 - rmse: 1.0011

196/269 ━━━━━━━━━━━━━━━━━━━━ 22s 313ms/step - loss: 1.0166 - mae: 0.7079 - rmse: 1.0002

197/269 ━━━━━━━━━━━━━━━━━━━━ 22s 313ms/step - loss: 1.0149 - mae: 0.7072 - rmse: 0.9993

198/269 ━━━━━━━━━━━━━━━━━━━━ 22s 313ms/step - loss: 1.0133 - mae: 0.7065 - rmse: 0.9984

199/269 ━━━━━━━━━━━━━━━━━━━━ 21s 313ms/step - loss: 1.0116 - mae: 0.7058 - rmse: 0.9975

200/269 ━━━━━━━━━━━━━━━━━━━━ 21s 313ms/step - loss: 1.0099 - mae: 0.7051 - rmse: 0.9966

201/269 ━━━━━━━━━━━━━━━━━━━━ 21s 313ms/step - loss: 1.0082 - mae: 0.7044 - rmse: 0.9957

202/269 ━━━━━━━━━━━━━━━━━━━━ 20s 313ms/step - loss: 1.0066 - mae: 0.7037 - rmse: 0.9948

203/269 ━━━━━━━━━━━━━━━━━━━━ 20s 314ms/step - loss: 1.0050 - mae: 0.7030 - rmse: 0.9940

204/269 ━━━━━━━━━━━━━━━━━━━━ 20s 314ms/step - loss: 1.0034 - mae: 0.7023 - rmse: 0.9931

205/269 ━━━━━━━━━━━━━━━━━━━━ 20s 314ms/step - loss: 1.0018 - mae: 0.7016 - rmse: 0.9923

206/269 ━━━━━━━━━━━━━━━━━━━━ 19s 314ms/step - loss: 1.0002 - mae: 0.7010 - rmse: 0.9914

207/269 ━━━━━━━━━━━━━━━━━━━━ 19s 314ms/step - loss: 0.9986 - mae: 0.7003 - rmse: 0.9906

208/269 ━━━━━━━━━━━━━━━━━━━━ 19s 314ms/step - loss: 0.9970 - mae: 0.6996 - rmse: 0.9898

209/269 ━━━━━━━━━━━━━━━━━━━━ 18s 314ms/step - loss: 0.9955 - mae: 0.6989 - rmse: 0.9889

210/269 ━━━━━━━━━━━━━━━━━━━━ 18s 315ms/step - loss: 0.9939 - mae: 0.6983 - rmse: 0.9881

211/269 ━━━━━━━━━━━━━━━━━━━━ 18s 315ms/step - loss: 0.9923 - mae: 0.6976 - rmse: 0.9872

212/269 ━━━━━━━━━━━━━━━━━━━━ 17s 316ms/step - loss: 0.9908 - mae: 0.6969 - rmse: 0.9864

213/269 ━━━━━━━━━━━━━━━━━━━━ 17s 316ms/step - loss: 0.9892 - mae: 0.6962 - rmse: 0.9856

214/269 ━━━━━━━━━━━━━━━━━━━━ 17s 316ms/step - loss: 0.9876 - mae: 0.6956 - rmse: 0.9847

215/269 ━━━━━━━━━━━━━━━━━━━━ 17s 316ms/step - loss: 0.9861 - mae: 0.6949 - rmse: 0.9839

216/269 ━━━━━━━━━━━━━━━━━━━━ 16s 315ms/step - loss: 0.9845 - mae: 0.6942 - rmse: 0.9830

217/269 ━━━━━━━━━━━━━━━━━━━━ 16s 315ms/step - loss: 0.9830 - mae: 0.6936 - rmse: 0.9822

218/269 ━━━━━━━━━━━━━━━━━━━━ 16s 315ms/step - loss: 0.9814 - mae: 0.6929 - rmse: 0.9814

219/269 ━━━━━━━━━━━━━━━━━━━━ 15s 315ms/step - loss: 0.9799 - mae: 0.6923 - rmse: 0.9806

220/269 ━━━━━━━━━━━━━━━━━━━━ 15s 315ms/step - loss: 0.9784 - mae: 0.6916 - rmse: 0.9797

221/269 ━━━━━━━━━━━━━━━━━━━━ 15s 314ms/step - loss: 0.9769 - mae: 0.6909 - rmse: 0.9789

222/269 ━━━━━━━━━━━━━━━━━━━━ 14s 314ms/step - loss: 0.9753 - mae: 0.6903 - rmse: 0.9781

223/269 ━━━━━━━━━━━━━━━━━━━━ 14s 314ms/step - loss: 0.9738 - mae: 0.6896 - rmse: 0.9773

224/269 ━━━━━━━━━━━━━━━━━━━━ 14s 315ms/step - loss: 0.9723 - mae: 0.6890 - rmse: 0.9764

225/269 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.9708 - mae: 0.6883 - rmse: 0.9756

226/269 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.9693 - mae: 0.6877 - rmse: 0.9748

227/269 ━━━━━━━━━━━━━━━━━━━━ 13s 314ms/step - loss: 0.9678 - mae: 0.6870 - rmse: 0.9740

228/269 ━━━━━━━━━━━━━━━━━━━━ 12s 314ms/step - loss: 0.9662 - mae: 0.6863 - rmse: 0.9731

229/269 ━━━━━━━━━━━━━━━━━━━━ 12s 314ms/step - loss: 0.9647 - mae: 0.6857 - rmse: 0.9723

230/269 ━━━━━━━━━━━━━━━━━━━━ 12s 313ms/step - loss: 0.9632 - mae: 0.6850 - rmse: 0.9715

231/269 ━━━━━━━━━━━━━━━━━━━━ 11s 313ms/step - loss: 0.9617 - mae: 0.6844 - rmse: 0.9707

232/269 ━━━━━━━━━━━━━━━━━━━━ 11s 313ms/step - loss: 0.9602 - mae: 0.6837 - rmse: 0.9699

233/269 ━━━━━━━━━━━━━━━━━━━━ 11s 312ms/step - loss: 0.9588 - mae: 0.6831 - rmse: 0.9691

234/269 ━━━━━━━━━━━━━━━━━━━━ 10s 312ms/step - loss: 0.9573 - mae: 0.6824 - rmse: 0.9682

235/269 ━━━━━━━━━━━━━━━━━━━━ 10s 312ms/step - loss: 0.9558 - mae: 0.6817 - rmse: 0.9674

236/269 ━━━━━━━━━━━━━━━━━━━━ 10s 312ms/step - loss: 0.9543 - mae: 0.6811 - rmse: 0.9666

237/269 ━━━━━━━━━━━━━━━━━━━━ 9s 312ms/step - loss: 0.9529 - mae: 0.6804 - rmse: 0.9658

238/269 ━━━━━━━━━━━━━━━━━━━━ 9s 311ms/step - loss: 0.9514 - mae: 0.6798 - rmse: 0.9650

239/269 ━━━━━━━━━━━━━━━━━━━━ 9s 311ms/step - loss: 0.9499 - mae: 0.6792 - rmse: 0.9642

240/269 ━━━━━━━━━━━━━━━━━━━━ 9s 311ms/step - loss: 0.9485 - mae: 0.6785 - rmse: 0.9634

241/269 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 0.9470 - mae: 0.6779 - rmse: 0.9626

242/269 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 0.9456 - mae: 0.6772 - rmse: 0.9618

243/269 ━━━━━━━━━━━━━━━━━━━━ 8s 311ms/step - loss: 0.9441 - mae: 0.6766 - rmse: 0.9610

244/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.9427 - mae: 0.6760 - rmse: 0.9602

245/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.9413 - mae: 0.6753 - rmse: 0.9594

246/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.9399 - mae: 0.6747 - rmse: 0.9586

247/269 ━━━━━━━━━━━━━━━━━━━━ 6s 310ms/step - loss: 0.9384 - mae: 0.6741 - rmse: 0.9579

248/269 ━━━━━━━━━━━━━━━━━━━━ 6s 309ms/step - loss: 0.9370 - mae: 0.6735 - rmse: 0.9571

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 309ms/step - loss: 0.9356 - mae: 0.6728 - rmse: 0.9563

250/269 ━━━━━━━━━━━━━━━━━━━━ 5s 309ms/step - loss: 0.9342 - mae: 0.6722 - rmse: 0.9555

251/269 ━━━━━━━━━━━━━━━━━━━━ 5s 310ms/step - loss: 0.9328 - mae: 0.6716 - rmse: 0.9547

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 310ms/step - loss: 0.9314 - mae: 0.6710 - rmse: 0.9539

253/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.9300 - mae: 0.6704 - rmse: 0.9532

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.9286 - mae: 0.6697 - rmse: 0.9524

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.9273 - mae: 0.6691 - rmse: 0.9516

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.9259 - mae: 0.6685 - rmse: 0.9509

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 310ms/step - loss: 0.9245 - mae: 0.6679 - rmse: 0.9501

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 310ms/step - loss: 0.9231 - mae: 0.6673 - rmse: 0.9493

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 310ms/step - loss: 0.9218 - mae: 0.6667 - rmse: 0.9485

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 310ms/step - loss: 0.9204 - mae: 0.6661 - rmse: 0.9478

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 310ms/step - loss: 0.9190 - mae: 0.6655 - rmse: 0.9470

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 310ms/step - loss: 0.9177 - mae: 0.6649 - rmse: 0.9463

263/269 ━━━━━━━━━━━━━━━━━━━━ 1s 310ms/step - loss: 0.9163 - mae: 0.6643 - rmse: 0.9455

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 310ms/step - loss: 0.9150 - mae: 0.6637 - rmse: 0.9447

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 310ms/step - loss: 0.9136 - mae: 0.6631 - rmse: 0.9440

266/269 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.9123 - mae: 0.6625 - rmse: 0.9432

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.9110 - mae: 0.6619 - rmse: 0.9425

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.9096 - mae: 0.6613 - rmse: 0.9417

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - loss: 0.9083 - mae: 0.6607 - rmse: 0.9410

269/269 ━━━━━━━━━━━━━━━━━━━━ 90s 336ms/step - loss: 0.5550 - mae: 0.5025 - rmse: 0.7415 - val_loss: 1.0002 - val_mae: 0.6055 - val_rmse: 0.9976 - learning_rate: 0.0010

Epoch 3/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 380ms/step - loss: 1.0769 - mae: 0.6830 - rmse: 1.0353

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 339ms/step - loss: 0.9568 - mae: 0.6582 - rmse: 0.9736

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 319ms/step - loss: 0.9924 - mae: 0.6814 - rmse: 0.9920

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 322ms/step - loss: 0.9993 - mae: 0.6896 - rmse: 0.9959

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 331ms/step - loss: 0.9790 - mae: 0.6854 - rmse: 0.9857

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 331ms/step - loss: 0.9571 - mae: 0.6798 - rmse: 0.9744

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 328ms/step - loss: 0.9516 - mae: 0.6790 - rmse: 0.9717

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 325ms/step - loss: 0.9692 - mae: 0.6855 - rmse: 0.9806

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 325ms/step - loss: 0.9772 - mae: 0.6892 - rmse: 0.9848

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 323ms/step - loss: 0.9784 - mae: 0.6905 - rmse: 0.9855

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 320ms/step - loss: 0.9753 - mae: 0.6903 - rmse: 0.9840

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 316ms/step - loss: 0.9776 - mae: 0.6922 - rmse: 0.9852

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 313ms/step - loss: 0.9872 - mae: 0.6952 - rmse: 0.9900

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 310ms/step - loss: 1.0089 - mae: 0.7016 - rmse: 1.0003

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 312ms/step - loss: 1.0266 - mae: 0.7070 - rmse: 1.0087

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 317ms/step - loss: 1.0446 - mae: 0.7126 - rmse: 1.0172

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 321ms/step - loss: 1.0630 - mae: 0.7179 - rmse: 1.0258

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 325ms/step - loss: 1.0785 - mae: 0.7225 - rmse: 1.0330

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 323ms/step - loss: 1.0950 - mae: 0.7272 - rmse: 1.0406

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 324ms/step - loss: 1.1097 - mae: 0.7316 - rmse: 1.0474

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 322ms/step - loss: 1.1212 - mae: 0.7350 - rmse: 1.0528

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 323ms/step - loss: 1.1315 - mae: 0.7382 - rmse: 1.0576

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 321ms/step - loss: 1.1413 - mae: 0.7415 - rmse: 1.0622

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 319ms/step - loss: 1.1496 - mae: 0.7444 - rmse: 1.0661

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 319ms/step - loss: 1.1565 - mae: 0.7469 - rmse: 1.0693

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 318ms/step - loss: 1.1630 - mae: 0.7492 - rmse: 1.0724

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 317ms/step - loss: 1.1679 - mae: 0.7510 - rmse: 1.0748

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 316ms/step - loss: 1.1717 - mae: 0.7525 - rmse: 1.0766

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 316ms/step - loss: 1.1749 - mae: 0.7538 - rmse: 1.0782

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 315ms/step - loss: 1.1769 - mae: 0.7548 - rmse: 1.0792

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 314ms/step - loss: 1.1780 - mae: 0.7554 - rmse: 1.0798

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 314ms/step - loss: 1.1787 - mae: 0.7560 - rmse: 1.0802

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 315ms/step - loss: 1.1789 - mae: 0.7564 - rmse: 1.0804

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 316ms/step - loss: 1.1788 - mae: 0.7567 - rmse: 1.0805

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 316ms/step - loss: 1.1786 - mae: 0.7570 - rmse: 1.0804

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 315ms/step - loss: 1.1779 - mae: 0.7572 - rmse: 1.0802

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 315ms/step - loss: 1.1771 - mae: 0.7573 - rmse: 1.0799

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 314ms/step - loss: 1.1758 - mae: 0.7572 - rmse: 1.0794

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 313ms/step - loss: 1.1742 - mae: 0.7570 - rmse: 1.0787

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 312ms/step - loss: 1.1723 - mae: 0.7566 - rmse: 1.0779

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 311ms/step - loss: 1.1706 - mae: 0.7563 - rmse: 1.0771

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 311ms/step - loss: 1.1685 - mae: 0.7560 - rmse: 1.0762

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 310ms/step - loss: 1.1664 - mae: 0.7556 - rmse: 1.0753

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 309ms/step - loss: 1.1646 - mae: 0.7552 - rmse: 1.0745

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 308ms/step - loss: 1.1626 - mae: 0.7549 - rmse: 1.0736

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 307ms/step - loss: 1.1605 - mae: 0.7545 - rmse: 1.0726

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 307ms/step - loss: 1.1586 - mae: 0.7542 - rmse: 1.0718

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 307ms/step - loss: 1.1564 - mae: 0.7537 - rmse: 1.0708

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 307ms/step - loss: 1.1541 - mae: 0.7532 - rmse: 1.0697

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 308ms/step - loss: 1.1516 - mae: 0.7526 - rmse: 1.0686

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 308ms/step - loss: 1.1490 - mae: 0.7519 - rmse: 1.0674

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 307ms/step - loss: 1.1463 - mae: 0.7512 - rmse: 1.0661

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 307ms/step - loss: 1.1435 - mae: 0.7505 - rmse: 1.0648

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 307ms/step - loss: 1.1409 - mae: 0.7498 - rmse: 1.0636

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 307ms/step - loss: 1.1383 - mae: 0.7491 - rmse: 1.0624

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 307ms/step - loss: 1.1358 - mae: 0.7484 - rmse: 1.0612

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 307ms/step - loss: 1.1333 - mae: 0.7477 - rmse: 1.0600

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 307ms/step - loss: 1.1308 - mae: 0.7470 - rmse: 1.0588

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 307ms/step - loss: 1.1285 - mae: 0.7464 - rmse: 1.0577

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 307ms/step - loss: 1.1261 - mae: 0.7458 - rmse: 1.0566

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 306ms/step - loss: 1.1239 - mae: 0.7452 - rmse: 1.0555

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 306ms/step - loss: 1.1216 - mae: 0.7446 - rmse: 1.0545

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 306ms/step - loss: 1.1194 - mae: 0.7440 - rmse: 1.0534

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 306ms/step - loss: 1.1170 - mae: 0.7434 - rmse: 1.0523

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 306ms/step - loss: 1.1146 - mae: 0.7427 - rmse: 1.0511

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 306ms/step - loss: 1.1120 - mae: 0.7420 - rmse: 1.0499

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 306ms/step - loss: 1.1095 - mae: 0.7413 - rmse: 1.0487

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 306ms/step - loss: 1.1069 - mae: 0.7406 - rmse: 1.0474

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 306ms/step - loss: 1.1044 - mae: 0.7399 - rmse: 1.0462

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 306ms/step - loss: 1.1020 - mae: 0.7392 - rmse: 1.0450

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 307ms/step - loss: 1.0997 - mae: 0.7385 - rmse: 1.0439

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 308ms/step - loss: 1.0974 - mae: 0.7379 - rmse: 1.0428

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 309ms/step - loss: 1.0952 - mae: 0.7372 - rmse: 1.0417

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 311ms/step - loss: 1.0931 - mae: 0.7366 - rmse: 1.0407

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 312ms/step - loss: 1.0911 - mae: 0.7361 - rmse: 1.0398

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 312ms/step - loss: 1.0891 - mae: 0.7355 - rmse: 1.0388

 77/269 ━━━━━━━━━━━━━━━━━━━━ 59s 312ms/step - loss: 1.0873 - mae: 0.7350 - rmse: 1.0380

 78/269 ━━━━━━━━━━━━━━━━━━━━ 59s 312ms/step - loss: 1.0855 - mae: 0.7345 - rmse: 1.0371

 79/269 ━━━━━━━━━━━━━━━━━━━━ 59s 312ms/step - loss: 1.0838 - mae: 0.7341 - rmse: 1.0363

 80/269 ━━━━━━━━━━━━━━━━━━━━ 58s 311ms/step - loss: 1.0822 - mae: 0.7336 - rmse: 1.0355

 81/269 ━━━━━━━━━━━━━━━━━━━━ 58s 311ms/step - loss: 1.0809 - mae: 0.7333 - rmse: 1.0349

 82/269 ━━━━━━━━━━━━━━━━━━━━ 58s 311ms/step - loss: 1.0801 - mae: 0.7331 - rmse: 1.0346

 83/269 ━━━━━━━━━━━━━━━━━━━━ 57s 311ms/step - loss: 1.0796 - mae: 0.7330 - rmse: 1.0343

 84/269 ━━━━━━━━━━━━━━━━━━━━ 57s 311ms/step - loss: 1.0792 - mae: 0.7329 - rmse: 1.0342

 85/269 ━━━━━━━━━━━━━━━━━━━━ 57s 311ms/step - loss: 1.0789 - mae: 0.7328 - rmse: 1.0340

 86/269 ━━━━━━━━━━━━━━━━━━━━ 56s 310ms/step - loss: 1.0788 - mae: 0.7328 - rmse: 1.0340

 87/269 ━━━━━━━━━━━━━━━━━━━━ 56s 310ms/step - loss: 1.0787 - mae: 0.7328 - rmse: 1.0340

 88/269 ━━━━━━━━━━━━━━━━━━━━ 56s 310ms/step - loss: 1.0785 - mae: 0.7328 - rmse: 1.0339

 89/269 ━━━━━━━━━━━━━━━━━━━━ 55s 311ms/step - loss: 1.0784 - mae: 0.7328 - rmse: 1.0339

 90/269 ━━━━━━━━━━━━━━━━━━━━ 55s 311ms/step - loss: 1.0783 - mae: 0.7329 - rmse: 1.0339

 91/269 ━━━━━━━━━━━━━━━━━━━━ 55s 311ms/step - loss: 1.0782 - mae: 0.7329 - rmse: 1.0338

 92/269 ━━━━━━━━━━━━━━━━━━━━ 55s 311ms/step - loss: 1.0780 - mae: 0.7328 - rmse: 1.0338

 93/269 ━━━━━━━━━━━━━━━━━━━━ 54s 311ms/step - loss: 1.0777 - mae: 0.7328 - rmse: 1.0336

 94/269 ━━━━━━━━━━━━━━━━━━━━ 54s 311ms/step - loss: 1.0773 - mae: 0.7327 - rmse: 1.0335

 95/269 ━━━━━━━━━━━━━━━━━━━━ 54s 311ms/step - loss: 1.0769 - mae: 0.7326 - rmse: 1.0333

 96/269 ━━━━━━━━━━━━━━━━━━━━ 53s 310ms/step - loss: 1.0764 - mae: 0.7325 - rmse: 1.0331

 97/269 ━━━━━━━━━━━━━━━━━━━━ 53s 310ms/step - loss: 1.0758 - mae: 0.7323 - rmse: 1.0328

 98/269 ━━━━━━━━━━━━━━━━━━━━ 52s 310ms/step - loss: 1.0753 - mae: 0.7321 - rmse: 1.0326

 99/269 ━━━━━━━━━━━━━━━━━━━━ 52s 309ms/step - loss: 1.0746 - mae: 0.7319 - rmse: 1.0323

100/269 ━━━━━━━━━━━━━━━━━━━━ 52s 309ms/step - loss: 1.0739 - mae: 0.7317 - rmse: 1.0319

101/269 ━━━━━━━━━━━━━━━━━━━━ 51s 308ms/step - loss: 1.0732 - mae: 0.7315 - rmse: 1.0316

102/269 ━━━━━━━━━━━━━━━━━━━━ 51s 308ms/step - loss: 1.0725 - mae: 0.7313 - rmse: 1.0313

103/269 ━━━━━━━━━━━━━━━━━━━━ 51s 307ms/step - loss: 1.0717 - mae: 0.7310 - rmse: 1.0309

104/269 ━━━━━━━━━━━━━━━━━━━━ 50s 307ms/step - loss: 1.0710 - mae: 0.7308 - rmse: 1.0305

105/269 ━━━━━━━━━━━━━━━━━━━━ 50s 307ms/step - loss: 1.0702 - mae: 0.7306 - rmse: 1.0302

106/269 ━━━━━━━━━━━━━━━━━━━━ 49s 306ms/step - loss: 1.0693 - mae: 0.7303 - rmse: 1.0298

107/269 ━━━━━━━━━━━━━━━━━━━━ 49s 306ms/step - loss: 1.0684 - mae: 0.7300 - rmse: 1.0294

108/269 ━━━━━━━━━━━━━━━━━━━━ 49s 305ms/step - loss: 1.0675 - mae: 0.7297 - rmse: 1.0289

109/269 ━━━━━━━━━━━━━━━━━━━━ 48s 305ms/step - loss: 1.0665 - mae: 0.7294 - rmse: 1.0284

110/269 ━━━━━━━━━━━━━━━━━━━━ 48s 305ms/step - loss: 1.0655 - mae: 0.7290 - rmse: 1.0279

111/269 ━━━━━━━━━━━━━━━━━━━━ 48s 304ms/step - loss: 1.0644 - mae: 0.7287 - rmse: 1.0274

112/269 ━━━━━━━━━━━━━━━━━━━━ 47s 304ms/step - loss: 1.0633 - mae: 0.7283 - rmse: 1.0269

113/269 ━━━━━━━━━━━━━━━━━━━━ 47s 303ms/step - loss: 1.0622 - mae: 0.7279 - rmse: 1.0263

114/269 ━━━━━━━━━━━━━━━━━━━━ 47s 303ms/step - loss: 1.0610 - mae: 0.7275 - rmse: 1.0258

115/269 ━━━━━━━━━━━━━━━━━━━━ 46s 303ms/step - loss: 1.0598 - mae: 0.7270 - rmse: 1.0252

116/269 ━━━━━━━━━━━━━━━━━━━━ 46s 303ms/step - loss: 1.0585 - mae: 0.7266 - rmse: 1.0245

117/269 ━━━━━━━━━━━━━━━━━━━━ 46s 303ms/step - loss: 1.0573 - mae: 0.7261 - rmse: 1.0239

118/269 ━━━━━━━━━━━━━━━━━━━━ 45s 303ms/step - loss: 1.0560 - mae: 0.7256 - rmse: 1.0233

119/269 ━━━━━━━━━━━━━━━━━━━━ 45s 302ms/step - loss: 1.0547 - mae: 0.7251 - rmse: 1.0226

120/269 ━━━━━━━━━━━━━━━━━━━━ 45s 302ms/step - loss: 1.0533 - mae: 0.7246 - rmse: 1.0220

121/269 ━━━━━━━━━━━━━━━━━━━━ 44s 302ms/step - loss: 1.0520 - mae: 0.7241 - rmse: 1.0213

122/269 ━━━━━━━━━━━━━━━━━━━━ 44s 302ms/step - loss: 1.0506 - mae: 0.7236 - rmse: 1.0206

123/269 ━━━━━━━━━━━━━━━━━━━━ 44s 302ms/step - loss: 1.0492 - mae: 0.7230 - rmse: 1.0199

124/269 ━━━━━━━━━━━━━━━━━━━━ 43s 302ms/step - loss: 1.0477 - mae: 0.7224 - rmse: 1.0192

125/269 ━━━━━━━━━━━━━━━━━━━━ 43s 302ms/step - loss: 1.0463 - mae: 0.7219 - rmse: 1.0184

126/269 ━━━━━━━━━━━━━━━━━━━━ 43s 302ms/step - loss: 1.0448 - mae: 0.7213 - rmse: 1.0177

127/269 ━━━━━━━━━━━━━━━━━━━━ 42s 302ms/step - loss: 1.0433 - mae: 0.7207 - rmse: 1.0169

128/269 ━━━━━━━━━━━━━━━━━━━━ 42s 302ms/step - loss: 1.0417 - mae: 0.7200 - rmse: 1.0161

129/269 ━━━━━━━━━━━━━━━━━━━━ 42s 302ms/step - loss: 1.0402 - mae: 0.7194 - rmse: 1.0154

130/269 ━━━━━━━━━━━━━━━━━━━━ 41s 302ms/step - loss: 1.0387 - mae: 0.7188 - rmse: 1.0146

131/269 ━━━━━━━━━━━━━━━━━━━━ 41s 303ms/step - loss: 1.0371 - mae: 0.7182 - rmse: 1.0138

132/269 ━━━━━━━━━━━━━━━━━━━━ 41s 304ms/step - loss: 1.0355 - mae: 0.7175 - rmse: 1.0130

133/269 ━━━━━━━━━━━━━━━━━━━━ 41s 304ms/step - loss: 1.0340 - mae: 0.7169 - rmse: 1.0122

134/269 ━━━━━━━━━━━━━━━━━━━━ 41s 304ms/step - loss: 1.0324 - mae: 0.7162 - rmse: 1.0114

135/269 ━━━━━━━━━━━━━━━━━━━━ 40s 304ms/step - loss: 1.0309 - mae: 0.7156 - rmse: 1.0106

136/269 ━━━━━━━━━━━━━━━━━━━━ 40s 305ms/step - loss: 1.0293 - mae: 0.7150 - rmse: 1.0098

137/269 ━━━━━━━━━━━━━━━━━━━━ 40s 305ms/step - loss: 1.0277 - mae: 0.7143 - rmse: 1.0090

138/269 ━━━━━━━━━━━━━━━━━━━━ 39s 305ms/step - loss: 1.0261 - mae: 0.7137 - rmse: 1.0082

139/269 ━━━━━━━━━━━━━━━━━━━━ 39s 306ms/step - loss: 1.0245 - mae: 0.7130 - rmse: 1.0073

140/269 ━━━━━━━━━━━━━━━━━━━━ 39s 306ms/step - loss: 1.0229 - mae: 0.7124 - rmse: 1.0065

141/269 ━━━━━━━━━━━━━━━━━━━━ 39s 307ms/step - loss: 1.0213 - mae: 0.7117 - rmse: 1.0057

142/269 ━━━━━━━━━━━━━━━━━━━━ 39s 308ms/step - loss: 1.0197 - mae: 0.7111 - rmse: 1.0048

143/269 ━━━━━━━━━━━━━━━━━━━━ 38s 308ms/step - loss: 1.0180 - mae: 0.7104 - rmse: 1.0040

144/269 ━━━━━━━━━━━━━━━━━━━━ 38s 308ms/step - loss: 1.0164 - mae: 0.7097 - rmse: 1.0031

145/269 ━━━━━━━━━━━━━━━━━━━━ 38s 308ms/step - loss: 1.0148 - mae: 0.7090 - rmse: 1.0023

146/269 ━━━━━━━━━━━━━━━━━━━━ 37s 308ms/step - loss: 1.0131 - mae: 0.7083 - rmse: 1.0014

147/269 ━━━━━━━━━━━━━━━━━━━━ 37s 308ms/step - loss: 1.0114 - mae: 0.7076 - rmse: 1.0006

148/269 ━━━━━━━━━━━━━━━━━━━━ 37s 308ms/step - loss: 1.0097 - mae: 0.7069 - rmse: 0.9997

149/269 ━━━━━━━━━━━━━━━━━━━━ 36s 308ms/step - loss: 1.0081 - mae: 0.7062 - rmse: 0.9988

150/269 ━━━━━━━━━━━━━━━━━━━━ 36s 308ms/step - loss: 1.0064 - mae: 0.7055 - rmse: 0.9979

151/269 ━━━━━━━━━━━━━━━━━━━━ 36s 307ms/step - loss: 1.0047 - mae: 0.7048 - rmse: 0.9970

152/269 ━━━━━━━━━━━━━━━━━━━━ 35s 307ms/step - loss: 1.0030 - mae: 0.7041 - rmse: 0.9961

153/269 ━━━━━━━━━━━━━━━━━━━━ 35s 307ms/step - loss: 1.0013 - mae: 0.7033 - rmse: 0.9952

154/269 ━━━━━━━━━━━━━━━━━━━━ 35s 307ms/step - loss: 0.9996 - mae: 0.7026 - rmse: 0.9944

155/269 ━━━━━━━━━━━━━━━━━━━━ 34s 307ms/step - loss: 0.9979 - mae: 0.7019 - rmse: 0.9935

156/269 ━━━━━━━━━━━━━━━━━━━━ 34s 307ms/step - loss: 0.9963 - mae: 0.7012 - rmse: 0.9926

157/269 ━━━━━━━━━━━━━━━━━━━━ 34s 306ms/step - loss: 0.9946 - mae: 0.7004 - rmse: 0.9917

158/269 ━━━━━━━━━━━━━━━━━━━━ 33s 306ms/step - loss: 0.9929 - mae: 0.6997 - rmse: 0.9908

159/269 ━━━━━━━━━━━━━━━━━━━━ 33s 306ms/step - loss: 0.9912 - mae: 0.6990 - rmse: 0.9899

160/269 ━━━━━━━━━━━━━━━━━━━━ 33s 306ms/step - loss: 0.9895 - mae: 0.6982 - rmse: 0.9890

161/269 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - loss: 0.9878 - mae: 0.6975 - rmse: 0.9881

162/269 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - loss: 0.9861 - mae: 0.6968 - rmse: 0.9871

163/269 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - loss: 0.9844 - mae: 0.6960 - rmse: 0.9862

164/269 ━━━━━━━━━━━━━━━━━━━━ 32s 305ms/step - loss: 0.9827 - mae: 0.6953 - rmse: 0.9853

165/269 ━━━━━━━━━━━━━━━━━━━━ 31s 305ms/step - loss: 0.9810 - mae: 0.6946 - rmse: 0.9844

166/269 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.9793 - mae: 0.6938 - rmse: 0.9835

167/269 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.9776 - mae: 0.6931 - rmse: 0.9826

168/269 ━━━━━━━━━━━━━━━━━━━━ 30s 304ms/step - loss: 0.9760 - mae: 0.6924 - rmse: 0.9817

169/269 ━━━━━━━━━━━━━━━━━━━━ 30s 304ms/step - loss: 0.9743 - mae: 0.6917 - rmse: 0.9809

170/269 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 0.9727 - mae: 0.6910 - rmse: 0.9800

171/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.9711 - mae: 0.6903 - rmse: 0.9791

172/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.9695 - mae: 0.6896 - rmse: 0.9783

173/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.9679 - mae: 0.6889 - rmse: 0.9774

174/269 ━━━━━━━━━━━━━━━━━━━━ 28s 303ms/step - loss: 0.9664 - mae: 0.6883 - rmse: 0.9766

175/269 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 0.9648 - mae: 0.6876 - rmse: 0.9757

176/269 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 0.9632 - mae: 0.6869 - rmse: 0.9749

177/269 ━━━━━━━━━━━━━━━━━━━━ 27s 302ms/step - loss: 0.9617 - mae: 0.6863 - rmse: 0.9740

178/269 ━━━━━━━━━━━━━━━━━━━━ 27s 302ms/step - loss: 0.9601 - mae: 0.6856 - rmse: 0.9732

179/269 ━━━━━━━━━━━━━━━━━━━━ 27s 302ms/step - loss: 0.9586 - mae: 0.6850 - rmse: 0.9724

180/269 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 0.9570 - mae: 0.6843 - rmse: 0.9715

181/269 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 0.9555 - mae: 0.6836 - rmse: 0.9707

182/269 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 0.9539 - mae: 0.6830 - rmse: 0.9698

183/269 ━━━━━━━━━━━━━━━━━━━━ 26s 302ms/step - loss: 0.9524 - mae: 0.6823 - rmse: 0.9690

184/269 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 0.9508 - mae: 0.6817 - rmse: 0.9682

185/269 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 0.9493 - mae: 0.6810 - rmse: 0.9673

186/269 ━━━━━━━━━━━━━━━━━━━━ 25s 303ms/step - loss: 0.9477 - mae: 0.6804 - rmse: 0.9665

187/269 ━━━━━━━━━━━━━━━━━━━━ 24s 303ms/step - loss: 0.9462 - mae: 0.6797 - rmse: 0.9656

188/269 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.9446 - mae: 0.6790 - rmse: 0.9648

189/269 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.9431 - mae: 0.6784 - rmse: 0.9639

190/269 ━━━━━━━━━━━━━━━━━━━━ 24s 304ms/step - loss: 0.9416 - mae: 0.6777 - rmse: 0.9631

191/269 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.9400 - mae: 0.6770 - rmse: 0.9623

192/269 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.9385 - mae: 0.6764 - rmse: 0.9614

193/269 ━━━━━━━━━━━━━━━━━━━━ 23s 304ms/step - loss: 0.9370 - mae: 0.6757 - rmse: 0.9606

194/269 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 0.9355 - mae: 0.6750 - rmse: 0.9597

195/269 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 0.9339 - mae: 0.6744 - rmse: 0.9589

196/269 ━━━━━━━━━━━━━━━━━━━━ 22s 305ms/step - loss: 0.9324 - mae: 0.6737 - rmse: 0.9581

197/269 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 0.9309 - mae: 0.6731 - rmse: 0.9572

198/269 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 0.9294 - mae: 0.6724 - rmse: 0.9564

199/269 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 0.9279 - mae: 0.6718 - rmse: 0.9556

200/269 ━━━━━━━━━━━━━━━━━━━━ 21s 305ms/step - loss: 0.9264 - mae: 0.6711 - rmse: 0.9547

201/269 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.9249 - mae: 0.6705 - rmse: 0.9539

202/269 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.9235 - mae: 0.6698 - rmse: 0.9531

203/269 ━━━━━━━━━━━━━━━━━━━━ 20s 305ms/step - loss: 0.9220 - mae: 0.6692 - rmse: 0.9523

204/269 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.9206 - mae: 0.6685 - rmse: 0.9515

205/269 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.9192 - mae: 0.6679 - rmse: 0.9507

206/269 ━━━━━━━━━━━━━━━━━━━━ 19s 304ms/step - loss: 0.9178 - mae: 0.6673 - rmse: 0.9499

207/269 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 0.9164 - mae: 0.6667 - rmse: 0.9492

208/269 ━━━━━━━━━━━━━━━━━━━━ 18s 304ms/step - loss: 0.9149 - mae: 0.6661 - rmse: 0.9484

209/269 ━━━━━━━━━━━━━━━━━━━━ 18s 303ms/step - loss: 0.9135 - mae: 0.6654 - rmse: 0.9476

210/269 ━━━━━━━━━━━━━━━━━━━━ 17s 303ms/step - loss: 0.9121 - mae: 0.6648 - rmse: 0.9468

211/269 ━━━━━━━━━━━━━━━━━━━━ 17s 303ms/step - loss: 0.9107 - mae: 0.6642 - rmse: 0.9460

212/269 ━━━━━━━━━━━━━━━━━━━━ 17s 303ms/step - loss: 0.9093 - mae: 0.6636 - rmse: 0.9452

213/269 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.9079 - mae: 0.6629 - rmse: 0.9445

214/269 ━━━━━━━━━━━━━━━━━━━━ 16s 303ms/step - loss: 0.9065 - mae: 0.6623 - rmse: 0.9437

215/269 ━━━━━━━━━━━━━━━━━━━━ 16s 302ms/step - loss: 0.9051 - mae: 0.6617 - rmse: 0.9429

216/269 ━━━━━━━━━━━━━━━━━━━━ 16s 302ms/step - loss: 0.9037 - mae: 0.6611 - rmse: 0.9421

217/269 ━━━━━━━━━━━━━━━━━━━━ 15s 302ms/step - loss: 0.9024 - mae: 0.6605 - rmse: 0.9413

218/269 ━━━━━━━━━━━━━━━━━━━━ 15s 302ms/step - loss: 0.9010 - mae: 0.6599 - rmse: 0.9406

219/269 ━━━━━━━━━━━━━━━━━━━━ 15s 302ms/step - loss: 0.8996 - mae: 0.6593 - rmse: 0.9398

220/269 ━━━━━━━━━━━━━━━━━━━━ 14s 301ms/step - loss: 0.8982 - mae: 0.6586 - rmse: 0.9390

221/269 ━━━━━━━━━━━━━━━━━━━━ 14s 301ms/step - loss: 0.8969 - mae: 0.6580 - rmse: 0.9383

222/269 ━━━━━━━━━━━━━━━━━━━━ 14s 301ms/step - loss: 0.8955 - mae: 0.6574 - rmse: 0.9375

223/269 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.8941 - mae: 0.6568 - rmse: 0.9367

224/269 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.8928 - mae: 0.6562 - rmse: 0.9359

225/269 ━━━━━━━━━━━━━━━━━━━━ 13s 301ms/step - loss: 0.8914 - mae: 0.6556 - rmse: 0.9352

226/269 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.8901 - mae: 0.6550 - rmse: 0.9344

227/269 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.8887 - mae: 0.6544 - rmse: 0.9336

228/269 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.8873 - mae: 0.6538 - rmse: 0.9329

229/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8860 - mae: 0.6532 - rmse: 0.9321

230/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8846 - mae: 0.6525 - rmse: 0.9313

231/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8833 - mae: 0.6519 - rmse: 0.9305

232/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8819 - mae: 0.6513 - rmse: 0.9298

233/269 ━━━━━━━━━━━━━━━━━━━━ 10s 300ms/step - loss: 0.8806 - mae: 0.6507 - rmse: 0.9290

234/269 ━━━━━━━━━━━━━━━━━━━━ 10s 300ms/step - loss: 0.8793 - mae: 0.6501 - rmse: 0.9283

235/269 ━━━━━━━━━━━━━━━━━━━━ 10s 300ms/step - loss: 0.8779 - mae: 0.6495 - rmse: 0.9275

236/269 ━━━━━━━━━━━━━━━━━━━━ 9s 301ms/step - loss: 0.8766 - mae: 0.6489 - rmse: 0.9267

237/269 ━━━━━━━━━━━━━━━━━━━━ 9s 302ms/step - loss: 0.8753 - mae: 0.6483 - rmse: 0.9260

238/269 ━━━━━━━━━━━━━━━━━━━━ 9s 302ms/step - loss: 0.8740 - mae: 0.6477 - rmse: 0.9252

239/269 ━━━━━━━━━━━━━━━━━━━━ 9s 303ms/step - loss: 0.8727 - mae: 0.6471 - rmse: 0.9245

240/269 ━━━━━━━━━━━━━━━━━━━━ 8s 303ms/step - loss: 0.8714 - mae: 0.6465 - rmse: 0.9237

241/269 ━━━━━━━━━━━━━━━━━━━━ 8s 303ms/step - loss: 0.8701 - mae: 0.6459 - rmse: 0.9230

242/269 ━━━━━━━━━━━━━━━━━━━━ 8s 304ms/step - loss: 0.8688 - mae: 0.6453 - rmse: 0.9222

243/269 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.8675 - mae: 0.6447 - rmse: 0.9215

244/269 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.8662 - mae: 0.6441 - rmse: 0.9207

245/269 ━━━━━━━━━━━━━━━━━━━━ 7s 304ms/step - loss: 0.8649 - mae: 0.6435 - rmse: 0.9200

246/269 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.8636 - mae: 0.6429 - rmse: 0.9192

247/269 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.8623 - mae: 0.6424 - rmse: 0.9185

248/269 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - loss: 0.8610 - mae: 0.6418 - rmse: 0.9178

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 303ms/step - loss: 0.8598 - mae: 0.6412 - rmse: 0.9170

250/269 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.8585 - mae: 0.6406 - rmse: 0.9163

251/269 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.8572 - mae: 0.6401 - rmse: 0.9156

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 303ms/step - loss: 0.8560 - mae: 0.6395 - rmse: 0.9148

253/269 ━━━━━━━━━━━━━━━━━━━━ 4s 303ms/step - loss: 0.8547 - mae: 0.6389 - rmse: 0.9141

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 303ms/step - loss: 0.8535 - mae: 0.6383 - rmse: 0.9134

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 303ms/step - loss: 0.8522 - mae: 0.6378 - rmse: 0.9127

256/269 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.8510 - mae: 0.6372 - rmse: 0.9119

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.8497 - mae: 0.6366 - rmse: 0.9112

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.8485 - mae: 0.6361 - rmse: 0.9105

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 303ms/step - loss: 0.8473 - mae: 0.6355 - rmse: 0.9098

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.8460 - mae: 0.6349 - rmse: 0.9090

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.8448 - mae: 0.6344 - rmse: 0.9083

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - loss: 0.8436 - mae: 0.6338 - rmse: 0.9076

263/269 ━━━━━━━━━━━━━━━━━━━━ 1s 303ms/step - loss: 0.8424 - mae: 0.6332 - rmse: 0.9069

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 302ms/step - loss: 0.8412 - mae: 0.6327 - rmse: 0.9062

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 302ms/step - loss: 0.8399 - mae: 0.6321 - rmse: 0.9055

266/269 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.8387 - mae: 0.6315 - rmse: 0.9048

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.8375 - mae: 0.6310 - rmse: 0.9040

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - loss: 0.8363 - mae: 0.6304 - rmse: 0.9033

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step - loss: 0.8351 - mae: 0.6299 - rmse: 0.9026

269/269 ━━━━━━━━━━━━━━━━━━━━ 92s 340ms/step - loss: 0.5163 - mae: 0.4826 - rmse: 0.7150 - val_loss: 0.9422 - val_mae: 0.5863 - val_rmse: 0.9681 - learning_rate: 0.0010

Epoch 4/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 345ms/step - loss: 1.0394 - mae: 0.6596 - rmse: 1.0171

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 315ms/step - loss: 0.9169 - mae: 0.6349 - rmse: 0.9527

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 297ms/step - loss: 0.9416 - mae: 0.6559 - rmse: 0.9662

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 295ms/step - loss: 0.9401 - mae: 0.6621 - rmse: 0.9658

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 307ms/step - loss: 0.9165 - mae: 0.6568 - rmse: 0.9534

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 309ms/step - loss: 0.8937 - mae: 0.6513 - rmse: 0.9412

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 303ms/step - loss: 0.8878 - mae: 0.6509 - rmse: 0.9383

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 297ms/step - loss: 0.9026 - mae: 0.6571 - rmse: 0.9460

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 297ms/step - loss: 0.9095 - mae: 0.6608 - rmse: 0.9498

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 298ms/step - loss: 0.9103 - mae: 0.6622 - rmse: 0.9503

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 296ms/step - loss: 0.9078 - mae: 0.6624 - rmse: 0.9491

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 292ms/step - loss: 0.9120 - mae: 0.6653 - rmse: 0.9514

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 289ms/step - loss: 0.9226 - mae: 0.6689 - rmse: 0.9568

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 287ms/step - loss: 0.9437 - mae: 0.6757 - rmse: 0.9671

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 284ms/step - loss: 0.9609 - mae: 0.6814 - rmse: 0.9756

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 282ms/step - loss: 0.9787 - mae: 0.6875 - rmse: 0.9843

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 283ms/step - loss: 0.9968 - mae: 0.6931 - rmse: 0.9929

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 285ms/step - loss: 1.0124 - mae: 0.6980 - rmse: 1.0004

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 285ms/step - loss: 1.0286 - mae: 0.7029 - rmse: 1.0081

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 284ms/step - loss: 1.0432 - mae: 0.7075 - rmse: 1.0151

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 285ms/step - loss: 1.0546 - mae: 0.7110 - rmse: 1.0206

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 285ms/step - loss: 1.0649 - mae: 0.7144 - rmse: 1.0255

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 284ms/step - loss: 1.0746 - mae: 0.7178 - rmse: 1.0302

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 283ms/step - loss: 1.0829 - mae: 0.7208 - rmse: 1.0342

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 285ms/step - loss: 1.0899 - mae: 0.7234 - rmse: 1.0376

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 286ms/step - loss: 1.0966 - mae: 0.7259 - rmse: 1.0409

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 285ms/step - loss: 1.1019 - mae: 0.7278 - rmse: 1.0434

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 284ms/step - loss: 1.1060 - mae: 0.7295 - rmse: 1.0455

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 289ms/step - loss: 1.1094 - mae: 0.7310 - rmse: 1.0472

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 290ms/step - loss: 1.1117 - mae: 0.7321 - rmse: 1.0484

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 288ms/step - loss: 1.1131 - mae: 0.7328 - rmse: 1.0492

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 287ms/step - loss: 1.1140 - mae: 0.7335 - rmse: 1.0497

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 287ms/step - loss: 1.1145 - mae: 0.7340 - rmse: 1.0501

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 287ms/step - loss: 1.1145 - mae: 0.7343 - rmse: 1.0502

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 286ms/step - loss: 1.1146 - mae: 0.7347 - rmse: 1.0503

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 285ms/step - loss: 1.1141 - mae: 0.7350 - rmse: 1.0502

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 285ms/step - loss: 1.1135 - mae: 0.7351 - rmse: 1.0499

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 284ms/step - loss: 1.1124 - mae: 0.7350 - rmse: 1.0495

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 284ms/step - loss: 1.1111 - mae: 0.7349 - rmse: 1.0489

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 284ms/step - loss: 1.1094 - mae: 0.7346 - rmse: 1.0482

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 285ms/step - loss: 1.1078 - mae: 0.7343 - rmse: 1.0475

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 286ms/step - loss: 1.1059 - mae: 0.7339 - rmse: 1.0466

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 286ms/step - loss: 1.1040 - mae: 0.7335 - rmse: 1.0458

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 286ms/step - loss: 1.1023 - mae: 0.7332 - rmse: 1.0450

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 286ms/step - loss: 1.1005 - mae: 0.7328 - rmse: 1.0442

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 286ms/step - loss: 1.0985 - mae: 0.7324 - rmse: 1.0432

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 287ms/step - loss: 1.0967 - mae: 0.7320 - rmse: 1.0424

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 288ms/step - loss: 1.0946 - mae: 0.7315 - rmse: 1.0415

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 288ms/step - loss: 1.0924 - mae: 0.7310 - rmse: 1.0404

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 289ms/step - loss: 1.0900 - mae: 0.7303 - rmse: 1.0393

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 290ms/step - loss: 1.0876 - mae: 0.7296 - rmse: 1.0381

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 290ms/step - loss: 1.0850 - mae: 0.7289 - rmse: 1.0369

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 291ms/step - loss: 1.0823 - mae: 0.7281 - rmse: 1.0356

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 291ms/step - loss: 1.0799 - mae: 0.7275 - rmse: 1.0344

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 291ms/step - loss: 1.0774 - mae: 0.7267 - rmse: 1.0332

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 291ms/step - loss: 1.0750 - mae: 0.7261 - rmse: 1.0321

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 291ms/step - loss: 1.0727 - mae: 0.7253 - rmse: 1.0309

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 291ms/step - loss: 1.0702 - mae: 0.7246 - rmse: 1.0298

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 291ms/step - loss: 1.0680 - mae: 0.7240 - rmse: 1.0287

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 290ms/step - loss: 1.0658 - mae: 0.7233 - rmse: 1.0276

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 291ms/step - loss: 1.0637 - mae: 0.7227 - rmse: 1.0266

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 292ms/step - loss: 1.0616 - mae: 0.7222 - rmse: 1.0256

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 293ms/step - loss: 1.0594 - mae: 0.7216 - rmse: 1.0246

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 294ms/step - loss: 1.0572 - mae: 0.7209 - rmse: 1.0235

 65/269 ━━━━━━━━━━━━━━━━━━━━ 59s 294ms/step - loss: 1.0549 - mae: 0.7203 - rmse: 1.0223

 66/269 ━━━━━━━━━━━━━━━━━━━━ 59s 294ms/step - loss: 1.0526 - mae: 0.7196 - rmse: 1.0212

 67/269 ━━━━━━━━━━━━━━━━━━━━ 59s 295ms/step - loss: 1.0502 - mae: 0.7188 - rmse: 1.0200

 68/269 ━━━━━━━━━━━━━━━━━━━━ 59s 295ms/step - loss: 1.0478 - mae: 0.7181 - rmse: 1.0188

 69/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 1.0454 - mae: 0.7174 - rmse: 1.0176

 70/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 1.0431 - mae: 0.7167 - rmse: 1.0165

 71/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 1.0409 - mae: 0.7161 - rmse: 1.0154

 72/269 ━━━━━━━━━━━━━━━━━━━━ 57s 294ms/step - loss: 1.0388 - mae: 0.7154 - rmse: 1.0144

 73/269 ━━━━━━━━━━━━━━━━━━━━ 57s 293ms/step - loss: 1.0367 - mae: 0.7148 - rmse: 1.0133

 74/269 ━━━━━━━━━━━━━━━━━━━━ 57s 293ms/step - loss: 1.0347 - mae: 0.7142 - rmse: 1.0123

 75/269 ━━━━━━━━━━━━━━━━━━━━ 56s 293ms/step - loss: 1.0329 - mae: 0.7136 - rmse: 1.0114

 76/269 ━━━━━━━━━━━━━━━━━━━━ 56s 293ms/step - loss: 1.0310 - mae: 0.7131 - rmse: 1.0105

 77/269 ━━━━━━━━━━━━━━━━━━━━ 56s 292ms/step - loss: 1.0293 - mae: 0.7126 - rmse: 1.0097

 78/269 ━━━━━━━━━━━━━━━━━━━━ 55s 292ms/step - loss: 1.0276 - mae: 0.7121 - rmse: 1.0088

 79/269 ━━━━━━━━━━━━━━━━━━━━ 55s 292ms/step - loss: 1.0260 - mae: 0.7117 - rmse: 1.0081

 80/269 ━━━━━━━━━━━━━━━━━━━━ 55s 292ms/step - loss: 1.0244 - mae: 0.7112 - rmse: 1.0073

 81/269 ━━━━━━━━━━━━━━━━━━━━ 54s 292ms/step - loss: 1.0233 - mae: 0.7109 - rmse: 1.0067

 82/269 ━━━━━━━━━━━━━━━━━━━━ 54s 291ms/step - loss: 1.0226 - mae: 0.7107 - rmse: 1.0064

 83/269 ━━━━━━━━━━━━━━━━━━━━ 54s 291ms/step - loss: 1.0220 - mae: 0.7106 - rmse: 1.0061

 84/269 ━━━━━━━━━━━━━━━━━━━━ 53s 291ms/step - loss: 1.0217 - mae: 0.7105 - rmse: 1.0060

 85/269 ━━━━━━━━━━━━━━━━━━━━ 53s 291ms/step - loss: 1.0214 - mae: 0.7104 - rmse: 1.0059

 86/269 ━━━━━━━━━━━━━━━━━━━━ 53s 290ms/step - loss: 1.0213 - mae: 0.7104 - rmse: 1.0058

 87/269 ━━━━━━━━━━━━━━━━━━━━ 52s 290ms/step - loss: 1.0212 - mae: 0.7104 - rmse: 1.0058

 88/269 ━━━━━━━━━━━━━━━━━━━━ 52s 290ms/step - loss: 1.0210 - mae: 0.7104 - rmse: 1.0058

 89/269 ━━━━━━━━━━━━━━━━━━━━ 52s 290ms/step - loss: 1.0209 - mae: 0.7104 - rmse: 1.0057

 90/269 ━━━━━━━━━━━━━━━━━━━━ 51s 290ms/step - loss: 1.0208 - mae: 0.7104 - rmse: 1.0057

 91/269 ━━━━━━━━━━━━━━━━━━━━ 51s 290ms/step - loss: 1.0206 - mae: 0.7104 - rmse: 1.0056

 92/269 ━━━━━━━━━━━━━━━━━━━━ 51s 290ms/step - loss: 1.0203 - mae: 0.7103 - rmse: 1.0055

 93/269 ━━━━━━━━━━━━━━━━━━━━ 51s 290ms/step - loss: 1.0200 - mae: 0.7103 - rmse: 1.0054

 94/269 ━━━━━━━━━━━━━━━━━━━━ 50s 290ms/step - loss: 1.0196 - mae: 0.7102 - rmse: 1.0052

 95/269 ━━━━━━━━━━━━━━━━━━━━ 50s 291ms/step - loss: 1.0192 - mae: 0.7100 - rmse: 1.0050

 96/269 ━━━━━━━━━━━━━━━━━━━━ 50s 291ms/step - loss: 1.0187 - mae: 0.7099 - rmse: 1.0048

 97/269 ━━━━━━━━━━━━━━━━━━━━ 50s 292ms/step - loss: 1.0181 - mae: 0.7097 - rmse: 1.0045

 98/269 ━━━━━━━━━━━━━━━━━━━━ 49s 292ms/step - loss: 1.0175 - mae: 0.7096 - rmse: 1.0043

 99/269 ━━━━━━━━━━━━━━━━━━━━ 49s 294ms/step - loss: 1.0169 - mae: 0.7094 - rmse: 1.0039

100/269 ━━━━━━━━━━━━━━━━━━━━ 49s 295ms/step - loss: 1.0162 - mae: 0.7091 - rmse: 1.0036

101/269 ━━━━━━━━━━━━━━━━━━━━ 49s 296ms/step - loss: 1.0155 - mae: 0.7089 - rmse: 1.0033

102/269 ━━━━━━━━━━━━━━━━━━━━ 49s 297ms/step - loss: 1.0148 - mae: 0.7087 - rmse: 1.0030

103/269 ━━━━━━━━━━━━━━━━━━━━ 49s 298ms/step - loss: 1.0141 - mae: 0.7085 - rmse: 1.0026

104/269 ━━━━━━━━━━━━━━━━━━━━ 49s 298ms/step - loss: 1.0134 - mae: 0.7083 - rmse: 1.0023

105/269 ━━━━━━━━━━━━━━━━━━━━ 48s 299ms/step - loss: 1.0126 - mae: 0.7080 - rmse: 1.0019

106/269 ━━━━━━━━━━━━━━━━━━━━ 48s 300ms/step - loss: 1.0118 - mae: 0.7078 - rmse: 1.0015

107/269 ━━━━━━━━━━━━━━━━━━━━ 48s 301ms/step - loss: 1.0110 - mae: 0.7075 - rmse: 1.0011

108/269 ━━━━━━━━━━━━━━━━━━━━ 48s 301ms/step - loss: 1.0101 - mae: 0.7072 - rmse: 1.0007

109/269 ━━━━━━━━━━━━━━━━━━━━ 48s 302ms/step - loss: 1.0092 - mae: 0.7069 - rmse: 1.0002

110/269 ━━━━━━━━━━━━━━━━━━━━ 48s 302ms/step - loss: 1.0082 - mae: 0.7065 - rmse: 0.9997

111/269 ━━━━━━━━━━━━━━━━━━━━ 47s 303ms/step - loss: 1.0071 - mae: 0.7062 - rmse: 0.9992

112/269 ━━━━━━━━━━━━━━━━━━━━ 47s 303ms/step - loss: 1.0061 - mae: 0.7058 - rmse: 0.9987

113/269 ━━━━━━━━━━━━━━━━━━━━ 47s 303ms/step - loss: 1.0050 - mae: 0.7054 - rmse: 0.9981

114/269 ━━━━━━━━━━━━━━━━━━━━ 47s 304ms/step - loss: 1.0039 - mae: 0.7049 - rmse: 0.9975

115/269 ━━━━━━━━━━━━━━━━━━━━ 46s 304ms/step - loss: 1.0027 - mae: 0.7045 - rmse: 0.9970

116/269 ━━━━━━━━━━━━━━━━━━━━ 46s 304ms/step - loss: 1.0015 - mae: 0.7040 - rmse: 0.9964

117/269 ━━━━━━━━━━━━━━━━━━━━ 46s 304ms/step - loss: 1.0003 - mae: 0.7036 - rmse: 0.9957

118/269 ━━━━━━━━━━━━━━━━━━━━ 45s 303ms/step - loss: 0.9990 - mae: 0.7031 - rmse: 0.9951

119/269 ━━━━━━━━━━━━━━━━━━━━ 45s 303ms/step - loss: 0.9978 - mae: 0.7026 - rmse: 0.9945

120/269 ━━━━━━━━━━━━━━━━━━━━ 45s 303ms/step - loss: 0.9965 - mae: 0.7021 - rmse: 0.9938

121/269 ━━━━━━━━━━━━━━━━━━━━ 44s 303ms/step - loss: 0.9952 - mae: 0.7016 - rmse: 0.9932

122/269 ━━━━━━━━━━━━━━━━━━━━ 44s 302ms/step - loss: 0.9939 - mae: 0.7010 - rmse: 0.9925

123/269 ━━━━━━━━━━━━━━━━━━━━ 44s 303ms/step - loss: 0.9925 - mae: 0.7005 - rmse: 0.9918

124/269 ━━━━━━━━━━━━━━━━━━━━ 43s 303ms/step - loss: 0.9912 - mae: 0.6999 - rmse: 0.9911

125/269 ━━━━━━━━━━━━━━━━━━━━ 43s 303ms/step - loss: 0.9898 - mae: 0.6994 - rmse: 0.9904

126/269 ━━━━━━━━━━━━━━━━━━━━ 43s 303ms/step - loss: 0.9884 - mae: 0.6988 - rmse: 0.9896

127/269 ━━━━━━━━━━━━━━━━━━━━ 42s 303ms/step - loss: 0.9869 - mae: 0.6982 - rmse: 0.9889

128/269 ━━━━━━━━━━━━━━━━━━━━ 42s 303ms/step - loss: 0.9855 - mae: 0.6976 - rmse: 0.9881

129/269 ━━━━━━━━━━━━━━━━━━━━ 42s 302ms/step - loss: 0.9840 - mae: 0.6970 - rmse: 0.9874

130/269 ━━━━━━━━━━━━━━━━━━━━ 41s 302ms/step - loss: 0.9825 - mae: 0.6963 - rmse: 0.9866

131/269 ━━━━━━━━━━━━━━━━━━━━ 41s 302ms/step - loss: 0.9811 - mae: 0.6957 - rmse: 0.9858

132/269 ━━━━━━━━━━━━━━━━━━━━ 41s 302ms/step - loss: 0.9796 - mae: 0.6951 - rmse: 0.9850

133/269 ━━━━━━━━━━━━━━━━━━━━ 40s 301ms/step - loss: 0.9781 - mae: 0.6945 - rmse: 0.9843

134/269 ━━━━━━━━━━━━━━━━━━━━ 40s 301ms/step - loss: 0.9766 - mae: 0.6939 - rmse: 0.9835

135/269 ━━━━━━━━━━━━━━━━━━━━ 40s 301ms/step - loss: 0.9751 - mae: 0.6932 - rmse: 0.9827

136/269 ━━━━━━━━━━━━━━━━━━━━ 39s 301ms/step - loss: 0.9736 - mae: 0.6926 - rmse: 0.9819

137/269 ━━━━━━━━━━━━━━━━━━━━ 39s 300ms/step - loss: 0.9721 - mae: 0.6920 - rmse: 0.9811

138/269 ━━━━━━━━━━━━━━━━━━━━ 39s 300ms/step - loss: 0.9706 - mae: 0.6913 - rmse: 0.9803

139/269 ━━━━━━━━━━━━━━━━━━━━ 39s 300ms/step - loss: 0.9691 - mae: 0.6907 - rmse: 0.9795

140/269 ━━━━━━━━━━━━━━━━━━━━ 38s 300ms/step - loss: 0.9676 - mae: 0.6901 - rmse: 0.9787

141/269 ━━━━━━━━━━━━━━━━━━━━ 38s 300ms/step - loss: 0.9660 - mae: 0.6894 - rmse: 0.9779

142/269 ━━━━━━━━━━━━━━━━━━━━ 38s 299ms/step - loss: 0.9645 - mae: 0.6888 - rmse: 0.9771

143/269 ━━━━━━━━━━━━━━━━━━━━ 37s 299ms/step - loss: 0.9629 - mae: 0.6881 - rmse: 0.9763

144/269 ━━━━━━━━━━━━━━━━━━━━ 37s 299ms/step - loss: 0.9614 - mae: 0.6874 - rmse: 0.9754

145/269 ━━━━━━━━━━━━━━━━━━━━ 36s 298ms/step - loss: 0.9598 - mae: 0.6868 - rmse: 0.9746

146/269 ━━━━━━━━━━━━━━━━━━━━ 36s 298ms/step - loss: 0.9582 - mae: 0.6861 - rmse: 0.9737

147/269 ━━━━━━━━━━━━━━━━━━━━ 36s 298ms/step - loss: 0.9566 - mae: 0.6854 - rmse: 0.9729

148/269 ━━━━━━━━━━━━━━━━━━━━ 36s 298ms/step - loss: 0.9550 - mae: 0.6847 - rmse: 0.9720

149/269 ━━━━━━━━━━━━━━━━━━━━ 35s 298ms/step - loss: 0.9534 - mae: 0.6840 - rmse: 0.9712

150/269 ━━━━━━━━━━━━━━━━━━━━ 35s 298ms/step - loss: 0.9518 - mae: 0.6833 - rmse: 0.9703

151/269 ━━━━━━━━━━━━━━━━━━━━ 35s 298ms/step - loss: 0.9502 - mae: 0.6825 - rmse: 0.9694

152/269 ━━━━━━━━━━━━━━━━━━━━ 34s 298ms/step - loss: 0.9486 - mae: 0.6818 - rmse: 0.9685

153/269 ━━━━━━━━━━━━━━━━━━━━ 34s 298ms/step - loss: 0.9470 - mae: 0.6811 - rmse: 0.9677

154/269 ━━━━━━━━━━━━━━━━━━━━ 34s 298ms/step - loss: 0.9454 - mae: 0.6804 - rmse: 0.9668

155/269 ━━━━━━━━━━━━━━━━━━━━ 34s 300ms/step - loss: 0.9438 - mae: 0.6797 - rmse: 0.9659

156/269 ━━━━━━━━━━━━━━━━━━━━ 33s 300ms/step - loss: 0.9422 - mae: 0.6790 - rmse: 0.9651

157/269 ━━━━━━━━━━━━━━━━━━━━ 33s 300ms/step - loss: 0.9406 - mae: 0.6783 - rmse: 0.9642

158/269 ━━━━━━━━━━━━━━━━━━━━ 33s 300ms/step - loss: 0.9389 - mae: 0.6775 - rmse: 0.9633

159/269 ━━━━━━━━━━━━━━━━━━━━ 33s 301ms/step - loss: 0.9373 - mae: 0.6768 - rmse: 0.9624

160/269 ━━━━━━━━━━━━━━━━━━━━ 32s 301ms/step - loss: 0.9357 - mae: 0.6761 - rmse: 0.9615

161/269 ━━━━━━━━━━━━━━━━━━━━ 32s 301ms/step - loss: 0.9341 - mae: 0.6754 - rmse: 0.9606

162/269 ━━━━━━━━━━━━━━━━━━━━ 32s 302ms/step - loss: 0.9325 - mae: 0.6746 - rmse: 0.9597

163/269 ━━━━━━━━━━━━━━━━━━━━ 31s 302ms/step - loss: 0.9309 - mae: 0.6739 - rmse: 0.9589

164/269 ━━━━━━━━━━━━━━━━━━━━ 31s 302ms/step - loss: 0.9292 - mae: 0.6732 - rmse: 0.9580

165/269 ━━━━━━━━━━━━━━━━━━━━ 31s 302ms/step - loss: 0.9276 - mae: 0.6725 - rmse: 0.9571

166/269 ━━━━━━━━━━━━━━━━━━━━ 31s 302ms/step - loss: 0.9260 - mae: 0.6717 - rmse: 0.9562

167/269 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.9244 - mae: 0.6710 - rmse: 0.9553

168/269 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.9229 - mae: 0.6703 - rmse: 0.9544

169/269 ━━━━━━━━━━━━━━━━━━━━ 30s 302ms/step - loss: 0.9213 - mae: 0.6696 - rmse: 0.9536

170/269 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 0.9198 - mae: 0.6689 - rmse: 0.9527

171/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.9182 - mae: 0.6683 - rmse: 0.9519

172/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.9167 - mae: 0.6676 - rmse: 0.9511

173/269 ━━━━━━━━━━━━━━━━━━━━ 29s 302ms/step - loss: 0.9152 - mae: 0.6669 - rmse: 0.9502

174/269 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 0.9137 - mae: 0.6663 - rmse: 0.9494

175/269 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 0.9123 - mae: 0.6656 - rmse: 0.9486

176/269 ━━━━━━━━━━━━━━━━━━━━ 28s 302ms/step - loss: 0.9108 - mae: 0.6650 - rmse: 0.9478

177/269 ━━━━━━━━━━━━━━━━━━━━ 27s 301ms/step - loss: 0.9093 - mae: 0.6643 - rmse: 0.9469

178/269 ━━━━━━━━━━━━━━━━━━━━ 27s 301ms/step - loss: 0.9078 - mae: 0.6637 - rmse: 0.9461

179/269 ━━━━━━━━━━━━━━━━━━━━ 27s 301ms/step - loss: 0.9063 - mae: 0.6630 - rmse: 0.9453

180/269 ━━━━━━━━━━━━━━━━━━━━ 26s 301ms/step - loss: 0.9049 - mae: 0.6624 - rmse: 0.9445

181/269 ━━━━━━━━━━━━━━━━━━━━ 26s 301ms/step - loss: 0.9034 - mae: 0.6617 - rmse: 0.9437

182/269 ━━━━━━━━━━━━━━━━━━━━ 26s 300ms/step - loss: 0.9019 - mae: 0.6611 - rmse: 0.9428

183/269 ━━━━━━━━━━━━━━━━━━━━ 25s 300ms/step - loss: 0.9005 - mae: 0.6604 - rmse: 0.9420

184/269 ━━━━━━━━━━━━━━━━━━━━ 25s 300ms/step - loss: 0.8990 - mae: 0.6598 - rmse: 0.9412

185/269 ━━━━━━━━━━━━━━━━━━━━ 25s 300ms/step - loss: 0.8975 - mae: 0.6592 - rmse: 0.9404

186/269 ━━━━━━━━━━━━━━━━━━━━ 24s 299ms/step - loss: 0.8961 - mae: 0.6585 - rmse: 0.9396

187/269 ━━━━━━━━━━━━━━━━━━━━ 24s 300ms/step - loss: 0.8946 - mae: 0.6579 - rmse: 0.9387

188/269 ━━━━━━━━━━━━━━━━━━━━ 24s 300ms/step - loss: 0.8931 - mae: 0.6572 - rmse: 0.9379

189/269 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.8917 - mae: 0.6565 - rmse: 0.9371

190/269 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.8902 - mae: 0.6559 - rmse: 0.9363

191/269 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.8888 - mae: 0.6552 - rmse: 0.9354

192/269 ━━━━━━━━━━━━━━━━━━━━ 23s 299ms/step - loss: 0.8873 - mae: 0.6546 - rmse: 0.9346

193/269 ━━━━━━━━━━━━━━━━━━━━ 22s 299ms/step - loss: 0.8859 - mae: 0.6539 - rmse: 0.9338

194/269 ━━━━━━━━━━━━━━━━━━━━ 22s 299ms/step - loss: 0.8844 - mae: 0.6533 - rmse: 0.9330

195/269 ━━━━━━━━━━━━━━━━━━━━ 22s 298ms/step - loss: 0.8830 - mae: 0.6526 - rmse: 0.9321

196/269 ━━━━━━━━━━━━━━━━━━━━ 21s 299ms/step - loss: 0.8815 - mae: 0.6520 - rmse: 0.9313

197/269 ━━━━━━━━━━━━━━━━━━━━ 21s 298ms/step - loss: 0.8801 - mae: 0.6513 - rmse: 0.9305

198/269 ━━━━━━━━━━━━━━━━━━━━ 21s 298ms/step - loss: 0.8787 - mae: 0.6507 - rmse: 0.9297

199/269 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.8772 - mae: 0.6500 - rmse: 0.9289

200/269 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.8758 - mae: 0.6494 - rmse: 0.9281

201/269 ━━━━━━━━━━━━━━━━━━━━ 20s 298ms/step - loss: 0.8744 - mae: 0.6487 - rmse: 0.9273

202/269 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.8730 - mae: 0.6481 - rmse: 0.9265

203/269 ━━━━━━━━━━━━━━━━━━━━ 19s 298ms/step - loss: 0.8716 - mae: 0.6475 - rmse: 0.9257

204/269 ━━━━━━━━━━━━━━━━━━━━ 19s 299ms/step - loss: 0.8703 - mae: 0.6469 - rmse: 0.9249

205/269 ━━━━━━━━━━━━━━━━━━━━ 19s 299ms/step - loss: 0.8689 - mae: 0.6462 - rmse: 0.9241

206/269 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.8676 - mae: 0.6456 - rmse: 0.9234

207/269 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.8662 - mae: 0.6450 - rmse: 0.9226

208/269 ━━━━━━━━━━━━━━━━━━━━ 18s 299ms/step - loss: 0.8649 - mae: 0.6444 - rmse: 0.9218

209/269 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.8635 - mae: 0.6438 - rmse: 0.9211

210/269 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.8622 - mae: 0.6432 - rmse: 0.9203

211/269 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.8608 - mae: 0.6425 - rmse: 0.9195

212/269 ━━━━━━━━━━━━━━━━━━━━ 17s 299ms/step - loss: 0.8595 - mae: 0.6419 - rmse: 0.9188

213/269 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.8582 - mae: 0.6413 - rmse: 0.9180

214/269 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.8569 - mae: 0.6407 - rmse: 0.9172

215/269 ━━━━━━━━━━━━━━━━━━━━ 16s 299ms/step - loss: 0.8555 - mae: 0.6401 - rmse: 0.9165

216/269 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.8542 - mae: 0.6395 - rmse: 0.9157

217/269 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.8529 - mae: 0.6389 - rmse: 0.9149

218/269 ━━━━━━━━━━━━━━━━━━━━ 15s 299ms/step - loss: 0.8516 - mae: 0.6383 - rmse: 0.9142

219/269 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.8503 - mae: 0.6377 - rmse: 0.9134

220/269 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.8490 - mae: 0.6371 - rmse: 0.9127

221/269 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.8477 - mae: 0.6365 - rmse: 0.9119

222/269 ━━━━━━━━━━━━━━━━━━━━ 14s 299ms/step - loss: 0.8464 - mae: 0.6359 - rmse: 0.9112

223/269 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.8451 - mae: 0.6353 - rmse: 0.9104

224/269 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.8438 - mae: 0.6347 - rmse: 0.9097

225/269 ━━━━━━━━━━━━━━━━━━━━ 13s 299ms/step - loss: 0.8425 - mae: 0.6341 - rmse: 0.9089

226/269 ━━━━━━━━━━━━━━━━━━━━ 12s 299ms/step - loss: 0.8412 - mae: 0.6335 - rmse: 0.9081

227/269 ━━━━━━━━━━━━━━━━━━━━ 12s 299ms/step - loss: 0.8399 - mae: 0.6329 - rmse: 0.9074

228/269 ━━━━━━━━━━━━━━━━━━━━ 12s 300ms/step - loss: 0.8386 - mae: 0.6323 - rmse: 0.9066

229/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8373 - mae: 0.6317 - rmse: 0.9059

230/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8360 - mae: 0.6311 - rmse: 0.9051

231/269 ━━━━━━━━━━━━━━━━━━━━ 11s 300ms/step - loss: 0.8348 - mae: 0.6305 - rmse: 0.9044

232/269 ━━━━━━━━━━━━━━━━━━━━ 11s 299ms/step - loss: 0.8335 - mae: 0.6299 - rmse: 0.9036

233/269 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.8322 - mae: 0.6293 - rmse: 0.9029

234/269 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.8309 - mae: 0.6287 - rmse: 0.9021

235/269 ━━━━━━━━━━━━━━━━━━━━ 10s 299ms/step - loss: 0.8297 - mae: 0.6281 - rmse: 0.9014

236/269 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.8284 - mae: 0.6275 - rmse: 0.9007

237/269 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.8272 - mae: 0.6269 - rmse: 0.8999

238/269 ━━━━━━━━━━━━━━━━━━━━ 9s 299ms/step - loss: 0.8259 - mae: 0.6264 - rmse: 0.8992

239/269 ━━━━━━━━━━━━━━━━━━━━ 8s 299ms/step - loss: 0.8247 - mae: 0.6258 - rmse: 0.8984

240/269 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.8234 - mae: 0.6252 - rmse: 0.8977

241/269 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.8222 - mae: 0.6246 - rmse: 0.8970

242/269 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - loss: 0.8209 - mae: 0.6240 - rmse: 0.8962

243/269 ━━━━━━━━━━━━━━━━━━━━ 7s 299ms/step - loss: 0.8197 - mae: 0.6234 - rmse: 0.8955

244/269 ━━━━━━━━━━━━━━━━━━━━ 7s 299ms/step - loss: 0.8185 - mae: 0.6229 - rmse: 0.8948

245/269 ━━━━━━━━━━━━━━━━━━━━ 7s 299ms/step - loss: 0.8173 - mae: 0.6223 - rmse: 0.8941

246/269 ━━━━━━━━━━━━━━━━━━━━ 6s 299ms/step - loss: 0.8160 - mae: 0.6217 - rmse: 0.8933

247/269 ━━━━━━━━━━━━━━━━━━━━ 6s 299ms/step - loss: 0.8148 - mae: 0.6211 - rmse: 0.8926

248/269 ━━━━━━━━━━━━━━━━━━━━ 6s 299ms/step - loss: 0.8136 - mae: 0.6206 - rmse: 0.8919

249/269 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - loss: 0.8124 - mae: 0.6200 - rmse: 0.8912

250/269 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - loss: 0.8112 - mae: 0.6194 - rmse: 0.8905

251/269 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - loss: 0.8100 - mae: 0.6189 - rmse: 0.8897

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 299ms/step - loss: 0.8088 - mae: 0.6183 - rmse: 0.8890

253/269 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.8076 - mae: 0.6178 - rmse: 0.8883

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.8064 - mae: 0.6172 - rmse: 0.8876

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 299ms/step - loss: 0.8053 - mae: 0.6166 - rmse: 0.8869

256/269 ━━━━━━━━━━━━━━━━━━━━ 3s 299ms/step - loss: 0.8041 - mae: 0.6161 - rmse: 0.8862

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 299ms/step - loss: 0.8029 - mae: 0.6155 - rmse: 0.8855

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 298ms/step - loss: 0.8017 - mae: 0.6150 - rmse: 0.8848

259/269 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.8005 - mae: 0.6144 - rmse: 0.8841

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.7994 - mae: 0.6139 - rmse: 0.8834

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.7982 - mae: 0.6133 - rmse: 0.8827

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 298ms/step - loss: 0.7971 - mae: 0.6128 - rmse: 0.8820

263/269 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.7959 - mae: 0.6122 - rmse: 0.8813

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.7947 - mae: 0.6117 - rmse: 0.8806

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 298ms/step - loss: 0.7936 - mae: 0.6111 - rmse: 0.8799

266/269 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7925 - mae: 0.6106 - rmse: 0.8792

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7913 - mae: 0.6100 - rmse: 0.8785

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - loss: 0.7902 - mae: 0.6095 - rmse: 0.8778

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - loss: 0.7890 - mae: 0.6090 - rmse: 0.8771

269/269 ━━━━━━━━━━━━━━━━━━━━ 88s 325ms/step - loss: 0.4868 - mae: 0.4656 - rmse: 0.6941 - val_loss: 0.8922 - val_mae: 0.5868 - val_rmse: 0.9420 - learning_rate: 0.0010

Epoch 5/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 442ms/step - loss: 0.9934 - mae: 0.6546 - rmse: 0.9942

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 292ms/step - loss: 0.8790 - mae: 0.6330 - rmse: 0.9329

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 292ms/step - loss: 0.8959 - mae: 0.6534 - rmse: 0.9425

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 307ms/step - loss: 0.8915 - mae: 0.6588 - rmse: 0.9405

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 315ms/step - loss: 0.8666 - mae: 0.6524 - rmse: 0.9270

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 309ms/step - loss: 0.8455 - mae: 0.6472 - rmse: 0.9154

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 301ms/step - loss: 0.8431 - mae: 0.6479 - rmse: 0.9143

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 295ms/step - loss: 0.8587 - mae: 0.6542 - rmse: 0.9227

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 291ms/step - loss: 0.8665 - mae: 0.6579 - rmse: 0.9270

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 287ms/step - loss: 0.8678 - mae: 0.6591 - rmse: 0.9278

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 284ms/step - loss: 0.8663 - mae: 0.6594 - rmse: 0.9271

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 282ms/step - loss: 0.8731 - mae: 0.6625 - rmse: 0.9308

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 281ms/step - loss: 0.8850 - mae: 0.6665 - rmse: 0.9369

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 279ms/step - loss: 0.9056 - mae: 0.6731 - rmse: 0.9472

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 277ms/step - loss: 0.9227 - mae: 0.6788 - rmse: 0.9558

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 276ms/step - loss: 0.9398 - mae: 0.6845 - rmse: 0.9643

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 275ms/step - loss: 0.9575 - mae: 0.6898 - rmse: 0.9729

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 275ms/step - loss: 0.9723 - mae: 0.6943 - rmse: 0.9802

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 276ms/step - loss: 0.9877 - mae: 0.6986 - rmse: 0.9877

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 275ms/step - loss: 1.0011 - mae: 0.7024 - rmse: 0.9943

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 275ms/step - loss: 1.0115 - mae: 0.7052 - rmse: 0.9994

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 275ms/step - loss: 1.0207 - mae: 0.7078 - rmse: 1.0039

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 275ms/step - loss: 1.0295 - mae: 0.7106 - rmse: 1.0083

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 277ms/step - loss: 1.0371 - mae: 0.7130 - rmse: 1.0120

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 280ms/step - loss: 1.0434 - mae: 0.7150 - rmse: 1.0152

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 284ms/step - loss: 1.0495 - mae: 0.7169 - rmse: 1.0182

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 289ms/step - loss: 1.0542 - mae: 0.7183 - rmse: 1.0206

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 290ms/step - loss: 1.0580 - mae: 0.7195 - rmse: 1.0225

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 292ms/step - loss: 1.0611 - mae: 0.7206 - rmse: 1.0242

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 292ms/step - loss: 1.0633 - mae: 0.7213 - rmse: 1.0253

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 294ms/step - loss: 1.0645 - mae: 0.7218 - rmse: 1.0260

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 295ms/step - loss: 1.0654 - mae: 0.7222 - rmse: 1.0265

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 296ms/step - loss: 1.0659 - mae: 0.7224 - rmse: 1.0269

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 298ms/step - loss: 1.0660 - mae: 0.7226 - rmse: 1.0270

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 299ms/step - loss: 1.0660 - mae: 0.7228 - rmse: 1.0271

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 298ms/step - loss: 1.0655 - mae: 0.7228 - rmse: 1.0270

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 298ms/step - loss: 1.0650 - mae: 0.7228 - rmse: 1.0268

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 299ms/step - loss: 1.0640 - mae: 0.7226 - rmse: 1.0264

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 300ms/step - loss: 1.0627 - mae: 0.7224 - rmse: 1.0258

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 301ms/step - loss: 1.0612 - mae: 0.7220 - rmse: 1.0251

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 301ms/step - loss: 1.0597 - mae: 0.7216 - rmse: 1.0244

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 303ms/step - loss: 1.0580 - mae: 0.7212 - rmse: 1.0237

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 305ms/step - loss: 1.0562 - mae: 0.7207 - rmse: 1.0229

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 304ms/step - loss: 1.0546 - mae: 0.7203 - rmse: 1.0221

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 303ms/step - loss: 1.0530 - mae: 0.7199 - rmse: 1.0214

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 303ms/step - loss: 1.0511 - mae: 0.7194 - rmse: 1.0205

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 303ms/step - loss: 1.0494 - mae: 0.7190 - rmse: 1.0197

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 302ms/step - loss: 1.0476 - mae: 0.7185 - rmse: 1.0188

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 301ms/step - loss: 1.0455 - mae: 0.7179 - rmse: 1.0178

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 301ms/step - loss: 1.0433 - mae: 0.7172 - rmse: 1.0167

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 301ms/step - loss: 1.0410 - mae: 0.7166 - rmse: 1.0156

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 301ms/step - loss: 1.0386 - mae: 0.7158 - rmse: 1.0145

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 300ms/step - loss: 1.0361 - mae: 0.7150 - rmse: 1.0132

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 299ms/step - loss: 1.0339 - mae: 0.7144 - rmse: 1.0121

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 299ms/step - loss: 1.0315 - mae: 0.7136 - rmse: 1.0110

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 298ms/step - loss: 1.0293 - mae: 0.7129 - rmse: 1.0099

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 297ms/step - loss: 1.0270 - mae: 0.7122 - rmse: 1.0088

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 297ms/step - loss: 1.0247 - mae: 0.7115 - rmse: 1.0076

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 297ms/step - loss: 1.0227 - mae: 0.7109 - rmse: 1.0066

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 297ms/step - loss: 1.0206 - mae: 0.7102 - rmse: 1.0056

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 296ms/step - loss: 1.0186 - mae: 0.7096 - rmse: 1.0046

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 296ms/step - loss: 1.0166 - mae: 0.7091 - rmse: 1.0036

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 296ms/step - loss: 1.0146 - mae: 0.7085 - rmse: 1.0026

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 296ms/step - loss: 1.0126 - mae: 0.7078 - rmse: 1.0016

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 295ms/step - loss: 1.0104 - mae: 0.7071 - rmse: 1.0005

 66/269 ━━━━━━━━━━━━━━━━━━━━ 59s 295ms/step - loss: 1.0081 - mae: 0.7064 - rmse: 0.9994

 67/269 ━━━━━━━━━━━━━━━━━━━━ 59s 295ms/step - loss: 1.0059 - mae: 0.7057 - rmse: 0.9982

 68/269 ━━━━━━━━━━━━━━━━━━━━ 59s 295ms/step - loss: 1.0036 - mae: 0.7050 - rmse: 0.9971

 69/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 1.0014 - mae: 0.7043 - rmse: 0.9960

 70/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 0.9992 - mae: 0.7036 - rmse: 0.9949

 71/269 ━━━━━━━━━━━━━━━━━━━━ 58s 294ms/step - loss: 0.9972 - mae: 0.7029 - rmse: 0.9938

 72/269 ━━━━━━━━━━━━━━━━━━━━ 57s 294ms/step - loss: 0.9952 - mae: 0.7023 - rmse: 0.9928

 73/269 ━━━━━━━━━━━━━━━━━━━━ 57s 294ms/step - loss: 0.9932 - mae: 0.7016 - rmse: 0.9918

 74/269 ━━━━━━━━━━━━━━━━━━━━ 57s 294ms/step - loss: 0.9914 - mae: 0.7010 - rmse: 0.9909

 75/269 ━━━━━━━━━━━━━━━━━━━━ 57s 294ms/step - loss: 0.9897 - mae: 0.7005 - rmse: 0.9901

 76/269 ━━━━━━━━━━━━━━━━━━━━ 56s 294ms/step - loss: 0.9880 - mae: 0.6999 - rmse: 0.9892

 77/269 ━━━━━━━━━━━━━━━━━━━━ 56s 294ms/step - loss: 0.9864 - mae: 0.6994 - rmse: 0.9884

 78/269 ━━━━━━━━━━━━━━━━━━━━ 56s 293ms/step - loss: 0.9849 - mae: 0.6990 - rmse: 0.9877

 79/269 ━━━━━━━━━━━━━━━━━━━━ 55s 293ms/step - loss: 0.9835 - mae: 0.6985 - rmse: 0.9869

 80/269 ━━━━━━━━━━━━━━━━━━━━ 55s 293ms/step - loss: 0.9820 - mae: 0.6981 - rmse: 0.9862

 81/269 ━━━━━━━━━━━━━━━━━━━━ 55s 293ms/step - loss: 0.9810 - mae: 0.6978 - rmse: 0.9857

 82/269 ━━━━━━━━━━━━━━━━━━━━ 54s 293ms/step - loss: 0.9803 - mae: 0.6976 - rmse: 0.9854

 83/269 ━━━━━━━━━━━━━━━━━━━━ 54s 294ms/step - loss: 0.9799 - mae: 0.6974 - rmse: 0.9852

 84/269 ━━━━━━━━━━━━━━━━━━━━ 54s 295ms/step - loss: 0.9795 - mae: 0.6973 - rmse: 0.9850

 85/269 ━━━━━━━━━━━━━━━━━━━━ 54s 296ms/step - loss: 0.9793 - mae: 0.6973 - rmse: 0.9849

 86/269 ━━━━━━━━━━━━━━━━━━━━ 54s 296ms/step - loss: 0.9792 - mae: 0.6972 - rmse: 0.9849

 87/269 ━━━━━━━━━━━━━━━━━━━━ 54s 297ms/step - loss: 0.9791 - mae: 0.6972 - rmse: 0.9849

 88/269 ━━━━━━━━━━━━━━━━━━━━ 53s 297ms/step - loss: 0.9789 - mae: 0.6972 - rmse: 0.9848

 89/269 ━━━━━━━━━━━━━━━━━━━━ 53s 298ms/step - loss: 0.9788 - mae: 0.6972 - rmse: 0.9848

 90/269 ━━━━━━━━━━━━━━━━━━━━ 53s 299ms/step - loss: 0.9787 - mae: 0.6972 - rmse: 0.9848

 91/269 ━━━━━━━━━━━━━━━━━━━━ 53s 299ms/step - loss: 0.9786 - mae: 0.6971 - rmse: 0.9847

 92/269 ━━━━━━━━━━━━━━━━━━━━ 53s 300ms/step - loss: 0.9783 - mae: 0.6971 - rmse: 0.9846

 93/269 ━━━━━━━━━━━━━━━━━━━━ 52s 300ms/step - loss: 0.9780 - mae: 0.6970 - rmse: 0.9845

 94/269 ━━━━━━━━━━━━━━━━━━━━ 52s 300ms/step - loss: 0.9777 - mae: 0.6969 - rmse: 0.9843

 95/269 ━━━━━━━━━━━━━━━━━━━━ 52s 300ms/step - loss: 0.9772 - mae: 0.6968 - rmse: 0.9841

 96/269 ━━━━━━━━━━━━━━━━━━━━ 52s 301ms/step - loss: 0.9768 - mae: 0.6966 - rmse: 0.9839

 97/269 ━━━━━━━━━━━━━━━━━━━━ 51s 301ms/step - loss: 0.9762 - mae: 0.6965 - rmse: 0.9836

 98/269 ━━━━━━━━━━━━━━━━━━━━ 51s 302ms/step - loss: 0.9757 - mae: 0.6963 - rmse: 0.9834

 99/269 ━━━━━━━━━━━━━━━━━━━━ 51s 302ms/step - loss: 0.9750 - mae: 0.6961 - rmse: 0.9831

100/269 ━━━━━━━━━━━━━━━━━━━━ 51s 302ms/step - loss: 0.9744 - mae: 0.6958 - rmse: 0.9827

101/269 ━━━━━━━━━━━━━━━━━━━━ 50s 302ms/step - loss: 0.9737 - mae: 0.6956 - rmse: 0.9824

102/269 ━━━━━━━━━━━━━━━━━━━━ 50s 302ms/step - loss: 0.9730 - mae: 0.6954 - rmse: 0.9821

103/269 ━━━━━━━━━━━━━━━━━━━━ 50s 302ms/step - loss: 0.9723 - mae: 0.6951 - rmse: 0.9817

104/269 ━━━━━━━━━━━━━━━━━━━━ 49s 301ms/step - loss: 0.9716 - mae: 0.6949 - rmse: 0.9814

105/269 ━━━━━━━━━━━━━━━━━━━━ 49s 301ms/step - loss: 0.9709 - mae: 0.6947 - rmse: 0.9810

106/269 ━━━━━━━━━━━━━━━━━━━━ 49s 301ms/step - loss: 0.9701 - mae: 0.6944 - rmse: 0.9806

107/269 ━━━━━━━━━━━━━━━━━━━━ 48s 302ms/step - loss: 0.9693 - mae: 0.6941 - rmse: 0.9802

108/269 ━━━━━━━━━━━━━━━━━━━━ 48s 302ms/step - loss: 0.9684 - mae: 0.6938 - rmse: 0.9798

109/269 ━━━━━━━━━━━━━━━━━━━━ 48s 302ms/step - loss: 0.9675 - mae: 0.6935 - rmse: 0.9793

110/269 ━━━━━━━━━━━━━━━━━━━━ 47s 302ms/step - loss: 0.9666 - mae: 0.6931 - rmse: 0.9789

111/269 ━━━━━━━━━━━━━━━━━━━━ 47s 302ms/step - loss: 0.9656 - mae: 0.6928 - rmse: 0.9784

112/269 ━━━━━━━━━━━━━━━━━━━━ 47s 301ms/step - loss: 0.9646 - mae: 0.6924 - rmse: 0.9778

113/269 ━━━━━━━━━━━━━━━━━━━━ 46s 301ms/step - loss: 0.9635 - mae: 0.6919 - rmse: 0.9773

114/269 ━━━━━━━━━━━━━━━━━━━━ 46s 301ms/step - loss: 0.9624 - mae: 0.6915 - rmse: 0.9767

115/269 ━━━━━━━━━━━━━━━━━━━━ 46s 301ms/step - loss: 0.9613 - mae: 0.6911 - rmse: 0.9762

116/269 ━━━━━━━━━━━━━━━━━━━━ 45s 300ms/step - loss: 0.9601 - mae: 0.6906 - rmse: 0.9756

117/269 ━━━━━━━━━━━━━━━━━━━━ 45s 300ms/step - loss: 0.9590 - mae: 0.6901 - rmse: 0.9750

118/269 ━━━━━━━━━━━━━━━━━━━━ 45s 300ms/step - loss: 0.9578 - mae: 0.6896 - rmse: 0.9743

119/269 ━━━━━━━━━━━━━━━━━━━━ 44s 300ms/step - loss: 0.9566 - mae: 0.6892 - rmse: 0.9737

120/269 ━━━━━━━━━━━━━━━━━━━━ 44s 299ms/step - loss: 0.9553 - mae: 0.6887 - rmse: 0.9731

121/269 ━━━━━━━━━━━━━━━━━━━━ 44s 299ms/step - loss: 0.9541 - mae: 0.6881 - rmse: 0.9724

122/269 ━━━━━━━━━━━━━━━━━━━━ 43s 299ms/step - loss: 0.9528 - mae: 0.6876 - rmse: 0.9717

123/269 ━━━━━━━━━━━━━━━━━━━━ 43s 299ms/step - loss: 0.9515 - mae: 0.6871 - rmse: 0.9711

124/269 ━━━━━━━━━━━━━━━━━━━━ 43s 298ms/step - loss: 0.9502 - mae: 0.6865 - rmse: 0.9704

125/269 ━━━━━━━━━━━━━━━━━━━━ 42s 298ms/step - loss: 0.9489 - mae: 0.6859 - rmse: 0.9697

126/269 ━━━━━━━━━━━━━━━━━━━━ 42s 298ms/step - loss: 0.9475 - mae: 0.6853 - rmse: 0.9689

127/269 ━━━━━━━━━━━━━━━━━━━━ 42s 298ms/step - loss: 0.9461 - mae: 0.6847 - rmse: 0.9682

128/269 ━━━━━━━━━━━━━━━━━━━━ 41s 297ms/step - loss: 0.9447 - mae: 0.6841 - rmse: 0.9675

129/269 ━━━━━━━━━━━━━━━━━━━━ 41s 297ms/step - loss: 0.9433 - mae: 0.6835 - rmse: 0.9667

130/269 ━━━━━━━━━━━━━━━━━━━━ 41s 297ms/step - loss: 0.9419 - mae: 0.6829 - rmse: 0.9659

131/269 ━━━━━━━━━━━━━━━━━━━━ 41s 298ms/step - loss: 0.9405 - mae: 0.6823 - rmse: 0.9652

132/269 ━━━━━━━━━━━━━━━━━━━━ 40s 298ms/step - loss: 0.9390 - mae: 0.6816 - rmse: 0.9644

133/269 ━━━━━━━━━━━━━━━━━━━━ 40s 298ms/step - loss: 0.9376 - mae: 0.6810 - rmse: 0.9637

134/269 ━━━━━━━━━━━━━━━━━━━━ 40s 298ms/step - loss: 0.9362 - mae: 0.6804 - rmse: 0.9629

135/269 ━━━━━━━━━━━━━━━━━━━━ 39s 298ms/step - loss: 0.9347 - mae: 0.6798 - rmse: 0.9621

136/269 ━━━━━━━━━━━━━━━━━━━━ 39s 300ms/step - loss: 0.9333 - mae: 0.6792 - rmse: 0.9613

137/269 ━━━━━━━━━━━━━━━━━━━━ 39s 301ms/step - loss: 0.9319 - mae: 0.6785 - rmse: 0.9606

138/269 ━━━━━━━━━━━━━━━━━━━━ 39s 302ms/step - loss: 0.9304 - mae: 0.6779 - rmse: 0.9598

139/269 ━━━━━━━━━━━━━━━━━━━━ 39s 302ms/step - loss: 0.9290 - mae: 0.6773 - rmse: 0.9590

140/269 ━━━━━━━━━━━━━━━━━━━━ 38s 302ms/step - loss: 0.9275 - mae: 0.6766 - rmse: 0.9582

141/269 ━━━━━━━━━━━━━━━━━━━━ 38s 302ms/step - loss: 0.9260 - mae: 0.6760 - rmse: 0.9574

142/269 ━━━━━━━━━━━━━━━━━━━━ 38s 302ms/step - loss: 0.9245 - mae: 0.6753 - rmse: 0.9566

143/269 ━━━━━━━━━━━━━━━━━━━━ 38s 302ms/step - loss: 0.9230 - mae: 0.6747 - rmse: 0.9558

144/269 ━━━━━━━━━━━━━━━━━━━━ 37s 303ms/step - loss: 0.9215 - mae: 0.6740 - rmse: 0.9550

145/269 ━━━━━━━━━━━━━━━━━━━━ 37s 303ms/step - loss: 0.9200 - mae: 0.6733 - rmse: 0.9541

146/269 ━━━━━━━━━━━━━━━━━━━━ 37s 304ms/step - loss: 0.9185 - mae: 0.6727 - rmse: 0.9533

147/269 ━━━━━━━━━━━━━━━━━━━━ 37s 304ms/step - loss: 0.9170 - mae: 0.6720 - rmse: 0.9525

148/269 ━━━━━━━━━━━━━━━━━━━━ 36s 304ms/step - loss: 0.9155 - mae: 0.6713 - rmse: 0.9516

149/269 ━━━━━━━━━━━━━━━━━━━━ 36s 304ms/step - loss: 0.9139 - mae: 0.6706 - rmse: 0.9508

150/269 ━━━━━━━━━━━━━━━━━━━━ 36s 304ms/step - loss: 0.9124 - mae: 0.6699 - rmse: 0.9499

151/269 ━━━━━━━━━━━━━━━━━━━━ 35s 304ms/step - loss: 0.9108 - mae: 0.6692 - rmse: 0.9491

152/269 ━━━━━━━━━━━━━━━━━━━━ 35s 304ms/step - loss: 0.9093 - mae: 0.6685 - rmse: 0.9482

153/269 ━━━━━━━━━━━━━━━━━━━━ 35s 304ms/step - loss: 0.9078 - mae: 0.6678 - rmse: 0.9474

154/269 ━━━━━━━━━━━━━━━━━━━━ 35s 305ms/step - loss: 0.9062 - mae: 0.6671 - rmse: 0.9465

155/269 ━━━━━━━━━━━━━━━━━━━━ 34s 305ms/step - loss: 0.9047 - mae: 0.6664 - rmse: 0.9457

156/269 ━━━━━━━━━━━━━━━━━━━━ 34s 305ms/step - loss: 0.9031 - mae: 0.6656 - rmse: 0.9448

157/269 ━━━━━━━━━━━━━━━━━━━━ 34s 305ms/step - loss: 0.9016 - mae: 0.6649 - rmse: 0.9439

158/269 ━━━━━━━━━━━━━━━━━━━━ 33s 305ms/step - loss: 0.9000 - mae: 0.6642 - rmse: 0.9431

159/269 ━━━━━━━━━━━━━━━━━━━━ 33s 304ms/step - loss: 0.8985 - mae: 0.6635 - rmse: 0.9422

160/269 ━━━━━━━━━━━━━━━━━━━━ 33s 304ms/step - loss: 0.8969 - mae: 0.6628 - rmse: 0.9413

161/269 ━━━━━━━━━━━━━━━━━━━━ 32s 304ms/step - loss: 0.8954 - mae: 0.6621 - rmse: 0.9405

162/269 ━━━━━━━━━━━━━━━━━━━━ 32s 304ms/step - loss: 0.8938 - mae: 0.6613 - rmse: 0.9396

163/269 ━━━━━━━━━━━━━━━━━━━━ 32s 304ms/step - loss: 0.8923 - mae: 0.6606 - rmse: 0.9387

164/269 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.8907 - mae: 0.6599 - rmse: 0.9379

165/269 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.8892 - mae: 0.6592 - rmse: 0.9370

166/269 ━━━━━━━━━━━━━━━━━━━━ 31s 304ms/step - loss: 0.8876 - mae: 0.6585 - rmse: 0.9361

167/269 ━━━━━━━━━━━━━━━━━━━━ 30s 304ms/step - loss: 0.8861 - mae: 0.6578 - rmse: 0.9353

168/269 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 0.8846 - mae: 0.6571 - rmse: 0.9344

169/269 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 0.8831 - mae: 0.6564 - rmse: 0.9336

170/269 ━━━━━━━━━━━━━━━━━━━━ 30s 303ms/step - loss: 0.8816 - mae: 0.6557 - rmse: 0.9327

171/269 ━━━━━━━━━━━━━━━━━━━━ 29s 303ms/step - loss: 0.8802 - mae: 0.6551 - rmse: 0.9319

172/269 ━━━━━━━━━━━━━━━━━━━━ 29s 304ms/step - loss: 0.8787 - mae: 0.6544 - rmse: 0.9311

173/269 ━━━━━━━━━━━━━━━━━━━━ 29s 305ms/step - loss: 0.8773 - mae: 0.6538 - rmse: 0.9303

174/269 ━━━━━━━━━━━━━━━━━━━━ 28s 305ms/step - loss: 0.8758 - mae: 0.6531 - rmse: 0.9295

175/269 ━━━━━━━━━━━━━━━━━━━━ 28s 305ms/step - loss: 0.8744 - mae: 0.6525 - rmse: 0.9287

176/269 ━━━━━━━━━━━━━━━━━━━━ 28s 305ms/step - loss: 0.8730 - mae: 0.6518 - rmse: 0.9279

177/269 ━━━━━━━━━━━━━━━━━━━━ 28s 306ms/step - loss: 0.8716 - mae: 0.6512 - rmse: 0.9271

178/269 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.8702 - mae: 0.6506 - rmse: 0.9263

179/269 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.8688 - mae: 0.6499 - rmse: 0.9255

180/269 ━━━━━━━━━━━━━━━━━━━━ 27s 306ms/step - loss: 0.8674 - mae: 0.6493 - rmse: 0.9247

181/269 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.8660 - mae: 0.6486 - rmse: 0.9239

182/269 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.8645 - mae: 0.6480 - rmse: 0.9231

183/269 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.8631 - mae: 0.6474 - rmse: 0.9223

184/269 ━━━━━━━━━━━━━━━━━━━━ 26s 306ms/step - loss: 0.8617 - mae: 0.6467 - rmse: 0.9214

185/269 ━━━━━━━━━━━━━━━━━━━━ 25s 306ms/step - loss: 0.8603 - mae: 0.6461 - rmse: 0.9206

186/269 ━━━━━━━━━━━━━━━━━━━━ 25s 306ms/step - loss: 0.8589 - mae: 0.6455 - rmse: 0.9198

187/269 ━━━━━━━━━━━━━━━━━━━━ 25s 306ms/step - loss: 0.8575 - mae: 0.6448 - rmse: 0.9190

188/269 ━━━━━━━━━━━━━━━━━━━━ 24s 307ms/step - loss: 0.8561 - mae: 0.6442 - rmse: 0.9182

189/269 ━━━━━━━━━━━━━━━━━━━━ 24s 307ms/step - loss: 0.8547 - mae: 0.6435 - rmse: 0.9174

190/269 ━━━━━━━━━━━━━━━━━━━━ 24s 307ms/step - loss: 0.8533 - mae: 0.6429 - rmse: 0.9166

191/269 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.8519 - mae: 0.6423 - rmse: 0.9158

192/269 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.8506 - mae: 0.6416 - rmse: 0.9150

193/269 ━━━━━━━━━━━━━━━━━━━━ 23s 307ms/step - loss: 0.8492 - mae: 0.6410 - rmse: 0.9142

194/269 ━━━━━━━━━━━━━━━━━━━━ 22s 306ms/step - loss: 0.8478 - mae: 0.6403 - rmse: 0.9134

195/269 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.8464 - mae: 0.6397 - rmse: 0.9126

196/269 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.8450 - mae: 0.6391 - rmse: 0.9118

197/269 ━━━━━━━━━━━━━━━━━━━━ 22s 307ms/step - loss: 0.8437 - mae: 0.6384 - rmse: 0.9110

198/269 ━━━━━━━━━━━━━━━━━━━━ 21s 307ms/step - loss: 0.8423 - mae: 0.6378 - rmse: 0.9102

199/269 ━━━━━━━━━━━━━━━━━━━━ 21s 307ms/step - loss: 0.8409 - mae: 0.6371 - rmse: 0.9094

200/269 ━━━━━━━━━━━━━━━━━━━━ 21s 307ms/step - loss: 0.8396 - mae: 0.6365 - rmse: 0.9086

201/269 ━━━━━━━━━━━━━━━━━━━━ 20s 307ms/step - loss: 0.8382 - mae: 0.6359 - rmse: 0.9079

202/269 ━━━━━━━━━━━━━━━━━━━━ 20s 307ms/step - loss: 0.8369 - mae: 0.6353 - rmse: 0.9071

203/269 ━━━━━━━━━━━━━━━━━━━━ 20s 307ms/step - loss: 0.8356 - mae: 0.6346 - rmse: 0.9063

204/269 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 0.8342 - mae: 0.6340 - rmse: 0.9055

205/269 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 0.8330 - mae: 0.6334 - rmse: 0.9048

206/269 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 0.8317 - mae: 0.6328 - rmse: 0.9040

207/269 ━━━━━━━━━━━━━━━━━━━━ 19s 307ms/step - loss: 0.8304 - mae: 0.6322 - rmse: 0.9033

208/269 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 0.8291 - mae: 0.6316 - rmse: 0.9025

209/269 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 0.8278 - mae: 0.6310 - rmse: 0.9018

210/269 ━━━━━━━━━━━━━━━━━━━━ 18s 307ms/step - loss: 0.8265 - mae: 0.6304 - rmse: 0.9010

211/269 ━━━━━━━━━━━━━━━━━━━━ 17s 307ms/step - loss: 0.8252 - mae: 0.6298 - rmse: 0.9003

212/269 ━━━━━━━━━━━━━━━━━━━━ 17s 307ms/step - loss: 0.8240 - mae: 0.6292 - rmse: 0.8995

213/269 ━━━━━━━━━━━━━━━━━━━━ 17s 307ms/step - loss: 0.8227 - mae: 0.6286 - rmse: 0.8988

214/269 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.8214 - mae: 0.6280 - rmse: 0.8980

215/269 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.8201 - mae: 0.6274 - rmse: 0.8973

216/269 ━━━━━━━━━━━━━━━━━━━━ 16s 307ms/step - loss: 0.8189 - mae: 0.6268 - rmse: 0.8965

217/269 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.8176 - mae: 0.6262 - rmse: 0.8958

218/269 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.8164 - mae: 0.6256 - rmse: 0.8951

219/269 ━━━━━━━━━━━━━━━━━━━━ 15s 307ms/step - loss: 0.8151 - mae: 0.6251 - rmse: 0.8943

220/269 ━━━━━━━━━━━━━━━━━━━━ 15s 308ms/step - loss: 0.8139 - mae: 0.6245 - rmse: 0.8936

221/269 ━━━━━━━━━━━━━━━━━━━━ 14s 308ms/step - loss: 0.8126 - mae: 0.6239 - rmse: 0.8928

222/269 ━━━━━━━━━━━━━━━━━━━━ 14s 308ms/step - loss: 0.8114 - mae: 0.6233 - rmse: 0.8921

223/269 ━━━━━━━━━━━━━━━━━━━━ 14s 308ms/step - loss: 0.8101 - mae: 0.6227 - rmse: 0.8914

224/269 ━━━━━━━━━━━━━━━━━━━━ 13s 308ms/step - loss: 0.8089 - mae: 0.6221 - rmse: 0.8906

225/269 ━━━━━━━━━━━━━━━━━━━━ 13s 308ms/step - loss: 0.8076 - mae: 0.6215 - rmse: 0.8899

226/269 ━━━━━━━━━━━━━━━━━━━━ 13s 308ms/step - loss: 0.8064 - mae: 0.6210 - rmse: 0.8891

227/269 ━━━━━━━━━━━━━━━━━━━━ 12s 308ms/step - loss: 0.8052 - mae: 0.6204 - rmse: 0.8884

228/269 ━━━━━━━━━━━━━━━━━━━━ 12s 308ms/step - loss: 0.8039 - mae: 0.6198 - rmse: 0.8877

229/269 ━━━━━━━━━━━━━━━━━━━━ 12s 308ms/step - loss: 0.8027 - mae: 0.6192 - rmse: 0.8869

230/269 ━━━━━━━━━━━━━━━━━━━━ 12s 308ms/step - loss: 0.8015 - mae: 0.6186 - rmse: 0.8862

231/269 ━━━━━━━━━━━━━━━━━━━━ 11s 308ms/step - loss: 0.8003 - mae: 0.6180 - rmse: 0.8855

232/269 ━━━━━━━━━━━━━━━━━━━━ 11s 308ms/step - loss: 0.7990 - mae: 0.6174 - rmse: 0.8847

233/269 ━━━━━━━━━━━━━━━━━━━━ 11s 308ms/step - loss: 0.7978 - mae: 0.6169 - rmse: 0.8840

234/269 ━━━━━━━━━━━━━━━━━━━━ 10s 308ms/step - loss: 0.7966 - mae: 0.6163 - rmse: 0.8833

235/269 ━━━━━━━━━━━━━━━━━━━━ 10s 309ms/step - loss: 0.7954 - mae: 0.6157 - rmse: 0.8825

236/269 ━━━━━━━━━━━━━━━━━━━━ 10s 309ms/step - loss: 0.7942 - mae: 0.6151 - rmse: 0.8818

237/269 ━━━━━━━━━━━━━━━━━━━━ 9s 309ms/step - loss: 0.7930 - mae: 0.6145 - rmse: 0.8811

238/269 ━━━━━━━━━━━━━━━━━━━━ 9s 309ms/step - loss: 0.7918 - mae: 0.6140 - rmse: 0.8804

239/269 ━━━━━━━━━━━━━━━━━━━━ 9s 309ms/step - loss: 0.7906 - mae: 0.6134 - rmse: 0.8797

240/269 ━━━━━━━━━━━━━━━━━━━━ 8s 309ms/step - loss: 0.7894 - mae: 0.6128 - rmse: 0.8789

241/269 ━━━━━━━━━━━━━━━━━━━━ 8s 309ms/step - loss: 0.7882 - mae: 0.6122 - rmse: 0.8782

242/269 ━━━━━━━━━━━━━━━━━━━━ 8s 309ms/step - loss: 0.7871 - mae: 0.6117 - rmse: 0.8775

243/269 ━━━━━━━━━━━━━━━━━━━━ 8s 310ms/step - loss: 0.7859 - mae: 0.6111 - rmse: 0.8768

244/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.7847 - mae: 0.6106 - rmse: 0.8761

245/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.7835 - mae: 0.6100 - rmse: 0.8754

246/269 ━━━━━━━━━━━━━━━━━━━━ 7s 310ms/step - loss: 0.7824 - mae: 0.6094 - rmse: 0.8747

247/269 ━━━━━━━━━━━━━━━━━━━━ 6s 310ms/step - loss: 0.7812 - mae: 0.6089 - rmse: 0.8740

248/269 ━━━━━━━━━━━━━━━━━━━━ 6s 310ms/step - loss: 0.7801 - mae: 0.6083 - rmse: 0.8733

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 310ms/step - loss: 0.7789 - mae: 0.6078 - rmse: 0.8726

250/269 ━━━━━━━━━━━━━━━━━━━━ 5s 310ms/step - loss: 0.7778 - mae: 0.6072 - rmse: 0.8719

251/269 ━━━━━━━━━━━━━━━━━━━━ 5s 310ms/step - loss: 0.7766 - mae: 0.6067 - rmse: 0.8712

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 310ms/step - loss: 0.7755 - mae: 0.6061 - rmse: 0.8705

253/269 ━━━━━━━━━━━━━━━━━━━━ 4s 309ms/step - loss: 0.7743 - mae: 0.6056 - rmse: 0.8698

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 309ms/step - loss: 0.7732 - mae: 0.6050 - rmse: 0.8691

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.7721 - mae: 0.6045 - rmse: 0.8684

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 310ms/step - loss: 0.7709 - mae: 0.6039 - rmse: 0.8677

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 310ms/step - loss: 0.7698 - mae: 0.6034 - rmse: 0.8670

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 311ms/step - loss: 0.7687 - mae: 0.6029 - rmse: 0.8663

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 311ms/step - loss: 0.7676 - mae: 0.6023 - rmse: 0.8656

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 0.7665 - mae: 0.6018 - rmse: 0.8650

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 0.7653 - mae: 0.6012 - rmse: 0.8643

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 311ms/step - loss: 0.7642 - mae: 0.6007 - rmse: 0.8636

263/269 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 0.7631 - mae: 0.6002 - rmse: 0.8629

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 0.7620 - mae: 0.5996 - rmse: 0.8622

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 311ms/step - loss: 0.7609 - mae: 0.5991 - rmse: 0.8616

266/269 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 0.7598 - mae: 0.5986 - rmse: 0.8609

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - loss: 0.7588 - mae: 0.5981 - rmse: 0.8602

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.7577 - mae: 0.5975 - rmse: 0.8595

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - loss: 0.7566 - mae: 0.5970 - rmse: 0.8589

269/269 ━━━━━━━━━━━━━━━━━━━━ 91s 338ms/step - loss: 0.4679 - mae: 0.4573 - rmse: 0.6805 - val_loss: 0.8051 - val_mae: 0.5562 - val_rmse: 0.8946 - learning_rate: 0.0010

Epoch 6/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 479ms/step - loss: 0.9474 - mae: 0.6412 - rmse: 0.9709

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 358ms/step - loss: 0.8543 - mae: 0.6269 - rmse: 0.9203

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 390ms/step - loss: 0.8705 - mae: 0.6472 - rmse: 0.9294

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 424ms/step - loss: 0.8638 - mae: 0.6518 - rmse: 0.9260

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 444ms/step - loss: 0.8389 - mae: 0.6454 - rmse: 0.9122

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 453ms/step - loss: 0.8206 - mae: 0.6414 - rmse: 0.9021

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 445ms/step - loss: 0.8201 - mae: 0.6430 - rmse: 0.9019

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 431ms/step - loss: 0.8340 - mae: 0.6491 - rmse: 0.9095

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 424ms/step - loss: 0.8414 - mae: 0.6526 - rmse: 0.9136

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 418ms/step - loss: 0.8424 - mae: 0.6535 - rmse: 0.9143

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 415ms/step - loss: 0.8406 - mae: 0.6532 - rmse: 0.9134

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 408ms/step - loss: 0.8475 - mae: 0.6560 - rmse: 0.9171

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 404ms/step - loss: 0.8595 - mae: 0.6596 - rmse: 0.9234

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 400ms/step - loss: 0.8793 - mae: 0.6657 - rmse: 0.9335

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 395ms/step - loss: 0.8956 - mae: 0.6709 - rmse: 0.9418

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 388ms/step - loss: 0.9125 - mae: 0.6763 - rmse: 0.9502

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 382ms/step - loss: 0.9299 - mae: 0.6813 - rmse: 0.9589

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 379ms/step - loss: 0.9444 - mae: 0.6855 - rmse: 0.9661

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 374ms/step - loss: 0.9595 - mae: 0.6896 - rmse: 0.9736

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 369ms/step - loss: 0.9727 - mae: 0.6932 - rmse: 0.9801

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 365ms/step - loss: 0.9828 - mae: 0.6959 - rmse: 0.9851

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 361ms/step - loss: 0.9917 - mae: 0.6984 - rmse: 0.9896

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 357ms/step - loss: 1.0004 - mae: 0.7010 - rmse: 0.9940

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 354ms/step - loss: 1.0079 - mae: 0.7033 - rmse: 0.9977

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 352ms/step - loss: 1.0141 - mae: 0.7052 - rmse: 1.0008

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 351ms/step - loss: 1.0202 - mae: 0.7070 - rmse: 1.0039

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 354ms/step - loss: 1.0248 - mae: 0.7083 - rmse: 1.0063

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 357ms/step - loss: 1.0284 - mae: 0.7094 - rmse: 1.0082

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 354ms/step - loss: 1.0314 - mae: 0.7103 - rmse: 1.0097

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 351ms/step - loss: 1.0334 - mae: 0.7109 - rmse: 1.0108

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 349ms/step - loss: 1.0345 - mae: 0.7112 - rmse: 1.0115

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 348ms/step - loss: 1.0353 - mae: 0.7115 - rmse: 1.0120

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 347ms/step - loss: 1.0357 - mae: 0.7117 - rmse: 1.0123

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 345ms/step - loss: 1.0358 - mae: 0.7117 - rmse: 1.0124

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 346ms/step - loss: 1.0358 - mae: 0.7118 - rmse: 1.0125

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 344ms/step - loss: 1.0354 - mae: 0.7118 - rmse: 1.0123

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 342ms/step - loss: 1.0348 - mae: 0.7117 - rmse: 1.0121

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 341ms/step - loss: 1.0338 - mae: 0.7114 - rmse: 1.0117

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 340ms/step - loss: 1.0326 - mae: 0.7111 - rmse: 1.0112

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 341ms/step - loss: 1.0311 - mae: 0.7107 - rmse: 1.0105

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 341ms/step - loss: 1.0297 - mae: 0.7103 - rmse: 1.0099

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 342ms/step - loss: 1.0281 - mae: 0.7098 - rmse: 1.0091

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 342ms/step - loss: 1.0264 - mae: 0.7093 - rmse: 1.0083

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 341ms/step - loss: 1.0249 - mae: 0.7089 - rmse: 1.0076

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 339ms/step - loss: 1.0233 - mae: 0.7085 - rmse: 1.0069

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 338ms/step - loss: 1.0215 - mae: 0.7079 - rmse: 1.0060

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 337ms/step - loss: 1.0199 - mae: 0.7075 - rmse: 1.0052

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 336ms/step - loss: 1.0180 - mae: 0.7070 - rmse: 1.0043

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 335ms/step - loss: 1.0160 - mae: 0.7064 - rmse: 1.0033

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 335ms/step - loss: 1.0139 - mae: 0.7057 - rmse: 1.0023

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 336ms/step - loss: 1.0116 - mae: 0.7050 - rmse: 1.0012

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 338ms/step - loss: 1.0093 - mae: 0.7042 - rmse: 1.0000

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 340ms/step - loss: 1.0069 - mae: 0.7034 - rmse: 0.9988

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 342ms/step - loss: 1.0046 - mae: 0.7027 - rmse: 0.9977

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 343ms/step - loss: 1.0024 - mae: 0.7020 - rmse: 0.9966

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 343ms/step - loss: 1.0002 - mae: 0.7013 - rmse: 0.9955

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 343ms/step - loss: 0.9980 - mae: 0.7006 - rmse: 0.9944

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 342ms/step - loss: 0.9957 - mae: 0.6999 - rmse: 0.9933

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 341ms/step - loss: 0.9937 - mae: 0.6992 - rmse: 0.9923

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 340ms/step - loss: 0.9917 - mae: 0.6986 - rmse: 0.9912

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 339ms/step - loss: 0.9897 - mae: 0.6980 - rmse: 0.9903

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 339ms/step - loss: 0.9878 - mae: 0.6974 - rmse: 0.9893

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 339ms/step - loss: 0.9859 - mae: 0.6968 - rmse: 0.9883

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 339ms/step - loss: 0.9839 - mae: 0.6962 - rmse: 0.9873

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 339ms/step - loss: 0.9818 - mae: 0.6955 - rmse: 0.9862

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 339ms/step - loss: 0.9796 - mae: 0.6948 - rmse: 0.9851

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 340ms/step - loss: 0.9774 - mae: 0.6941 - rmse: 0.9840

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 340ms/step - loss: 0.9751 - mae: 0.6933 - rmse: 0.9828

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 340ms/step - loss: 0.9730 - mae: 0.6926 - rmse: 0.9817

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 339ms/step - loss: 0.9709 - mae: 0.6919 - rmse: 0.9806

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 339ms/step - loss: 0.9689 - mae: 0.6913 - rmse: 0.9796

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 339ms/step - loss: 0.9670 - mae: 0.6906 - rmse: 0.9787

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 339ms/step - loss: 0.9651 - mae: 0.6900 - rmse: 0.9777

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 339ms/step - loss: 0.9633 - mae: 0.6894 - rmse: 0.9768

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 339ms/step - loss: 0.9616 - mae: 0.6889 - rmse: 0.9759

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 338ms/step - loss: 0.9600 - mae: 0.6883 - rmse: 0.9751

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 341ms/step - loss: 0.9584 - mae: 0.6878 - rmse: 0.9743

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 342ms/step - loss: 0.9569 - mae: 0.6873 - rmse: 0.9735

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 343ms/step - loss: 0.9555 - mae: 0.6869 - rmse: 0.9728

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 343ms/step - loss: 0.9541 - mae: 0.6864 - rmse: 0.9721

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 343ms/step - loss: 0.9530 - mae: 0.6861 - rmse: 0.9715

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 343ms/step - loss: 0.9523 - mae: 0.6859 - rmse: 0.9712

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 343ms/step - loss: 0.9518 - mae: 0.6857 - rmse: 0.9710

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 343ms/step - loss: 0.9514 - mae: 0.6856 - rmse: 0.9708

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 343ms/step - loss: 0.9511 - mae: 0.6855 - rmse: 0.9707

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 344ms/step - loss: 0.9509 - mae: 0.6854 - rmse: 0.9706

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 346ms/step - loss: 0.9508 - mae: 0.6854 - rmse: 0.9705

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 349ms/step - loss: 0.9506 - mae: 0.6853 - rmse: 0.9704

 89/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 350ms/step - loss: 0.9504 - mae: 0.6853 - rmse: 0.9704

 90/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 349ms/step - loss: 0.9503 - mae: 0.6853 - rmse: 0.9703

 91/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 349ms/step - loss: 0.9500 - mae: 0.6852 - rmse: 0.9703

 92/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 349ms/step - loss: 0.9498 - mae: 0.6852 - rmse: 0.9701

 93/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 349ms/step - loss: 0.9495 - mae: 0.6851 - rmse: 0.9700

 94/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 348ms/step - loss: 0.9491 - mae: 0.6850 - rmse: 0.9698

 95/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 348ms/step - loss: 0.9486 - mae: 0.6848 - rmse: 0.9696

 96/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 347ms/step - loss: 0.9481 - mae: 0.6847 - rmse: 0.9693

 97/269 ━━━━━━━━━━━━━━━━━━━━ 59s 346ms/step - loss: 0.9476 - mae: 0.6845 - rmse: 0.9691

 98/269 ━━━━━━━━━━━━━━━━━━━━ 59s 346ms/step - loss: 0.9470 - mae: 0.6843 - rmse: 0.9688

 99/269 ━━━━━━━━━━━━━━━━━━━━ 58s 345ms/step - loss: 0.9463 - mae: 0.6841 - rmse: 0.9685

100/269 ━━━━━━━━━━━━━━━━━━━━ 58s 344ms/step - loss: 0.9457 - mae: 0.6839 - rmse: 0.9681

101/269 ━━━━━━━━━━━━━━━━━━━━ 57s 343ms/step - loss: 0.9450 - mae: 0.6836 - rmse: 0.9678

102/269 ━━━━━━━━━━━━━━━━━━━━ 57s 342ms/step - loss: 0.9443 - mae: 0.6834 - rmse: 0.9675

103/269 ━━━━━━━━━━━━━━━━━━━━ 56s 342ms/step - loss: 0.9436 - mae: 0.6832 - rmse: 0.9671

104/269 ━━━━━━━━━━━━━━━━━━━━ 56s 341ms/step - loss: 0.9429 - mae: 0.6829 - rmse: 0.9668

105/269 ━━━━━━━━━━━━━━━━━━━━ 55s 340ms/step - loss: 0.9422 - mae: 0.6827 - rmse: 0.9664

106/269 ━━━━━━━━━━━━━━━━━━━━ 55s 339ms/step - loss: 0.9414 - mae: 0.6824 - rmse: 0.9660

107/269 ━━━━━━━━━━━━━━━━━━━━ 54s 339ms/step - loss: 0.9406 - mae: 0.6821 - rmse: 0.9656

108/269 ━━━━━━━━━━━━━━━━━━━━ 54s 339ms/step - loss: 0.9397 - mae: 0.6818 - rmse: 0.9651

109/269 ━━━━━━━━━━━━━━━━━━━━ 54s 338ms/step - loss: 0.9388 - mae: 0.6815 - rmse: 0.9647

110/269 ━━━━━━━━━━━━━━━━━━━━ 53s 338ms/step - loss: 0.9378 - mae: 0.6811 - rmse: 0.9642

111/269 ━━━━━━━━━━━━━━━━━━━━ 53s 338ms/step - loss: 0.9368 - mae: 0.6807 - rmse: 0.9637

112/269 ━━━━━━━━━━━━━━━━━━━━ 53s 338ms/step - loss: 0.9358 - mae: 0.6803 - rmse: 0.9631

113/269 ━━━━━━━━━━━━━━━━━━━━ 52s 338ms/step - loss: 0.9348 - mae: 0.6799 - rmse: 0.9626

114/269 ━━━━━━━━━━━━━━━━━━━━ 52s 338ms/step - loss: 0.9337 - mae: 0.6795 - rmse: 0.9620

115/269 ━━━━━━━━━━━━━━━━━━━━ 52s 339ms/step - loss: 0.9326 - mae: 0.6791 - rmse: 0.9614

116/269 ━━━━━━━━━━━━━━━━━━━━ 51s 339ms/step - loss: 0.9314 - mae: 0.6786 - rmse: 0.9608

117/269 ━━━━━━━━━━━━━━━━━━━━ 51s 338ms/step - loss: 0.9303 - mae: 0.6781 - rmse: 0.9602

118/269 ━━━━━━━━━━━━━━━━━━━━ 51s 338ms/step - loss: 0.9291 - mae: 0.6776 - rmse: 0.9596

119/269 ━━━━━━━━━━━━━━━━━━━━ 50s 338ms/step - loss: 0.9279 - mae: 0.6771 - rmse: 0.9589

120/269 ━━━━━━━━━━━━━━━━━━━━ 50s 337ms/step - loss: 0.9266 - mae: 0.6766 - rmse: 0.9583

121/269 ━━━━━━━━━━━━━━━━━━━━ 49s 337ms/step - loss: 0.9254 - mae: 0.6761 - rmse: 0.9576

122/269 ━━━━━━━━━━━━━━━━━━━━ 49s 337ms/step - loss: 0.9241 - mae: 0.6756 - rmse: 0.9570

123/269 ━━━━━━━━━━━━━━━━━━━━ 49s 337ms/step - loss: 0.9228 - mae: 0.6750 - rmse: 0.9563

124/269 ━━━━━━━━━━━━━━━━━━━━ 48s 337ms/step - loss: 0.9215 - mae: 0.6745 - rmse: 0.9556

125/269 ━━━━━━━━━━━━━━━━━━━━ 48s 336ms/step - loss: 0.9202 - mae: 0.6739 - rmse: 0.9549

126/269 ━━━━━━━━━━━━━━━━━━━━ 48s 336ms/step - loss: 0.9189 - mae: 0.6733 - rmse: 0.9541

127/269 ━━━━━━━━━━━━━━━━━━━━ 47s 337ms/step - loss: 0.9175 - mae: 0.6727 - rmse: 0.9534

128/269 ━━━━━━━━━━━━━━━━━━━━ 47s 337ms/step - loss: 0.9161 - mae: 0.6721 - rmse: 0.9527

129/269 ━━━━━━━━━━━━━━━━━━━━ 47s 337ms/step - loss: 0.9147 - mae: 0.6715 - rmse: 0.9519

130/269 ━━━━━━━━━━━━━━━━━━━━ 46s 337ms/step - loss: 0.9133 - mae: 0.6709 - rmse: 0.9512

131/269 ━━━━━━━━━━━━━━━━━━━━ 46s 337ms/step - loss: 0.9119 - mae: 0.6702 - rmse: 0.9504

132/269 ━━━━━━━━━━━━━━━━━━━━ 46s 338ms/step - loss: 0.9105 - mae: 0.6696 - rmse: 0.9496

133/269 ━━━━━━━━━━━━━━━━━━━━ 45s 338ms/step - loss: 0.9091 - mae: 0.6690 - rmse: 0.9489

134/269 ━━━━━━━━━━━━━━━━━━━━ 45s 338ms/step - loss: 0.9077 - mae: 0.6684 - rmse: 0.9481

135/269 ━━━━━━━━━━━━━━━━━━━━ 45s 338ms/step - loss: 0.9063 - mae: 0.6678 - rmse: 0.9473

136/269 ━━━━━━━━━━━━━━━━━━━━ 44s 337ms/step - loss: 0.9049 - mae: 0.6672 - rmse: 0.9466

137/269 ━━━━━━━━━━━━━━━━━━━━ 44s 337ms/step - loss: 0.9035 - mae: 0.6665 - rmse: 0.9458

138/269 ━━━━━━━━━━━━━━━━━━━━ 44s 337ms/step - loss: 0.9021 - mae: 0.6659 - rmse: 0.9450

139/269 ━━━━━━━━━━━━━━━━━━━━ 43s 337ms/step - loss: 0.9007 - mae: 0.6653 - rmse: 0.9442

140/269 ━━━━━━━━━━━━━━━━━━━━ 43s 337ms/step - loss: 0.8992 - mae: 0.6647 - rmse: 0.9434

141/269 ━━━━━━━━━━━━━━━━━━━━ 42s 336ms/step - loss: 0.8978 - mae: 0.6640 - rmse: 0.9426

142/269 ━━━━━━━━━━━━━━━━━━━━ 42s 336ms/step - loss: 0.8963 - mae: 0.6634 - rmse: 0.9418

143/269 ━━━━━━━━━━━━━━━━━━━━ 42s 335ms/step - loss: 0.8949 - mae: 0.6628 - rmse: 0.9410

144/269 ━━━━━━━━━━━━━━━━━━━━ 41s 335ms/step - loss: 0.8934 - mae: 0.6621 - rmse: 0.9402

145/269 ━━━━━━━━━━━━━━━━━━━━ 41s 334ms/step - loss: 0.8919 - mae: 0.6614 - rmse: 0.9394

146/269 ━━━━━━━━━━━━━━━━━━━━ 41s 334ms/step - loss: 0.8905 - mae: 0.6608 - rmse: 0.9386

147/269 ━━━━━━━━━━━━━━━━━━━━ 40s 334ms/step - loss: 0.8890 - mae: 0.6601 - rmse: 0.9378

148/269 ━━━━━━━━━━━━━━━━━━━━ 40s 334ms/step - loss: 0.8875 - mae: 0.6594 - rmse: 0.9369

149/269 ━━━━━━━━━━━━━━━━━━━━ 40s 334ms/step - loss: 0.8860 - mae: 0.6587 - rmse: 0.9361

150/269 ━━━━━━━━━━━━━━━━━━━━ 39s 334ms/step - loss: 0.8845 - mae: 0.6580 - rmse: 0.9352

151/269 ━━━━━━━━━━━━━━━━━━━━ 39s 334ms/step - loss: 0.8830 - mae: 0.6573 - rmse: 0.9344

152/269 ━━━━━━━━━━━━━━━━━━━━ 39s 333ms/step - loss: 0.8815 - mae: 0.6567 - rmse: 0.9335

153/269 ━━━━━━━━━━━━━━━━━━━━ 38s 333ms/step - loss: 0.8800 - mae: 0.6560 - rmse: 0.9327

154/269 ━━━━━━━━━━━━━━━━━━━━ 38s 333ms/step - loss: 0.8785 - mae: 0.6553 - rmse: 0.9319

155/269 ━━━━━━━━━━━━━━━━━━━━ 37s 333ms/step - loss: 0.8769 - mae: 0.6546 - rmse: 0.9310

156/269 ━━━━━━━━━━━━━━━━━━━━ 37s 333ms/step - loss: 0.8754 - mae: 0.6539 - rmse: 0.9302

157/269 ━━━━━━━━━━━━━━━━━━━━ 37s 332ms/step - loss: 0.8739 - mae: 0.6532 - rmse: 0.9293

158/269 ━━━━━━━━━━━━━━━━━━━━ 36s 332ms/step - loss: 0.8724 - mae: 0.6525 - rmse: 0.9284

159/269 ━━━━━━━━━━━━━━━━━━━━ 36s 332ms/step - loss: 0.8709 - mae: 0.6518 - rmse: 0.9276

160/269 ━━━━━━━━━━━━━━━━━━━━ 36s 332ms/step - loss: 0.8694 - mae: 0.6511 - rmse: 0.9267

161/269 ━━━━━━━━━━━━━━━━━━━━ 35s 332ms/step - loss: 0.8679 - mae: 0.6504 - rmse: 0.9259

162/269 ━━━━━━━━━━━━━━━━━━━━ 35s 332ms/step - loss: 0.8664 - mae: 0.6497 - rmse: 0.9250

163/269 ━━━━━━━━━━━━━━━━━━━━ 35s 333ms/step - loss: 0.8649 - mae: 0.6489 - rmse: 0.9241

164/269 ━━━━━━━━━━━━━━━━━━━━ 35s 334ms/step - loss: 0.8634 - mae: 0.6482 - rmse: 0.9233

165/269 ━━━━━━━━━━━━━━━━━━━━ 34s 334ms/step - loss: 0.8619 - mae: 0.6475 - rmse: 0.9224

166/269 ━━━━━━━━━━━━━━━━━━━━ 34s 335ms/step - loss: 0.8604 - mae: 0.6469 - rmse: 0.9216

167/269 ━━━━━━━━━━━━━━━━━━━━ 34s 335ms/step - loss: 0.8589 - mae: 0.6462 - rmse: 0.9207

168/269 ━━━━━━━━━━━━━━━━━━━━ 33s 335ms/step - loss: 0.8574 - mae: 0.6455 - rmse: 0.9199

169/269 ━━━━━━━━━━━━━━━━━━━━ 33s 335ms/step - loss: 0.8560 - mae: 0.6448 - rmse: 0.9190

170/269 ━━━━━━━━━━━━━━━━━━━━ 33s 335ms/step - loss: 0.8545 - mae: 0.6442 - rmse: 0.9182

171/269 ━━━━━━━━━━━━━━━━━━━━ 32s 337ms/step - loss: 0.8531 - mae: 0.6435 - rmse: 0.9174

172/269 ━━━━━━━━━━━━━━━━━━━━ 32s 337ms/step - loss: 0.8517 - mae: 0.6429 - rmse: 0.9166

173/269 ━━━━━━━━━━━━━━━━━━━━ 32s 337ms/step - loss: 0.8503 - mae: 0.6422 - rmse: 0.9158

174/269 ━━━━━━━━━━━━━━━━━━━━ 32s 338ms/step - loss: 0.8489 - mae: 0.6416 - rmse: 0.9150

175/269 ━━━━━━━━━━━━━━━━━━━━ 31s 338ms/step - loss: 0.8475 - mae: 0.6410 - rmse: 0.9142

176/269 ━━━━━━━━━━━━━━━━━━━━ 31s 338ms/step - loss: 0.8462 - mae: 0.6403 - rmse: 0.9134

177/269 ━━━━━━━━━━━━━━━━━━━━ 31s 338ms/step - loss: 0.8448 - mae: 0.6397 - rmse: 0.9126

178/269 ━━━━━━━━━━━━━━━━━━━━ 30s 338ms/step - loss: 0.8434 - mae: 0.6391 - rmse: 0.9118

179/269 ━━━━━━━━━━━━━━━━━━━━ 30s 339ms/step - loss: 0.8421 - mae: 0.6385 - rmse: 0.9111

180/269 ━━━━━━━━━━━━━━━━━━━━ 30s 339ms/step - loss: 0.8407 - mae: 0.6378 - rmse: 0.9103

181/269 ━━━━━━━━━━━━━━━━━━━━ 29s 339ms/step - loss: 0.8393 - mae: 0.6372 - rmse: 0.9095

182/269 ━━━━━━━━━━━━━━━━━━━━ 29s 339ms/step - loss: 0.8380 - mae: 0.6366 - rmse: 0.9087

183/269 ━━━━━━━━━━━━━━━━━━━━ 29s 339ms/step - loss: 0.8366 - mae: 0.6360 - rmse: 0.9079

184/269 ━━━━━━━━━━━━━━━━━━━━ 28s 339ms/step - loss: 0.8352 - mae: 0.6353 - rmse: 0.9071

185/269 ━━━━━━━━━━━━━━━━━━━━ 28s 338ms/step - loss: 0.8339 - mae: 0.6347 - rmse: 0.9063

186/269 ━━━━━━━━━━━━━━━━━━━━ 28s 338ms/step - loss: 0.8325 - mae: 0.6341 - rmse: 0.9055

187/269 ━━━━━━━━━━━━━━━━━━━━ 27s 338ms/step - loss: 0.8312 - mae: 0.6335 - rmse: 0.9047

188/269 ━━━━━━━━━━━━━━━━━━━━ 27s 338ms/step - loss: 0.8298 - mae: 0.6328 - rmse: 0.9039

189/269 ━━━━━━━━━━━━━━━━━━━━ 27s 338ms/step - loss: 0.8284 - mae: 0.6322 - rmse: 0.9031

190/269 ━━━━━━━━━━━━━━━━━━━━ 26s 337ms/step - loss: 0.8271 - mae: 0.6316 - rmse: 0.9024

191/269 ━━━━━━━━━━━━━━━━━━━━ 26s 337ms/step - loss: 0.8257 - mae: 0.6310 - rmse: 0.9016

192/269 ━━━━━━━━━━━━━━━━━━━━ 25s 337ms/step - loss: 0.8244 - mae: 0.6303 - rmse: 0.9008

193/269 ━━━━━━━━━━━━━━━━━━━━ 25s 337ms/step - loss: 0.8231 - mae: 0.6297 - rmse: 0.9000

194/269 ━━━━━━━━━━━━━━━━━━━━ 25s 337ms/step - loss: 0.8217 - mae: 0.6291 - rmse: 0.8992

195/269 ━━━━━━━━━━━━━━━━━━━━ 24s 337ms/step - loss: 0.8204 - mae: 0.6284 - rmse: 0.8984

196/269 ━━━━━━━━━━━━━━━━━━━━ 24s 337ms/step - loss: 0.8190 - mae: 0.6278 - rmse: 0.8976

197/269 ━━━━━━━━━━━━━━━━━━━━ 24s 336ms/step - loss: 0.8177 - mae: 0.6272 - rmse: 0.8968

198/269 ━━━━━━━━━━━━━━━━━━━━ 23s 336ms/step - loss: 0.8164 - mae: 0.6266 - rmse: 0.8961

199/269 ━━━━━━━━━━━━━━━━━━━━ 23s 336ms/step - loss: 0.8151 - mae: 0.6260 - rmse: 0.8953

200/269 ━━━━━━━━━━━━━━━━━━━━ 23s 335ms/step - loss: 0.8137 - mae: 0.6253 - rmse: 0.8945

201/269 ━━━━━━━━━━━━━━━━━━━━ 22s 335ms/step - loss: 0.8124 - mae: 0.6247 - rmse: 0.8937

202/269 ━━━━━━━━━━━━━━━━━━━━ 22s 335ms/step - loss: 0.8111 - mae: 0.6241 - rmse: 0.8930

203/269 ━━━━━━━━━━━━━━━━━━━━ 22s 334ms/step - loss: 0.8099 - mae: 0.6235 - rmse: 0.8922

204/269 ━━━━━━━━━━━━━━━━━━━━ 21s 334ms/step - loss: 0.8086 - mae: 0.6229 - rmse: 0.8914

205/269 ━━━━━━━━━━━━━━━━━━━━ 21s 334ms/step - loss: 0.8073 - mae: 0.6223 - rmse: 0.8907

206/269 ━━━━━━━━━━━━━━━━━━━━ 21s 334ms/step - loss: 0.8061 - mae: 0.6217 - rmse: 0.8900

207/269 ━━━━━━━━━━━━━━━━━━━━ 20s 333ms/step - loss: 0.8048 - mae: 0.6211 - rmse: 0.8892

208/269 ━━━━━━━━━━━━━━━━━━━━ 20s 333ms/step - loss: 0.8036 - mae: 0.6205 - rmse: 0.8885

209/269 ━━━━━━━━━━━━━━━━━━━━ 20s 334ms/step - loss: 0.8023 - mae: 0.6200 - rmse: 0.8877

210/269 ━━━━━━━━━━━━━━━━━━━━ 19s 334ms/step - loss: 0.8011 - mae: 0.6194 - rmse: 0.8870

211/269 ━━━━━━━━━━━━━━━━━━━━ 19s 333ms/step - loss: 0.7998 - mae: 0.6188 - rmse: 0.8863

212/269 ━━━━━━━━━━━━━━━━━━━━ 18s 333ms/step - loss: 0.7986 - mae: 0.6182 - rmse: 0.8855

213/269 ━━━━━━━━━━━━━━━━━━━━ 18s 333ms/step - loss: 0.7974 - mae: 0.6176 - rmse: 0.8848

214/269 ━━━━━━━━━━━━━━━━━━━━ 18s 332ms/step - loss: 0.7961 - mae: 0.6170 - rmse: 0.8840

215/269 ━━━━━━━━━━━━━━━━━━━━ 17s 333ms/step - loss: 0.7949 - mae: 0.6164 - rmse: 0.8833

216/269 ━━━━━━━━━━━━━━━━━━━━ 17s 333ms/step - loss: 0.7937 - mae: 0.6159 - rmse: 0.8826

217/269 ━━━━━━━━━━━━━━━━━━━━ 17s 333ms/step - loss: 0.7925 - mae: 0.6153 - rmse: 0.8818

218/269 ━━━━━━━━━━━━━━━━━━━━ 16s 333ms/step - loss: 0.7912 - mae: 0.6147 - rmse: 0.8811

219/269 ━━━━━━━━━━━━━━━━━━━━ 16s 334ms/step - loss: 0.7900 - mae: 0.6141 - rmse: 0.8804

220/269 ━━━━━━━━━━━━━━━━━━━━ 16s 334ms/step - loss: 0.7888 - mae: 0.6136 - rmse: 0.8797

221/269 ━━━━━━━━━━━━━━━━━━━━ 16s 335ms/step - loss: 0.7876 - mae: 0.6130 - rmse: 0.8789

222/269 ━━━━━━━━━━━━━━━━━━━━ 15s 336ms/step - loss: 0.7864 - mae: 0.6124 - rmse: 0.8782

223/269 ━━━━━━━━━━━━━━━━━━━━ 15s 336ms/step - loss: 0.7852 - mae: 0.6118 - rmse: 0.8775

224/269 ━━━━━━━━━━━━━━━━━━━━ 15s 336ms/step - loss: 0.7840 - mae: 0.6113 - rmse: 0.8767

225/269 ━━━━━━━━━━━━━━━━━━━━ 14s 336ms/step - loss: 0.7828 - mae: 0.6107 - rmse: 0.8760

226/269 ━━━━━━━━━━━━━━━━━━━━ 14s 336ms/step - loss: 0.7816 - mae: 0.6101 - rmse: 0.8753

227/269 ━━━━━━━━━━━━━━━━━━━━ 14s 337ms/step - loss: 0.7804 - mae: 0.6096 - rmse: 0.8746

228/269 ━━━━━━━━━━━━━━━━━━━━ 13s 337ms/step - loss: 0.7792 - mae: 0.6090 - rmse: 0.8738

229/269 ━━━━━━━━━━━━━━━━━━━━ 13s 337ms/step - loss: 0.7780 - mae: 0.6084 - rmse: 0.8731

230/269 ━━━━━━━━━━━━━━━━━━━━ 13s 337ms/step - loss: 0.7768 - mae: 0.6078 - rmse: 0.8724

231/269 ━━━━━━━━━━━━━━━━━━━━ 12s 337ms/step - loss: 0.7756 - mae: 0.6073 - rmse: 0.8717

232/269 ━━━━━━━━━━━━━━━━━━━━ 12s 337ms/step - loss: 0.7744 - mae: 0.6067 - rmse: 0.8710

233/269 ━━━━━━━━━━━━━━━━━━━━ 12s 337ms/step - loss: 0.7733 - mae: 0.6061 - rmse: 0.8702

234/269 ━━━━━━━━━━━━━━━━━━━━ 11s 337ms/step - loss: 0.7721 - mae: 0.6056 - rmse: 0.8695

235/269 ━━━━━━━━━━━━━━━━━━━━ 11s 337ms/step - loss: 0.7709 - mae: 0.6050 - rmse: 0.8688

236/269 ━━━━━━━━━━━━━━━━━━━━ 11s 336ms/step - loss: 0.7697 - mae: 0.6044 - rmse: 0.8681

237/269 ━━━━━━━━━━━━━━━━━━━━ 10s 336ms/step - loss: 0.7686 - mae: 0.6039 - rmse: 0.8674

238/269 ━━━━━━━━━━━━━━━━━━━━ 10s 336ms/step - loss: 0.7674 - mae: 0.6033 - rmse: 0.8667

239/269 ━━━━━━━━━━━━━━━━━━━━ 10s 336ms/step - loss: 0.7663 - mae: 0.6027 - rmse: 0.8660

240/269 ━━━━━━━━━━━━━━━━━━━━ 9s 336ms/step - loss: 0.7651 - mae: 0.6022 - rmse: 0.8652

241/269 ━━━━━━━━━━━━━━━━━━━━ 9s 336ms/step - loss: 0.7640 - mae: 0.6016 - rmse: 0.8645

242/269 ━━━━━━━━━━━━━━━━━━━━ 9s 335ms/step - loss: 0.7628 - mae: 0.6011 - rmse: 0.8638

243/269 ━━━━━━━━━━━━━━━━━━━━ 8s 335ms/step - loss: 0.7617 - mae: 0.6005 - rmse: 0.8631

244/269 ━━━━━━━━━━━━━━━━━━━━ 8s 335ms/step - loss: 0.7605 - mae: 0.6000 - rmse: 0.8624

245/269 ━━━━━━━━━━━━━━━━━━━━ 8s 335ms/step - loss: 0.7594 - mae: 0.5994 - rmse: 0.8617

246/269 ━━━━━━━━━━━━━━━━━━━━ 7s 335ms/step - loss: 0.7583 - mae: 0.5989 - rmse: 0.8610

247/269 ━━━━━━━━━━━━━━━━━━━━ 7s 334ms/step - loss: 0.7571 - mae: 0.5983 - rmse: 0.8604

248/269 ━━━━━━━━━━━━━━━━━━━━ 7s 334ms/step - loss: 0.7560 - mae: 0.5978 - rmse: 0.8597

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 334ms/step - loss: 0.7549 - mae: 0.5972 - rmse: 0.8590

250/269 ━━━━━━━━━━━━━━━━━━━━ 6s 334ms/step - loss: 0.7538 - mae: 0.5967 - rmse: 0.8583

251/269 ━━━━━━━━━━━━━━━━━━━━ 6s 334ms/step - loss: 0.7527 - mae: 0.5962 - rmse: 0.8576

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 333ms/step - loss: 0.7516 - mae: 0.5956 - rmse: 0.8569

253/269 ━━━━━━━━━━━━━━━━━━━━ 5s 333ms/step - loss: 0.7505 - mae: 0.5951 - rmse: 0.8562

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 333ms/step - loss: 0.7494 - mae: 0.5946 - rmse: 0.8555

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 333ms/step - loss: 0.7483 - mae: 0.5940 - rmse: 0.8549

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 333ms/step - loss: 0.7472 - mae: 0.5935 - rmse: 0.8542

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 333ms/step - loss: 0.7461 - mae: 0.5930 - rmse: 0.8535

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 333ms/step - loss: 0.7450 - mae: 0.5924 - rmse: 0.8528

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 333ms/step - loss: 0.7439 - mae: 0.5919 - rmse: 0.8521

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - loss: 0.7428 - mae: 0.5914 - rmse: 0.8515

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 333ms/step - loss: 0.7418 - mae: 0.5909 - rmse: 0.8508

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - loss: 0.7407 - mae: 0.5903 - rmse: 0.8501

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 334ms/step - loss: 0.7396 - mae: 0.5898 - rmse: 0.8495

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 334ms/step - loss: 0.7385 - mae: 0.5893 - rmse: 0.8488

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 333ms/step - loss: 0.7375 - mae: 0.5888 - rmse: 0.8481

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 333ms/step - loss: 0.7364 - mae: 0.5882 - rmse: 0.8475

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - loss: 0.7354 - mae: 0.5877 - rmse: 0.8468

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - loss: 0.7343 - mae: 0.5872 - rmse: 0.8461

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - loss: 0.7333 - mae: 0.5867 - rmse: 0.8455

269/269 ━━━━━━━━━━━━━━━━━━━━ 97s 362ms/step - loss: 0.4532 - mae: 0.4500 - rmse: 0.6697 - val_loss: 0.7919 - val_mae: 0.5516 - val_rmse: 0.8873 - learning_rate: 0.0010

Epoch 7/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 3:20:32 45s/step - loss: 0.9822 - mae: 0.6584 - rmse: 0.9887

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 285ms/step - loss: 0.8726 - mae: 0.6358 - rmse: 0.9297

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 320ms/step - loss: 0.8739 - mae: 0.6495 - rmse: 0.9311

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 322ms/step - loss: 0.8617 - mae: 0.6516 - rmse: 0.9247

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 329ms/step - loss: 0.8339 - mae: 0.6437 - rmse: 0.9093

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 342ms/step - loss: 0.8123 - mae: 0.6375 - rmse: 0.8971

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 351ms/step - loss: 0.8078 - mae: 0.6369 - rmse: 0.8948

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 348ms/step - loss: 0.8185 - mae: 0.6414 - rmse: 0.9008

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 339ms/step - loss: 0.8237 - mae: 0.6437 - rmse: 0.9038

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 336ms/step - loss: 0.8234 - mae: 0.6438 - rmse: 0.9037

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 333ms/step - loss: 0.8206 - mae: 0.6430 - rmse: 0.9023

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 327ms/step - loss: 0.8274 - mae: 0.6455 - rmse: 0.9060

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 323ms/step - loss: 0.8388 - mae: 0.6490 - rmse: 0.9121

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 318ms/step - loss: 0.8568 - mae: 0.6548 - rmse: 0.9214

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 316ms/step - loss: 0.8722 - mae: 0.6599 - rmse: 0.9294

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 317ms/step - loss: 0.8876 - mae: 0.6652 - rmse: 0.9373

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 314ms/step - loss: 0.9037 - mae: 0.6701 - rmse: 0.9454

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 313ms/step - loss: 0.9171 - mae: 0.6742 - rmse: 0.9522

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 314ms/step - loss: 0.9312 - mae: 0.6782 - rmse: 0.9592

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 311ms/step - loss: 0.9437 - mae: 0.6818 - rmse: 0.9655

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 309ms/step - loss: 0.9532 - mae: 0.6844 - rmse: 0.9704

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 307ms/step - loss: 0.9617 - mae: 0.6869 - rmse: 0.9747

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 308ms/step - loss: 0.9703 - mae: 0.6895 - rmse: 0.9790

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 307ms/step - loss: 0.9776 - mae: 0.6919 - rmse: 0.9828

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 311ms/step - loss: 0.9837 - mae: 0.6938 - rmse: 0.9859

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 312ms/step - loss: 0.9896 - mae: 0.6956 - rmse: 0.9889

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 317ms/step - loss: 0.9942 - mae: 0.6970 - rmse: 0.9913

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 319ms/step - loss: 0.9978 - mae: 0.6981 - rmse: 0.9932

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 319ms/step - loss: 1.0008 - mae: 0.6991 - rmse: 0.9948

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 323ms/step - loss: 1.0028 - mae: 0.6997 - rmse: 0.9958

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 324ms/step - loss: 1.0040 - mae: 0.7001 - rmse: 0.9965

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 327ms/step - loss: 1.0048 - mae: 0.7003 - rmse: 0.9970

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 327ms/step - loss: 1.0052 - mae: 0.7005 - rmse: 0.9973

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 327ms/step - loss: 1.0052 - mae: 0.7006 - rmse: 0.9974

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 327ms/step - loss: 1.0052 - mae: 0.7006 - rmse: 0.9975

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 326ms/step - loss: 1.0047 - mae: 0.7006 - rmse: 0.9973

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 325ms/step - loss: 1.0041 - mae: 0.7005 - rmse: 0.9971

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 325ms/step - loss: 1.0031 - mae: 0.7002 - rmse: 0.9966

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 324ms/step - loss: 1.0019 - mae: 0.6999 - rmse: 0.9961

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 324ms/step - loss: 1.0004 - mae: 0.6994 - rmse: 0.9954

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 324ms/step - loss: 0.9990 - mae: 0.6991 - rmse: 0.9947

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 324ms/step - loss: 0.9974 - mae: 0.6986 - rmse: 0.9940

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 324ms/step - loss: 0.9957 - mae: 0.6981 - rmse: 0.9932

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 324ms/step - loss: 0.9942 - mae: 0.6977 - rmse: 0.9925

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 324ms/step - loss: 0.9926 - mae: 0.6973 - rmse: 0.9917

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 322ms/step - loss: 0.9909 - mae: 0.6968 - rmse: 0.9908

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 321ms/step - loss: 0.9892 - mae: 0.6963 - rmse: 0.9900

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 320ms/step - loss: 0.9874 - mae: 0.6958 - rmse: 0.9892

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 320ms/step - loss: 0.9854 - mae: 0.6952 - rmse: 0.9882

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 320ms/step - loss: 0.9833 - mae: 0.6946 - rmse: 0.9871

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 320ms/step - loss: 0.9811 - mae: 0.6939 - rmse: 0.9860

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 320ms/step - loss: 0.9789 - mae: 0.6932 - rmse: 0.9849

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 319ms/step - loss: 0.9766 - mae: 0.6924 - rmse: 0.9837

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 319ms/step - loss: 0.9744 - mae: 0.6918 - rmse: 0.9827

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 318ms/step - loss: 0.9723 - mae: 0.6911 - rmse: 0.9815

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 318ms/step - loss: 0.9701 - mae: 0.6904 - rmse: 0.9805

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 317ms/step - loss: 0.9680 - mae: 0.6897 - rmse: 0.9794

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 317ms/step - loss: 0.9659 - mae: 0.6890 - rmse: 0.9783

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 318ms/step - loss: 0.9639 - mae: 0.6884 - rmse: 0.9773

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 319ms/step - loss: 0.9619 - mae: 0.6878 - rmse: 0.9763

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 319ms/step - loss: 0.9601 - mae: 0.6872 - rmse: 0.9753

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 319ms/step - loss: 0.9582 - mae: 0.6867 - rmse: 0.9744

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 318ms/step - loss: 0.9564 - mae: 0.6861 - rmse: 0.9735

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 318ms/step - loss: 0.9544 - mae: 0.6855 - rmse: 0.9725

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 317ms/step - loss: 0.9524 - mae: 0.6849 - rmse: 0.9714

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 317ms/step - loss: 0.9503 - mae: 0.6842 - rmse: 0.9703

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 317ms/step - loss: 0.9482 - mae: 0.6835 - rmse: 0.9692

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 317ms/step - loss: 0.9460 - mae: 0.6827 - rmse: 0.9681

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 316ms/step - loss: 0.9440 - mae: 0.6821 - rmse: 0.9670

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 316ms/step - loss: 0.9419 - mae: 0.6814 - rmse: 0.9660

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 316ms/step - loss: 0.9401 - mae: 0.6808 - rmse: 0.9650

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 317ms/step - loss: 0.9382 - mae: 0.6801 - rmse: 0.9640

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 317ms/step - loss: 0.9364 - mae: 0.6795 - rmse: 0.9631

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 317ms/step - loss: 0.9347 - mae: 0.6790 - rmse: 0.9622

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 317ms/step - loss: 0.9331 - mae: 0.6784 - rmse: 0.9614

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 317ms/step - loss: 0.9315 - mae: 0.6779 - rmse: 0.9605

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 317ms/step - loss: 0.9300 - mae: 0.6774 - rmse: 0.9598

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 317ms/step - loss: 0.9286 - mae: 0.6770 - rmse: 0.9591

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 317ms/step - loss: 0.9273 - mae: 0.6765 - rmse: 0.9584

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 318ms/step - loss: 0.9259 - mae: 0.6761 - rmse: 0.9577

 81/269 ━━━━━━━━━━━━━━━━━━━━ 59s 318ms/step - loss: 0.9249 - mae: 0.6758 - rmse: 0.9572

 82/269 ━━━━━━━━━━━━━━━━━━━━ 59s 319ms/step - loss: 0.9243 - mae: 0.6756 - rmse: 0.9569

 83/269 ━━━━━━━━━━━━━━━━━━━━ 59s 319ms/step - loss: 0.9239 - mae: 0.6755 - rmse: 0.9567

 84/269 ━━━━━━━━━━━━━━━━━━━━ 59s 320ms/step - loss: 0.9236 - mae: 0.6754 - rmse: 0.9565

 85/269 ━━━━━━━━━━━━━━━━━━━━ 58s 320ms/step - loss: 0.9233 - mae: 0.6753 - rmse: 0.9564

 86/269 ━━━━━━━━━━━━━━━━━━━━ 58s 321ms/step - loss: 0.9232 - mae: 0.6752 - rmse: 0.9564

 87/269 ━━━━━━━━━━━━━━━━━━━━ 58s 320ms/step - loss: 0.9231 - mae: 0.6752 - rmse: 0.9564

 88/269 ━━━━━━━━━━━━━━━━━━━━ 57s 320ms/step - loss: 0.9230 - mae: 0.6752 - rmse: 0.9563

 89/269 ━━━━━━━━━━━━━━━━━━━━ 57s 321ms/step - loss: 0.9229 - mae: 0.6752 - rmse: 0.9563

 90/269 ━━━━━━━━━━━━━━━━━━━━ 57s 320ms/step - loss: 0.9228 - mae: 0.6752 - rmse: 0.9563

 91/269 ━━━━━━━━━━━━━━━━━━━━ 57s 322ms/step - loss: 0.9227 - mae: 0.6751 - rmse: 0.9562

 92/269 ━━━━━━━━━━━━━━━━━━━━ 57s 323ms/step - loss: 0.9224 - mae: 0.6751 - rmse: 0.9561

 93/269 ━━━━━━━━━━━━━━━━━━━━ 57s 324ms/step - loss: 0.9222 - mae: 0.6750 - rmse: 0.9560

 94/269 ━━━━━━━━━━━━━━━━━━━━ 56s 325ms/step - loss: 0.9218 - mae: 0.6749 - rmse: 0.9558

 95/269 ━━━━━━━━━━━━━━━━━━━━ 56s 326ms/step - loss: 0.9214 - mae: 0.6748 - rmse: 0.9556

 96/269 ━━━━━━━━━━━━━━━━━━━━ 56s 327ms/step - loss: 0.9210 - mae: 0.6746 - rmse: 0.9554

 97/269 ━━━━━━━━━━━━━━━━━━━━ 56s 329ms/step - loss: 0.9205 - mae: 0.6745 - rmse: 0.9552

 98/269 ━━━━━━━━━━━━━━━━━━━━ 56s 329ms/step - loss: 0.9199 - mae: 0.6743 - rmse: 0.9549

 99/269 ━━━━━━━━━━━━━━━━━━━━ 56s 330ms/step - loss: 0.9193 - mae: 0.6741 - rmse: 0.9546

100/269 ━━━━━━━━━━━━━━━━━━━━ 55s 330ms/step - loss: 0.9187 - mae: 0.6739 - rmse: 0.9543

101/269 ━━━━━━━━━━━━━━━━━━━━ 55s 330ms/step - loss: 0.9181 - mae: 0.6737 - rmse: 0.9540

102/269 ━━━━━━━━━━━━━━━━━━━━ 55s 330ms/step - loss: 0.9175 - mae: 0.6734 - rmse: 0.9537

103/269 ━━━━━━━━━━━━━━━━━━━━ 54s 330ms/step - loss: 0.9168 - mae: 0.6732 - rmse: 0.9533

104/269 ━━━━━━━━━━━━━━━━━━━━ 54s 330ms/step - loss: 0.9161 - mae: 0.6730 - rmse: 0.9530

105/269 ━━━━━━━━━━━━━━━━━━━━ 54s 330ms/step - loss: 0.9154 - mae: 0.6728 - rmse: 0.9526

106/269 ━━━━━━━━━━━━━━━━━━━━ 53s 330ms/step - loss: 0.9147 - mae: 0.6725 - rmse: 0.9523

107/269 ━━━━━━━━━━━━━━━━━━━━ 53s 332ms/step - loss: 0.9139 - mae: 0.6723 - rmse: 0.9519

108/269 ━━━━━━━━━━━━━━━━━━━━ 53s 334ms/step - loss: 0.9131 - mae: 0.6720 - rmse: 0.9514

109/269 ━━━━━━━━━━━━━━━━━━━━ 53s 334ms/step - loss: 0.9123 - mae: 0.6717 - rmse: 0.9510

110/269 ━━━━━━━━━━━━━━━━━━━━ 53s 338ms/step - loss: 0.9114 - mae: 0.6713 - rmse: 0.9505

111/269 ━━━━━━━━━━━━━━━━━━━━ 53s 340ms/step - loss: 0.9104 - mae: 0.6710 - rmse: 0.9500

112/269 ━━━━━━━━━━━━━━━━━━━━ 53s 342ms/step - loss: 0.9095 - mae: 0.6706 - rmse: 0.9495

113/269 ━━━━━━━━━━━━━━━━━━━━ 53s 343ms/step - loss: 0.9085 - mae: 0.6702 - rmse: 0.9490

114/269 ━━━━━━━━━━━━━━━━━━━━ 53s 344ms/step - loss: 0.9075 - mae: 0.6698 - rmse: 0.9485

115/269 ━━━━━━━━━━━━━━━━━━━━ 53s 346ms/step - loss: 0.9064 - mae: 0.6694 - rmse: 0.9479

116/269 ━━━━━━━━━━━━━━━━━━━━ 53s 347ms/step - loss: 0.9053 - mae: 0.6689 - rmse: 0.9473

117/269 ━━━━━━━━━━━━━━━━━━━━ 52s 347ms/step - loss: 0.9042 - mae: 0.6685 - rmse: 0.9467

118/269 ━━━━━━━━━━━━━━━━━━━━ 52s 347ms/step - loss: 0.9031 - mae: 0.6680 - rmse: 0.9461

119/269 ━━━━━━━━━━━━━━━━━━━━ 52s 347ms/step - loss: 0.9020 - mae: 0.6675 - rmse: 0.9455

120/269 ━━━━━━━━━━━━━━━━━━━━ 51s 347ms/step - loss: 0.9008 - mae: 0.6670 - rmse: 0.9449

121/269 ━━━━━━━━━━━━━━━━━━━━ 51s 347ms/step - loss: 0.8996 - mae: 0.6666 - rmse: 0.9443

122/269 ━━━━━━━━━━━━━━━━━━━━ 51s 348ms/step - loss: 0.8984 - mae: 0.6660 - rmse: 0.9436

123/269 ━━━━━━━━━━━━━━━━━━━━ 50s 349ms/step - loss: 0.8972 - mae: 0.6655 - rmse: 0.9430

124/269 ━━━━━━━━━━━━━━━━━━━━ 50s 350ms/step - loss: 0.8960 - mae: 0.6650 - rmse: 0.9423

125/269 ━━━━━━━━━━━━━━━━━━━━ 50s 351ms/step - loss: 0.8947 - mae: 0.6644 - rmse: 0.9416

126/269 ━━━━━━━━━━━━━━━━━━━━ 50s 353ms/step - loss: 0.8934 - mae: 0.6639 - rmse: 0.9409

127/269 ━━━━━━━━━━━━━━━━━━━━ 50s 355ms/step - loss: 0.8921 - mae: 0.6633 - rmse: 0.9402

128/269 ━━━━━━━━━━━━━━━━━━━━ 50s 356ms/step - loss: 0.8908 - mae: 0.6627 - rmse: 0.9395

129/269 ━━━━━━━━━━━━━━━━━━━━ 49s 356ms/step - loss: 0.8895 - mae: 0.6621 - rmse: 0.9387

130/269 ━━━━━━━━━━━━━━━━━━━━ 49s 357ms/step - loss: 0.8882 - mae: 0.6615 - rmse: 0.9380

131/269 ━━━━━━━━━━━━━━━━━━━━ 49s 358ms/step - loss: 0.8868 - mae: 0.6609 - rmse: 0.9373

132/269 ━━━━━━━━━━━━━━━━━━━━ 49s 358ms/step - loss: 0.8855 - mae: 0.6603 - rmse: 0.9365

133/269 ━━━━━━━━━━━━━━━━━━━━ 49s 361ms/step - loss: 0.8841 - mae: 0.6597 - rmse: 0.9358

134/269 ━━━━━━━━━━━━━━━━━━━━ 48s 363ms/step - loss: 0.8828 - mae: 0.6591 - rmse: 0.9351

135/269 ━━━━━━━━━━━━━━━━━━━━ 48s 363ms/step - loss: 0.8814 - mae: 0.6585 - rmse: 0.9343

136/269 ━━━━━━━━━━━━━━━━━━━━ 48s 363ms/step - loss: 0.8801 - mae: 0.6580 - rmse: 0.9336

137/269 ━━━━━━━━━━━━━━━━━━━━ 48s 364ms/step - loss: 0.8788 - mae: 0.6574 - rmse: 0.9328

138/269 ━━━━━━━━━━━━━━━━━━━━ 47s 365ms/step - loss: 0.8774 - mae: 0.6568 - rmse: 0.9321

139/269 ━━━━━━━━━━━━━━━━━━━━ 47s 367ms/step - loss: 0.8760 - mae: 0.6562 - rmse: 0.9313

140/269 ━━━━━━━━━━━━━━━━━━━━ 47s 369ms/step - loss: 0.8747 - mae: 0.6556 - rmse: 0.9305

141/269 ━━━━━━━━━━━━━━━━━━━━ 47s 369ms/step - loss: 0.8733 - mae: 0.6549 - rmse: 0.9298

142/269 ━━━━━━━━━━━━━━━━━━━━ 47s 370ms/step - loss: 0.8719 - mae: 0.6543 - rmse: 0.9290

143/269 ━━━━━━━━━━━━━━━━━━━━ 46s 372ms/step - loss: 0.8705 - mae: 0.6537 - rmse: 0.9282

144/269 ━━━━━━━━━━━━━━━━━━━━ 46s 372ms/step - loss: 0.8691 - mae: 0.6531 - rmse: 0.9274

145/269 ━━━━━━━━━━━━━━━━━━━━ 46s 372ms/step - loss: 0.8677 - mae: 0.6524 - rmse: 0.9266

146/269 ━━━━━━━━━━━━━━━━━━━━ 45s 373ms/step - loss: 0.8663 - mae: 0.6518 - rmse: 0.9258

147/269 ━━━━━━━━━━━━━━━━━━━━ 45s 373ms/step - loss: 0.8648 - mae: 0.6511 - rmse: 0.9250

148/269 ━━━━━━━━━━━━━━━━━━━━ 45s 373ms/step - loss: 0.8634 - mae: 0.6505 - rmse: 0.9242

149/269 ━━━━━━━━━━━━━━━━━━━━ 44s 374ms/step - loss: 0.8620 - mae: 0.6498 - rmse: 0.9234

150/269 ━━━━━━━━━━━━━━━━━━━━ 44s 374ms/step - loss: 0.8605 - mae: 0.6491 - rmse: 0.9226

151/269 ━━━━━━━━━━━━━━━━━━━━ 44s 373ms/step - loss: 0.8591 - mae: 0.6485 - rmse: 0.9218

152/269 ━━━━━━━━━━━━━━━━━━━━ 43s 373ms/step - loss: 0.8576 - mae: 0.6478 - rmse: 0.9209

153/269 ━━━━━━━━━━━━━━━━━━━━ 43s 374ms/step - loss: 0.8562 - mae: 0.6471 - rmse: 0.9201

154/269 ━━━━━━━━━━━━━━━━━━━━ 43s 375ms/step - loss: 0.8548 - mae: 0.6465 - rmse: 0.9193

155/269 ━━━━━━━━━━━━━━━━━━━━ 42s 374ms/step - loss: 0.8533 - mae: 0.6458 - rmse: 0.9185

156/269 ━━━━━━━━━━━━━━━━━━━━ 42s 374ms/step - loss: 0.8519 - mae: 0.6451 - rmse: 0.9176

157/269 ━━━━━━━━━━━━━━━━━━━━ 41s 374ms/step - loss: 0.8504 - mae: 0.6444 - rmse: 0.9168

158/269 ━━━━━━━━━━━━━━━━━━━━ 41s 374ms/step - loss: 0.8490 - mae: 0.6438 - rmse: 0.9160

159/269 ━━━━━━━━━━━━━━━━━━━━ 41s 374ms/step - loss: 0.8475 - mae: 0.6431 - rmse: 0.9151

160/269 ━━━━━━━━━━━━━━━━━━━━ 40s 374ms/step - loss: 0.8461 - mae: 0.6424 - rmse: 0.9143

161/269 ━━━━━━━━━━━━━━━━━━━━ 40s 375ms/step - loss: 0.8446 - mae: 0.6417 - rmse: 0.9135

162/269 ━━━━━━━━━━━━━━━━━━━━ 40s 374ms/step - loss: 0.8431 - mae: 0.6410 - rmse: 0.9126

163/269 ━━━━━━━━━━━━━━━━━━━━ 39s 374ms/step - loss: 0.8417 - mae: 0.6404 - rmse: 0.9118

164/269 ━━━━━━━━━━━━━━━━━━━━ 39s 375ms/step - loss: 0.8403 - mae: 0.6397 - rmse: 0.9109

165/269 ━━━━━━━━━━━━━━━━━━━━ 39s 375ms/step - loss: 0.8388 - mae: 0.6390 - rmse: 0.9101

166/269 ━━━━━━━━━━━━━━━━━━━━ 38s 376ms/step - loss: 0.8374 - mae: 0.6383 - rmse: 0.9093

167/269 ━━━━━━━━━━━━━━━━━━━━ 38s 379ms/step - loss: 0.8359 - mae: 0.6376 - rmse: 0.9084

168/269 ━━━━━━━━━━━━━━━━━━━━ 38s 380ms/step - loss: 0.8345 - mae: 0.6370 - rmse: 0.9076

169/269 ━━━━━━━━━━━━━━━━━━━━ 38s 382ms/step - loss: 0.8331 - mae: 0.6363 - rmse: 0.9068

170/269 ━━━━━━━━━━━━━━━━━━━━ 37s 383ms/step - loss: 0.8318 - mae: 0.6357 - rmse: 0.9060

171/269 ━━━━━━━━━━━━━━━━━━━━ 37s 387ms/step - loss: 0.8304 - mae: 0.6351 - rmse: 0.9052

172/269 ━━━━━━━━━━━━━━━━━━━━ 37s 390ms/step - loss: 0.8290 - mae: 0.6344 - rmse: 0.9044

173/269 ━━━━━━━━━━━━━━━━━━━━ 37s 393ms/step - loss: 0.8277 - mae: 0.6338 - rmse: 0.9037

174/269 ━━━━━━━━━━━━━━━━━━━━ 37s 396ms/step - loss: 0.8264 - mae: 0.6332 - rmse: 0.9029

175/269 ━━━━━━━━━━━━━━━━━━━━ 37s 398ms/step - loss: 0.8251 - mae: 0.6326 - rmse: 0.9021

176/269 ━━━━━━━━━━━━━━━━━━━━ 37s 399ms/step - loss: 0.8237 - mae: 0.6320 - rmse: 0.9013

177/269 ━━━━━━━━━━━━━━━━━━━━ 36s 401ms/step - loss: 0.8224 - mae: 0.6314 - rmse: 0.9006

178/269 ━━━━━━━━━━━━━━━━━━━━ 36s 402ms/step - loss: 0.8211 - mae: 0.6308 - rmse: 0.8998

179/269 ━━━━━━━━━━━━━━━━━━━━ 36s 402ms/step - loss: 0.8198 - mae: 0.6302 - rmse: 0.8990

180/269 ━━━━━━━━━━━━━━━━━━━━ 35s 402ms/step - loss: 0.8185 - mae: 0.6296 - rmse: 0.8983

181/269 ━━━━━━━━━━━━━━━━━━━━ 35s 402ms/step - loss: 0.8172 - mae: 0.6290 - rmse: 0.8975

182/269 ━━━━━━━━━━━━━━━━━━━━ 34s 402ms/step - loss: 0.8158 - mae: 0.6284 - rmse: 0.8967

183/269 ━━━━━━━━━━━━━━━━━━━━ 34s 402ms/step - loss: 0.8145 - mae: 0.6277 - rmse: 0.8960

184/269 ━━━━━━━━━━━━━━━━━━━━ 34s 402ms/step - loss: 0.8132 - mae: 0.6271 - rmse: 0.8952

185/269 ━━━━━━━━━━━━━━━━━━━━ 33s 402ms/step - loss: 0.8119 - mae: 0.6265 - rmse: 0.8944

186/269 ━━━━━━━━━━━━━━━━━━━━ 33s 402ms/step - loss: 0.8106 - mae: 0.6259 - rmse: 0.8936

187/269 ━━━━━━━━━━━━━━━━━━━━ 32s 402ms/step - loss: 0.8093 - mae: 0.6253 - rmse: 0.8929

188/269 ━━━━━━━━━━━━━━━━━━━━ 32s 402ms/step - loss: 0.8080 - mae: 0.6247 - rmse: 0.8921

189/269 ━━━━━━━━━━━━━━━━━━━━ 32s 402ms/step - loss: 0.8067 - mae: 0.6241 - rmse: 0.8913

190/269 ━━━━━━━━━━━━━━━━━━━━ 31s 402ms/step - loss: 0.8054 - mae: 0.6235 - rmse: 0.8906

191/269 ━━━━━━━━━━━━━━━━━━━━ 31s 402ms/step - loss: 0.8041 - mae: 0.6228 - rmse: 0.8898

192/269 ━━━━━━━━━━━━━━━━━━━━ 31s 403ms/step - loss: 0.8028 - mae: 0.6222 - rmse: 0.8890

193/269 ━━━━━━━━━━━━━━━━━━━━ 30s 403ms/step - loss: 0.8015 - mae: 0.6216 - rmse: 0.8882

194/269 ━━━━━━━━━━━━━━━━━━━━ 30s 403ms/step - loss: 0.8002 - mae: 0.6210 - rmse: 0.8875

195/269 ━━━━━━━━━━━━━━━━━━━━ 29s 404ms/step - loss: 0.7989 - mae: 0.6204 - rmse: 0.8867

196/269 ━━━━━━━━━━━━━━━━━━━━ 29s 404ms/step - loss: 0.7976 - mae: 0.6198 - rmse: 0.8859

197/269 ━━━━━━━━━━━━━━━━━━━━ 29s 404ms/step - loss: 0.7963 - mae: 0.6192 - rmse: 0.8852

198/269 ━━━━━━━━━━━━━━━━━━━━ 28s 404ms/step - loss: 0.7950 - mae: 0.6186 - rmse: 0.8844

199/269 ━━━━━━━━━━━━━━━━━━━━ 28s 404ms/step - loss: 0.7937 - mae: 0.6179 - rmse: 0.8836

200/269 ━━━━━━━━━━━━━━━━━━━━ 27s 404ms/step - loss: 0.7925 - mae: 0.6173 - rmse: 0.8829

201/269 ━━━━━━━━━━━━━━━━━━━━ 27s 404ms/step - loss: 0.7912 - mae: 0.6167 - rmse: 0.8821

202/269 ━━━━━━━━━━━━━━━━━━━━ 27s 404ms/step - loss: 0.7899 - mae: 0.6161 - rmse: 0.8814

203/269 ━━━━━━━━━━━━━━━━━━━━ 26s 404ms/step - loss: 0.7887 - mae: 0.6155 - rmse: 0.8806

204/269 ━━━━━━━━━━━━━━━━━━━━ 26s 405ms/step - loss: 0.7875 - mae: 0.6149 - rmse: 0.8799

205/269 ━━━━━━━━━━━━━━━━━━━━ 26s 406ms/step - loss: 0.7863 - mae: 0.6144 - rmse: 0.8791

206/269 ━━━━━━━━━━━━━━━━━━━━ 25s 407ms/step - loss: 0.7850 - mae: 0.6138 - rmse: 0.8784

207/269 ━━━━━━━━━━━━━━━━━━━━ 25s 407ms/step - loss: 0.7838 - mae: 0.6132 - rmse: 0.8777

208/269 ━━━━━━━━━━━━━━━━━━━━ 24s 409ms/step - loss: 0.7826 - mae: 0.6126 - rmse: 0.8769

209/269 ━━━━━━━━━━━━━━━━━━━━ 24s 409ms/step - loss: 0.7814 - mae: 0.6120 - rmse: 0.8762

210/269 ━━━━━━━━━━━━━━━━━━━━ 24s 410ms/step - loss: 0.7802 - mae: 0.6115 - rmse: 0.8755

211/269 ━━━━━━━━━━━━━━━━━━━━ 23s 410ms/step - loss: 0.7790 - mae: 0.6109 - rmse: 0.8748

212/269 ━━━━━━━━━━━━━━━━━━━━ 23s 411ms/step - loss: 0.7778 - mae: 0.6103 - rmse: 0.8740

213/269 ━━━━━━━━━━━━━━━━━━━━ 23s 412ms/step - loss: 0.7766 - mae: 0.6097 - rmse: 0.8733

214/269 ━━━━━━━━━━━━━━━━━━━━ 22s 412ms/step - loss: 0.7754 - mae: 0.6092 - rmse: 0.8726

215/269 ━━━━━━━━━━━━━━━━━━━━ 22s 413ms/step - loss: 0.7742 - mae: 0.6086 - rmse: 0.8719

216/269 ━━━━━━━━━━━━━━━━━━━━ 21s 413ms/step - loss: 0.7730 - mae: 0.6080 - rmse: 0.8712

217/269 ━━━━━━━━━━━━━━━━━━━━ 21s 413ms/step - loss: 0.7718 - mae: 0.6075 - rmse: 0.8704

218/269 ━━━━━━━━━━━━━━━━━━━━ 21s 413ms/step - loss: 0.7707 - mae: 0.6069 - rmse: 0.8697

219/269 ━━━━━━━━━━━━━━━━━━━━ 20s 413ms/step - loss: 0.7695 - mae: 0.6063 - rmse: 0.8690

220/269 ━━━━━━━━━━━━━━━━━━━━ 20s 413ms/step - loss: 0.7683 - mae: 0.6058 - rmse: 0.8683

221/269 ━━━━━━━━━━━━━━━━━━━━ 19s 413ms/step - loss: 0.7671 - mae: 0.6052 - rmse: 0.8676

222/269 ━━━━━━━━━━━━━━━━━━━━ 19s 413ms/step - loss: 0.7660 - mae: 0.6046 - rmse: 0.8669

223/269 ━━━━━━━━━━━━━━━━━━━━ 18s 413ms/step - loss: 0.7648 - mae: 0.6041 - rmse: 0.8661

224/269 ━━━━━━━━━━━━━━━━━━━━ 18s 412ms/step - loss: 0.7636 - mae: 0.6035 - rmse: 0.8654

225/269 ━━━━━━━━━━━━━━━━━━━━ 18s 412ms/step - loss: 0.7625 - mae: 0.6030 - rmse: 0.8647

226/269 ━━━━━━━━━━━━━━━━━━━━ 17s 411ms/step - loss: 0.7613 - mae: 0.6024 - rmse: 0.8640

227/269 ━━━━━━━━━━━━━━━━━━━━ 17s 411ms/step - loss: 0.7601 - mae: 0.6018 - rmse: 0.8633

228/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7590 - mae: 0.6013 - rmse: 0.8626

229/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7578 - mae: 0.6007 - rmse: 0.8619

230/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7567 - mae: 0.6001 - rmse: 0.8612

231/269 ━━━━━━━━━━━━━━━━━━━━ 15s 411ms/step - loss: 0.7555 - mae: 0.5996 - rmse: 0.8604

232/269 ━━━━━━━━━━━━━━━━━━━━ 15s 410ms/step - loss: 0.7544 - mae: 0.5990 - rmse: 0.8597

233/269 ━━━━━━━━━━━━━━━━━━━━ 14s 410ms/step - loss: 0.7532 - mae: 0.5984 - rmse: 0.8590

234/269 ━━━━━━━━━━━━━━━━━━━━ 14s 410ms/step - loss: 0.7521 - mae: 0.5979 - rmse: 0.8583

235/269 ━━━━━━━━━━━━━━━━━━━━ 13s 410ms/step - loss: 0.7509 - mae: 0.5973 - rmse: 0.8576

236/269 ━━━━━━━━━━━━━━━━━━━━ 13s 410ms/step - loss: 0.7498 - mae: 0.5967 - rmse: 0.8569

237/269 ━━━━━━━━━━━━━━━━━━━━ 13s 409ms/step - loss: 0.7487 - mae: 0.5962 - rmse: 0.8562

238/269 ━━━━━━━━━━━━━━━━━━━━ 12s 409ms/step - loss: 0.7475 - mae: 0.5956 - rmse: 0.8555

239/269 ━━━━━━━━━━━━━━━━━━━━ 12s 409ms/step - loss: 0.7464 - mae: 0.5951 - rmse: 0.8548

240/269 ━━━━━━━━━━━━━━━━━━━━ 11s 409ms/step - loss: 0.7453 - mae: 0.5945 - rmse: 0.8541

241/269 ━━━━━━━━━━━━━━━━━━━━ 11s 409ms/step - loss: 0.7442 - mae: 0.5940 - rmse: 0.8534

242/269 ━━━━━━━━━━━━━━━━━━━━ 11s 409ms/step - loss: 0.7431 - mae: 0.5934 - rmse: 0.8527

243/269 ━━━━━━━━━━━━━━━━━━━━ 10s 409ms/step - loss: 0.7420 - mae: 0.5929 - rmse: 0.8520

244/269 ━━━━━━━━━━━━━━━━━━━━ 10s 409ms/step - loss: 0.7409 - mae: 0.5923 - rmse: 0.8513

245/269 ━━━━━━━━━━━━━━━━━━━━ 9s 409ms/step - loss: 0.7398 - mae: 0.5918 - rmse: 0.8507

246/269 ━━━━━━━━━━━━━━━━━━━━ 9s 409ms/step - loss: 0.7387 - mae: 0.5912 - rmse: 0.8500

247/269 ━━━━━━━━━━━━━━━━━━━━ 9s 409ms/step - loss: 0.7376 - mae: 0.5907 - rmse: 0.8493

248/269 ━━━━━━━━━━━━━━━━━━━━ 8s 409ms/step - loss: 0.7365 - mae: 0.5901 - rmse: 0.8486

249/269 ━━━━━━━━━━━━━━━━━━━━ 8s 410ms/step - loss: 0.7354 - mae: 0.5896 - rmse: 0.8479

250/269 ━━━━━━━━━━━━━━━━━━━━ 7s 410ms/step - loss: 0.7343 - mae: 0.5891 - rmse: 0.8472

251/269 ━━━━━━━━━━━━━━━━━━━━ 7s 410ms/step - loss: 0.7332 - mae: 0.5885 - rmse: 0.8466

252/269 ━━━━━━━━━━━━━━━━━━━━ 6s 410ms/step - loss: 0.7321 - mae: 0.5880 - rmse: 0.8459

253/269 ━━━━━━━━━━━━━━━━━━━━ 6s 410ms/step - loss: 0.7311 - mae: 0.5875 - rmse: 0.8452

254/269 ━━━━━━━━━━━━━━━━━━━━ 6s 411ms/step - loss: 0.7300 - mae: 0.5870 - rmse: 0.8445

255/269 ━━━━━━━━━━━━━━━━━━━━ 5s 411ms/step - loss: 0.7289 - mae: 0.5864 - rmse: 0.8439

256/269 ━━━━━━━━━━━━━━━━━━━━ 5s 411ms/step - loss: 0.7279 - mae: 0.5859 - rmse: 0.8432

257/269 ━━━━━━━━━━━━━━━━━━━━ 4s 411ms/step - loss: 0.7268 - mae: 0.5854 - rmse: 0.8425

258/269 ━━━━━━━━━━━━━━━━━━━━ 4s 411ms/step - loss: 0.7257 - mae: 0.5849 - rmse: 0.8419

259/269 ━━━━━━━━━━━━━━━━━━━━ 4s 411ms/step - loss: 0.7247 - mae: 0.5843 - rmse: 0.8412

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 411ms/step - loss: 0.7236 - mae: 0.5838 - rmse: 0.8405

261/269 ━━━━━━━━━━━━━━━━━━━━ 3s 411ms/step - loss: 0.7226 - mae: 0.5833 - rmse: 0.8399

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 412ms/step - loss: 0.7215 - mae: 0.5828 - rmse: 0.8392

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 413ms/step - loss: 0.7205 - mae: 0.5823 - rmse: 0.8385

264/269 ━━━━━━━━━━━━━━━━━━━━ 2s 413ms/step - loss: 0.7195 - mae: 0.5817 - rmse: 0.8379

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 413ms/step - loss: 0.7184 - mae: 0.5812 - rmse: 0.8372

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 413ms/step - loss: 0.7174 - mae: 0.5807 - rmse: 0.8366

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 413ms/step - loss: 0.7164 - mae: 0.5802 - rmse: 0.8359

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 413ms/step - loss: 0.7153 - mae: 0.5797 - rmse: 0.8353

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 412ms/step - loss: 0.7143 - mae: 0.5792 - rmse: 0.8346

269/269 ━━━━━━━━━━━━━━━━━━━━ 176s 489ms/step - loss: 0.4420 - mae: 0.4436 - rmse: 0.6614 - val_loss: 0.7250 - val_mae: 0.5283 - val_rmse: 0.8488 - learning_rate: 0.0010

Epoch 8/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 425ms/step - loss: 0.9829 - mae: 0.6873 - rmse: 0.9891

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 323ms/step - loss: 0.8767 - mae: 0.6597 - rmse: 0.9321

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 339ms/step - loss: 0.8717 - mae: 0.6674 - rmse: 0.9300

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 377ms/step - loss: 0.8550 - mae: 0.6663 - rmse: 0.9212

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 382ms/step - loss: 0.8265 - mae: 0.6570 - rmse: 0.9052

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 371ms/step - loss: 0.8060 - mae: 0.6505 - rmse: 0.8937

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 359ms/step - loss: 0.8013 - mae: 0.6493 - rmse: 0.8912

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 354ms/step - loss: 0.8114 - mae: 0.6530 - rmse: 0.8969

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 357ms/step - loss: 0.8151 - mae: 0.6542 - rmse: 0.8991

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 355ms/step - loss: 0.8138 - mae: 0.6533 - rmse: 0.8985

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 357ms/step - loss: 0.8104 - mae: 0.6518 - rmse: 0.8967

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 358ms/step - loss: 0.8157 - mae: 0.6534 - rmse: 0.8997

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 356ms/step - loss: 0.8263 - mae: 0.6560 - rmse: 0.9054

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 356ms/step - loss: 0.8450 - mae: 0.6614 - rmse: 0.9151

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 357ms/step - loss: 0.8610 - mae: 0.6663 - rmse: 0.9234

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 355ms/step - loss: 0.8776 - mae: 0.6715 - rmse: 0.9318

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 353ms/step - loss: 0.8944 - mae: 0.6762 - rmse: 0.9404

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 351ms/step - loss: 0.9082 - mae: 0.6801 - rmse: 0.9474

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 351ms/step - loss: 0.9225 - mae: 0.6840 - rmse: 0.9546

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 353ms/step - loss: 0.9351 - mae: 0.6873 - rmse: 0.9610

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 355ms/step - loss: 0.9447 - mae: 0.6897 - rmse: 0.9659

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 356ms/step - loss: 0.9533 - mae: 0.6919 - rmse: 0.9702

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 356ms/step - loss: 0.9617 - mae: 0.6942 - rmse: 0.9745

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 357ms/step - loss: 0.9690 - mae: 0.6963 - rmse: 0.9783

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 358ms/step - loss: 0.9750 - mae: 0.6980 - rmse: 0.9814

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 360ms/step - loss: 0.9809 - mae: 0.6995 - rmse: 0.9844

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 364ms/step - loss: 0.9853 - mae: 0.7006 - rmse: 0.9867

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 371ms/step - loss: 0.9888 - mae: 0.7014 - rmse: 0.9885

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 377ms/step - loss: 0.9917 - mae: 0.7020 - rmse: 0.9901

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 387ms/step - loss: 0.9935 - mae: 0.7023 - rmse: 0.9911

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 396ms/step - loss: 0.9945 - mae: 0.7024 - rmse: 0.9917

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 401ms/step - loss: 0.9952 - mae: 0.7023 - rmse: 0.9921

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 402ms/step - loss: 0.9955 - mae: 0.7022 - rmse: 0.9924

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 406ms/step - loss: 0.9954 - mae: 0.7020 - rmse: 0.9925

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 407ms/step - loss: 0.9953 - mae: 0.7019 - rmse: 0.9925

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 409ms/step - loss: 0.9948 - mae: 0.7016 - rmse: 0.9923

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 410ms/step - loss: 0.9941 - mae: 0.7013 - rmse: 0.9920

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 411ms/step - loss: 0.9930 - mae: 0.7008 - rmse: 0.9915

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 413ms/step - loss: 0.9917 - mae: 0.7003 - rmse: 0.9909

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 416ms/step - loss: 0.9900 - mae: 0.6996 - rmse: 0.9902

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 416ms/step - loss: 0.9885 - mae: 0.6990 - rmse: 0.9895

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 414ms/step - loss: 0.9868 - mae: 0.6984 - rmse: 0.9886

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 412ms/step - loss: 0.9850 - mae: 0.6977 - rmse: 0.9878

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 410ms/step - loss: 0.9834 - mae: 0.6971 - rmse: 0.9870

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 409ms/step - loss: 0.9817 - mae: 0.6965 - rmse: 0.9862

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 408ms/step - loss: 0.9798 - mae: 0.6958 - rmse: 0.9852

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 406ms/step - loss: 0.9780 - mae: 0.6952 - rmse: 0.9844

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 404ms/step - loss: 0.9761 - mae: 0.6945 - rmse: 0.9834

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 402ms/step - loss: 0.9740 - mae: 0.6938 - rmse: 0.9824

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 401ms/step - loss: 0.9718 - mae: 0.6930 - rmse: 0.9813

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 399ms/step - loss: 0.9696 - mae: 0.6922 - rmse: 0.9801

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 399ms/step - loss: 0.9672 - mae: 0.6913 - rmse: 0.9789

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 399ms/step - loss: 0.9649 - mae: 0.6905 - rmse: 0.9777

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 397ms/step - loss: 0.9627 - mae: 0.6897 - rmse: 0.9766

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 396ms/step - loss: 0.9604 - mae: 0.6889 - rmse: 0.9755

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 395ms/step - loss: 0.9582 - mae: 0.6881 - rmse: 0.9744

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 395ms/step - loss: 0.9560 - mae: 0.6873 - rmse: 0.9732

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 394ms/step - loss: 0.9538 - mae: 0.6865 - rmse: 0.9721

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 394ms/step - loss: 0.9518 - mae: 0.6858 - rmse: 0.9710

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 395ms/step - loss: 0.9497 - mae: 0.6851 - rmse: 0.9700

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 395ms/step - loss: 0.9477 - mae: 0.6845 - rmse: 0.9690

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 396ms/step - loss: 0.9458 - mae: 0.6838 - rmse: 0.9680

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 396ms/step - loss: 0.9439 - mae: 0.6832 - rmse: 0.9670

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 395ms/step - loss: 0.9418 - mae: 0.6825 - rmse: 0.9659

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 395ms/step - loss: 0.9397 - mae: 0.6818 - rmse: 0.9648

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 396ms/step - loss: 0.9376 - mae: 0.6810 - rmse: 0.9637

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 396ms/step - loss: 0.9354 - mae: 0.6802 - rmse: 0.9626

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 396ms/step - loss: 0.9332 - mae: 0.6795 - rmse: 0.9614

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 398ms/step - loss: 0.9311 - mae: 0.6787 - rmse: 0.9603

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 398ms/step - loss: 0.9290 - mae: 0.6780 - rmse: 0.9592

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 398ms/step - loss: 0.9271 - mae: 0.6773 - rmse: 0.9582

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 399ms/step - loss: 0.9252 - mae: 0.6766 - rmse: 0.9572

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 400ms/step - loss: 0.9233 - mae: 0.6760 - rmse: 0.9562

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 401ms/step - loss: 0.9216 - mae: 0.6753 - rmse: 0.9553

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 401ms/step - loss: 0.9199 - mae: 0.6747 - rmse: 0.9544

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 401ms/step - loss: 0.9183 - mae: 0.6741 - rmse: 0.9536

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 401ms/step - loss: 0.9167 - mae: 0.6736 - rmse: 0.9528

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 401ms/step - loss: 0.9153 - mae: 0.6731 - rmse: 0.9520

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 402ms/step - loss: 0.9139 - mae: 0.6726 - rmse: 0.9513

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 402ms/step - loss: 0.9125 - mae: 0.6721 - rmse: 0.9506

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 402ms/step - loss: 0.9115 - mae: 0.6718 - rmse: 0.9500

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 401ms/step - loss: 0.9108 - mae: 0.6715 - rmse: 0.9497

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 401ms/step - loss: 0.9103 - mae: 0.6713 - rmse: 0.9495

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 403ms/step - loss: 0.9099 - mae: 0.6712 - rmse: 0.9493

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 405ms/step - loss: 0.9096 - mae: 0.6710 - rmse: 0.9492

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 407ms/step - loss: 0.9094 - mae: 0.6709 - rmse: 0.9491

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 408ms/step - loss: 0.9093 - mae: 0.6709 - rmse: 0.9490

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 411ms/step - loss: 0.9091 - mae: 0.6708 - rmse: 0.9490

 89/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 415ms/step - loss: 0.9089 - mae: 0.6707 - rmse: 0.9489

 90/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 415ms/step - loss: 0.9088 - mae: 0.6706 - rmse: 0.9488

 91/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 415ms/step - loss: 0.9086 - mae: 0.6706 - rmse: 0.9488

 92/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 415ms/step - loss: 0.9083 - mae: 0.6705 - rmse: 0.9486

 93/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 414ms/step - loss: 0.9080 - mae: 0.6704 - rmse: 0.9485

 94/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 413ms/step - loss: 0.9076 - mae: 0.6702 - rmse: 0.9483

 95/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 412ms/step - loss: 0.9072 - mae: 0.6700 - rmse: 0.9481

 96/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 411ms/step - loss: 0.9067 - mae: 0.6699 - rmse: 0.9479

 97/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 411ms/step - loss: 0.9062 - mae: 0.6697 - rmse: 0.9476

 98/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 410ms/step - loss: 0.9056 - mae: 0.6694 - rmse: 0.9473

 99/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 410ms/step - loss: 0.9050 - mae: 0.6692 - rmse: 0.9470

100/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 410ms/step - loss: 0.9043 - mae: 0.6690 - rmse: 0.9467

101/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 410ms/step - loss: 0.9037 - mae: 0.6687 - rmse: 0.9464

102/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 410ms/step - loss: 0.9031 - mae: 0.6685 - rmse: 0.9460

103/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 410ms/step - loss: 0.9024 - mae: 0.6682 - rmse: 0.9457

104/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 409ms/step - loss: 0.9017 - mae: 0.6680 - rmse: 0.9453

105/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 409ms/step - loss: 0.9010 - mae: 0.6677 - rmse: 0.9450

106/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 410ms/step - loss: 0.9003 - mae: 0.6674 - rmse: 0.9446

107/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 409ms/step - loss: 0.8995 - mae: 0.6671 - rmse: 0.9442

108/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 408ms/step - loss: 0.8987 - mae: 0.6668 - rmse: 0.9438

109/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 408ms/step - loss: 0.8978 - mae: 0.6665 - rmse: 0.9433

110/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 408ms/step - loss: 0.8969 - mae: 0.6661 - rmse: 0.9428

111/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 407ms/step - loss: 0.8959 - mae: 0.6657 - rmse: 0.9423

112/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 407ms/step - loss: 0.8950 - mae: 0.6653 - rmse: 0.9418

113/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 406ms/step - loss: 0.8940 - mae: 0.6649 - rmse: 0.9413

114/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 406ms/step - loss: 0.8929 - mae: 0.6644 - rmse: 0.9407

115/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 405ms/step - loss: 0.8919 - mae: 0.6640 - rmse: 0.9402

116/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 405ms/step - loss: 0.8908 - mae: 0.6635 - rmse: 0.9396

117/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 404ms/step - loss: 0.8897 - mae: 0.6630 - rmse: 0.9390

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 405ms/step - loss: 0.8885 - mae: 0.6625 - rmse: 0.9384

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 405ms/step - loss: 0.8874 - mae: 0.6620 - rmse: 0.9378

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 406ms/step - loss: 0.8862 - mae: 0.6615 - rmse: 0.9371

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 406ms/step - loss: 0.8851 - mae: 0.6610 - rmse: 0.9365

122/269 ━━━━━━━━━━━━━━━━━━━━ 59s 407ms/step - loss: 0.8839 - mae: 0.6605 - rmse: 0.9358

123/269 ━━━━━━━━━━━━━━━━━━━━ 59s 407ms/step - loss: 0.8826 - mae: 0.6599 - rmse: 0.9352

124/269 ━━━━━━━━━━━━━━━━━━━━ 59s 407ms/step - loss: 0.8814 - mae: 0.6593 - rmse: 0.9345

125/269 ━━━━━━━━━━━━━━━━━━━━ 58s 408ms/step - loss: 0.8801 - mae: 0.6588 - rmse: 0.9338

126/269 ━━━━━━━━━━━━━━━━━━━━ 58s 408ms/step - loss: 0.8788 - mae: 0.6582 - rmse: 0.9331

127/269 ━━━━━━━━━━━━━━━━━━━━ 57s 408ms/step - loss: 0.8775 - mae: 0.6576 - rmse: 0.9324

128/269 ━━━━━━━━━━━━━━━━━━━━ 57s 408ms/step - loss: 0.8762 - mae: 0.6570 - rmse: 0.9316

129/269 ━━━━━━━━━━━━━━━━━━━━ 57s 408ms/step - loss: 0.8749 - mae: 0.6564 - rmse: 0.9309

130/269 ━━━━━━━━━━━━━━━━━━━━ 56s 408ms/step - loss: 0.8736 - mae: 0.6558 - rmse: 0.9302

131/269 ━━━━━━━━━━━━━━━━━━━━ 56s 407ms/step - loss: 0.8722 - mae: 0.6552 - rmse: 0.9294

132/269 ━━━━━━━━━━━━━━━━━━━━ 55s 407ms/step - loss: 0.8709 - mae: 0.6545 - rmse: 0.9287

133/269 ━━━━━━━━━━━━━━━━━━━━ 55s 407ms/step - loss: 0.8696 - mae: 0.6539 - rmse: 0.9280

134/269 ━━━━━━━━━━━━━━━━━━━━ 55s 408ms/step - loss: 0.8682 - mae: 0.6533 - rmse: 0.9272

135/269 ━━━━━━━━━━━━━━━━━━━━ 55s 412ms/step - loss: 0.8669 - mae: 0.6527 - rmse: 0.9265

136/269 ━━━━━━━━━━━━━━━━━━━━ 54s 412ms/step - loss: 0.8656 - mae: 0.6521 - rmse: 0.9257

137/269 ━━━━━━━━━━━━━━━━━━━━ 54s 413ms/step - loss: 0.8642 - mae: 0.6515 - rmse: 0.9250

138/269 ━━━━━━━━━━━━━━━━━━━━ 54s 413ms/step - loss: 0.8629 - mae: 0.6509 - rmse: 0.9242

139/269 ━━━━━━━━━━━━━━━━━━━━ 53s 414ms/step - loss: 0.8615 - mae: 0.6503 - rmse: 0.9235

140/269 ━━━━━━━━━━━━━━━━━━━━ 53s 414ms/step - loss: 0.8602 - mae: 0.6496 - rmse: 0.9227

141/269 ━━━━━━━━━━━━━━━━━━━━ 52s 414ms/step - loss: 0.8588 - mae: 0.6490 - rmse: 0.9219

142/269 ━━━━━━━━━━━━━━━━━━━━ 52s 413ms/step - loss: 0.8574 - mae: 0.6484 - rmse: 0.9211

143/269 ━━━━━━━━━━━━━━━━━━━━ 52s 413ms/step - loss: 0.8560 - mae: 0.6477 - rmse: 0.9204

144/269 ━━━━━━━━━━━━━━━━━━━━ 51s 412ms/step - loss: 0.8546 - mae: 0.6471 - rmse: 0.9196

145/269 ━━━━━━━━━━━━━━━━━━━━ 51s 412ms/step - loss: 0.8532 - mae: 0.6465 - rmse: 0.9188

146/269 ━━━━━━━━━━━━━━━━━━━━ 50s 411ms/step - loss: 0.8518 - mae: 0.6458 - rmse: 0.9180

147/269 ━━━━━━━━━━━━━━━━━━━━ 50s 411ms/step - loss: 0.8504 - mae: 0.6451 - rmse: 0.9172

148/269 ━━━━━━━━━━━━━━━━━━━━ 49s 410ms/step - loss: 0.8490 - mae: 0.6445 - rmse: 0.9163

149/269 ━━━━━━━━━━━━━━━━━━━━ 49s 410ms/step - loss: 0.8475 - mae: 0.6438 - rmse: 0.9155

150/269 ━━━━━━━━━━━━━━━━━━━━ 48s 410ms/step - loss: 0.8461 - mae: 0.6431 - rmse: 0.9147

151/269 ━━━━━━━━━━━━━━━━━━━━ 48s 410ms/step - loss: 0.8447 - mae: 0.6424 - rmse: 0.9139

152/269 ━━━━━━━━━━━━━━━━━━━━ 47s 409ms/step - loss: 0.8433 - mae: 0.6417 - rmse: 0.9131

153/269 ━━━━━━━━━━━━━━━━━━━━ 47s 408ms/step - loss: 0.8418 - mae: 0.6411 - rmse: 0.9122

154/269 ━━━━━━━━━━━━━━━━━━━━ 46s 408ms/step - loss: 0.8404 - mae: 0.6404 - rmse: 0.9114

155/269 ━━━━━━━━━━━━━━━━━━━━ 46s 407ms/step - loss: 0.8390 - mae: 0.6397 - rmse: 0.9106

156/269 ━━━━━━━━━━━━━━━━━━━━ 45s 407ms/step - loss: 0.8375 - mae: 0.6390 - rmse: 0.9098

157/269 ━━━━━━━━━━━━━━━━━━━━ 45s 407ms/step - loss: 0.8361 - mae: 0.6383 - rmse: 0.9089

158/269 ━━━━━━━━━━━━━━━━━━━━ 45s 407ms/step - loss: 0.8346 - mae: 0.6376 - rmse: 0.9081

159/269 ━━━━━━━━━━━━━━━━━━━━ 44s 406ms/step - loss: 0.8332 - mae: 0.6369 - rmse: 0.9073

160/269 ━━━━━━━━━━━━━━━━━━━━ 44s 406ms/step - loss: 0.8318 - mae: 0.6363 - rmse: 0.9064

161/269 ━━━━━━━━━━━━━━━━━━━━ 43s 405ms/step - loss: 0.8303 - mae: 0.6356 - rmse: 0.9056

162/269 ━━━━━━━━━━━━━━━━━━━━ 43s 405ms/step - loss: 0.8289 - mae: 0.6349 - rmse: 0.9048

163/269 ━━━━━━━━━━━━━━━━━━━━ 42s 405ms/step - loss: 0.8274 - mae: 0.6342 - rmse: 0.9039

164/269 ━━━━━━━━━━━━━━━━━━━━ 42s 405ms/step - loss: 0.8260 - mae: 0.6335 - rmse: 0.9031

165/269 ━━━━━━━━━━━━━━━━━━━━ 42s 405ms/step - loss: 0.8246 - mae: 0.6328 - rmse: 0.9022

166/269 ━━━━━━━━━━━━━━━━━━━━ 41s 406ms/step - loss: 0.8232 - mae: 0.6321 - rmse: 0.9014

167/269 ━━━━━━━━━━━━━━━━━━━━ 41s 406ms/step - loss: 0.8217 - mae: 0.6314 - rmse: 0.9006

168/269 ━━━━━━━━━━━━━━━━━━━━ 41s 406ms/step - loss: 0.8204 - mae: 0.6308 - rmse: 0.8998

169/269 ━━━━━━━━━━━━━━━━━━━━ 40s 406ms/step - loss: 0.8190 - mae: 0.6301 - rmse: 0.8990

170/269 ━━━━━━━━━━━━━━━━━━━━ 40s 407ms/step - loss: 0.8176 - mae: 0.6295 - rmse: 0.8982

171/269 ━━━━━━━━━━━━━━━━━━━━ 39s 408ms/step - loss: 0.8162 - mae: 0.6288 - rmse: 0.8974

172/269 ━━━━━━━━━━━━━━━━━━━━ 39s 409ms/step - loss: 0.8149 - mae: 0.6282 - rmse: 0.8966

173/269 ━━━━━━━━━━━━━━━━━━━━ 39s 409ms/step - loss: 0.8136 - mae: 0.6276 - rmse: 0.8958

174/269 ━━━━━━━━━━━━━━━━━━━━ 39s 411ms/step - loss: 0.8123 - mae: 0.6269 - rmse: 0.8950

175/269 ━━━━━━━━━━━━━━━━━━━━ 38s 412ms/step - loss: 0.8109 - mae: 0.6263 - rmse: 0.8943

176/269 ━━━━━━━━━━━━━━━━━━━━ 38s 413ms/step - loss: 0.8096 - mae: 0.6257 - rmse: 0.8935

177/269 ━━━━━━━━━━━━━━━━━━━━ 38s 414ms/step - loss: 0.8083 - mae: 0.6251 - rmse: 0.8927

178/269 ━━━━━━━━━━━━━━━━━━━━ 37s 415ms/step - loss: 0.8070 - mae: 0.6245 - rmse: 0.8919

179/269 ━━━━━━━━━━━━━━━━━━━━ 37s 415ms/step - loss: 0.8057 - mae: 0.6239 - rmse: 0.8912

180/269 ━━━━━━━━━━━━━━━━━━━━ 36s 415ms/step - loss: 0.8044 - mae: 0.6233 - rmse: 0.8904

181/269 ━━━━━━━━━━━━━━━━━━━━ 36s 416ms/step - loss: 0.8031 - mae: 0.6226 - rmse: 0.8896

182/269 ━━━━━━━━━━━━━━━━━━━━ 36s 416ms/step - loss: 0.8018 - mae: 0.6220 - rmse: 0.8889

183/269 ━━━━━━━━━━━━━━━━━━━━ 35s 416ms/step - loss: 0.8005 - mae: 0.6214 - rmse: 0.8881

184/269 ━━━━━━━━━━━━━━━━━━━━ 35s 416ms/step - loss: 0.7992 - mae: 0.6208 - rmse: 0.8873

185/269 ━━━━━━━━━━━━━━━━━━━━ 34s 416ms/step - loss: 0.7979 - mae: 0.6202 - rmse: 0.8866

186/269 ━━━━━━━━━━━━━━━━━━━━ 34s 416ms/step - loss: 0.7966 - mae: 0.6196 - rmse: 0.8858

187/269 ━━━━━━━━━━━━━━━━━━━━ 34s 415ms/step - loss: 0.7953 - mae: 0.6189 - rmse: 0.8850

188/269 ━━━━━━━━━━━━━━━━━━━━ 33s 415ms/step - loss: 0.7940 - mae: 0.6183 - rmse: 0.8842

189/269 ━━━━━━━━━━━━━━━━━━━━ 33s 414ms/step - loss: 0.7927 - mae: 0.6177 - rmse: 0.8835

190/269 ━━━━━━━━━━━━━━━━━━━━ 32s 414ms/step - loss: 0.7914 - mae: 0.6171 - rmse: 0.8827

191/269 ━━━━━━━━━━━━━━━━━━━━ 32s 414ms/step - loss: 0.7901 - mae: 0.6165 - rmse: 0.8819

192/269 ━━━━━━━━━━━━━━━━━━━━ 31s 413ms/step - loss: 0.7888 - mae: 0.6158 - rmse: 0.8811

193/269 ━━━━━━━━━━━━━━━━━━━━ 31s 413ms/step - loss: 0.7876 - mae: 0.6152 - rmse: 0.8804

194/269 ━━━━━━━━━━━━━━━━━━━━ 30s 412ms/step - loss: 0.7863 - mae: 0.6146 - rmse: 0.8796

195/269 ━━━━━━━━━━━━━━━━━━━━ 30s 412ms/step - loss: 0.7850 - mae: 0.6140 - rmse: 0.8788

196/269 ━━━━━━━━━━━━━━━━━━━━ 30s 411ms/step - loss: 0.7837 - mae: 0.6134 - rmse: 0.8781

197/269 ━━━━━━━━━━━━━━━━━━━━ 29s 411ms/step - loss: 0.7824 - mae: 0.6127 - rmse: 0.8773

198/269 ━━━━━━━━━━━━━━━━━━━━ 29s 410ms/step - loss: 0.7812 - mae: 0.6121 - rmse: 0.8765

199/269 ━━━━━━━━━━━━━━━━━━━━ 28s 410ms/step - loss: 0.7799 - mae: 0.6115 - rmse: 0.8758

200/269 ━━━━━━━━━━━━━━━━━━━━ 28s 410ms/step - loss: 0.7786 - mae: 0.6109 - rmse: 0.8750

201/269 ━━━━━━━━━━━━━━━━━━━━ 27s 409ms/step - loss: 0.7774 - mae: 0.6103 - rmse: 0.8742

202/269 ━━━━━━━━━━━━━━━━━━━━ 27s 409ms/step - loss: 0.7761 - mae: 0.6097 - rmse: 0.8735

203/269 ━━━━━━━━━━━━━━━━━━━━ 26s 408ms/step - loss: 0.7749 - mae: 0.6091 - rmse: 0.8727

204/269 ━━━━━━━━━━━━━━━━━━━━ 26s 408ms/step - loss: 0.7737 - mae: 0.6085 - rmse: 0.8720

205/269 ━━━━━━━━━━━━━━━━━━━━ 26s 407ms/step - loss: 0.7725 - mae: 0.6079 - rmse: 0.8713

206/269 ━━━━━━━━━━━━━━━━━━━━ 25s 407ms/step - loss: 0.7713 - mae: 0.6073 - rmse: 0.8705

207/269 ━━━━━━━━━━━━━━━━━━━━ 25s 407ms/step - loss: 0.7701 - mae: 0.6067 - rmse: 0.8698

208/269 ━━━━━━━━━━━━━━━━━━━━ 24s 407ms/step - loss: 0.7689 - mae: 0.6061 - rmse: 0.8691

209/269 ━━━━━━━━━━━━━━━━━━━━ 24s 407ms/step - loss: 0.7677 - mae: 0.6056 - rmse: 0.8684

210/269 ━━━━━━━━━━━━━━━━━━━━ 24s 409ms/step - loss: 0.7665 - mae: 0.6050 - rmse: 0.8676

211/269 ━━━━━━━━━━━━━━━━━━━━ 23s 412ms/step - loss: 0.7653 - mae: 0.6044 - rmse: 0.8669

212/269 ━━━━━━━━━━━━━━━━━━━━ 23s 414ms/step - loss: 0.7641 - mae: 0.6038 - rmse: 0.8662

213/269 ━━━━━━━━━━━━━━━━━━━━ 23s 415ms/step - loss: 0.7629 - mae: 0.6033 - rmse: 0.8655

214/269 ━━━━━━━━━━━━━━━━━━━━ 22s 416ms/step - loss: 0.7618 - mae: 0.6027 - rmse: 0.8648

215/269 ━━━━━━━━━━━━━━━━━━━━ 22s 418ms/step - loss: 0.7606 - mae: 0.6021 - rmse: 0.8640

216/269 ━━━━━━━━━━━━━━━━━━━━ 22s 418ms/step - loss: 0.7594 - mae: 0.6015 - rmse: 0.8633

217/269 ━━━━━━━━━━━━━━━━━━━━ 21s 418ms/step - loss: 0.7583 - mae: 0.6010 - rmse: 0.8626

218/269 ━━━━━━━━━━━━━━━━━━━━ 21s 418ms/step - loss: 0.7571 - mae: 0.6004 - rmse: 0.8619

219/269 ━━━━━━━━━━━━━━━━━━━━ 20s 418ms/step - loss: 0.7559 - mae: 0.5998 - rmse: 0.8612

220/269 ━━━━━━━━━━━━━━━━━━━━ 20s 418ms/step - loss: 0.7548 - mae: 0.5993 - rmse: 0.8605

221/269 ━━━━━━━━━━━━━━━━━━━━ 20s 418ms/step - loss: 0.7536 - mae: 0.5987 - rmse: 0.8597

222/269 ━━━━━━━━━━━━━━━━━━━━ 19s 419ms/step - loss: 0.7524 - mae: 0.5981 - rmse: 0.8590

223/269 ━━━━━━━━━━━━━━━━━━━━ 19s 419ms/step - loss: 0.7513 - mae: 0.5976 - rmse: 0.8583

224/269 ━━━━━━━━━━━━━━━━━━━━ 18s 419ms/step - loss: 0.7501 - mae: 0.5970 - rmse: 0.8576

225/269 ━━━━━━━━━━━━━━━━━━━━ 18s 420ms/step - loss: 0.7490 - mae: 0.5964 - rmse: 0.8569

226/269 ━━━━━━━━━━━━━━━━━━━━ 18s 420ms/step - loss: 0.7478 - mae: 0.5959 - rmse: 0.8562

227/269 ━━━━━━━━━━━━━━━━━━━━ 17s 421ms/step - loss: 0.7467 - mae: 0.5953 - rmse: 0.8555

228/269 ━━━━━━━━━━━━━━━━━━━━ 17s 422ms/step - loss: 0.7455 - mae: 0.5947 - rmse: 0.8548

229/269 ━━━━━━━━━━━━━━━━━━━━ 16s 424ms/step - loss: 0.7444 - mae: 0.5942 - rmse: 0.8541

230/269 ━━━━━━━━━━━━━━━━━━━━ 16s 424ms/step - loss: 0.7433 - mae: 0.5936 - rmse: 0.8533

231/269 ━━━━━━━━━━━━━━━━━━━━ 16s 424ms/step - loss: 0.7421 - mae: 0.5930 - rmse: 0.8526

232/269 ━━━━━━━━━━━━━━━━━━━━ 15s 423ms/step - loss: 0.7410 - mae: 0.5925 - rmse: 0.8519

233/269 ━━━━━━━━━━━━━━━━━━━━ 15s 423ms/step - loss: 0.7398 - mae: 0.5919 - rmse: 0.8512

234/269 ━━━━━━━━━━━━━━━━━━━━ 14s 425ms/step - loss: 0.7387 - mae: 0.5913 - rmse: 0.8505

235/269 ━━━━━━━━━━━━━━━━━━━━ 14s 428ms/step - loss: 0.7376 - mae: 0.5908 - rmse: 0.8498

236/269 ━━━━━━━━━━━━━━━━━━━━ 14s 430ms/step - loss: 0.7365 - mae: 0.5902 - rmse: 0.8491

237/269 ━━━━━━━━━━━━━━━━━━━━ 13s 431ms/step - loss: 0.7353 - mae: 0.5896 - rmse: 0.8484

238/269 ━━━━━━━━━━━━━━━━━━━━ 13s 432ms/step - loss: 0.7342 - mae: 0.5891 - rmse: 0.8477

239/269 ━━━━━━━━━━━━━━━━━━━━ 12s 432ms/step - loss: 0.7331 - mae: 0.5885 - rmse: 0.8470

240/269 ━━━━━━━━━━━━━━━━━━━━ 12s 431ms/step - loss: 0.7320 - mae: 0.5880 - rmse: 0.8463

241/269 ━━━━━━━━━━━━━━━━━━━━ 12s 431ms/step - loss: 0.7309 - mae: 0.5874 - rmse: 0.8456

242/269 ━━━━━━━━━━━━━━━━━━━━ 11s 431ms/step - loss: 0.7298 - mae: 0.5869 - rmse: 0.8449

243/269 ━━━━━━━━━━━━━━━━━━━━ 11s 431ms/step - loss: 0.7287 - mae: 0.5863 - rmse: 0.8442

244/269 ━━━━━━━━━━━━━━━━━━━━ 10s 430ms/step - loss: 0.7276 - mae: 0.5858 - rmse: 0.8436

245/269 ━━━━━━━━━━━━━━━━━━━━ 10s 431ms/step - loss: 0.7265 - mae: 0.5852 - rmse: 0.8429

246/269 ━━━━━━━━━━━━━━━━━━━━ 9s 431ms/step - loss: 0.7254 - mae: 0.5847 - rmse: 0.8422

247/269 ━━━━━━━━━━━━━━━━━━━━ 9s 430ms/step - loss: 0.7244 - mae: 0.5841 - rmse: 0.8415

248/269 ━━━━━━━━━━━━━━━━━━━━ 9s 430ms/step - loss: 0.7233 - mae: 0.5836 - rmse: 0.8408

249/269 ━━━━━━━━━━━━━━━━━━━━ 8s 430ms/step - loss: 0.7222 - mae: 0.5831 - rmse: 0.8401

250/269 ━━━━━━━━━━━━━━━━━━━━ 8s 430ms/step - loss: 0.7211 - mae: 0.5825 - rmse: 0.8395

251/269 ━━━━━━━━━━━━━━━━━━━━ 7s 430ms/step - loss: 0.7201 - mae: 0.5820 - rmse: 0.8388

252/269 ━━━━━━━━━━━━━━━━━━━━ 7s 430ms/step - loss: 0.7190 - mae: 0.5815 - rmse: 0.8381

253/269 ━━━━━━━━━━━━━━━━━━━━ 6s 429ms/step - loss: 0.7180 - mae: 0.5809 - rmse: 0.8374

254/269 ━━━━━━━━━━━━━━━━━━━━ 6s 429ms/step - loss: 0.7169 - mae: 0.5804 - rmse: 0.8368

255/269 ━━━━━━━━━━━━━━━━━━━━ 6s 429ms/step - loss: 0.7158 - mae: 0.5799 - rmse: 0.8361

256/269 ━━━━━━━━━━━━━━━━━━━━ 5s 429ms/step - loss: 0.7148 - mae: 0.5794 - rmse: 0.8354

257/269 ━━━━━━━━━━━━━━━━━━━━ 5s 429ms/step - loss: 0.7137 - mae: 0.5788 - rmse: 0.8348

258/269 ━━━━━━━━━━━━━━━━━━━━ 4s 428ms/step - loss: 0.7127 - mae: 0.5783 - rmse: 0.8341

259/269 ━━━━━━━━━━━━━━━━━━━━ 4s 429ms/step - loss: 0.7117 - mae: 0.5778 - rmse: 0.8334

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 429ms/step - loss: 0.7106 - mae: 0.5773 - rmse: 0.8328

261/269 ━━━━━━━━━━━━━━━━━━━━ 3s 429ms/step - loss: 0.7096 - mae: 0.5767 - rmse: 0.8321

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 428ms/step - loss: 0.7086 - mae: 0.5762 - rmse: 0.8315

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 428ms/step - loss: 0.7075 - mae: 0.5757 - rmse: 0.8308

264/269 ━━━━━━━━━━━━━━━━━━━━ 2s 428ms/step - loss: 0.7065 - mae: 0.5752 - rmse: 0.8301

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 428ms/step - loss: 0.7055 - mae: 0.5747 - rmse: 0.8295

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 427ms/step - loss: 0.7045 - mae: 0.5742 - rmse: 0.8288

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step - loss: 0.7034 - mae: 0.5736 - rmse: 0.8282

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 426ms/step - loss: 0.7024 - mae: 0.5731 - rmse: 0.8275

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step - loss: 0.7014 - mae: 0.5726 - rmse: 0.8269

269/269 ━━━━━━━━━━━━━━━━━━━━ 122s 453ms/step - loss: 0.4327 - mae: 0.4372 - rmse: 0.6543 - val_loss: 0.7505 - val_mae: 0.5430 - val_rmse: 0.8638 - learning_rate: 0.0010

Epoch 9/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 388ms/step - loss: 0.9523 - mae: 0.6655 - rmse: 0.9736

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 268ms/step - loss: 0.8373 - mae: 0.6352 - rmse: 0.9104

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 267ms/step - loss: 0.8366 - mae: 0.6450 - rmse: 0.9108

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 270ms/step - loss: 0.8255 - mae: 0.6464 - rmse: 0.9050

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 269ms/step - loss: 0.8004 - mae: 0.6388 - rmse: 0.8908

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 276ms/step - loss: 0.7820 - mae: 0.6332 - rmse: 0.8803

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 279ms/step - loss: 0.7771 - mae: 0.6322 - rmse: 0.8777

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 282ms/step - loss: 0.7871 - mae: 0.6363 - rmse: 0.8834

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 287ms/step - loss: 0.7923 - mae: 0.6386 - rmse: 0.8865

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 293ms/step - loss: 0.7919 - mae: 0.6385 - rmse: 0.8863

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 296ms/step - loss: 0.7895 - mae: 0.6377 - rmse: 0.8851

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 300ms/step - loss: 0.7955 - mae: 0.6399 - rmse: 0.8885

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 317ms/step - loss: 0.8064 - mae: 0.6431 - rmse: 0.8944

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 322ms/step - loss: 0.8236 - mae: 0.6486 - rmse: 0.9035

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 334ms/step - loss: 0.8383 - mae: 0.6535 - rmse: 0.9112

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 435ms/step - loss: 0.8535 - mae: 0.6587 - rmse: 0.9191

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 444ms/step - loss: 0.8694 - mae: 0.6635 - rmse: 0.9273

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 456ms/step - loss: 0.8827 - mae: 0.6675 - rmse: 0.9342

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 457ms/step - loss: 0.8969 - mae: 0.6715 - rmse: 0.9414

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 456ms/step - loss: 0.9092 - mae: 0.6750 - rmse: 0.9477

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 460ms/step - loss: 0.9188 - mae: 0.6776 - rmse: 0.9526

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 461ms/step - loss: 0.9273 - mae: 0.6800 - rmse: 0.9570

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 458ms/step - loss: 0.9356 - mae: 0.6825 - rmse: 0.9613

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 458ms/step - loss: 0.9428 - mae: 0.6848 - rmse: 0.9650

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 459ms/step - loss: 0.9488 - mae: 0.6866 - rmse: 0.9681

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 454ms/step - loss: 0.9547 - mae: 0.6884 - rmse: 0.9712

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 450ms/step - loss: 0.9593 - mae: 0.6897 - rmse: 0.9736

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 445ms/step - loss: 0.9628 - mae: 0.6908 - rmse: 0.9755

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 442ms/step - loss: 0.9659 - mae: 0.6917 - rmse: 0.9772

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 440ms/step - loss: 0.9679 - mae: 0.6922 - rmse: 0.9783

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 437ms/step - loss: 0.9691 - mae: 0.6925 - rmse: 0.9790

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 434ms/step - loss: 0.9699 - mae: 0.6927 - rmse: 0.9795

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 431ms/step - loss: 0.9704 - mae: 0.6927 - rmse: 0.9798

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 428ms/step - loss: 0.9704 - mae: 0.6927 - rmse: 0.9800

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 425ms/step - loss: 0.9704 - mae: 0.6927 - rmse: 0.9800

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 423ms/step - loss: 0.9700 - mae: 0.6925 - rmse: 0.9799

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 424ms/step - loss: 0.9695 - mae: 0.6924 - rmse: 0.9797

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 424ms/step - loss: 0.9685 - mae: 0.6920 - rmse: 0.9793

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 422ms/step - loss: 0.9673 - mae: 0.6916 - rmse: 0.9787

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 420ms/step - loss: 0.9659 - mae: 0.6910 - rmse: 0.9781

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 420ms/step - loss: 0.9646 - mae: 0.6906 - rmse: 0.9774

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 419ms/step - loss: 0.9630 - mae: 0.6900 - rmse: 0.9767

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 418ms/step - loss: 0.9614 - mae: 0.6894 - rmse: 0.9759

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 417ms/step - loss: 0.9599 - mae: 0.6889 - rmse: 0.9751

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 416ms/step - loss: 0.9583 - mae: 0.6884 - rmse: 0.9744

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 414ms/step - loss: 0.9565 - mae: 0.6878 - rmse: 0.9735

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 412ms/step - loss: 0.9549 - mae: 0.6872 - rmse: 0.9727

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 410ms/step - loss: 0.9531 - mae: 0.6866 - rmse: 0.9718

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 409ms/step - loss: 0.9511 - mae: 0.6859 - rmse: 0.9708

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 407ms/step - loss: 0.9491 - mae: 0.6851 - rmse: 0.9698

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 407ms/step - loss: 0.9469 - mae: 0.6844 - rmse: 0.9687

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 406ms/step - loss: 0.9447 - mae: 0.6835 - rmse: 0.9675

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 409ms/step - loss: 0.9424 - mae: 0.6827 - rmse: 0.9663

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 417ms/step - loss: 0.9403 - mae: 0.6820 - rmse: 0.9653

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 420ms/step - loss: 0.9381 - mae: 0.6812 - rmse: 0.9641

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 423ms/step - loss: 0.9360 - mae: 0.6804 - rmse: 0.9631

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 425ms/step - loss: 0.9339 - mae: 0.6797 - rmse: 0.9620

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 425ms/step - loss: 0.9318 - mae: 0.6789 - rmse: 0.9609

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 426ms/step - loss: 0.9298 - mae: 0.6782 - rmse: 0.9598

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 425ms/step - loss: 0.9278 - mae: 0.6775 - rmse: 0.9588

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 427ms/step - loss: 0.9260 - mae: 0.6768 - rmse: 0.9578

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 428ms/step - loss: 0.9241 - mae: 0.6762 - rmse: 0.9569

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 427ms/step - loss: 0.9222 - mae: 0.6756 - rmse: 0.9559

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 427ms/step - loss: 0.9203 - mae: 0.6749 - rmse: 0.9549

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 426ms/step - loss: 0.9183 - mae: 0.6742 - rmse: 0.9538

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 426ms/step - loss: 0.9162 - mae: 0.6735 - rmse: 0.9527

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 426ms/step - loss: 0.9141 - mae: 0.6727 - rmse: 0.9516

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 426ms/step - loss: 0.9120 - mae: 0.6720 - rmse: 0.9505

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 427ms/step - loss: 0.9099 - mae: 0.6712 - rmse: 0.9494

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 427ms/step - loss: 0.9079 - mae: 0.6705 - rmse: 0.9483

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 426ms/step - loss: 0.9061 - mae: 0.6699 - rmse: 0.9474

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 425ms/step - loss: 0.9043 - mae: 0.6692 - rmse: 0.9464

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 424ms/step - loss: 0.9025 - mae: 0.6686 - rmse: 0.9455

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 422ms/step - loss: 0.9008 - mae: 0.6680 - rmse: 0.9446

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 421ms/step - loss: 0.8992 - mae: 0.6674 - rmse: 0.9437

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 420ms/step - loss: 0.8977 - mae: 0.6668 - rmse: 0.9429

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 419ms/step - loss: 0.8962 - mae: 0.6663 - rmse: 0.9421

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 419ms/step - loss: 0.8948 - mae: 0.6658 - rmse: 0.9414

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 418ms/step - loss: 0.8935 - mae: 0.6653 - rmse: 0.9407

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 417ms/step - loss: 0.8922 - mae: 0.6649 - rmse: 0.9400

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 416ms/step - loss: 0.8912 - mae: 0.6645 - rmse: 0.9395

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 415ms/step - loss: 0.8905 - mae: 0.6643 - rmse: 0.9392

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 416ms/step - loss: 0.8901 - mae: 0.6641 - rmse: 0.9389

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 418ms/step - loss: 0.8897 - mae: 0.6640 - rmse: 0.9388

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 417ms/step - loss: 0.8894 - mae: 0.6638 - rmse: 0.9387

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 416ms/step - loss: 0.8893 - mae: 0.6638 - rmse: 0.9386

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 415ms/step - loss: 0.8892 - mae: 0.6637 - rmse: 0.9386

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 414ms/step - loss: 0.8890 - mae: 0.6636 - rmse: 0.9385

 89/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 414ms/step - loss: 0.8889 - mae: 0.6636 - rmse: 0.9384

 90/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 413ms/step - loss: 0.8887 - mae: 0.6635 - rmse: 0.9384

 91/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 414ms/step - loss: 0.8885 - mae: 0.6635 - rmse: 0.9383

 92/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 414ms/step - loss: 0.8883 - mae: 0.6634 - rmse: 0.9382

 93/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 414ms/step - loss: 0.8880 - mae: 0.6632 - rmse: 0.9381

 94/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 414ms/step - loss: 0.8876 - mae: 0.6631 - rmse: 0.9379

 95/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 415ms/step - loss: 0.8872 - mae: 0.6629 - rmse: 0.9377

 96/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 416ms/step - loss: 0.8867 - mae: 0.6628 - rmse: 0.9374

 97/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 416ms/step - loss: 0.8862 - mae: 0.6626 - rmse: 0.9372

 98/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 417ms/step - loss: 0.8857 - mae: 0.6624 - rmse: 0.9369

 99/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 418ms/step - loss: 0.8851 - mae: 0.6621 - rmse: 0.9366

100/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 419ms/step - loss: 0.8844 - mae: 0.6619 - rmse: 0.9363

101/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 419ms/step - loss: 0.8838 - mae: 0.6616 - rmse: 0.9360

102/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 419ms/step - loss: 0.8832 - mae: 0.6614 - rmse: 0.9356

103/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 420ms/step - loss: 0.8825 - mae: 0.6612 - rmse: 0.9353

104/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 421ms/step - loss: 0.8819 - mae: 0.6609 - rmse: 0.9350

105/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 421ms/step - loss: 0.8812 - mae: 0.6607 - rmse: 0.9346

106/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 421ms/step - loss: 0.8805 - mae: 0.6604 - rmse: 0.9342

107/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 420ms/step - loss: 0.8797 - mae: 0.6601 - rmse: 0.9338

108/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 420ms/step - loss: 0.8789 - mae: 0.6598 - rmse: 0.9334

109/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 420ms/step - loss: 0.8781 - mae: 0.6595 - rmse: 0.9330

110/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 420ms/step - loss: 0.8772 - mae: 0.6591 - rmse: 0.9325

111/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 420ms/step - loss: 0.8763 - mae: 0.6587 - rmse: 0.9320

112/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 420ms/step - loss: 0.8753 - mae: 0.6583 - rmse: 0.9315

113/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 419ms/step - loss: 0.8744 - mae: 0.6579 - rmse: 0.9310

114/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 418ms/step - loss: 0.8734 - mae: 0.6575 - rmse: 0.9304

115/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 418ms/step - loss: 0.8723 - mae: 0.6570 - rmse: 0.9299

116/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 418ms/step - loss: 0.8713 - mae: 0.6566 - rmse: 0.9293

117/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 417ms/step - loss: 0.8702 - mae: 0.6561 - rmse: 0.9287

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 417ms/step - loss: 0.8691 - mae: 0.6556 - rmse: 0.9281

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 417ms/step - loss: 0.8680 - mae: 0.6551 - rmse: 0.9275

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 416ms/step - loss: 0.8669 - mae: 0.6546 - rmse: 0.9269

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 415ms/step - loss: 0.8657 - mae: 0.6541 - rmse: 0.9263

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 415ms/step - loss: 0.8645 - mae: 0.6536 - rmse: 0.9256

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 415ms/step - loss: 0.8633 - mae: 0.6530 - rmse: 0.9249

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 415ms/step - loss: 0.8621 - mae: 0.6525 - rmse: 0.9243

125/269 ━━━━━━━━━━━━━━━━━━━━ 59s 414ms/step - loss: 0.8609 - mae: 0.6519 - rmse: 0.9236

126/269 ━━━━━━━━━━━━━━━━━━━━ 59s 415ms/step - loss: 0.8596 - mae: 0.6513 - rmse: 0.9229

127/269 ━━━━━━━━━━━━━━━━━━━━ 58s 415ms/step - loss: 0.8584 - mae: 0.6507 - rmse: 0.9222

128/269 ━━━━━━━━━━━━━━━━━━━━ 58s 415ms/step - loss: 0.8571 - mae: 0.6502 - rmse: 0.9215

129/269 ━━━━━━━━━━━━━━━━━━━━ 58s 415ms/step - loss: 0.8558 - mae: 0.6496 - rmse: 0.9208

130/269 ━━━━━━━━━━━━━━━━━━━━ 57s 417ms/step - loss: 0.8545 - mae: 0.6490 - rmse: 0.9200

131/269 ━━━━━━━━━━━━━━━━━━━━ 57s 417ms/step - loss: 0.8532 - mae: 0.6484 - rmse: 0.9193

132/269 ━━━━━━━━━━━━━━━━━━━━ 57s 417ms/step - loss: 0.8519 - mae: 0.6478 - rmse: 0.9186

133/269 ━━━━━━━━━━━━━━━━━━━━ 56s 416ms/step - loss: 0.8506 - mae: 0.6472 - rmse: 0.9178

134/269 ━━━━━━━━━━━━━━━━━━━━ 56s 416ms/step - loss: 0.8493 - mae: 0.6466 - rmse: 0.9171

135/269 ━━━━━━━━━━━━━━━━━━━━ 55s 416ms/step - loss: 0.8480 - mae: 0.6459 - rmse: 0.9164

136/269 ━━━━━━━━━━━━━━━━━━━━ 55s 415ms/step - loss: 0.8467 - mae: 0.6453 - rmse: 0.9156

137/269 ━━━━━━━━━━━━━━━━━━━━ 54s 415ms/step - loss: 0.8454 - mae: 0.6447 - rmse: 0.9149

138/269 ━━━━━━━━━━━━━━━━━━━━ 54s 414ms/step - loss: 0.8441 - mae: 0.6441 - rmse: 0.9141

139/269 ━━━━━━━━━━━━━━━━━━━━ 53s 414ms/step - loss: 0.8427 - mae: 0.6435 - rmse: 0.9134

140/269 ━━━━━━━━━━━━━━━━━━━━ 53s 413ms/step - loss: 0.8414 - mae: 0.6429 - rmse: 0.9126

141/269 ━━━━━━━━━━━━━━━━━━━━ 52s 412ms/step - loss: 0.8401 - mae: 0.6423 - rmse: 0.9119

142/269 ━━━━━━━━━━━━━━━━━━━━ 52s 412ms/step - loss: 0.8387 - mae: 0.6417 - rmse: 0.9111

143/269 ━━━━━━━━━━━━━━━━━━━━ 51s 412ms/step - loss: 0.8374 - mae: 0.6411 - rmse: 0.9103

144/269 ━━━━━━━━━━━━━━━━━━━━ 51s 412ms/step - loss: 0.8360 - mae: 0.6404 - rmse: 0.9096

145/269 ━━━━━━━━━━━━━━━━━━━━ 51s 412ms/step - loss: 0.8346 - mae: 0.6398 - rmse: 0.9088

146/269 ━━━━━━━━━━━━━━━━━━━━ 50s 412ms/step - loss: 0.8333 - mae: 0.6391 - rmse: 0.9080

147/269 ━━━━━━━━━━━━━━━━━━━━ 50s 412ms/step - loss: 0.8319 - mae: 0.6385 - rmse: 0.9072

148/269 ━━━━━━━━━━━━━━━━━━━━ 49s 412ms/step - loss: 0.8305 - mae: 0.6378 - rmse: 0.9064

149/269 ━━━━━━━━━━━━━━━━━━━━ 49s 412ms/step - loss: 0.8291 - mae: 0.6371 - rmse: 0.9056

150/269 ━━━━━━━━━━━━━━━━━━━━ 49s 412ms/step - loss: 0.8277 - mae: 0.6365 - rmse: 0.9048

151/269 ━━━━━━━━━━━━━━━━━━━━ 48s 412ms/step - loss: 0.8263 - mae: 0.6358 - rmse: 0.9039

152/269 ━━━━━━━━━━━━━━━━━━━━ 48s 415ms/step - loss: 0.8249 - mae: 0.6351 - rmse: 0.9031

153/269 ━━━━━━━━━━━━━━━━━━━━ 48s 415ms/step - loss: 0.8235 - mae: 0.6344 - rmse: 0.9023

154/269 ━━━━━━━━━━━━━━━━━━━━ 47s 415ms/step - loss: 0.8221 - mae: 0.6338 - rmse: 0.9015

155/269 ━━━━━━━━━━━━━━━━━━━━ 47s 415ms/step - loss: 0.8207 - mae: 0.6331 - rmse: 0.9007

156/269 ━━━━━━━━━━━━━━━━━━━━ 46s 415ms/step - loss: 0.8193 - mae: 0.6324 - rmse: 0.8999

157/269 ━━━━━━━━━━━━━━━━━━━━ 46s 416ms/step - loss: 0.8179 - mae: 0.6317 - rmse: 0.8991

158/269 ━━━━━━━━━━━━━━━━━━━━ 46s 417ms/step - loss: 0.8165 - mae: 0.6311 - rmse: 0.8982

159/269 ━━━━━━━━━━━━━━━━━━━━ 46s 422ms/step - loss: 0.8151 - mae: 0.6304 - rmse: 0.8974

160/269 ━━━━━━━━━━━━━━━━━━━━ 46s 423ms/step - loss: 0.8137 - mae: 0.6297 - rmse: 0.8966

161/269 ━━━━━━━━━━━━━━━━━━━━ 45s 424ms/step - loss: 0.8123 - mae: 0.6290 - rmse: 0.8958

162/269 ━━━━━━━━━━━━━━━━━━━━ 45s 424ms/step - loss: 0.8109 - mae: 0.6283 - rmse: 0.8949

163/269 ━━━━━━━━━━━━━━━━━━━━ 44s 424ms/step - loss: 0.8095 - mae: 0.6277 - rmse: 0.8941

164/269 ━━━━━━━━━━━━━━━━━━━━ 44s 423ms/step - loss: 0.8081 - mae: 0.6270 - rmse: 0.8933

165/269 ━━━━━━━━━━━━━━━━━━━━ 44s 423ms/step - loss: 0.8067 - mae: 0.6263 - rmse: 0.8924

166/269 ━━━━━━━━━━━━━━━━━━━━ 43s 423ms/step - loss: 0.8053 - mae: 0.6256 - rmse: 0.8916

167/269 ━━━━━━━━━━━━━━━━━━━━ 43s 423ms/step - loss: 0.8039 - mae: 0.6250 - rmse: 0.8908

168/269 ━━━━━━━━━━━━━━━━━━━━ 42s 423ms/step - loss: 0.8025 - mae: 0.6243 - rmse: 0.8900

169/269 ━━━━━━━━━━━━━━━━━━━━ 42s 422ms/step - loss: 0.8012 - mae: 0.6236 - rmse: 0.8892

170/269 ━━━━━━━━━━━━━━━━━━━━ 41s 422ms/step - loss: 0.7998 - mae: 0.6230 - rmse: 0.8884

171/269 ━━━━━━━━━━━━━━━━━━━━ 41s 422ms/step - loss: 0.7985 - mae: 0.6224 - rmse: 0.8876

172/269 ━━━━━━━━━━━━━━━━━━━━ 40s 421ms/step - loss: 0.7972 - mae: 0.6217 - rmse: 0.8868

173/269 ━━━━━━━━━━━━━━━━━━━━ 40s 421ms/step - loss: 0.7959 - mae: 0.6211 - rmse: 0.8861

174/269 ━━━━━━━━━━━━━━━━━━━━ 39s 420ms/step - loss: 0.7946 - mae: 0.6205 - rmse: 0.8853

175/269 ━━━━━━━━━━━━━━━━━━━━ 39s 420ms/step - loss: 0.7933 - mae: 0.6199 - rmse: 0.8846

176/269 ━━━━━━━━━━━━━━━━━━━━ 39s 420ms/step - loss: 0.7921 - mae: 0.6193 - rmse: 0.8838

177/269 ━━━━━━━━━━━━━━━━━━━━ 38s 419ms/step - loss: 0.7908 - mae: 0.6187 - rmse: 0.8830

178/269 ━━━━━━━━━━━━━━━━━━━━ 38s 419ms/step - loss: 0.7895 - mae: 0.6181 - rmse: 0.8823

179/269 ━━━━━━━━━━━━━━━━━━━━ 37s 418ms/step - loss: 0.7882 - mae: 0.6175 - rmse: 0.8815

180/269 ━━━━━━━━━━━━━━━━━━━━ 37s 418ms/step - loss: 0.7870 - mae: 0.6169 - rmse: 0.8808

181/269 ━━━━━━━━━━━━━━━━━━━━ 36s 417ms/step - loss: 0.7857 - mae: 0.6163 - rmse: 0.8800

182/269 ━━━━━━━━━━━━━━━━━━━━ 36s 418ms/step - loss: 0.7844 - mae: 0.6157 - rmse: 0.8792

183/269 ━━━━━━━━━━━━━━━━━━━━ 35s 418ms/step - loss: 0.7832 - mae: 0.6151 - rmse: 0.8785

184/269 ━━━━━━━━━━━━━━━━━━━━ 35s 420ms/step - loss: 0.7819 - mae: 0.6144 - rmse: 0.8777

185/269 ━━━━━━━━━━━━━━━━━━━━ 35s 419ms/step - loss: 0.7806 - mae: 0.6138 - rmse: 0.8770

186/269 ━━━━━━━━━━━━━━━━━━━━ 34s 419ms/step - loss: 0.7794 - mae: 0.6132 - rmse: 0.8762

187/269 ━━━━━━━━━━━━━━━━━━━━ 34s 419ms/step - loss: 0.7781 - mae: 0.6126 - rmse: 0.8754

188/269 ━━━━━━━━━━━━━━━━━━━━ 33s 419ms/step - loss: 0.7768 - mae: 0.6120 - rmse: 0.8747

189/269 ━━━━━━━━━━━━━━━━━━━━ 33s 419ms/step - loss: 0.7755 - mae: 0.6114 - rmse: 0.8739

190/269 ━━━━━━━━━━━━━━━━━━━━ 33s 420ms/step - loss: 0.7743 - mae: 0.6108 - rmse: 0.8731

191/269 ━━━━━━━━━━━━━━━━━━━━ 32s 420ms/step - loss: 0.7730 - mae: 0.6102 - rmse: 0.8724

192/269 ━━━━━━━━━━━━━━━━━━━━ 32s 421ms/step - loss: 0.7718 - mae: 0.6095 - rmse: 0.8716

193/269 ━━━━━━━━━━━━━━━━━━━━ 31s 421ms/step - loss: 0.7705 - mae: 0.6089 - rmse: 0.8708

194/269 ━━━━━━━━━━━━━━━━━━━━ 31s 421ms/step - loss: 0.7692 - mae: 0.6083 - rmse: 0.8701

195/269 ━━━━━━━━━━━━━━━━━━━━ 31s 422ms/step - loss: 0.7680 - mae: 0.6077 - rmse: 0.8693

196/269 ━━━━━━━━━━━━━━━━━━━━ 30s 423ms/step - loss: 0.7667 - mae: 0.6071 - rmse: 0.8686

197/269 ━━━━━━━━━━━━━━━━━━━━ 30s 423ms/step - loss: 0.7655 - mae: 0.6065 - rmse: 0.8678

198/269 ━━━━━━━━━━━━━━━━━━━━ 30s 423ms/step - loss: 0.7643 - mae: 0.6059 - rmse: 0.8670

199/269 ━━━━━━━━━━━━━━━━━━━━ 29s 423ms/step - loss: 0.7630 - mae: 0.6053 - rmse: 0.8663

200/269 ━━━━━━━━━━━━━━━━━━━━ 29s 424ms/step - loss: 0.7618 - mae: 0.6046 - rmse: 0.8655

201/269 ━━━━━━━━━━━━━━━━━━━━ 28s 423ms/step - loss: 0.7606 - mae: 0.6040 - rmse: 0.8648

202/269 ━━━━━━━━━━━━━━━━━━━━ 28s 423ms/step - loss: 0.7594 - mae: 0.6034 - rmse: 0.8640

203/269 ━━━━━━━━━━━━━━━━━━━━ 27s 423ms/step - loss: 0.7582 - mae: 0.6029 - rmse: 0.8633

204/269 ━━━━━━━━━━━━━━━━━━━━ 27s 423ms/step - loss: 0.7570 - mae: 0.6023 - rmse: 0.8626

205/269 ━━━━━━━━━━━━━━━━━━━━ 27s 422ms/step - loss: 0.7558 - mae: 0.6017 - rmse: 0.8619

206/269 ━━━━━━━━━━━━━━━━━━━━ 26s 422ms/step - loss: 0.7546 - mae: 0.6011 - rmse: 0.8611

207/269 ━━━━━━━━━━━━━━━━━━━━ 26s 423ms/step - loss: 0.7534 - mae: 0.6005 - rmse: 0.8604

208/269 ━━━━━━━━━━━━━━━━━━━━ 25s 423ms/step - loss: 0.7523 - mae: 0.5999 - rmse: 0.8597

209/269 ━━━━━━━━━━━━━━━━━━━━ 25s 422ms/step - loss: 0.7511 - mae: 0.5994 - rmse: 0.8590

210/269 ━━━━━━━━━━━━━━━━━━━━ 24s 422ms/step - loss: 0.7499 - mae: 0.5988 - rmse: 0.8583

211/269 ━━━━━━━━━━━━━━━━━━━━ 24s 422ms/step - loss: 0.7488 - mae: 0.5982 - rmse: 0.8576

212/269 ━━━━━━━━━━━━━━━━━━━━ 23s 421ms/step - loss: 0.7476 - mae: 0.5976 - rmse: 0.8568

213/269 ━━━━━━━━━━━━━━━━━━━━ 23s 420ms/step - loss: 0.7465 - mae: 0.5971 - rmse: 0.8561

214/269 ━━━━━━━━━━━━━━━━━━━━ 23s 419ms/step - loss: 0.7453 - mae: 0.5965 - rmse: 0.8554

215/269 ━━━━━━━━━━━━━━━━━━━━ 22s 419ms/step - loss: 0.7441 - mae: 0.5959 - rmse: 0.8547

216/269 ━━━━━━━━━━━━━━━━━━━━ 22s 418ms/step - loss: 0.7430 - mae: 0.5954 - rmse: 0.8540

217/269 ━━━━━━━━━━━━━━━━━━━━ 21s 418ms/step - loss: 0.7419 - mae: 0.5948 - rmse: 0.8533

218/269 ━━━━━━━━━━━━━━━━━━━━ 21s 417ms/step - loss: 0.7407 - mae: 0.5942 - rmse: 0.8526

219/269 ━━━━━━━━━━━━━━━━━━━━ 20s 416ms/step - loss: 0.7396 - mae: 0.5937 - rmse: 0.8519

220/269 ━━━━━━━━━━━━━━━━━━━━ 20s 416ms/step - loss: 0.7384 - mae: 0.5931 - rmse: 0.8512

221/269 ━━━━━━━━━━━━━━━━━━━━ 19s 415ms/step - loss: 0.7373 - mae: 0.5926 - rmse: 0.8505

222/269 ━━━━━━━━━━━━━━━━━━━━ 19s 415ms/step - loss: 0.7362 - mae: 0.5920 - rmse: 0.8498

223/269 ━━━━━━━━━━━━━━━━━━━━ 19s 414ms/step - loss: 0.7351 - mae: 0.5914 - rmse: 0.8490

224/269 ━━━━━━━━━━━━━━━━━━━━ 18s 414ms/step - loss: 0.7339 - mae: 0.5909 - rmse: 0.8483

225/269 ━━━━━━━━━━━━━━━━━━━━ 18s 413ms/step - loss: 0.7328 - mae: 0.5903 - rmse: 0.8476

226/269 ━━━━━━━━━━━━━━━━━━━━ 17s 413ms/step - loss: 0.7317 - mae: 0.5898 - rmse: 0.8469

227/269 ━━━━━━━━━━━━━━━━━━━━ 17s 412ms/step - loss: 0.7306 - mae: 0.5892 - rmse: 0.8462

228/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7294 - mae: 0.5886 - rmse: 0.8455

229/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7283 - mae: 0.5881 - rmse: 0.8448

230/269 ━━━━━━━━━━━━━━━━━━━━ 16s 411ms/step - loss: 0.7272 - mae: 0.5875 - rmse: 0.8441

231/269 ━━━━━━━━━━━━━━━━━━━━ 15s 410ms/step - loss: 0.7261 - mae: 0.5869 - rmse: 0.8434

232/269 ━━━━━━━━━━━━━━━━━━━━ 15s 410ms/step - loss: 0.7250 - mae: 0.5864 - rmse: 0.8427

233/269 ━━━━━━━━━━━━━━━━━━━━ 14s 409ms/step - loss: 0.7239 - mae: 0.5858 - rmse: 0.8420

234/269 ━━━━━━━━━━━━━━━━━━━━ 14s 410ms/step - loss: 0.7228 - mae: 0.5853 - rmse: 0.8413

235/269 ━━━━━━━━━━━━━━━━━━━━ 13s 410ms/step - loss: 0.7217 - mae: 0.5847 - rmse: 0.8406

236/269 ━━━━━━━━━━━━━━━━━━━━ 13s 410ms/step - loss: 0.7206 - mae: 0.5842 - rmse: 0.8399

237/269 ━━━━━━━━━━━━━━━━━━━━ 13s 411ms/step - loss: 0.7195 - mae: 0.5836 - rmse: 0.8393

238/269 ━━━━━━━━━━━━━━━━━━━━ 12s 411ms/step - loss: 0.7184 - mae: 0.5831 - rmse: 0.8386

239/269 ━━━━━━━━━━━━━━━━━━━━ 12s 412ms/step - loss: 0.7173 - mae: 0.5825 - rmse: 0.8379

240/269 ━━━━━━━━━━━━━━━━━━━━ 11s 413ms/step - loss: 0.7162 - mae: 0.5820 - rmse: 0.8372

241/269 ━━━━━━━━━━━━━━━━━━━━ 11s 413ms/step - loss: 0.7152 - mae: 0.5814 - rmse: 0.8365

242/269 ━━━━━━━━━━━━━━━━━━━━ 11s 413ms/step - loss: 0.7141 - mae: 0.5809 - rmse: 0.8358

243/269 ━━━━━━━━━━━━━━━━━━━━ 10s 413ms/step - loss: 0.7130 - mae: 0.5803 - rmse: 0.8352

244/269 ━━━━━━━━━━━━━━━━━━━━ 10s 414ms/step - loss: 0.7120 - mae: 0.5798 - rmse: 0.8345

245/269 ━━━━━━━━━━━━━━━━━━━━ 9s 414ms/step - loss: 0.7109 - mae: 0.5793 - rmse: 0.8338

246/269 ━━━━━━━━━━━━━━━━━━━━ 9s 414ms/step - loss: 0.7098 - mae: 0.5787 - rmse: 0.8331

247/269 ━━━━━━━━━━━━━━━━━━━━ 9s 414ms/step - loss: 0.7088 - mae: 0.5782 - rmse: 0.8325

248/269 ━━━━━━━━━━━━━━━━━━━━ 8s 414ms/step - loss: 0.7077 - mae: 0.5777 - rmse: 0.8318

249/269 ━━━━━━━━━━━━━━━━━━━━ 8s 414ms/step - loss: 0.7067 - mae: 0.5771 - rmse: 0.8311

250/269 ━━━━━━━━━━━━━━━━━━━━ 7s 415ms/step - loss: 0.7056 - mae: 0.5766 - rmse: 0.8305

251/269 ━━━━━━━━━━━━━━━━━━━━ 7s 415ms/step - loss: 0.7046 - mae: 0.5761 - rmse: 0.8298

252/269 ━━━━━━━━━━━━━━━━━━━━ 7s 415ms/step - loss: 0.7036 - mae: 0.5756 - rmse: 0.8291

253/269 ━━━━━━━━━━━━━━━━━━━━ 6s 416ms/step - loss: 0.7025 - mae: 0.5751 - rmse: 0.8285

254/269 ━━━━━━━━━━━━━━━━━━━━ 6s 416ms/step - loss: 0.7015 - mae: 0.5745 - rmse: 0.8278

255/269 ━━━━━━━━━━━━━━━━━━━━ 5s 416ms/step - loss: 0.7005 - mae: 0.5740 - rmse: 0.8272

256/269 ━━━━━━━━━━━━━━━━━━━━ 5s 416ms/step - loss: 0.6995 - mae: 0.5735 - rmse: 0.8265

257/269 ━━━━━━━━━━━━━━━━━━━━ 4s 416ms/step - loss: 0.6984 - mae: 0.5730 - rmse: 0.8258

258/269 ━━━━━━━━━━━━━━━━━━━━ 4s 416ms/step - loss: 0.6974 - mae: 0.5725 - rmse: 0.8252

259/269 ━━━━━━━━━━━━━━━━━━━━ 4s 416ms/step - loss: 0.6964 - mae: 0.5720 - rmse: 0.8245

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 415ms/step - loss: 0.6954 - mae: 0.5714 - rmse: 0.8239

261/269 ━━━━━━━━━━━━━━━━━━━━ 3s 415ms/step - loss: 0.6944 - mae: 0.5709 - rmse: 0.8232

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 415ms/step - loss: 0.6934 - mae: 0.5704 - rmse: 0.8226

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 415ms/step - loss: 0.6924 - mae: 0.5699 - rmse: 0.8219

264/269 ━━━━━━━━━━━━━━━━━━━━ 2s 415ms/step - loss: 0.6914 - mae: 0.5694 - rmse: 0.8213

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 415ms/step - loss: 0.6904 - mae: 0.5689 - rmse: 0.8207

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 415ms/step - loss: 0.6894 - mae: 0.5684 - rmse: 0.8200

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 415ms/step - loss: 0.6884 - mae: 0.5679 - rmse: 0.8194

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 415ms/step - loss: 0.6874 - mae: 0.5674 - rmse: 0.8187

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step - loss: 0.6865 - mae: 0.5669 - rmse: 0.8181

269/269 ━━━━━━━━━━━━━━━━━━━━ 124s 460ms/step - loss: 0.4248 - mae: 0.4338 - rmse: 0.6483 - val_loss: 0.7231 - val_mae: 0.5251 - val_rmse: 0.8478 - learning_rate: 0.0010

Epoch 10/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 566ms/step - loss: 0.9645 - mae: 0.7019 - rmse: 0.9798

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 382ms/step - loss: 0.8497 - mae: 0.6642 - rmse: 0.9173

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 381ms/step - loss: 0.8340 - mae: 0.6642 - rmse: 0.9093

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 421ms/step - loss: 0.8173 - mae: 0.6606 - rmse: 0.9003

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 425ms/step - loss: 0.7889 - mae: 0.6495 - rmse: 0.8841

  6/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 524ms/step - loss: 0.7682 - mae: 0.6418 - rmse: 0.8722

  7/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 602ms/step - loss: 0.7627 - mae: 0.6397 - rmse: 0.8693

  8/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 642ms/step - loss: 0.7724 - mae: 0.6430 - rmse: 0.8749

  9/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 726ms/step - loss: 0.7771 - mae: 0.6444 - rmse: 0.8777

 10/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 737ms/step - loss: 0.7764 - mae: 0.6435 - rmse: 0.8774

 11/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 874ms/step - loss: 0.7736 - mae: 0.6419 - rmse: 0.8759

 12/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 878ms/step - loss: 0.7792 - mae: 0.6432 - rmse: 0.8792

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 882ms/step - loss: 0.7903 - mae: 0.6457 - rmse: 0.8853

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:44 881ms/step - loss: 0.8079 - mae: 0.6506 - rmse: 0.8946

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 907ms/step - loss: 0.8228 - mae: 0.6549 - rmse: 0.9025

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:48 901ms/step - loss: 0.8380 - mae: 0.6594 - rmse: 0.9105

 17/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 894ms/step - loss: 0.8541 - mae: 0.6638 - rmse: 0.9188

 18/269 ━━━━━━━━━━━━━━━━━━━━ 3:41 884ms/step - loss: 0.8675 - mae: 0.6674 - rmse: 0.9258

 19/269 ━━━━━━━━━━━━━━━━━━━━ 3:39 877ms/step - loss: 0.8814 - mae: 0.6710 - rmse: 0.9330

 20/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 876ms/step - loss: 0.8936 - mae: 0.6743 - rmse: 0.9393

 21/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 874ms/step - loss: 0.9031 - mae: 0.6766 - rmse: 0.9442

 22/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 876ms/step - loss: 0.9116 - mae: 0.6788 - rmse: 0.9487

 23/269 ━━━━━━━━━━━━━━━━━━━━ 3:37 883ms/step - loss: 0.9201 - mae: 0.6812 - rmse: 0.9531

 24/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 877ms/step - loss: 0.9275 - mae: 0.6833 - rmse: 0.9569

 25/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 877ms/step - loss: 0.9335 - mae: 0.6849 - rmse: 0.9601

 26/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 880ms/step - loss: 0.9395 - mae: 0.6865 - rmse: 0.9632

 27/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 882ms/step - loss: 0.9440 - mae: 0.6876 - rmse: 0.9656

 28/269 ━━━━━━━━━━━━━━━━━━━━ 3:30 874ms/step - loss: 0.9475 - mae: 0.6884 - rmse: 0.9676

 29/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 866ms/step - loss: 0.9505 - mae: 0.6891 - rmse: 0.9692

 30/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 868ms/step - loss: 0.9524 - mae: 0.6894 - rmse: 0.9703

 31/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 878ms/step - loss: 0.9536 - mae: 0.6894 - rmse: 0.9710

 32/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 870ms/step - loss: 0.9543 - mae: 0.6894 - rmse: 0.9714

 33/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 859ms/step - loss: 0.9548 - mae: 0.6893 - rmse: 0.9718

 34/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 848ms/step - loss: 0.9549 - mae: 0.6891 - rmse: 0.9719

 35/269 ━━━━━━━━━━━━━━━━━━━━ 3:15 836ms/step - loss: 0.9549 - mae: 0.6890 - rmse: 0.9720

 36/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 831ms/step - loss: 0.9546 - mae: 0.6887 - rmse: 0.9719

 37/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 822ms/step - loss: 0.9541 - mae: 0.6884 - rmse: 0.9718

 38/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 825ms/step - loss: 0.9533 - mae: 0.6880 - rmse: 0.9714

 39/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 820ms/step - loss: 0.9522 - mae: 0.6875 - rmse: 0.9709

 40/269 ━━━━━━━━━━━━━━━━━━━━ 3:06 814ms/step - loss: 0.9508 - mae: 0.6868 - rmse: 0.9703

 41/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 806ms/step - loss: 0.9495 - mae: 0.6863 - rmse: 0.9697

 42/269 ━━━━━━━━━━━━━━━━━━━━ 3:00 795ms/step - loss: 0.9480 - mae: 0.6856 - rmse: 0.9689

 43/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 785ms/step - loss: 0.9465 - mae: 0.6850 - rmse: 0.9682

 44/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 776ms/step - loss: 0.9450 - mae: 0.6844 - rmse: 0.9675

 45/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 768ms/step - loss: 0.9435 - mae: 0.6838 - rmse: 0.9667

 46/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 760ms/step - loss: 0.9418 - mae: 0.6831 - rmse: 0.9659

 47/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 752ms/step - loss: 0.9402 - mae: 0.6825 - rmse: 0.9651

 48/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 744ms/step - loss: 0.9385 - mae: 0.6819 - rmse: 0.9642

 49/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 737ms/step - loss: 0.9366 - mae: 0.6811 - rmse: 0.9633

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 736ms/step - loss: 0.9346 - mae: 0.6803 - rmse: 0.9623

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 735ms/step - loss: 0.9325 - mae: 0.6795 - rmse: 0.9612

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 743ms/step - loss: 0.9304 - mae: 0.6787 - rmse: 0.9601

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 748ms/step - loss: 0.9281 - mae: 0.6778 - rmse: 0.9589

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 756ms/step - loss: 0.9261 - mae: 0.6771 - rmse: 0.9579

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 767ms/step - loss: 0.9241 - mae: 0.6763 - rmse: 0.9568

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 780ms/step - loss: 0.9221 - mae: 0.6756 - rmse: 0.9558

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 791ms/step - loss: 0.9201 - mae: 0.6748 - rmse: 0.9547

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 800ms/step - loss: 0.9180 - mae: 0.6740 - rmse: 0.9537

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 806ms/step - loss: 0.9161 - mae: 0.6733 - rmse: 0.9527

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 815ms/step - loss: 0.9141 - mae: 0.6726 - rmse: 0.9516

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 814ms/step - loss: 0.9123 - mae: 0.6720 - rmse: 0.9507

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 814ms/step - loss: 0.9105 - mae: 0.6713 - rmse: 0.9497

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 814ms/step - loss: 0.9087 - mae: 0.6707 - rmse: 0.9488

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 816ms/step - loss: 0.9068 - mae: 0.6700 - rmse: 0.9478

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 824ms/step - loss: 0.9048 - mae: 0.6693 - rmse: 0.9467

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 832ms/step - loss: 0.9027 - mae: 0.6686 - rmse: 0.9456

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 833ms/step - loss: 0.9007 - mae: 0.6678 - rmse: 0.9446

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 836ms/step - loss: 0.8986 - mae: 0.6671 - rmse: 0.9434

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 835ms/step - loss: 0.8966 - mae: 0.6664 - rmse: 0.9424

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 841ms/step - loss: 0.8947 - mae: 0.6657 - rmse: 0.9413

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 843ms/step - loss: 0.8929 - mae: 0.6650 - rmse: 0.9404

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 843ms/step - loss: 0.8911 - mae: 0.6643 - rmse: 0.9394

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 843ms/step - loss: 0.8894 - mae: 0.6637 - rmse: 0.9385

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 842ms/step - loss: 0.8877 - mae: 0.6631 - rmse: 0.9376

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 838ms/step - loss: 0.8862 - mae: 0.6625 - rmse: 0.9368

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 837ms/step - loss: 0.8847 - mae: 0.6620 - rmse: 0.9360

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 832ms/step - loss: 0.8833 - mae: 0.6614 - rmse: 0.9353

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 826ms/step - loss: 0.8819 - mae: 0.6609 - rmse: 0.9346

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 820ms/step - loss: 0.8806 - mae: 0.6605 - rmse: 0.9339

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:34 816ms/step - loss: 0.8793 - mae: 0.6600 - rmse: 0.9332

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 813ms/step - loss: 0.8784 - mae: 0.6597 - rmse: 0.9327

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 810ms/step - loss: 0.8777 - mae: 0.6594 - rmse: 0.9324

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 806ms/step - loss: 0.8773 - mae: 0.6592 - rmse: 0.9321

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 803ms/step - loss: 0.8769 - mae: 0.6591 - rmse: 0.9320

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 800ms/step - loss: 0.8766 - mae: 0.6590 - rmse: 0.9318

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 796ms/step - loss: 0.8764 - mae: 0.6589 - rmse: 0.9318

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 795ms/step - loss: 0.8763 - mae: 0.6588 - rmse: 0.9317

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 799ms/step - loss: 0.8761 - mae: 0.6587 - rmse: 0.9316

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 807ms/step - loss: 0.8759 - mae: 0.6587 - rmse: 0.9316

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 817ms/step - loss: 0.8758 - mae: 0.6586 - rmse: 0.9315

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 826ms/step - loss: 0.8756 - mae: 0.6585 - rmse: 0.9314

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 830ms/step - loss: 0.8753 - mae: 0.6584 - rmse: 0.9313

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 836ms/step - loss: 0.8750 - mae: 0.6583 - rmse: 0.9312

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 842ms/step - loss: 0.8746 - mae: 0.6581 - rmse: 0.9310

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 847ms/step - loss: 0.8742 - mae: 0.6580 - rmse: 0.9308

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 852ms/step - loss: 0.8737 - mae: 0.6578 - rmse: 0.9305

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 858ms/step - loss: 0.8732 - mae: 0.6576 - rmse: 0.9303

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 857ms/step - loss: 0.8726 - mae: 0.6574 - rmse: 0.9300

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 858ms/step - loss: 0.8720 - mae: 0.6571 - rmse: 0.9297

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 856ms/step - loss: 0.8714 - mae: 0.6569 - rmse: 0.9293

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 854ms/step - loss: 0.8708 - mae: 0.6566 - rmse: 0.9290

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 851ms/step - loss: 0.8702 - mae: 0.6564 - rmse: 0.9287

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 849ms/step - loss: 0.8695 - mae: 0.6561 - rmse: 0.9283

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 845ms/step - loss: 0.8688 - mae: 0.6559 - rmse: 0.9280

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 842ms/step - loss: 0.8682 - mae: 0.6556 - rmse: 0.9276

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 839ms/step - loss: 0.8675 - mae: 0.6553 - rmse: 0.9273

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 835ms/step - loss: 0.8667 - mae: 0.6550 - rmse: 0.9269

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 832ms/step - loss: 0.8659 - mae: 0.6547 - rmse: 0.9264

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 828ms/step - loss: 0.8651 - mae: 0.6544 - rmse: 0.9260

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 824ms/step - loss: 0.8642 - mae: 0.6540 - rmse: 0.9255

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 823ms/step - loss: 0.8633 - mae: 0.6536 - rmse: 0.9250

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 820ms/step - loss: 0.8623 - mae: 0.6532 - rmse: 0.9245

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 816ms/step - loss: 0.8614 - mae: 0.6528 - rmse: 0.9240

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 815ms/step - loss: 0.8604 - mae: 0.6524 - rmse: 0.9235

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 811ms/step - loss: 0.8594 - mae: 0.6519 - rmse: 0.9229

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 812ms/step - loss: 0.8583 - mae: 0.6515 - rmse: 0.9223

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 816ms/step - loss: 0.8572 - mae: 0.6510 - rmse: 0.9217

118/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 815ms/step - loss: 0.8561 - mae: 0.6505 - rmse: 0.9211

119/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 816ms/step - loss: 0.8550 - mae: 0.6500 - rmse: 0.9205

120/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 814ms/step - loss: 0.8539 - mae: 0.6495 - rmse: 0.9199

121/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 812ms/step - loss: 0.8528 - mae: 0.6490 - rmse: 0.9193

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 811ms/step - loss: 0.8516 - mae: 0.6485 - rmse: 0.9187

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 808ms/step - loss: 0.8504 - mae: 0.6479 - rmse: 0.9180

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 804ms/step - loss: 0.8492 - mae: 0.6474 - rmse: 0.9173

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 801ms/step - loss: 0.8480 - mae: 0.6468 - rmse: 0.9166

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 797ms/step - loss: 0.8468 - mae: 0.6462 - rmse: 0.9159

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 793ms/step - loss: 0.8455 - mae: 0.6457 - rmse: 0.9152

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 789ms/step - loss: 0.8443 - mae: 0.6451 - rmse: 0.9145

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 786ms/step - loss: 0.8430 - mae: 0.6445 - rmse: 0.9138

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 782ms/step - loss: 0.8417 - mae: 0.6439 - rmse: 0.9131

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 779ms/step - loss: 0.8404 - mae: 0.6433 - rmse: 0.9124

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 775ms/step - loss: 0.8391 - mae: 0.6427 - rmse: 0.9116

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 772ms/step - loss: 0.8379 - mae: 0.6421 - rmse: 0.9109

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 768ms/step - loss: 0.8366 - mae: 0.6415 - rmse: 0.9102

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 765ms/step - loss: 0.8353 - mae: 0.6409 - rmse: 0.9095

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 762ms/step - loss: 0.8340 - mae: 0.6403 - rmse: 0.9087

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 759ms/step - loss: 0.8327 - mae: 0.6397 - rmse: 0.9080

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 759ms/step - loss: 0.8314 - mae: 0.6391 - rmse: 0.9072

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 758ms/step - loss: 0.8301 - mae: 0.6385 - rmse: 0.9065

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 757ms/step - loss: 0.8288 - mae: 0.6379 - rmse: 0.9058

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 757ms/step - loss: 0.8275 - mae: 0.6373 - rmse: 0.9050

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 759ms/step - loss: 0.8262 - mae: 0.6366 - rmse: 0.9042

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 757ms/step - loss: 0.8248 - mae: 0.6360 - rmse: 0.9035

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 758ms/step - loss: 0.8235 - mae: 0.6354 - rmse: 0.9027

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 760ms/step - loss: 0.8221 - mae: 0.6347 - rmse: 0.9019

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 762ms/step - loss: 0.8208 - mae: 0.6341 - rmse: 0.9011

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 762ms/step - loss: 0.8194 - mae: 0.6334 - rmse: 0.9003

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 762ms/step - loss: 0.8180 - mae: 0.6327 - rmse: 0.8995

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 763ms/step - loss: 0.8166 - mae: 0.6321 - rmse: 0.8987

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 765ms/step - loss: 0.8153 - mae: 0.6314 - rmse: 0.8979

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 766ms/step - loss: 0.8139 - mae: 0.6307 - rmse: 0.8971

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 768ms/step - loss: 0.8125 - mae: 0.6301 - rmse: 0.8963

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 768ms/step - loss: 0.8111 - mae: 0.6294 - rmse: 0.8955

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 767ms/step - loss: 0.8097 - mae: 0.6287 - rmse: 0.8947

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 767ms/step - loss: 0.8084 - mae: 0.6281 - rmse: 0.8939

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 767ms/step - loss: 0.8070 - mae: 0.6274 - rmse: 0.8931

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 767ms/step - loss: 0.8056 - mae: 0.6267 - rmse: 0.8922

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 767ms/step - loss: 0.8042 - mae: 0.6260 - rmse: 0.8914

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 766ms/step - loss: 0.8028 - mae: 0.6253 - rmse: 0.8906

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 766ms/step - loss: 0.8014 - mae: 0.6247 - rmse: 0.8898

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 768ms/step - loss: 0.8000 - mae: 0.6240 - rmse: 0.8890

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 769ms/step - loss: 0.7987 - mae: 0.6233 - rmse: 0.8881

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 770ms/step - loss: 0.7973 - mae: 0.6226 - rmse: 0.8873

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 769ms/step - loss: 0.7959 - mae: 0.6219 - rmse: 0.8865

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 771ms/step - loss: 0.7945 - mae: 0.6213 - rmse: 0.8857

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 770ms/step - loss: 0.7931 - mae: 0.6206 - rmse: 0.8849

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 768ms/step - loss: 0.7918 - mae: 0.6199 - rmse: 0.8840

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 766ms/step - loss: 0.7904 - mae: 0.6193 - rmse: 0.8832

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 765ms/step - loss: 0.7891 - mae: 0.6186 - rmse: 0.8825

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 763ms/step - loss: 0.7878 - mae: 0.6180 - rmse: 0.8817

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 761ms/step - loss: 0.7865 - mae: 0.6174 - rmse: 0.8809

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 759ms/step - loss: 0.7852 - mae: 0.6167 - rmse: 0.8801

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 756ms/step - loss: 0.7839 - mae: 0.6161 - rmse: 0.8794

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 754ms/step - loss: 0.7827 - mae: 0.6155 - rmse: 0.8786

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 752ms/step - loss: 0.7814 - mae: 0.6149 - rmse: 0.8779

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 749ms/step - loss: 0.7801 - mae: 0.6143 - rmse: 0.8771

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 746ms/step - loss: 0.7789 - mae: 0.6137 - rmse: 0.8764

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 743ms/step - loss: 0.7776 - mae: 0.6131 - rmse: 0.8756

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 741ms/step - loss: 0.7764 - mae: 0.6125 - rmse: 0.8749

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 738ms/step - loss: 0.7751 - mae: 0.6119 - rmse: 0.8741

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 735ms/step - loss: 0.7739 - mae: 0.6113 - rmse: 0.8733

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 733ms/step - loss: 0.7726 - mae: 0.6107 - rmse: 0.8726

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 730ms/step - loss: 0.7714 - mae: 0.6101 - rmse: 0.8718

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 728ms/step - loss: 0.7701 - mae: 0.6095 - rmse: 0.8711

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 729ms/step - loss: 0.7689 - mae: 0.6089 - rmse: 0.8703

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 730ms/step - loss: 0.7677 - mae: 0.6083 - rmse: 0.8696

187/269 ━━━━━━━━━━━━━━━━━━━━ 59s 731ms/step - loss: 0.7664 - mae: 0.6077 - rmse: 0.8688

188/269 ━━━━━━━━━━━━━━━━━━━━ 59s 732ms/step - loss: 0.7652 - mae: 0.6071 - rmse: 0.8681

189/269 ━━━━━━━━━━━━━━━━━━━━ 58s 733ms/step - loss: 0.7639 - mae: 0.6065 - rmse: 0.8673

190/269 ━━━━━━━━━━━━━━━━━━━━ 58s 734ms/step - loss: 0.7627 - mae: 0.6059 - rmse: 0.8665

191/269 ━━━━━━━━━━━━━━━━━━━━ 57s 736ms/step - loss: 0.7614 - mae: 0.6053 - rmse: 0.8658

192/269 ━━━━━━━━━━━━━━━━━━━━ 56s 737ms/step - loss: 0.7602 - mae: 0.6046 - rmse: 0.8650

193/269 ━━━━━━━━━━━━━━━━━━━━ 56s 739ms/step - loss: 0.7590 - mae: 0.6040 - rmse: 0.8643

194/269 ━━━━━━━━━━━━━━━━━━━━ 55s 741ms/step - loss: 0.7577 - mae: 0.6034 - rmse: 0.8635

195/269 ━━━━━━━━━━━━━━━━━━━━ 55s 744ms/step - loss: 0.7565 - mae: 0.6028 - rmse: 0.8628

196/269 ━━━━━━━━━━━━━━━━━━━━ 54s 744ms/step - loss: 0.7553 - mae: 0.6022 - rmse: 0.8620

197/269 ━━━━━━━━━━━━━━━━━━━━ 53s 743ms/step - loss: 0.7540 - mae: 0.6016 - rmse: 0.8613

198/269 ━━━━━━━━━━━━━━━━━━━━ 52s 742ms/step - loss: 0.7528 - mae: 0.6010 - rmse: 0.8605

199/269 ━━━━━━━━━━━━━━━━━━━━ 51s 741ms/step - loss: 0.7516 - mae: 0.6004 - rmse: 0.8598

200/269 ━━━━━━━━━━━━━━━━━━━━ 51s 740ms/step - loss: 0.7504 - mae: 0.5998 - rmse: 0.8590

201/269 ━━━━━━━━━━━━━━━━━━━━ 50s 740ms/step - loss: 0.7492 - mae: 0.5992 - rmse: 0.8583

202/269 ━━━━━━━━━━━━━━━━━━━━ 49s 739ms/step - loss: 0.7480 - mae: 0.5986 - rmse: 0.8576

203/269 ━━━━━━━━━━━━━━━━━━━━ 48s 738ms/step - loss: 0.7468 - mae: 0.5980 - rmse: 0.8568

204/269 ━━━━━━━━━━━━━━━━━━━━ 47s 738ms/step - loss: 0.7457 - mae: 0.5974 - rmse: 0.8561

205/269 ━━━━━━━━━━━━━━━━━━━━ 47s 738ms/step - loss: 0.7445 - mae: 0.5969 - rmse: 0.8554

206/269 ━━━━━━━━━━━━━━━━━━━━ 46s 738ms/step - loss: 0.7433 - mae: 0.5963 - rmse: 0.8547

207/269 ━━━━━━━━━━━━━━━━━━━━ 45s 736ms/step - loss: 0.7422 - mae: 0.5957 - rmse: 0.8540

208/269 ━━━━━━━━━━━━━━━━━━━━ 44s 734ms/step - loss: 0.7410 - mae: 0.5951 - rmse: 0.8533

209/269 ━━━━━━━━━━━━━━━━━━━━ 44s 734ms/step - loss: 0.7399 - mae: 0.5946 - rmse: 0.8526

210/269 ━━━━━━━━━━━━━━━━━━━━ 43s 733ms/step - loss: 0.7388 - mae: 0.5940 - rmse: 0.8518

211/269 ━━━━━━━━━━━━━━━━━━━━ 42s 734ms/step - loss: 0.7376 - mae: 0.5934 - rmse: 0.8511

212/269 ━━━━━━━━━━━━━━━━━━━━ 41s 734ms/step - loss: 0.7365 - mae: 0.5929 - rmse: 0.8504

213/269 ━━━━━━━━━━━━━━━━━━━━ 41s 735ms/step - loss: 0.7353 - mae: 0.5923 - rmse: 0.8497

214/269 ━━━━━━━━━━━━━━━━━━━━ 40s 734ms/step - loss: 0.7342 - mae: 0.5917 - rmse: 0.8490

215/269 ━━━━━━━━━━━━━━━━━━━━ 39s 735ms/step - loss: 0.7331 - mae: 0.5912 - rmse: 0.8483

216/269 ━━━━━━━━━━━━━━━━━━━━ 38s 735ms/step - loss: 0.7319 - mae: 0.5906 - rmse: 0.8476

217/269 ━━━━━━━━━━━━━━━━━━━━ 38s 736ms/step - loss: 0.7308 - mae: 0.5901 - rmse: 0.8469

218/269 ━━━━━━━━━━━━━━━━━━━━ 37s 737ms/step - loss: 0.7297 - mae: 0.5895 - rmse: 0.8462

219/269 ━━━━━━━━━━━━━━━━━━━━ 36s 737ms/step - loss: 0.7286 - mae: 0.5889 - rmse: 0.8455

220/269 ━━━━━━━━━━━━━━━━━━━━ 36s 738ms/step - loss: 0.7275 - mae: 0.5884 - rmse: 0.8448

221/269 ━━━━━━━━━━━━━━━━━━━━ 35s 738ms/step - loss: 0.7264 - mae: 0.5878 - rmse: 0.8441

222/269 ━━━━━━━━━━━━━━━━━━━━ 34s 737ms/step - loss: 0.7253 - mae: 0.5873 - rmse: 0.8434

223/269 ━━━━━━━━━━━━━━━━━━━━ 33s 736ms/step - loss: 0.7241 - mae: 0.5867 - rmse: 0.8427

224/269 ━━━━━━━━━━━━━━━━━━━━ 33s 735ms/step - loss: 0.7230 - mae: 0.5862 - rmse: 0.8420

225/269 ━━━━━━━━━━━━━━━━━━━━ 32s 734ms/step - loss: 0.7219 - mae: 0.5856 - rmse: 0.8413

226/269 ━━━━━━━━━━━━━━━━━━━━ 31s 733ms/step - loss: 0.7208 - mae: 0.5851 - rmse: 0.8406

227/269 ━━━━━━━━━━━━━━━━━━━━ 30s 732ms/step - loss: 0.7197 - mae: 0.5845 - rmse: 0.8400

228/269 ━━━━━━━━━━━━━━━━━━━━ 29s 730ms/step - loss: 0.7186 - mae: 0.5840 - rmse: 0.8393

229/269 ━━━━━━━━━━━━━━━━━━━━ 29s 729ms/step - loss: 0.7175 - mae: 0.5834 - rmse: 0.8386

230/269 ━━━━━━━━━━━━━━━━━━━━ 28s 727ms/step - loss: 0.7164 - mae: 0.5828 - rmse: 0.8379

231/269 ━━━━━━━━━━━━━━━━━━━━ 27s 725ms/step - loss: 0.7153 - mae: 0.5823 - rmse: 0.8372

232/269 ━━━━━━━━━━━━━━━━━━━━ 26s 723ms/step - loss: 0.7142 - mae: 0.5817 - rmse: 0.8365

233/269 ━━━━━━━━━━━━━━━━━━━━ 25s 721ms/step - loss: 0.7132 - mae: 0.5812 - rmse: 0.8358

234/269 ━━━━━━━━━━━━━━━━━━━━ 25s 720ms/step - loss: 0.7121 - mae: 0.5806 - rmse: 0.8351

235/269 ━━━━━━━━━━━━━━━━━━━━ 24s 718ms/step - loss: 0.7110 - mae: 0.5801 - rmse: 0.8344

236/269 ━━━━━━━━━━━━━━━━━━━━ 23s 716ms/step - loss: 0.7099 - mae: 0.5795 - rmse: 0.8337

237/269 ━━━━━━━━━━━━━━━━━━━━ 22s 715ms/step - loss: 0.7088 - mae: 0.5790 - rmse: 0.8330

238/269 ━━━━━━━━━━━━━━━━━━━━ 22s 713ms/step - loss: 0.7078 - mae: 0.5784 - rmse: 0.8324

239/269 ━━━━━━━━━━━━━━━━━━━━ 21s 712ms/step - loss: 0.7067 - mae: 0.5779 - rmse: 0.8317

240/269 ━━━━━━━━━━━━━━━━━━━━ 20s 711ms/step - loss: 0.7056 - mae: 0.5773 - rmse: 0.8310

241/269 ━━━━━━━━━━━━━━━━━━━━ 19s 711ms/step - loss: 0.7046 - mae: 0.5768 - rmse: 0.8303

242/269 ━━━━━━━━━━━━━━━━━━━━ 19s 711ms/step - loss: 0.7035 - mae: 0.5763 - rmse: 0.8297

243/269 ━━━━━━━━━━━━━━━━━━━━ 18s 712ms/step - loss: 0.7025 - mae: 0.5757 - rmse: 0.8290

244/269 ━━━━━━━━━━━━━━━━━━━━ 17s 713ms/step - loss: 0.7014 - mae: 0.5752 - rmse: 0.8283

245/269 ━━━━━━━━━━━━━━━━━━━━ 17s 715ms/step - loss: 0.7004 - mae: 0.5746 - rmse: 0.8276

246/269 ━━━━━━━━━━━━━━━━━━━━ 16s 716ms/step - loss: 0.6993 - mae: 0.5741 - rmse: 0.8270

247/269 ━━━━━━━━━━━━━━━━━━━━ 15s 718ms/step - loss: 0.6983 - mae: 0.5736 - rmse: 0.8263

248/269 ━━━━━━━━━━━━━━━━━━━━ 15s 720ms/step - loss: 0.6973 - mae: 0.5731 - rmse: 0.8256

249/269 ━━━━━━━━━━━━━━━━━━━━ 14s 720ms/step - loss: 0.6962 - mae: 0.5725 - rmse: 0.8250

250/269 ━━━━━━━━━━━━━━━━━━━━ 13s 722ms/step - loss: 0.6952 - mae: 0.5720 - rmse: 0.8243

251/269 ━━━━━━━━━━━━━━━━━━━━ 13s 723ms/step - loss: 0.6942 - mae: 0.5715 - rmse: 0.8237

252/269 ━━━━━━━━━━━━━━━━━━━━ 12s 724ms/step - loss: 0.6932 - mae: 0.5710 - rmse: 0.8230

253/269 ━━━━━━━━━━━━━━━━━━━━ 11s 724ms/step - loss: 0.6922 - mae: 0.5704 - rmse: 0.8223

254/269 ━━━━━━━━━━━━━━━━━━━━ 10s 724ms/step - loss: 0.6911 - mae: 0.5699 - rmse: 0.8217

255/269 ━━━━━━━━━━━━━━━━━━━━ 10s 724ms/step - loss: 0.6901 - mae: 0.5694 - rmse: 0.8210

256/269 ━━━━━━━━━━━━━━━━━━━━ 9s 723ms/step - loss: 0.6891 - mae: 0.5689 - rmse: 0.8204

257/269 ━━━━━━━━━━━━━━━━━━━━ 8s 723ms/step - loss: 0.6881 - mae: 0.5684 - rmse: 0.8197

258/269 ━━━━━━━━━━━━━━━━━━━━ 7s 722ms/step - loss: 0.6871 - mae: 0.5679 - rmse: 0.8191

259/269 ━━━━━━━━━━━━━━━━━━━━ 7s 722ms/step - loss: 0.6861 - mae: 0.5674 - rmse: 0.8184

260/269 ━━━━━━━━━━━━━━━━━━━━ 6s 721ms/step - loss: 0.6851 - mae: 0.5668 - rmse: 0.8178

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 721ms/step - loss: 0.6841 - mae: 0.5663 - rmse: 0.8171

262/269 ━━━━━━━━━━━━━━━━━━━━ 5s 721ms/step - loss: 0.6831 - mae: 0.5658 - rmse: 0.8165

263/269 ━━━━━━━━━━━━━━━━━━━━ 4s 720ms/step - loss: 0.6821 - mae: 0.5653 - rmse: 0.8158

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 720ms/step - loss: 0.6812 - mae: 0.5648 - rmse: 0.8152

265/269 ━━━━━━━━━━━━━━━━━━━━ 2s 720ms/step - loss: 0.6802 - mae: 0.5643 - rmse: 0.8146

266/269 ━━━━━━━━━━━━━━━━━━━━ 2s 720ms/step - loss: 0.6792 - mae: 0.5638 - rmse: 0.8139

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 720ms/step - loss: 0.6782 - mae: 0.5633 - rmse: 0.8133

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 720ms/step - loss: 0.6773 - mae: 0.5628 - rmse: 0.8127

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 719ms/step - loss: 0.6763 - mae: 0.5623 - rmse: 0.8120

269/269 ━━━━━━━━━━━━━━━━━━━━ 214s 797ms/step - loss: 0.4185 - mae: 0.4299 - rmse: 0.6435 - val_loss: 0.7208 - val_mae: 0.5345 - val_rmse: 0.8465 - learning_rate: 0.0010

Epoch 11/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 5:10 1s/step - loss: 0.8984 - mae: 0.6877 - rmse: 0.9456

  2/269 ━━━━━━━━━━━━━━━━━━━━ 4:59 1s/step - loss: 0.7984 - mae: 0.6533 - rmse: 0.8894

  3/269 ━━━━━━━━━━━━━━━━━━━━ 4:09 939ms/step - loss: 0.7831 - mae: 0.6523 - rmse: 0.8812

  4/269 ━━━━━━━━━━━━━━━━━━━━ 3:59 904ms/step - loss: 0.7682 - mae: 0.6487 - rmse: 0.8730

  5/269 ━━━━━━━━━━━━━━━━━━━━ 3:46 859ms/step - loss: 0.7431 - mae: 0.6386 - rmse: 0.8582

  6/269 ━━━━━━━━━━━━━━━━━━━━ 3:42 847ms/step - loss: 0.7229 - mae: 0.6302 - rmse: 0.8461

  7/269 ━━━━━━━━━━━━━━━━━━━━ 3:32 810ms/step - loss: 0.7184 - mae: 0.6275 - rmse: 0.8437

  8/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 808ms/step - loss: 0.7305 - mae: 0.6308 - rmse: 0.8508

  9/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 795ms/step - loss: 0.7373 - mae: 0.6325 - rmse: 0.8548

 10/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 793ms/step - loss: 0.7383 - mae: 0.6319 - rmse: 0.8556

 11/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 772ms/step - loss: 0.7372 - mae: 0.6305 - rmse: 0.8550

 12/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 782ms/step - loss: 0.7441 - mae: 0.6323 - rmse: 0.8591

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:16 769ms/step - loss: 0.7563 - mae: 0.6353 - rmse: 0.8659

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:12 755ms/step - loss: 0.7748 - mae: 0.6405 - rmse: 0.8758

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 767ms/step - loss: 0.7908 - mae: 0.6452 - rmse: 0.8845

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:16 778ms/step - loss: 0.8069 - mae: 0.6501 - rmse: 0.8931

 17/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 790ms/step - loss: 0.8233 - mae: 0.6546 - rmse: 0.9017

 18/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 790ms/step - loss: 0.8369 - mae: 0.6584 - rmse: 0.9089

 19/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 801ms/step - loss: 0.8508 - mae: 0.6621 - rmse: 0.9162

 20/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 812ms/step - loss: 0.8631 - mae: 0.6654 - rmse: 0.9227

 21/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 812ms/step - loss: 0.8728 - mae: 0.6678 - rmse: 0.9278

 22/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 813ms/step - loss: 0.8814 - mae: 0.6701 - rmse: 0.9324

 23/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 805ms/step - loss: 0.8900 - mae: 0.6725 - rmse: 0.9369

 24/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 810ms/step - loss: 0.8976 - mae: 0.6747 - rmse: 0.9409

 25/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 825ms/step - loss: 0.9037 - mae: 0.6765 - rmse: 0.9442

 26/269 ━━━━━━━━━━━━━━━━━━━━ 3:24 843ms/step - loss: 0.9098 - mae: 0.6781 - rmse: 0.9475

 27/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 857ms/step - loss: 0.9146 - mae: 0.6794 - rmse: 0.9500

 28/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 870ms/step - loss: 0.9184 - mae: 0.6803 - rmse: 0.9521

 29/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 895ms/step - loss: 0.9216 - mae: 0.6811 - rmse: 0.9539

 30/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 904ms/step - loss: 0.9237 - mae: 0.6815 - rmse: 0.9551

 31/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 911ms/step - loss: 0.9251 - mae: 0.6817 - rmse: 0.9560

 32/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 915ms/step - loss: 0.9261 - mae: 0.6817 - rmse: 0.9566

 33/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 927ms/step - loss: 0.9266 - mae: 0.6816 - rmse: 0.9570

 34/269 ━━━━━━━━━━━━━━━━━━━━ 3:40 939ms/step - loss: 0.9269 - mae: 0.6815 - rmse: 0.9572

 35/269 ━━━━━━━━━━━━━━━━━━━━ 3:46 968ms/step - loss: 0.9270 - mae: 0.6814 - rmse: 0.9574

 36/269 ━━━━━━━━━━━━━━━━━━━━ 3:44 964ms/step - loss: 0.9268 - mae: 0.6812 - rmse: 0.9573

 37/269 ━━━━━━━━━━━━━━━━━━━━ 3:41 953ms/step - loss: 0.9264 - mae: 0.6810 - rmse: 0.9572

 38/269 ━━━━━━━━━━━━━━━━━━━━ 3:37 943ms/step - loss: 0.9257 - mae: 0.6806 - rmse: 0.9569

 39/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 935ms/step - loss: 0.9247 - mae: 0.6801 - rmse: 0.9565

 40/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 926ms/step - loss: 0.9235 - mae: 0.6795 - rmse: 0.9559

 41/269 ━━━━━━━━━━━━━━━━━━━━ 3:28 916ms/step - loss: 0.9224 - mae: 0.6791 - rmse: 0.9554

 42/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 907ms/step - loss: 0.9211 - mae: 0.6785 - rmse: 0.9548

 43/269 ━━━━━━━━━━━━━━━━━━━━ 3:23 902ms/step - loss: 0.9197 - mae: 0.6779 - rmse: 0.9541

 44/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 898ms/step - loss: 0.9185 - mae: 0.6774 - rmse: 0.9535

 45/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 889ms/step - loss: 0.9171 - mae: 0.6769 - rmse: 0.9529

 46/269 ━━━━━━━━━━━━━━━━━━━━ 3:16 881ms/step - loss: 0.9156 - mae: 0.6763 - rmse: 0.9521

 47/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 875ms/step - loss: 0.9142 - mae: 0.6757 - rmse: 0.9514

 48/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 873ms/step - loss: 0.9126 - mae: 0.6751 - rmse: 0.9506

 49/269 ━━━━━━━━━━━━━━━━━━━━ 3:12 874ms/step - loss: 0.9109 - mae: 0.6744 - rmse: 0.9497

 50/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 870ms/step - loss: 0.9090 - mae: 0.6737 - rmse: 0.9488

 51/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 873ms/step - loss: 0.9071 - mae: 0.6729 - rmse: 0.9478

 52/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 876ms/step - loss: 0.9051 - mae: 0.6721 - rmse: 0.9467

 53/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 882ms/step - loss: 0.9030 - mae: 0.6713 - rmse: 0.9457

 54/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 884ms/step - loss: 0.9012 - mae: 0.6706 - rmse: 0.9447

 55/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 884ms/step - loss: 0.8992 - mae: 0.6699 - rmse: 0.9437

 56/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 890ms/step - loss: 0.8974 - mae: 0.6692 - rmse: 0.9427

 57/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 891ms/step - loss: 0.8955 - mae: 0.6684 - rmse: 0.9417

 58/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 898ms/step - loss: 0.8935 - mae: 0.6677 - rmse: 0.9407

 59/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 898ms/step - loss: 0.8918 - mae: 0.6670 - rmse: 0.9398

 60/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 900ms/step - loss: 0.8900 - mae: 0.6663 - rmse: 0.9388

 61/269 ━━━━━━━━━━━━━━━━━━━━ 3:07 900ms/step - loss: 0.8883 - mae: 0.6657 - rmse: 0.9379

 62/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 896ms/step - loss: 0.8866 - mae: 0.6651 - rmse: 0.9371

 63/269 ━━━━━━━━━━━━━━━━━━━━ 3:04 895ms/step - loss: 0.8850 - mae: 0.6645 - rmse: 0.9362

 64/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 896ms/step - loss: 0.8832 - mae: 0.6639 - rmse: 0.9353

 65/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 897ms/step - loss: 0.8814 - mae: 0.6632 - rmse: 0.9343

 66/269 ━━━━━━━━━━━━━━━━━━━━ 3:01 893ms/step - loss: 0.8795 - mae: 0.6625 - rmse: 0.9333

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 889ms/step - loss: 0.8775 - mae: 0.6617 - rmse: 0.9322

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 884ms/step - loss: 0.8756 - mae: 0.6610 - rmse: 0.9312

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 882ms/step - loss: 0.8738 - mae: 0.6603 - rmse: 0.9302

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 879ms/step - loss: 0.8719 - mae: 0.6596 - rmse: 0.9292

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 886ms/step - loss: 0.8703 - mae: 0.6590 - rmse: 0.9283

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 889ms/step - loss: 0.8686 - mae: 0.6583 - rmse: 0.9274

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 893ms/step - loss: 0.8670 - mae: 0.6577 - rmse: 0.9265

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 900ms/step - loss: 0.8655 - mae: 0.6571 - rmse: 0.9257

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 908ms/step - loss: 0.8640 - mae: 0.6565 - rmse: 0.9249

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 920ms/step - loss: 0.8626 - mae: 0.6560 - rmse: 0.9242

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 922ms/step - loss: 0.8613 - mae: 0.6555 - rmse: 0.9235

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 922ms/step - loss: 0.8600 - mae: 0.6550 - rmse: 0.9228

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 921ms/step - loss: 0.8588 - mae: 0.6546 - rmse: 0.9222

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 918ms/step - loss: 0.8576 - mae: 0.6541 - rmse: 0.9215

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 914ms/step - loss: 0.8567 - mae: 0.6538 - rmse: 0.9211

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 912ms/step - loss: 0.8562 - mae: 0.6536 - rmse: 0.9208

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 908ms/step - loss: 0.8558 - mae: 0.6534 - rmse: 0.9206

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 905ms/step - loss: 0.8556 - mae: 0.6532 - rmse: 0.9205

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 903ms/step - loss: 0.8554 - mae: 0.6531 - rmse: 0.9204

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 900ms/step - loss: 0.8553 - mae: 0.6531 - rmse: 0.9204

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:43 897ms/step - loss: 0.8552 - mae: 0.6530 - rmse: 0.9204

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 895ms/step - loss: 0.8551 - mae: 0.6529 - rmse: 0.9204

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 893ms/step - loss: 0.8551 - mae: 0.6529 - rmse: 0.9204

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 894ms/step - loss: 0.8550 - mae: 0.6528 - rmse: 0.9204

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 892ms/step - loss: 0.8549 - mae: 0.6528 - rmse: 0.9203

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 891ms/step - loss: 0.8548 - mae: 0.6527 - rmse: 0.9203

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 890ms/step - loss: 0.8545 - mae: 0.6526 - rmse: 0.9202

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 893ms/step - loss: 0.8542 - mae: 0.6525 - rmse: 0.9200

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 891ms/step - loss: 0.8539 - mae: 0.6523 - rmse: 0.9199

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 887ms/step - loss: 0.8535 - mae: 0.6521 - rmse: 0.9197

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 884ms/step - loss: 0.8531 - mae: 0.6519 - rmse: 0.9194

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:30 880ms/step - loss: 0.8526 - mae: 0.6517 - rmse: 0.9192

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 875ms/step - loss: 0.8521 - mae: 0.6515 - rmse: 0.9189

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 871ms/step - loss: 0.8515 - mae: 0.6513 - rmse: 0.9187

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 868ms/step - loss: 0.8510 - mae: 0.6511 - rmse: 0.9184

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 863ms/step - loss: 0.8505 - mae: 0.6508 - rmse: 0.9181

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 858ms/step - loss: 0.8499 - mae: 0.6506 - rmse: 0.9178

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 853ms/step - loss: 0.8493 - mae: 0.6504 - rmse: 0.9175

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 847ms/step - loss: 0.8487 - mae: 0.6501 - rmse: 0.9172

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 842ms/step - loss: 0.8480 - mae: 0.6499 - rmse: 0.9168

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 837ms/step - loss: 0.8474 - mae: 0.6496 - rmse: 0.9165

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 832ms/step - loss: 0.8466 - mae: 0.6493 - rmse: 0.9161

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 828ms/step - loss: 0.8459 - mae: 0.6489 - rmse: 0.9157

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 823ms/step - loss: 0.8451 - mae: 0.6486 - rmse: 0.9152

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 819ms/step - loss: 0.8442 - mae: 0.6482 - rmse: 0.9148

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 815ms/step - loss: 0.8434 - mae: 0.6478 - rmse: 0.9143

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 810ms/step - loss: 0.8425 - mae: 0.6474 - rmse: 0.9138

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 805ms/step - loss: 0.8415 - mae: 0.6470 - rmse: 0.9133

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 801ms/step - loss: 0.8406 - mae: 0.6466 - rmse: 0.9128

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 796ms/step - loss: 0.8396 - mae: 0.6461 - rmse: 0.9122

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 794ms/step - loss: 0.8386 - mae: 0.6457 - rmse: 0.9117

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 793ms/step - loss: 0.8376 - mae: 0.6452 - rmse: 0.9111

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 792ms/step - loss: 0.8365 - mae: 0.6447 - rmse: 0.9105

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 789ms/step - loss: 0.8355 - mae: 0.6442 - rmse: 0.9100

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 787ms/step - loss: 0.8344 - mae: 0.6438 - rmse: 0.9094

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 784ms/step - loss: 0.8333 - mae: 0.6432 - rmse: 0.9087

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 782ms/step - loss: 0.8322 - mae: 0.6427 - rmse: 0.9081

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 780ms/step - loss: 0.8311 - mae: 0.6422 - rmse: 0.9075

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 779ms/step - loss: 0.8299 - mae: 0.6416 - rmse: 0.9068

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 780ms/step - loss: 0.8287 - mae: 0.6411 - rmse: 0.9062

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 779ms/step - loss: 0.8275 - mae: 0.6405 - rmse: 0.9055

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 780ms/step - loss: 0.8263 - mae: 0.6399 - rmse: 0.9048

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 779ms/step - loss: 0.8251 - mae: 0.6393 - rmse: 0.9041

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 779ms/step - loss: 0.8239 - mae: 0.6388 - rmse: 0.9034

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 779ms/step - loss: 0.8227 - mae: 0.6382 - rmse: 0.9027

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 780ms/step - loss: 0.8215 - mae: 0.6376 - rmse: 0.9020

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 780ms/step - loss: 0.8203 - mae: 0.6370 - rmse: 0.9013

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 782ms/step - loss: 0.8190 - mae: 0.6364 - rmse: 0.9006

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 782ms/step - loss: 0.8178 - mae: 0.6358 - rmse: 0.8999

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 782ms/step - loss: 0.8166 - mae: 0.6352 - rmse: 0.8992

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 783ms/step - loss: 0.8153 - mae: 0.6347 - rmse: 0.8985

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 783ms/step - loss: 0.8141 - mae: 0.6341 - rmse: 0.8978

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 782ms/step - loss: 0.8129 - mae: 0.6335 - rmse: 0.8971

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 780ms/step - loss: 0.8116 - mae: 0.6329 - rmse: 0.8964

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 778ms/step - loss: 0.8103 - mae: 0.6323 - rmse: 0.8956

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 777ms/step - loss: 0.8091 - mae: 0.6317 - rmse: 0.8949

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 777ms/step - loss: 0.8078 - mae: 0.6311 - rmse: 0.8941

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 776ms/step - loss: 0.8065 - mae: 0.6304 - rmse: 0.8934

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 776ms/step - loss: 0.8052 - mae: 0.6298 - rmse: 0.8926

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 776ms/step - loss: 0.8039 - mae: 0.6292 - rmse: 0.8919

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 777ms/step - loss: 0.8026 - mae: 0.6285 - rmse: 0.8911

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 776ms/step - loss: 0.8013 - mae: 0.6279 - rmse: 0.8903

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 776ms/step - loss: 0.7999 - mae: 0.6272 - rmse: 0.8895

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 779ms/step - loss: 0.7986 - mae: 0.6266 - rmse: 0.8888

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 781ms/step - loss: 0.7973 - mae: 0.6259 - rmse: 0.8880

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 782ms/step - loss: 0.7959 - mae: 0.6253 - rmse: 0.8872

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 784ms/step - loss: 0.7946 - mae: 0.6246 - rmse: 0.8864

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 785ms/step - loss: 0.7933 - mae: 0.6239 - rmse: 0.8856

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 784ms/step - loss: 0.7920 - mae: 0.6233 - rmse: 0.8848

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 783ms/step - loss: 0.7906 - mae: 0.6226 - rmse: 0.8840

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 785ms/step - loss: 0.7893 - mae: 0.6219 - rmse: 0.8833

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 784ms/step - loss: 0.7879 - mae: 0.6213 - rmse: 0.8825

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 785ms/step - loss: 0.7866 - mae: 0.6206 - rmse: 0.8817

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 785ms/step - loss: 0.7853 - mae: 0.6199 - rmse: 0.8809

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 786ms/step - loss: 0.7839 - mae: 0.6193 - rmse: 0.8801

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 787ms/step - loss: 0.7826 - mae: 0.6186 - rmse: 0.8793

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 788ms/step - loss: 0.7813 - mae: 0.6179 - rmse: 0.8785

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 789ms/step - loss: 0.7799 - mae: 0.6173 - rmse: 0.8777

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 788ms/step - loss: 0.7786 - mae: 0.6166 - rmse: 0.8769

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 790ms/step - loss: 0.7773 - mae: 0.6159 - rmse: 0.8761

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 795ms/step - loss: 0.7760 - mae: 0.6153 - rmse: 0.8753

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 799ms/step - loss: 0.7747 - mae: 0.6146 - rmse: 0.8745

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 798ms/step - loss: 0.7734 - mae: 0.6140 - rmse: 0.8737

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 797ms/step - loss: 0.7721 - mae: 0.6134 - rmse: 0.8729

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 795ms/step - loss: 0.7708 - mae: 0.6128 - rmse: 0.8722

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 793ms/step - loss: 0.7696 - mae: 0.6121 - rmse: 0.8714

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 792ms/step - loss: 0.7684 - mae: 0.6115 - rmse: 0.8707

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 789ms/step - loss: 0.7671 - mae: 0.6109 - rmse: 0.8700

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 787ms/step - loss: 0.7659 - mae: 0.6103 - rmse: 0.8692

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 784ms/step - loss: 0.7647 - mae: 0.6097 - rmse: 0.8685

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 781ms/step - loss: 0.7635 - mae: 0.6092 - rmse: 0.8678

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 779ms/step - loss: 0.7623 - mae: 0.6086 - rmse: 0.8670

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 776ms/step - loss: 0.7611 - mae: 0.6080 - rmse: 0.8663

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 774ms/step - loss: 0.7599 - mae: 0.6074 - rmse: 0.8656

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 771ms/step - loss: 0.7587 - mae: 0.6068 - rmse: 0.8648

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 769ms/step - loss: 0.7574 - mae: 0.6062 - rmse: 0.8641

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 766ms/step - loss: 0.7562 - mae: 0.6056 - rmse: 0.8634

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 764ms/step - loss: 0.7550 - mae: 0.6050 - rmse: 0.8626

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 761ms/step - loss: 0.7538 - mae: 0.6044 - rmse: 0.8619

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 759ms/step - loss: 0.7526 - mae: 0.6038 - rmse: 0.8611

187/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 758ms/step - loss: 0.7514 - mae: 0.6032 - rmse: 0.8604

188/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 756ms/step - loss: 0.7502 - mae: 0.6026 - rmse: 0.8597

189/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 756ms/step - loss: 0.7490 - mae: 0.6020 - rmse: 0.8589

190/269 ━━━━━━━━━━━━━━━━━━━━ 59s 757ms/step - loss: 0.7478 - mae: 0.6014 - rmse: 0.8582

191/269 ━━━━━━━━━━━━━━━━━━━━ 59s 757ms/step - loss: 0.7466 - mae: 0.6008 - rmse: 0.8574

192/269 ━━━━━━━━━━━━━━━━━━━━ 58s 757ms/step - loss: 0.7454 - mae: 0.6002 - rmse: 0.8567

193/269 ━━━━━━━━━━━━━━━━━━━━ 57s 758ms/step - loss: 0.7442 - mae: 0.5996 - rmse: 0.8560

194/269 ━━━━━━━━━━━━━━━━━━━━ 56s 758ms/step - loss: 0.7430 - mae: 0.5990 - rmse: 0.8552

195/269 ━━━━━━━━━━━━━━━━━━━━ 56s 761ms/step - loss: 0.7418 - mae: 0.5984 - rmse: 0.8545

196/269 ━━━━━━━━━━━━━━━━━━━━ 55s 763ms/step - loss: 0.7406 - mae: 0.5978 - rmse: 0.8537

197/269 ━━━━━━━━━━━━━━━━━━━━ 55s 765ms/step - loss: 0.7394 - mae: 0.5972 - rmse: 0.8530

198/269 ━━━━━━━━━━━━━━━━━━━━ 54s 766ms/step - loss: 0.7382 - mae: 0.5966 - rmse: 0.8523

199/269 ━━━━━━━━━━━━━━━━━━━━ 53s 768ms/step - loss: 0.7370 - mae: 0.5960 - rmse: 0.8515

200/269 ━━━━━━━━━━━━━━━━━━━━ 53s 770ms/step - loss: 0.7359 - mae: 0.5954 - rmse: 0.8508

201/269 ━━━━━━━━━━━━━━━━━━━━ 52s 770ms/step - loss: 0.7347 - mae: 0.5948 - rmse: 0.8501

202/269 ━━━━━━━━━━━━━━━━━━━━ 51s 769ms/step - loss: 0.7335 - mae: 0.5942 - rmse: 0.8494

203/269 ━━━━━━━━━━━━━━━━━━━━ 50s 768ms/step - loss: 0.7324 - mae: 0.5936 - rmse: 0.8486

204/269 ━━━━━━━━━━━━━━━━━━━━ 49s 766ms/step - loss: 0.7312 - mae: 0.5931 - rmse: 0.8479

205/269 ━━━━━━━━━━━━━━━━━━━━ 48s 764ms/step - loss: 0.7301 - mae: 0.5925 - rmse: 0.8472

206/269 ━━━━━━━━━━━━━━━━━━━━ 48s 763ms/step - loss: 0.7290 - mae: 0.5919 - rmse: 0.8465

207/269 ━━━━━━━━━━━━━━━━━━━━ 47s 761ms/step - loss: 0.7279 - mae: 0.5914 - rmse: 0.8458

208/269 ━━━━━━━━━━━━━━━━━━━━ 46s 760ms/step - loss: 0.7268 - mae: 0.5908 - rmse: 0.8451

209/269 ━━━━━━━━━━━━━━━━━━━━ 45s 758ms/step - loss: 0.7256 - mae: 0.5902 - rmse: 0.8445

210/269 ━━━━━━━━━━━━━━━━━━━━ 44s 756ms/step - loss: 0.7245 - mae: 0.5897 - rmse: 0.8438

211/269 ━━━━━━━━━━━━━━━━━━━━ 43s 756ms/step - loss: 0.7234 - mae: 0.5891 - rmse: 0.8431

212/269 ━━━━━━━━━━━━━━━━━━━━ 43s 755ms/step - loss: 0.7223 - mae: 0.5885 - rmse: 0.8424

213/269 ━━━━━━━━━━━━━━━━━━━━ 42s 754ms/step - loss: 0.7212 - mae: 0.5880 - rmse: 0.8417

214/269 ━━━━━━━━━━━━━━━━━━━━ 41s 754ms/step - loss: 0.7201 - mae: 0.5874 - rmse: 0.8410

215/269 ━━━━━━━━━━━━━━━━━━━━ 40s 754ms/step - loss: 0.7190 - mae: 0.5869 - rmse: 0.8403

216/269 ━━━━━━━━━━━━━━━━━━━━ 39s 755ms/step - loss: 0.7179 - mae: 0.5863 - rmse: 0.8396

217/269 ━━━━━━━━━━━━━━━━━━━━ 39s 755ms/step - loss: 0.7168 - mae: 0.5857 - rmse: 0.8389

218/269 ━━━━━━━━━━━━━━━━━━━━ 38s 755ms/step - loss: 0.7157 - mae: 0.5852 - rmse: 0.8382

219/269 ━━━━━━━━━━━━━━━━━━━━ 37s 755ms/step - loss: 0.7146 - mae: 0.5846 - rmse: 0.8375

220/269 ━━━━━━━━━━━━━━━━━━━━ 36s 755ms/step - loss: 0.7136 - mae: 0.5841 - rmse: 0.8368

221/269 ━━━━━━━━━━━━━━━━━━━━ 36s 755ms/step - loss: 0.7125 - mae: 0.5835 - rmse: 0.8362

222/269 ━━━━━━━━━━━━━━━━━━━━ 35s 755ms/step - loss: 0.7114 - mae: 0.5830 - rmse: 0.8355

223/269 ━━━━━━━━━━━━━━━━━━━━ 34s 755ms/step - loss: 0.7103 - mae: 0.5824 - rmse: 0.8348

224/269 ━━━━━━━━━━━━━━━━━━━━ 33s 755ms/step - loss: 0.7092 - mae: 0.5819 - rmse: 0.8341

225/269 ━━━━━━━━━━━━━━━━━━━━ 33s 756ms/step - loss: 0.7081 - mae: 0.5813 - rmse: 0.8334

226/269 ━━━━━━━━━━━━━━━━━━━━ 32s 757ms/step - loss: 0.7071 - mae: 0.5808 - rmse: 0.8327

227/269 ━━━━━━━━━━━━━━━━━━━━ 31s 757ms/step - loss: 0.7060 - mae: 0.5802 - rmse: 0.8321

228/269 ━━━━━━━━━━━━━━━━━━━━ 31s 756ms/step - loss: 0.7049 - mae: 0.5797 - rmse: 0.8314

229/269 ━━━━━━━━━━━━━━━━━━━━ 30s 757ms/step - loss: 0.7038 - mae: 0.5791 - rmse: 0.8307

230/269 ━━━━━━━━━━━━━━━━━━━━ 29s 757ms/step - loss: 0.7028 - mae: 0.5786 - rmse: 0.8300

231/269 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 0.7017 - mae: 0.5780 - rmse: 0.8293

232/269 ━━━━━━━━━━━━━━━━━━━━ 27s 756ms/step - loss: 0.7006 - mae: 0.5775 - rmse: 0.8286

233/269 ━━━━━━━━━━━━━━━━━━━━ 27s 757ms/step - loss: 0.6996 - mae: 0.5769 - rmse: 0.8280

234/269 ━━━━━━━━━━━━━━━━━━━━ 26s 758ms/step - loss: 0.6985 - mae: 0.5764 - rmse: 0.8273

235/269 ━━━━━━━━━━━━━━━━━━━━ 25s 758ms/step - loss: 0.6975 - mae: 0.5758 - rmse: 0.8266

236/269 ━━━━━━━━━━━━━━━━━━━━ 25s 758ms/step - loss: 0.6964 - mae: 0.5753 - rmse: 0.8259

237/269 ━━━━━━━━━━━━━━━━━━━━ 24s 757ms/step - loss: 0.6954 - mae: 0.5747 - rmse: 0.8252

238/269 ━━━━━━━━━━━━━━━━━━━━ 23s 757ms/step - loss: 0.6943 - mae: 0.5742 - rmse: 0.8246

239/269 ━━━━━━━━━━━━━━━━━━━━ 22s 757ms/step - loss: 0.6933 - mae: 0.5736 - rmse: 0.8239

240/269 ━━━━━━━━━━━━━━━━━━━━ 21s 757ms/step - loss: 0.6922 - mae: 0.5731 - rmse: 0.8232

241/269 ━━━━━━━━━━━━━━━━━━━━ 21s 759ms/step - loss: 0.6912 - mae: 0.5726 - rmse: 0.8226

242/269 ━━━━━━━━━━━━━━━━━━━━ 20s 759ms/step - loss: 0.6902 - mae: 0.5720 - rmse: 0.8219

243/269 ━━━━━━━━━━━━━━━━━━━━ 19s 761ms/step - loss: 0.6891 - mae: 0.5715 - rmse: 0.8212

244/269 ━━━━━━━━━━━━━━━━━━━━ 19s 761ms/step - loss: 0.6881 - mae: 0.5710 - rmse: 0.8206

245/269 ━━━━━━━━━━━━━━━━━━━━ 18s 760ms/step - loss: 0.6871 - mae: 0.5704 - rmse: 0.8199

246/269 ━━━━━━━━━━━━━━━━━━━━ 17s 761ms/step - loss: 0.6861 - mae: 0.5699 - rmse: 0.8193

247/269 ━━━━━━━━━━━━━━━━━━━━ 16s 760ms/step - loss: 0.6851 - mae: 0.5694 - rmse: 0.8186

248/269 ━━━━━━━━━━━━━━━━━━━━ 15s 760ms/step - loss: 0.6841 - mae: 0.5689 - rmse: 0.8179

249/269 ━━━━━━━━━━━━━━━━━━━━ 15s 759ms/step - loss: 0.6831 - mae: 0.5683 - rmse: 0.8173

250/269 ━━━━━━━━━━━━━━━━━━━━ 14s 758ms/step - loss: 0.6821 - mae: 0.5678 - rmse: 0.8166

251/269 ━━━━━━━━━━━━━━━━━━━━ 13s 757ms/step - loss: 0.6811 - mae: 0.5673 - rmse: 0.8160

252/269 ━━━━━━━━━━━━━━━━━━━━ 12s 756ms/step - loss: 0.6801 - mae: 0.5668 - rmse: 0.8153

253/269 ━━━━━━━━━━━━━━━━━━━━ 12s 754ms/step - loss: 0.6791 - mae: 0.5663 - rmse: 0.8147

254/269 ━━━━━━━━━━━━━━━━━━━━ 11s 752ms/step - loss: 0.6781 - mae: 0.5657 - rmse: 0.8140

255/269 ━━━━━━━━━━━━━━━━━━━━ 10s 751ms/step - loss: 0.6771 - mae: 0.5652 - rmse: 0.8134

256/269 ━━━━━━━━━━━━━━━━━━━━ 9s 749ms/step - loss: 0.6761 - mae: 0.5647 - rmse: 0.8128

257/269 ━━━━━━━━━━━━━━━━━━━━ 8s 747ms/step - loss: 0.6751 - mae: 0.5642 - rmse: 0.8121

258/269 ━━━━━━━━━━━━━━━━━━━━ 8s 746ms/step - loss: 0.6741 - mae: 0.5637 - rmse: 0.8115

259/269 ━━━━━━━━━━━━━━━━━━━━ 7s 744ms/step - loss: 0.6732 - mae: 0.5632 - rmse: 0.8108

260/269 ━━━━━━━━━━━━━━━━━━━━ 6s 743ms/step - loss: 0.6722 - mae: 0.5627 - rmse: 0.8102

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 741ms/step - loss: 0.6712 - mae: 0.5622 - rmse: 0.8096

262/269 ━━━━━━━━━━━━━━━━━━━━ 5s 739ms/step - loss: 0.6702 - mae: 0.5617 - rmse: 0.8089

263/269 ━━━━━━━━━━━━━━━━━━━━ 4s 737ms/step - loss: 0.6693 - mae: 0.5612 - rmse: 0.8083

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 736ms/step - loss: 0.6683 - mae: 0.5607 - rmse: 0.8076

265/269 ━━━━━━━━━━━━━━━━━━━━ 2s 734ms/step - loss: 0.6674 - mae: 0.5602 - rmse: 0.8070

266/269 ━━━━━━━━━━━━━━━━━━━━ 2s 734ms/step - loss: 0.6664 - mae: 0.5597 - rmse: 0.8064

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 733ms/step - loss: 0.6654 - mae: 0.5592 - rmse: 0.8058

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 732ms/step - loss: 0.6645 - mae: 0.5587 - rmse: 0.8051

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 729ms/step - loss: 0.6636 - mae: 0.5582 - rmse: 0.8045

269/269 ━━━━━━━━━━━━━━━━━━━━ 217s 805ms/step - loss: 0.4113 - mae: 0.4262 - rmse: 0.6380 - val_loss: 0.7138 - val_mae: 0.5194 - val_rmse: 0.8424 - learning_rate: 0.0010

Epoch 12/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 6:34 1s/step - loss: 0.8691 - mae: 0.6604 - rmse: 0.9300

  2/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.7807 - mae: 0.6334 - rmse: 0.8798

  3/269 ━━━━━━━━━━━━━━━━━━━━ 3:52 873ms/step - loss: 0.7729 - mae: 0.6362 - rmse: 0.8758

  4/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 849ms/step - loss: 0.7578 - mae: 0.6331 - rmse: 0.8673

  5/269 ━━━━━━━━━━━━━━━━━━━━ 4:07 939ms/step - loss: 0.7325 - mae: 0.6235 - rmse: 0.8522

  6/269 ━━━━━━━━━━━━━━━━━━━━ 4:09 949ms/step - loss: 0.7158 - mae: 0.6175 - rmse: 0.8423

  7/269 ━━━━━━━━━━━━━━━━━━━━ 4:22 1s/step - loss: 0.7113 - mae: 0.6159 - rmse: 0.8398

  8/269 ━━━━━━━━━━━━━━━━━━━━ 4:29 1s/step - loss: 0.7200 - mae: 0.6192 - rmse: 0.8449

  9/269 ━━━━━━━━━━━━━━━━━━━━ 4:14 978ms/step - loss: 0.7240 - mae: 0.6205 - rmse: 0.8474

 10/269 ━━━━━━━━━━━━━━━━━━━━ 4:06 950ms/step - loss: 0.7231 - mae: 0.6197 - rmse: 0.8470

 11/269 ━━━━━━━━━━━━━━━━━━━━ 4:01 936ms/step - loss: 0.7203 - mae: 0.6182 - rmse: 0.8454

 12/269 ━━━━━━━━━━━━━━━━━━━━ 3:59 931ms/step - loss: 0.7258 - mae: 0.6197 - rmse: 0.8487

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:55 920ms/step - loss: 0.7366 - mae: 0.6223 - rmse: 0.8548

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:55 925ms/step - loss: 0.7535 - mae: 0.6272 - rmse: 0.8641

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:59 942ms/step - loss: 0.7685 - mae: 0.6317 - rmse: 0.8722

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:57 938ms/step - loss: 0.7840 - mae: 0.6366 - rmse: 0.8806

 17/269 ━━━━━━━━━━━━━━━━━━━━ 3:54 932ms/step - loss: 0.7997 - mae: 0.6411 - rmse: 0.8890

 18/269 ━━━━━━━━━━━━━━━━━━━━ 3:51 921ms/step - loss: 0.8127 - mae: 0.6450 - rmse: 0.8960

 19/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 921ms/step - loss: 0.8262 - mae: 0.6487 - rmse: 0.9031

 20/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 925ms/step - loss: 0.8381 - mae: 0.6521 - rmse: 0.9095

 21/269 ━━━━━━━━━━━━━━━━━━━━ 3:51 931ms/step - loss: 0.8474 - mae: 0.6546 - rmse: 0.9145

 22/269 ━━━━━━━━━━━━━━━━━━━━ 3:53 945ms/step - loss: 0.8559 - mae: 0.6570 - rmse: 0.9190

 23/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 935ms/step - loss: 0.8645 - mae: 0.6596 - rmse: 0.9236

 24/269 ━━━━━━━━━━━━━━━━━━━━ 3:49 935ms/step - loss: 0.8720 - mae: 0.6619 - rmse: 0.9276

 25/269 ━━━━━━━━━━━━━━━━━━━━ 3:46 930ms/step - loss: 0.8781 - mae: 0.6638 - rmse: 0.9310

 26/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 930ms/step - loss: 0.8842 - mae: 0.6655 - rmse: 0.9342

 27/269 ━━━━━━━━━━━━━━━━━━━━ 3:47 938ms/step - loss: 0.8889 - mae: 0.6668 - rmse: 0.9368

 28/269 ━━━━━━━━━━━━━━━━━━━━ 3:44 932ms/step - loss: 0.8926 - mae: 0.6679 - rmse: 0.9388

 29/269 ━━━━━━━━━━━━━━━━━━━━ 3:40 919ms/step - loss: 0.8958 - mae: 0.6688 - rmse: 0.9406

 30/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 914ms/step - loss: 0.8980 - mae: 0.6693 - rmse: 0.9419

 31/269 ━━━━━━━━━━━━━━━━━━━━ 3:35 906ms/step - loss: 0.8996 - mae: 0.6696 - rmse: 0.9428

 32/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 893ms/step - loss: 0.9007 - mae: 0.6698 - rmse: 0.9435

 33/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 878ms/step - loss: 0.9014 - mae: 0.6699 - rmse: 0.9440

 34/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 862ms/step - loss: 0.9018 - mae: 0.6699 - rmse: 0.9443

 35/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 847ms/step - loss: 0.9021 - mae: 0.6699 - rmse: 0.9445

 36/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 832ms/step - loss: 0.9021 - mae: 0.6698 - rmse: 0.9446

 37/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 820ms/step - loss: 0.9019 - mae: 0.6697 - rmse: 0.9446

 38/269 ━━━━━━━━━━━━━━━━━━━━ 3:06 809ms/step - loss: 0.9013 - mae: 0.6694 - rmse: 0.9444

 39/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 797ms/step - loss: 0.9005 - mae: 0.6690 - rmse: 0.9440

 40/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 786ms/step - loss: 0.8994 - mae: 0.6686 - rmse: 0.9435

 41/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 775ms/step - loss: 0.8985 - mae: 0.6682 - rmse: 0.9431

 42/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 764ms/step - loss: 0.8972 - mae: 0.6676 - rmse: 0.9425

 43/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 753ms/step - loss: 0.8960 - mae: 0.6671 - rmse: 0.9418

 44/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 743ms/step - loss: 0.8948 - mae: 0.6667 - rmse: 0.9413

 45/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 733ms/step - loss: 0.8936 - mae: 0.6662 - rmse: 0.9406

 46/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 725ms/step - loss: 0.8921 - mae: 0.6656 - rmse: 0.9399

 47/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 719ms/step - loss: 0.8907 - mae: 0.6651 - rmse: 0.9392

 48/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 722ms/step - loss: 0.8892 - mae: 0.6646 - rmse: 0.9385

 49/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 728ms/step - loss: 0.8876 - mae: 0.6639 - rmse: 0.9376

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 730ms/step - loss: 0.8858 - mae: 0.6632 - rmse: 0.9367

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 727ms/step - loss: 0.8839 - mae: 0.6625 - rmse: 0.9357

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 732ms/step - loss: 0.8820 - mae: 0.6617 - rmse: 0.9347

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 733ms/step - loss: 0.8800 - mae: 0.6609 - rmse: 0.9336

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 737ms/step - loss: 0.8782 - mae: 0.6603 - rmse: 0.9327

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 736ms/step - loss: 0.8764 - mae: 0.6595 - rmse: 0.9317

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 734ms/step - loss: 0.8746 - mae: 0.6589 - rmse: 0.9308

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 735ms/step - loss: 0.8728 - mae: 0.6582 - rmse: 0.9298

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 737ms/step - loss: 0.8709 - mae: 0.6574 - rmse: 0.9288

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:34 735ms/step - loss: 0.8693 - mae: 0.6568 - rmse: 0.9279

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 732ms/step - loss: 0.8675 - mae: 0.6562 - rmse: 0.9270

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 730ms/step - loss: 0.8659 - mae: 0.6556 - rmse: 0.9261

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:30 728ms/step - loss: 0.8643 - mae: 0.6550 - rmse: 0.9253

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 726ms/step - loss: 0.8627 - mae: 0.6544 - rmse: 0.9244

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 728ms/step - loss: 0.8610 - mae: 0.6538 - rmse: 0.9235

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 731ms/step - loss: 0.8592 - mae: 0.6532 - rmse: 0.9226

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 730ms/step - loss: 0.8574 - mae: 0.6525 - rmse: 0.9216

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 733ms/step - loss: 0.8555 - mae: 0.6518 - rmse: 0.9206

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 731ms/step - loss: 0.8537 - mae: 0.6511 - rmse: 0.9195

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 733ms/step - loss: 0.8519 - mae: 0.6504 - rmse: 0.9186

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 736ms/step - loss: 0.8501 - mae: 0.6498 - rmse: 0.9176

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 734ms/step - loss: 0.8485 - mae: 0.6492 - rmse: 0.9167

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 733ms/step - loss: 0.8469 - mae: 0.6486 - rmse: 0.9158

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 742ms/step - loss: 0.8453 - mae: 0.6480 - rmse: 0.9150

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 752ms/step - loss: 0.8439 - mae: 0.6474 - rmse: 0.9142

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 759ms/step - loss: 0.8425 - mae: 0.6469 - rmse: 0.9134

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 761ms/step - loss: 0.8411 - mae: 0.6464 - rmse: 0.9127

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 763ms/step - loss: 0.8398 - mae: 0.6459 - rmse: 0.9120

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 762ms/step - loss: 0.8386 - mae: 0.6455 - rmse: 0.9113

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 761ms/step - loss: 0.8374 - mae: 0.6450 - rmse: 0.9107

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 761ms/step - loss: 0.8363 - mae: 0.6446 - rmse: 0.9101

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 761ms/step - loss: 0.8354 - mae: 0.6443 - rmse: 0.9096

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 759ms/step - loss: 0.8349 - mae: 0.6441 - rmse: 0.9094

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 756ms/step - loss: 0.8345 - mae: 0.6440 - rmse: 0.9092

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 755ms/step - loss: 0.8342 - mae: 0.6438 - rmse: 0.9090

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 753ms/step - loss: 0.8340 - mae: 0.6437 - rmse: 0.9090

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 753ms/step - loss: 0.8339 - mae: 0.6437 - rmse: 0.9089

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 755ms/step - loss: 0.8339 - mae: 0.6436 - rmse: 0.9089

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 754ms/step - loss: 0.8338 - mae: 0.6436 - rmse: 0.9089

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 757ms/step - loss: 0.8337 - mae: 0.6436 - rmse: 0.9089

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 762ms/step - loss: 0.8337 - mae: 0.6435 - rmse: 0.9089

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 766ms/step - loss: 0.8336 - mae: 0.6435 - rmse: 0.9088

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 771ms/step - loss: 0.8334 - mae: 0.6434 - rmse: 0.9088

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 779ms/step - loss: 0.8332 - mae: 0.6433 - rmse: 0.9087

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 783ms/step - loss: 0.8329 - mae: 0.6432 - rmse: 0.9085

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 785ms/step - loss: 0.8326 - mae: 0.6431 - rmse: 0.9084

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 788ms/step - loss: 0.8322 - mae: 0.6429 - rmse: 0.9082

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 790ms/step - loss: 0.8318 - mae: 0.6427 - rmse: 0.9079

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 795ms/step - loss: 0.8313 - mae: 0.6426 - rmse: 0.9077

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 801ms/step - loss: 0.8308 - mae: 0.6424 - rmse: 0.9075

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 800ms/step - loss: 0.8303 - mae: 0.6421 - rmse: 0.9072

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 799ms/step - loss: 0.8298 - mae: 0.6419 - rmse: 0.9069

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 798ms/step - loss: 0.8292 - mae: 0.6417 - rmse: 0.9066

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 797ms/step - loss: 0.8287 - mae: 0.6415 - rmse: 0.9063

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 797ms/step - loss: 0.8281 - mae: 0.6413 - rmse: 0.9060

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 797ms/step - loss: 0.8275 - mae: 0.6410 - rmse: 0.9057

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 797ms/step - loss: 0.8269 - mae: 0.6408 - rmse: 0.9054

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 798ms/step - loss: 0.8263 - mae: 0.6405 - rmse: 0.9050

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 799ms/step - loss: 0.8256 - mae: 0.6403 - rmse: 0.9047

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 802ms/step - loss: 0.8248 - mae: 0.6399 - rmse: 0.9043

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 804ms/step - loss: 0.8240 - mae: 0.6396 - rmse: 0.9038

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 809ms/step - loss: 0.8232 - mae: 0.6393 - rmse: 0.9034

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 807ms/step - loss: 0.8224 - mae: 0.6389 - rmse: 0.9029

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 809ms/step - loss: 0.8215 - mae: 0.6385 - rmse: 0.9024

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 808ms/step - loss: 0.8206 - mae: 0.6381 - rmse: 0.9019

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 806ms/step - loss: 0.8197 - mae: 0.6377 - rmse: 0.9014

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 805ms/step - loss: 0.8188 - mae: 0.6373 - rmse: 0.9009

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 801ms/step - loss: 0.8178 - mae: 0.6368 - rmse: 0.9004

118/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 798ms/step - loss: 0.8168 - mae: 0.6364 - rmse: 0.8998

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 795ms/step - loss: 0.8158 - mae: 0.6359 - rmse: 0.8992

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 791ms/step - loss: 0.8148 - mae: 0.6355 - rmse: 0.8987

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 788ms/step - loss: 0.8137 - mae: 0.6350 - rmse: 0.8981

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 785ms/step - loss: 0.8127 - mae: 0.6345 - rmse: 0.8975

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 782ms/step - loss: 0.8116 - mae: 0.6340 - rmse: 0.8969

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 779ms/step - loss: 0.8105 - mae: 0.6335 - rmse: 0.8962

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 776ms/step - loss: 0.8094 - mae: 0.6329 - rmse: 0.8956

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 772ms/step - loss: 0.8082 - mae: 0.6324 - rmse: 0.8949

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 768ms/step - loss: 0.8071 - mae: 0.6318 - rmse: 0.8943

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 764ms/step - loss: 0.8059 - mae: 0.6313 - rmse: 0.8936

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 760ms/step - loss: 0.8047 - mae: 0.6307 - rmse: 0.8929

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 757ms/step - loss: 0.8036 - mae: 0.6302 - rmse: 0.8923

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 755ms/step - loss: 0.8024 - mae: 0.6296 - rmse: 0.8916

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 753ms/step - loss: 0.8012 - mae: 0.6290 - rmse: 0.8909

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 752ms/step - loss: 0.8000 - mae: 0.6285 - rmse: 0.8902

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 750ms/step - loss: 0.7988 - mae: 0.6279 - rmse: 0.8895

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 749ms/step - loss: 0.7976 - mae: 0.6273 - rmse: 0.8888

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 747ms/step - loss: 0.7964 - mae: 0.6268 - rmse: 0.8881

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 745ms/step - loss: 0.7952 - mae: 0.6262 - rmse: 0.8874

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 744ms/step - loss: 0.7941 - mae: 0.6256 - rmse: 0.8867

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 745ms/step - loss: 0.7928 - mae: 0.6251 - rmse: 0.8860

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 745ms/step - loss: 0.7916 - mae: 0.6245 - rmse: 0.8853

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 744ms/step - loss: 0.7904 - mae: 0.6239 - rmse: 0.8846

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 744ms/step - loss: 0.7892 - mae: 0.6233 - rmse: 0.8839

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 746ms/step - loss: 0.7879 - mae: 0.6227 - rmse: 0.8831

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 748ms/step - loss: 0.7867 - mae: 0.6221 - rmse: 0.8824

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 752ms/step - loss: 0.7854 - mae: 0.6215 - rmse: 0.8817

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 754ms/step - loss: 0.7842 - mae: 0.6209 - rmse: 0.8809

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 753ms/step - loss: 0.7829 - mae: 0.6203 - rmse: 0.8802

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 753ms/step - loss: 0.7816 - mae: 0.6196 - rmse: 0.8794

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 754ms/step - loss: 0.7803 - mae: 0.6190 - rmse: 0.8786

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 753ms/step - loss: 0.7790 - mae: 0.6183 - rmse: 0.8779

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 751ms/step - loss: 0.7777 - mae: 0.6177 - rmse: 0.8771

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 750ms/step - loss: 0.7765 - mae: 0.6171 - rmse: 0.8763

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 748ms/step - loss: 0.7752 - mae: 0.6164 - rmse: 0.8756

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 747ms/step - loss: 0.7739 - mae: 0.6158 - rmse: 0.8748

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 745ms/step - loss: 0.7726 - mae: 0.6151 - rmse: 0.8740

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 743ms/step - loss: 0.7713 - mae: 0.6145 - rmse: 0.8732

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 742ms/step - loss: 0.7700 - mae: 0.6139 - rmse: 0.8725

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 741ms/step - loss: 0.7687 - mae: 0.6132 - rmse: 0.8717

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 741ms/step - loss: 0.7674 - mae: 0.6126 - rmse: 0.8709

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 741ms/step - loss: 0.7661 - mae: 0.6119 - rmse: 0.8701

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 740ms/step - loss: 0.7648 - mae: 0.6113 - rmse: 0.8693

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 739ms/step - loss: 0.7635 - mae: 0.6106 - rmse: 0.8685

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 738ms/step - loss: 0.7622 - mae: 0.6100 - rmse: 0.8677

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 740ms/step - loss: 0.7609 - mae: 0.6093 - rmse: 0.8670

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 740ms/step - loss: 0.7596 - mae: 0.6087 - rmse: 0.8662

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 740ms/step - loss: 0.7584 - mae: 0.6080 - rmse: 0.8654

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 739ms/step - loss: 0.7571 - mae: 0.6074 - rmse: 0.8646

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 739ms/step - loss: 0.7558 - mae: 0.6067 - rmse: 0.8639

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 738ms/step - loss: 0.7546 - mae: 0.6061 - rmse: 0.8631

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 738ms/step - loss: 0.7533 - mae: 0.6055 - rmse: 0.8623

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 737ms/step - loss: 0.7521 - mae: 0.6049 - rmse: 0.8616

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 739ms/step - loss: 0.7509 - mae: 0.6043 - rmse: 0.8609

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 740ms/step - loss: 0.7497 - mae: 0.6037 - rmse: 0.8601

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 739ms/step - loss: 0.7485 - mae: 0.6031 - rmse: 0.8594

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 739ms/step - loss: 0.7474 - mae: 0.6026 - rmse: 0.8587

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 739ms/step - loss: 0.7462 - mae: 0.6020 - rmse: 0.8580

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 738ms/step - loss: 0.7450 - mae: 0.6014 - rmse: 0.8573

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 738ms/step - loss: 0.7438 - mae: 0.6008 - rmse: 0.8565

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 737ms/step - loss: 0.7427 - mae: 0.6003 - rmse: 0.8558

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 737ms/step - loss: 0.7415 - mae: 0.5997 - rmse: 0.8551

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 736ms/step - loss: 0.7403 - mae: 0.5991 - rmse: 0.8544

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 736ms/step - loss: 0.7391 - mae: 0.5985 - rmse: 0.8537

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 736ms/step - loss: 0.7380 - mae: 0.5980 - rmse: 0.8529

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 736ms/step - loss: 0.7368 - mae: 0.5974 - rmse: 0.8522

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 736ms/step - loss: 0.7356 - mae: 0.5968 - rmse: 0.8515

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 736ms/step - loss: 0.7345 - mae: 0.5962 - rmse: 0.8508

187/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 736ms/step - loss: 0.7333 - mae: 0.5956 - rmse: 0.8500

188/269 ━━━━━━━━━━━━━━━━━━━━ 59s 737ms/step - loss: 0.7321 - mae: 0.5950 - rmse: 0.8493

189/269 ━━━━━━━━━━━━━━━━━━━━ 59s 739ms/step - loss: 0.7310 - mae: 0.5945 - rmse: 0.8486

190/269 ━━━━━━━━━━━━━━━━━━━━ 58s 739ms/step - loss: 0.7298 - mae: 0.5939 - rmse: 0.8479

191/269 ━━━━━━━━━━━━━━━━━━━━ 57s 739ms/step - loss: 0.7286 - mae: 0.5933 - rmse: 0.8471

192/269 ━━━━━━━━━━━━━━━━━━━━ 56s 739ms/step - loss: 0.7275 - mae: 0.5927 - rmse: 0.8464

193/269 ━━━━━━━━━━━━━━━━━━━━ 56s 739ms/step - loss: 0.7263 - mae: 0.5921 - rmse: 0.8457

194/269 ━━━━━━━━━━━━━━━━━━━━ 55s 739ms/step - loss: 0.7251 - mae: 0.5915 - rmse: 0.8450

195/269 ━━━━━━━━━━━━━━━━━━━━ 54s 739ms/step - loss: 0.7240 - mae: 0.5909 - rmse: 0.8442

196/269 ━━━━━━━━━━━━━━━━━━━━ 53s 738ms/step - loss: 0.7228 - mae: 0.5904 - rmse: 0.8435

197/269 ━━━━━━━━━━━━━━━━━━━━ 53s 738ms/step - loss: 0.7217 - mae: 0.5898 - rmse: 0.8428

198/269 ━━━━━━━━━━━━━━━━━━━━ 52s 737ms/step - loss: 0.7205 - mae: 0.5892 - rmse: 0.8421

199/269 ━━━━━━━━━━━━━━━━━━━━ 51s 736ms/step - loss: 0.7194 - mae: 0.5886 - rmse: 0.8414

200/269 ━━━━━━━━━━━━━━━━━━━━ 50s 735ms/step - loss: 0.7182 - mae: 0.5880 - rmse: 0.8406

201/269 ━━━━━━━━━━━━━━━━━━━━ 50s 735ms/step - loss: 0.7171 - mae: 0.5875 - rmse: 0.8399

202/269 ━━━━━━━━━━━━━━━━━━━━ 49s 736ms/step - loss: 0.7160 - mae: 0.5869 - rmse: 0.8392

203/269 ━━━━━━━━━━━━━━━━━━━━ 48s 734ms/step - loss: 0.7149 - mae: 0.5863 - rmse: 0.8385

204/269 ━━━━━━━━━━━━━━━━━━━━ 47s 733ms/step - loss: 0.7138 - mae: 0.5858 - rmse: 0.8378

205/269 ━━━━━━━━━━━━━━━━━━━━ 46s 732ms/step - loss: 0.7127 - mae: 0.5852 - rmse: 0.8372

206/269 ━━━━━━━━━━━━━━━━━━━━ 46s 731ms/step - loss: 0.7116 - mae: 0.5846 - rmse: 0.8365

207/269 ━━━━━━━━━━━━━━━━━━━━ 45s 730ms/step - loss: 0.7105 - mae: 0.5841 - rmse: 0.8358

208/269 ━━━━━━━━━━━━━━━━━━━━ 44s 728ms/step - loss: 0.7094 - mae: 0.5835 - rmse: 0.8351

209/269 ━━━━━━━━━━━━━━━━━━━━ 43s 726ms/step - loss: 0.7083 - mae: 0.5830 - rmse: 0.8344

210/269 ━━━━━━━━━━━━━━━━━━━━ 42s 724ms/step - loss: 0.7073 - mae: 0.5824 - rmse: 0.8337

211/269 ━━━━━━━━━━━━━━━━━━━━ 41s 722ms/step - loss: 0.7062 - mae: 0.5819 - rmse: 0.8330

212/269 ━━━━━━━━━━━━━━━━━━━━ 41s 720ms/step - loss: 0.7051 - mae: 0.5813 - rmse: 0.8324

213/269 ━━━━━━━━━━━━━━━━━━━━ 40s 718ms/step - loss: 0.7040 - mae: 0.5808 - rmse: 0.8317

214/269 ━━━━━━━━━━━━━━━━━━━━ 39s 716ms/step - loss: 0.7030 - mae: 0.5802 - rmse: 0.8310

215/269 ━━━━━━━━━━━━━━━━━━━━ 38s 715ms/step - loss: 0.7019 - mae: 0.5797 - rmse: 0.8303

216/269 ━━━━━━━━━━━━━━━━━━━━ 37s 713ms/step - loss: 0.7008 - mae: 0.5792 - rmse: 0.8296

217/269 ━━━━━━━━━━━━━━━━━━━━ 36s 711ms/step - loss: 0.6998 - mae: 0.5786 - rmse: 0.8290

218/269 ━━━━━━━━━━━━━━━━━━━━ 36s 709ms/step - loss: 0.6987 - mae: 0.5781 - rmse: 0.8283

219/269 ━━━━━━━━━━━━━━━━━━━━ 35s 708ms/step - loss: 0.6977 - mae: 0.5775 - rmse: 0.8276

220/269 ━━━━━━━━━━━━━━━━━━━━ 34s 707ms/step - loss: 0.6966 - mae: 0.5770 - rmse: 0.8269

221/269 ━━━━━━━━━━━━━━━━━━━━ 33s 706ms/step - loss: 0.6956 - mae: 0.5765 - rmse: 0.8263

222/269 ━━━━━━━━━━━━━━━━━━━━ 33s 706ms/step - loss: 0.6945 - mae: 0.5759 - rmse: 0.8256

223/269 ━━━━━━━━━━━━━━━━━━━━ 32s 707ms/step - loss: 0.6935 - mae: 0.5754 - rmse: 0.8249

224/269 ━━━━━━━━━━━━━━━━━━━━ 31s 706ms/step - loss: 0.6924 - mae: 0.5749 - rmse: 0.8243

225/269 ━━━━━━━━━━━━━━━━━━━━ 31s 706ms/step - loss: 0.6914 - mae: 0.5743 - rmse: 0.8236

226/269 ━━━━━━━━━━━━━━━━━━━━ 30s 707ms/step - loss: 0.6903 - mae: 0.5738 - rmse: 0.8229

227/269 ━━━━━━━━━━━━━━━━━━━━ 29s 707ms/step - loss: 0.6893 - mae: 0.5732 - rmse: 0.8222

228/269 ━━━━━━━━━━━━━━━━━━━━ 29s 708ms/step - loss: 0.6882 - mae: 0.5727 - rmse: 0.8216

229/269 ━━━━━━━━━━━━━━━━━━━━ 28s 707ms/step - loss: 0.6872 - mae: 0.5722 - rmse: 0.8209

230/269 ━━━━━━━━━━━━━━━━━━━━ 27s 707ms/step - loss: 0.6861 - mae: 0.5716 - rmse: 0.8202

231/269 ━━━━━━━━━━━━━━━━━━━━ 26s 707ms/step - loss: 0.6851 - mae: 0.5711 - rmse: 0.8195

232/269 ━━━━━━━━━━━━━━━━━━━━ 26s 707ms/step - loss: 0.6841 - mae: 0.5705 - rmse: 0.8189

233/269 ━━━━━━━━━━━━━━━━━━━━ 25s 706ms/step - loss: 0.6830 - mae: 0.5700 - rmse: 0.8182

234/269 ━━━━━━━━━━━━━━━━━━━━ 24s 707ms/step - loss: 0.6820 - mae: 0.5695 - rmse: 0.8175

235/269 ━━━━━━━━━━━━━━━━━━━━ 24s 709ms/step - loss: 0.6810 - mae: 0.5689 - rmse: 0.8169

236/269 ━━━━━━━━━━━━━━━━━━━━ 23s 713ms/step - loss: 0.6800 - mae: 0.5684 - rmse: 0.8162

237/269 ━━━━━━━━━━━━━━━━━━━━ 22s 716ms/step - loss: 0.6789 - mae: 0.5679 - rmse: 0.8155

238/269 ━━━━━━━━━━━━━━━━━━━━ 22s 718ms/step - loss: 0.6779 - mae: 0.5673 - rmse: 0.8149

239/269 ━━━━━━━━━━━━━━━━━━━━ 21s 718ms/step - loss: 0.6769 - mae: 0.5668 - rmse: 0.8142

240/269 ━━━━━━━━━━━━━━━━━━━━ 20s 720ms/step - loss: 0.6759 - mae: 0.5663 - rmse: 0.8136

241/269 ━━━━━━━━━━━━━━━━━━━━ 20s 721ms/step - loss: 0.6749 - mae: 0.5657 - rmse: 0.8129

242/269 ━━━━━━━━━━━━━━━━━━━━ 19s 722ms/step - loss: 0.6739 - mae: 0.5652 - rmse: 0.8123

243/269 ━━━━━━━━━━━━━━━━━━━━ 18s 723ms/step - loss: 0.6729 - mae: 0.5647 - rmse: 0.8116

244/269 ━━━━━━━━━━━━━━━━━━━━ 18s 725ms/step - loss: 0.6719 - mae: 0.5642 - rmse: 0.8110

245/269 ━━━━━━━━━━━━━━━━━━━━ 17s 727ms/step - loss: 0.6709 - mae: 0.5637 - rmse: 0.8103

246/269 ━━━━━━━━━━━━━━━━━━━━ 16s 729ms/step - loss: 0.6699 - mae: 0.5631 - rmse: 0.8097

247/269 ━━━━━━━━━━━━━━━━━━━━ 16s 730ms/step - loss: 0.6690 - mae: 0.5626 - rmse: 0.8090

248/269 ━━━━━━━━━━━━━━━━━━━━ 15s 731ms/step - loss: 0.6680 - mae: 0.5621 - rmse: 0.8084

249/269 ━━━━━━━━━━━━━━━━━━━━ 14s 734ms/step - loss: 0.6670 - mae: 0.5616 - rmse: 0.8077

250/269 ━━━━━━━━━━━━━━━━━━━━ 13s 735ms/step - loss: 0.6660 - mae: 0.5611 - rmse: 0.8071

251/269 ━━━━━━━━━━━━━━━━━━━━ 13s 736ms/step - loss: 0.6650 - mae: 0.5606 - rmse: 0.8064

252/269 ━━━━━━━━━━━━━━━━━━━━ 12s 736ms/step - loss: 0.6641 - mae: 0.5601 - rmse: 0.8058

253/269 ━━━━━━━━━━━━━━━━━━━━ 11s 736ms/step - loss: 0.6631 - mae: 0.5596 - rmse: 0.8052

254/269 ━━━━━━━━━━━━━━━━━━━━ 11s 737ms/step - loss: 0.6621 - mae: 0.5591 - rmse: 0.8045

255/269 ━━━━━━━━━━━━━━━━━━━━ 10s 737ms/step - loss: 0.6612 - mae: 0.5586 - rmse: 0.8039

256/269 ━━━━━━━━━━━━━━━━━━━━ 9s 738ms/step - loss: 0.6602 - mae: 0.5581 - rmse: 0.8033

257/269 ━━━━━━━━━━━━━━━━━━━━ 8s 739ms/step - loss: 0.6593 - mae: 0.5576 - rmse: 0.8026

258/269 ━━━━━━━━━━━━━━━━━━━━ 8s 744ms/step - loss: 0.6583 - mae: 0.5571 - rmse: 0.8020

259/269 ━━━━━━━━━━━━━━━━━━━━ 7s 746ms/step - loss: 0.6574 - mae: 0.5566 - rmse: 0.8014

260/269 ━━━━━━━━━━━━━━━━━━━━ 6s 745ms/step - loss: 0.6564 - mae: 0.5561 - rmse: 0.8007

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 746ms/step - loss: 0.6555 - mae: 0.5556 - rmse: 0.8001

262/269 ━━━━━━━━━━━━━━━━━━━━ 5s 748ms/step - loss: 0.6545 - mae: 0.5551 - rmse: 0.7995

263/269 ━━━━━━━━━━━━━━━━━━━━ 4s 751ms/step - loss: 0.6536 - mae: 0.5546 - rmse: 0.7989

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 758ms/step - loss: 0.6527 - mae: 0.5541 - rmse: 0.7982

265/269 ━━━━━━━━━━━━━━━━━━━━ 3s 761ms/step - loss: 0.6517 - mae: 0.5536 - rmse: 0.7976

266/269 ━━━━━━━━━━━━━━━━━━━━ 2s 763ms/step - loss: 0.6508 - mae: 0.5531 - rmse: 0.7970

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 766ms/step - loss: 0.6499 - mae: 0.5526 - rmse: 0.7964

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 772ms/step - loss: 0.6490 - mae: 0.5521 - rmse: 0.7958

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 770ms/step - loss: 0.6480 - mae: 0.5516 - rmse: 0.7952

269/269 ━━━━━━━━━━━━━━━━━━━━ 241s 894ms/step - loss: 0.4028 - mae: 0.4224 - rmse: 0.6314 - val_loss: 0.7404 - val_mae: 0.5412 - val_rmse: 0.8581 - learning_rate: 0.0010

Epoch 13/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 554ms/step - loss: 0.9156 - mae: 0.6722 - rmse: 0.9547

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 403ms/step - loss: 0.8146 - mae: 0.6387 - rmse: 0.8985

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 434ms/step - loss: 0.7905 - mae: 0.6364 - rmse: 0.8854

  4/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 471ms/step - loss: 0.7717 - mae: 0.6335 - rmse: 0.8749

  5/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 459ms/step - loss: 0.7448 - mae: 0.6244 - rmse: 0.8591

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 443ms/step - loss: 0.7249 - mae: 0.6175 - rmse: 0.8472

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 448ms/step - loss: 0.7162 - mae: 0.6150 - rmse: 0.8423

  8/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 467ms/step - loss: 0.7223 - mae: 0.6176 - rmse: 0.8460

  9/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 474ms/step - loss: 0.7255 - mae: 0.6189 - rmse: 0.8481

 10/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 499ms/step - loss: 0.7241 - mae: 0.6181 - rmse: 0.8473

 11/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 572ms/step - loss: 0.7204 - mae: 0.6165 - rmse: 0.8453

 12/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 697ms/step - loss: 0.7260 - mae: 0.6179 - rmse: 0.8486

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 809ms/step - loss: 0.7362 - mae: 0.6205 - rmse: 0.8544

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:42 871ms/step - loss: 0.7521 - mae: 0.6252 - rmse: 0.8632

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:51 910ms/step - loss: 0.7659 - mae: 0.6293 - rmse: 0.8708

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:59 947ms/step - loss: 0.7807 - mae: 0.6340 - rmse: 0.8788

 17/269 ━━━━━━━━━━━━━━━━━━━━ 4:09 990ms/step - loss: 0.7953 - mae: 0.6382 - rmse: 0.8867

 18/269 ━━━━━━━━━━━━━━━━━━━━ 4:19 1s/step - loss: 0.8073 - mae: 0.6417 - rmse: 0.8932

 19/269 ━━━━━━━━━━━━━━━━━━━━ 4:31 1s/step - loss: 0.8204 - mae: 0.6453 - rmse: 0.9001

 20/269 ━━━━━━━━━━━━━━━━━━━━ 4:34 1s/step - loss: 0.8319 - mae: 0.6484 - rmse: 0.9063

 21/269 ━━━━━━━━━━━━━━━━━━━━ 4:38 1s/step - loss: 0.8408 - mae: 0.6508 - rmse: 0.9111

 22/269 ━━━━━━━━━━━━━━━━━━━━ 4:37 1s/step - loss: 0.8490 - mae: 0.6530 - rmse: 0.9155

 23/269 ━━━━━━━━━━━━━━━━━━━━ 4:36 1s/step - loss: 0.8575 - mae: 0.6555 - rmse: 0.9201

 24/269 ━━━━━━━━━━━━━━━━━━━━ 4:33 1s/step - loss: 0.8649 - mae: 0.6578 - rmse: 0.9240

 25/269 ━━━━━━━━━━━━━━━━━━━━ 4:31 1s/step - loss: 0.8710 - mae: 0.6596 - rmse: 0.9273

 26/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.8769 - mae: 0.6613 - rmse: 0.9305

 27/269 ━━━━━━━━━━━━━━━━━━━━ 4:30 1s/step - loss: 0.8815 - mae: 0.6626 - rmse: 0.9330

 28/269 ━━━━━━━━━━━━━━━━━━━━ 4:27 1s/step - loss: 0.8851 - mae: 0.6635 - rmse: 0.9350

 29/269 ━━━━━━━━━━━━━━━━━━━━ 4:27 1s/step - loss: 0.8882 - mae: 0.6644 - rmse: 0.9368

 30/269 ━━━━━━━━━━━━━━━━━━━━ 4:28 1s/step - loss: 0.8904 - mae: 0.6649 - rmse: 0.9380

 31/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.8918 - mae: 0.6651 - rmse: 0.9389

 32/269 ━━━━━━━━━━━━━━━━━━━━ 4:34 1s/step - loss: 0.8929 - mae: 0.6653 - rmse: 0.9396

 33/269 ━━━━━━━━━━━━━━━━━━━━ 4:35 1s/step - loss: 0.8936 - mae: 0.6654 - rmse: 0.9400

 34/269 ━━━━━━━━━━━━━━━━━━━━ 4:38 1s/step - loss: 0.8939 - mae: 0.6654 - rmse: 0.9403

 35/269 ━━━━━━━━━━━━━━━━━━━━ 4:42 1s/step - loss: 0.8942 - mae: 0.6654 - rmse: 0.9405

 36/269 ━━━━━━━━━━━━━━━━━━━━ 4:42 1s/step - loss: 0.8941 - mae: 0.6653 - rmse: 0.9406

 37/269 ━━━━━━━━━━━━━━━━━━━━ 4:40 1s/step - loss: 0.8939 - mae: 0.6652 - rmse: 0.9406

 38/269 ━━━━━━━━━━━━━━━━━━━━ 4:38 1s/step - loss: 0.8934 - mae: 0.6649 - rmse: 0.9403

 39/269 ━━━━━━━━━━━━━━━━━━━━ 4:35 1s/step - loss: 0.8926 - mae: 0.6646 - rmse: 0.9400

 40/269 ━━━━━━━━━━━━━━━━━━━━ 4:34 1s/step - loss: 0.8916 - mae: 0.6642 - rmse: 0.9395

 41/269 ━━━━━━━━━━━━━━━━━━━━ 4:33 1s/step - loss: 0.8906 - mae: 0.6638 - rmse: 0.9391

 42/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.8895 - mae: 0.6633 - rmse: 0.9385

 43/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.8882 - mae: 0.6629 - rmse: 0.9379

 44/269 ━━━━━━━━━━━━━━━━━━━━ 4:34 1s/step - loss: 0.8871 - mae: 0.6624 - rmse: 0.9373

 45/269 ━━━━━━━━━━━━━━━━━━━━ 4:36 1s/step - loss: 0.8859 - mae: 0.6620 - rmse: 0.9368

 46/269 ━━━━━━━━━━━━━━━━━━━━ 4:36 1s/step - loss: 0.8846 - mae: 0.6615 - rmse: 0.9361

 47/269 ━━━━━━━━━━━━━━━━━━━━ 4:32 1s/step - loss: 0.8833 - mae: 0.6611 - rmse: 0.9354

 48/269 ━━━━━━━━━━━━━━━━━━━━ 4:28 1s/step - loss: 0.8820 - mae: 0.6606 - rmse: 0.9347

 49/269 ━━━━━━━━━━━━━━━━━━━━ 4:24 1s/step - loss: 0.8804 - mae: 0.6600 - rmse: 0.9339

 50/269 ━━━━━━━━━━━━━━━━━━━━ 4:20 1s/step - loss: 0.8787 - mae: 0.6593 - rmse: 0.9330

 51/269 ━━━━━━━━━━━━━━━━━━━━ 4:16 1s/step - loss: 0.8769 - mae: 0.6587 - rmse: 0.9321

 52/269 ━━━━━━━━━━━━━━━━━━━━ 4:12 1s/step - loss: 0.8751 - mae: 0.6580 - rmse: 0.9312

 53/269 ━━━━━━━━━━━━━━━━━━━━ 4:08 1s/step - loss: 0.8732 - mae: 0.6573 - rmse: 0.9302

 54/269 ━━━━━━━━━━━━━━━━━━━━ 4:04 1s/step - loss: 0.8716 - mae: 0.6566 - rmse: 0.9293

 55/269 ━━━━━━━━━━━━━━━━━━━━ 4:00 1s/step - loss: 0.8698 - mae: 0.6560 - rmse: 0.9283

 56/269 ━━━━━━━━━━━━━━━━━━━━ 3:56 1s/step - loss: 0.8681 - mae: 0.6554 - rmse: 0.9274

 57/269 ━━━━━━━━━━━━━━━━━━━━ 3:52 1s/step - loss: 0.8663 - mae: 0.6547 - rmse: 0.9265

 58/269 ━━━━━━━━━━━━━━━━━━━━ 3:49 1s/step - loss: 0.8645 - mae: 0.6540 - rmse: 0.9255

 59/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 1s/step - loss: 0.8629 - mae: 0.6534 - rmse: 0.9247

 60/269 ━━━━━━━━━━━━━━━━━━━━ 3:42 1s/step - loss: 0.8612 - mae: 0.6528 - rmse: 0.9237

 61/269 ━━━━━━━━━━━━━━━━━━━━ 3:39 1s/step - loss: 0.8596 - mae: 0.6523 - rmse: 0.9229

 62/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 1s/step - loss: 0.8581 - mae: 0.6517 - rmse: 0.9221

 63/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 1s/step - loss: 0.8565 - mae: 0.6512 - rmse: 0.9212

 64/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step - loss: 0.8549 - mae: 0.6506 - rmse: 0.9204

 65/269 ━━━━━━━━━━━━━━━━━━━━ 3:30 1s/step - loss: 0.8532 - mae: 0.6500 - rmse: 0.9194

 66/269 ━━━━━━━━━━━━━━━━━━━━ 3:28 1s/step - loss: 0.8514 - mae: 0.6494 - rmse: 0.9185

 67/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 1s/step - loss: 0.8496 - mae: 0.6487 - rmse: 0.9175

 68/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 1s/step - loss: 0.8477 - mae: 0.6480 - rmse: 0.9165

 69/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8460 - mae: 0.6474 - rmse: 0.9155

 70/269 ━━━━━━━━━━━━━━━━━━━━ 3:24 1s/step - loss: 0.8443 - mae: 0.6468 - rmse: 0.9146

 71/269 ━━━━━━━━━━━━━━━━━━━━ 3:24 1s/step - loss: 0.8427 - mae: 0.6462 - rmse: 0.9137

 72/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8412 - mae: 0.6456 - rmse: 0.9129

 73/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8397 - mae: 0.6451 - rmse: 0.9121

 74/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8383 - mae: 0.6445 - rmse: 0.9113

 75/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8370 - mae: 0.6440 - rmse: 0.9106

 76/269 ━━━━━━━━━━━━━━━━━━━━ 3:28 1s/step - loss: 0.8357 - mae: 0.6435 - rmse: 0.9099

 77/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 1s/step - loss: 0.8345 - mae: 0.6431 - rmse: 0.9092

 78/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step - loss: 0.8333 - mae: 0.6427 - rmse: 0.9086

 79/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step - loss: 0.8323 - mae: 0.6423 - rmse: 0.9080

 80/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 1s/step - loss: 0.8312 - mae: 0.6419 - rmse: 0.9074

 81/269 ━━━━━━━━━━━━━━━━━━━━ 3:35 1s/step - loss: 0.8304 - mae: 0.6416 - rmse: 0.9070

 82/269 ━━━━━━━━━━━━━━━━━━━━ 3:39 1s/step - loss: 0.8300 - mae: 0.6415 - rmse: 0.9068

 83/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 1s/step - loss: 0.8298 - mae: 0.6413 - rmse: 0.9067

 84/269 ━━━━━━━━━━━━━━━━━━━━ 3:37 1s/step - loss: 0.8296 - mae: 0.6413 - rmse: 0.9067

 85/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 1s/step - loss: 0.8296 - mae: 0.6412 - rmse: 0.9067

 86/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 1s/step - loss: 0.8296 - mae: 0.6412 - rmse: 0.9067

 87/269 ━━━━━━━━━━━━━━━━━━━━ 3:32 1s/step - loss: 0.8297 - mae: 0.6412 - rmse: 0.9068

 88/269 ━━━━━━━━━━━━━━━━━━━━ 3:30 1s/step - loss: 0.8297 - mae: 0.6411 - rmse: 0.9068

 89/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 1s/step - loss: 0.8298 - mae: 0.6411 - rmse: 0.9069

 90/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step - loss: 0.8299 - mae: 0.6411 - rmse: 0.9069

 91/269 ━━━━━━━━━━━━━━━━━━━━ 3:30 1s/step - loss: 0.8299 - mae: 0.6411 - rmse: 0.9070

 92/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 1s/step - loss: 0.8298 - mae: 0.6411 - rmse: 0.9070

 93/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 1s/step - loss: 0.8297 - mae: 0.6410 - rmse: 0.9069

 94/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8296 - mae: 0.6409 - rmse: 0.9068

 95/269 ━━━━━━━━━━━━━━━━━━━━ 3:24 1s/step - loss: 0.8293 - mae: 0.6408 - rmse: 0.9067

 96/269 ━━━━━━━━━━━━━━━━━━━━ 3:23 1s/step - loss: 0.8291 - mae: 0.6407 - rmse: 0.9066

 97/269 ━━━━━━━━━━━━━━━━━━━━ 3:23 1s/step - loss: 0.8287 - mae: 0.6406 - rmse: 0.9064

 98/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 1s/step - loss: 0.8284 - mae: 0.6404 - rmse: 0.9063

 99/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 1s/step - loss: 0.8280 - mae: 0.6402 - rmse: 0.9061

100/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 1s/step - loss: 0.8276 - mae: 0.6400 - rmse: 0.9058

101/269 ━━━━━━━━━━━━━━━━━━━━ 3:16 1s/step - loss: 0.8271 - mae: 0.6399 - rmse: 0.9056

102/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 1s/step - loss: 0.8267 - mae: 0.6397 - rmse: 0.9054

103/269 ━━━━━━━━━━━━━━━━━━━━ 3:12 1s/step - loss: 0.8262 - mae: 0.6395 - rmse: 0.9051

104/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 1s/step - loss: 0.8258 - mae: 0.6393 - rmse: 0.9049

105/269 ━━━━━━━━━━━━━━━━━━━━ 3:07 1s/step - loss: 0.8253 - mae: 0.6391 - rmse: 0.9046

106/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step - loss: 0.8247 - mae: 0.6389 - rmse: 0.9043

107/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 1s/step - loss: 0.8241 - mae: 0.6386 - rmse: 0.9040

108/269 ━━━━━━━━━━━━━━━━━━━━ 3:00 1s/step - loss: 0.8235 - mae: 0.6384 - rmse: 0.9037

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:58 1s/step - loss: 0.8229 - mae: 0.6381 - rmse: 0.9033

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 1s/step - loss: 0.8221 - mae: 0.6378 - rmse: 0.9029

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 1s/step - loss: 0.8214 - mae: 0.6374 - rmse: 0.9025

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 1s/step - loss: 0.8206 - mae: 0.6371 - rmse: 0.9021

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 1s/step - loss: 0.8198 - mae: 0.6367 - rmse: 0.9017

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 1s/step - loss: 0.8190 - mae: 0.6363 - rmse: 0.9012

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 1s/step - loss: 0.8181 - mae: 0.6359 - rmse: 0.9007

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 1s/step - loss: 0.8172 - mae: 0.6355 - rmse: 0.9002

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 1s/step - loss: 0.8163 - mae: 0.6351 - rmse: 0.8997

118/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step - loss: 0.8154 - mae: 0.6346 - rmse: 0.8992

119/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 1s/step - loss: 0.8144 - mae: 0.6342 - rmse: 0.8987

120/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 1s/step - loss: 0.8135 - mae: 0.6337 - rmse: 0.8981

121/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 1s/step - loss: 0.8125 - mae: 0.6333 - rmse: 0.8976

122/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 1s/step - loss: 0.8115 - mae: 0.6328 - rmse: 0.8970

123/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 1s/step - loss: 0.8105 - mae: 0.6323 - rmse: 0.8964

124/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 1s/step - loss: 0.8094 - mae: 0.6318 - rmse: 0.8958

125/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 1s/step - loss: 0.8083 - mae: 0.6313 - rmse: 0.8952

126/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.8073 - mae: 0.6308 - rmse: 0.8946

127/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.8061 - mae: 0.6302 - rmse: 0.8939

128/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.8050 - mae: 0.6297 - rmse: 0.8933

129/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.8039 - mae: 0.6291 - rmse: 0.8927

130/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 1s/step - loss: 0.8028 - mae: 0.6286 - rmse: 0.8920

131/269 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step - loss: 0.8016 - mae: 0.6280 - rmse: 0.8913

132/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 1s/step - loss: 0.8005 - mae: 0.6275 - rmse: 0.8907

133/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 1s/step - loss: 0.7993 - mae: 0.6269 - rmse: 0.8900

134/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 1s/step - loss: 0.7982 - mae: 0.6264 - rmse: 0.8894

135/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 1s/step - loss: 0.7971 - mae: 0.6258 - rmse: 0.8887

136/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 1s/step - loss: 0.7959 - mae: 0.6253 - rmse: 0.8880

137/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 1s/step - loss: 0.7947 - mae: 0.6247 - rmse: 0.8874

138/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 1s/step - loss: 0.7936 - mae: 0.6242 - rmse: 0.8867

139/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 1s/step - loss: 0.7924 - mae: 0.6236 - rmse: 0.8860

140/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 1s/step - loss: 0.7912 - mae: 0.6231 - rmse: 0.8853

141/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 1s/step - loss: 0.7901 - mae: 0.6225 - rmse: 0.8846

142/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 1s/step - loss: 0.7889 - mae: 0.6219 - rmse: 0.8839

143/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 1s/step - loss: 0.7877 - mae: 0.6213 - rmse: 0.8832

144/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 1s/step - loss: 0.7864 - mae: 0.6207 - rmse: 0.8825

145/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 1s/step - loss: 0.7852 - mae: 0.6201 - rmse: 0.8818

146/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 1s/step - loss: 0.7840 - mae: 0.6195 - rmse: 0.8810

147/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 1s/step - loss: 0.7828 - mae: 0.6189 - rmse: 0.8803

148/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 1s/step - loss: 0.7815 - mae: 0.6183 - rmse: 0.8796

149/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 1s/step - loss: 0.7803 - mae: 0.6177 - rmse: 0.8788

150/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 1s/step - loss: 0.7790 - mae: 0.6171 - rmse: 0.8781

151/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 1s/step - loss: 0.7777 - mae: 0.6164 - rmse: 0.8773

152/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 1s/step - loss: 0.7765 - mae: 0.6158 - rmse: 0.8766

153/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 1s/step - loss: 0.7752 - mae: 0.6152 - rmse: 0.8758

154/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 1s/step - loss: 0.7740 - mae: 0.6146 - rmse: 0.8751

155/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 1s/step - loss: 0.7727 - mae: 0.6139 - rmse: 0.8743

156/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 1s/step - loss: 0.7714 - mae: 0.6133 - rmse: 0.8736

157/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 1s/step - loss: 0.7702 - mae: 0.6127 - rmse: 0.8728

158/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 1s/step - loss: 0.7689 - mae: 0.6120 - rmse: 0.8720

159/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 1s/step - loss: 0.7676 - mae: 0.6114 - rmse: 0.8713

160/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 1s/step - loss: 0.7664 - mae: 0.6108 - rmse: 0.8705

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 1s/step - loss: 0.7651 - mae: 0.6101 - rmse: 0.8697

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 1s/step - loss: 0.7638 - mae: 0.6095 - rmse: 0.8690

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 1s/step - loss: 0.7626 - mae: 0.6088 - rmse: 0.8682

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 1s/step - loss: 0.7613 - mae: 0.6082 - rmse: 0.8674

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 1s/step - loss: 0.7600 - mae: 0.6076 - rmse: 0.8667

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 1s/step - loss: 0.7588 - mae: 0.6069 - rmse: 0.8659

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 1s/step - loss: 0.7575 - mae: 0.6063 - rmse: 0.8651

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 1s/step - loss: 0.7563 - mae: 0.6057 - rmse: 0.8644

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 1s/step - loss: 0.7551 - mae: 0.6051 - rmse: 0.8636

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 1s/step - loss: 0.7538 - mae: 0.6045 - rmse: 0.8629

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 1s/step - loss: 0.7527 - mae: 0.6039 - rmse: 0.8622

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 1s/step - loss: 0.7515 - mae: 0.6033 - rmse: 0.8614

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 1s/step - loss: 0.7503 - mae: 0.6027 - rmse: 0.8607

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 1s/step - loss: 0.7491 - mae: 0.6022 - rmse: 0.8600

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 1s/step - loss: 0.7480 - mae: 0.6016 - rmse: 0.8593

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 1s/step - loss: 0.7468 - mae: 0.6010 - rmse: 0.8586

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 1s/step - loss: 0.7457 - mae: 0.6005 - rmse: 0.8579

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 1s/step - loss: 0.7445 - mae: 0.5999 - rmse: 0.8572

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 1s/step - loss: 0.7434 - mae: 0.5993 - rmse: 0.8565

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 1s/step - loss: 0.7422 - mae: 0.5988 - rmse: 0.8558

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 1s/step - loss: 0.7411 - mae: 0.5982 - rmse: 0.8551

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 1s/step - loss: 0.7399 - mae: 0.5976 - rmse: 0.8544

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 1s/step - loss: 0.7387 - mae: 0.5971 - rmse: 0.8537

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 1s/step - loss: 0.7376 - mae: 0.5965 - rmse: 0.8530

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 1s/step - loss: 0.7364 - mae: 0.5959 - rmse: 0.8522

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 1s/step - loss: 0.7353 - mae: 0.5954 - rmse: 0.8515

187/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 1s/step - loss: 0.7341 - mae: 0.5948 - rmse: 0.8508

188/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 1s/step - loss: 0.7330 - mae: 0.5942 - rmse: 0.8501

189/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 1s/step - loss: 0.7318 - mae: 0.5936 - rmse: 0.8494

190/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 1s/step - loss: 0.7307 - mae: 0.5931 - rmse: 0.8487

191/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 1s/step - loss: 0.7295 - mae: 0.5925 - rmse: 0.8479

192/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 1s/step - loss: 0.7284 - mae: 0.5919 - rmse: 0.8472

193/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 1s/step - loss: 0.7272 - mae: 0.5913 - rmse: 0.8465

194/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 1s/step - loss: 0.7261 - mae: 0.5907 - rmse: 0.8458

195/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 1s/step - loss: 0.7249 - mae: 0.5902 - rmse: 0.8451

196/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 1s/step - loss: 0.7238 - mae: 0.5896 - rmse: 0.8444

197/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 1s/step - loss: 0.7227 - mae: 0.5890 - rmse: 0.8437

198/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 1s/step - loss: 0.7215 - mae: 0.5884 - rmse: 0.8429

199/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 1s/step - loss: 0.7204 - mae: 0.5879 - rmse: 0.8422

200/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 1s/step - loss: 0.7193 - mae: 0.5873 - rmse: 0.8415

201/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 1s/step - loss: 0.7181 - mae: 0.5867 - rmse: 0.8408

202/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 1s/step - loss: 0.7170 - mae: 0.5861 - rmse: 0.8401

203/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 1s/step - loss: 0.7159 - mae: 0.5856 - rmse: 0.8394

204/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 1s/step - loss: 0.7148 - mae: 0.5850 - rmse: 0.8387

205/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 1s/step - loss: 0.7138 - mae: 0.5845 - rmse: 0.8381

206/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 1s/step - loss: 0.7127 - mae: 0.5839 - rmse: 0.8374

207/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 1s/step - loss: 0.7116 - mae: 0.5834 - rmse: 0.8367

208/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 1s/step - loss: 0.7105 - mae: 0.5828 - rmse: 0.8360

209/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 1s/step - loss: 0.7095 - mae: 0.5823 - rmse: 0.8354

210/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 1s/step - loss: 0.7084 - mae: 0.5818 - rmse: 0.8347

211/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 1s/step - loss: 0.7073 - mae: 0.5812 - rmse: 0.8340

212/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 1s/step - loss: 0.7063 - mae: 0.5807 - rmse: 0.8333

213/269 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - loss: 0.7052 - mae: 0.5801 - rmse: 0.8327

214/269 ━━━━━━━━━━━━━━━━━━━━ 58s 1s/step - loss: 0.7041 - mae: 0.5796 - rmse: 0.8320

215/269 ━━━━━━━━━━━━━━━━━━━━ 57s 1s/step - loss: 0.7031 - mae: 0.5791 - rmse: 0.8313

216/269 ━━━━━━━━━━━━━━━━━━━━ 56s 1s/step - loss: 0.7020 - mae: 0.5785 - rmse: 0.8306

217/269 ━━━━━━━━━━━━━━━━━━━━ 55s 1s/step - loss: 0.7010 - mae: 0.5780 - rmse: 0.8300

218/269 ━━━━━━━━━━━━━━━━━━━━ 54s 1s/step - loss: 0.6999 - mae: 0.5775 - rmse: 0.8293

219/269 ━━━━━━━━━━━━━━━━━━━━ 53s 1s/step - loss: 0.6989 - mae: 0.5769 - rmse: 0.8286

220/269 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - loss: 0.6978 - mae: 0.5764 - rmse: 0.8280

221/269 ━━━━━━━━━━━━━━━━━━━━ 51s 1s/step - loss: 0.6968 - mae: 0.5759 - rmse: 0.8273

222/269 ━━━━━━━━━━━━━━━━━━━━ 50s 1s/step - loss: 0.6957 - mae: 0.5753 - rmse: 0.8266

223/269 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - loss: 0.6947 - mae: 0.5748 - rmse: 0.8260

224/269 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - loss: 0.6937 - mae: 0.5743 - rmse: 0.8253

225/269 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - loss: 0.6926 - mae: 0.5737 - rmse: 0.8246

226/269 ━━━━━━━━━━━━━━━━━━━━ 46s 1s/step - loss: 0.6916 - mae: 0.5732 - rmse: 0.8240

227/269 ━━━━━━━━━━━━━━━━━━━━ 45s 1s/step - loss: 0.6906 - mae: 0.5727 - rmse: 0.8233

228/269 ━━━━━━━━━━━━━━━━━━━━ 43s 1s/step - loss: 0.6895 - mae: 0.5721 - rmse: 0.8226

229/269 ━━━━━━━━━━━━━━━━━━━━ 42s 1s/step - loss: 0.6885 - mae: 0.5716 - rmse: 0.8220

230/269 ━━━━━━━━━━━━━━━━━━━━ 41s 1s/step - loss: 0.6875 - mae: 0.5711 - rmse: 0.8213

231/269 ━━━━━━━━━━━━━━━━━━━━ 40s 1s/step - loss: 0.6864 - mae: 0.5705 - rmse: 0.8206

232/269 ━━━━━━━━━━━━━━━━━━━━ 39s 1s/step - loss: 0.6854 - mae: 0.5700 - rmse: 0.8200

233/269 ━━━━━━━━━━━━━━━━━━━━ 38s 1s/step - loss: 0.6844 - mae: 0.5695 - rmse: 0.8193

234/269 ━━━━━━━━━━━━━━━━━━━━ 37s 1s/step - loss: 0.6834 - mae: 0.5689 - rmse: 0.8187

235/269 ━━━━━━━━━━━━━━━━━━━━ 36s 1s/step - loss: 0.6823 - mae: 0.5684 - rmse: 0.8180

236/269 ━━━━━━━━━━━━━━━━━━━━ 35s 1s/step - loss: 0.6813 - mae: 0.5679 - rmse: 0.8173

237/269 ━━━━━━━━━━━━━━━━━━━━ 34s 1s/step - loss: 0.6803 - mae: 0.5673 - rmse: 0.8167

238/269 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - loss: 0.6793 - mae: 0.5668 - rmse: 0.8160

239/269 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - loss: 0.6783 - mae: 0.5663 - rmse: 0.8154

240/269 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - loss: 0.6773 - mae: 0.5658 - rmse: 0.8147

241/269 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - loss: 0.6763 - mae: 0.5652 - rmse: 0.8141

242/269 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - loss: 0.6753 - mae: 0.5647 - rmse: 0.8134

243/269 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - loss: 0.6743 - mae: 0.5642 - rmse: 0.8128

244/269 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - loss: 0.6733 - mae: 0.5637 - rmse: 0.8121

245/269 ━━━━━━━━━━━━━━━━━━━━ 26s 1s/step - loss: 0.6723 - mae: 0.5632 - rmse: 0.8115

246/269 ━━━━━━━━━━━━━━━━━━━━ 24s 1s/step - loss: 0.6714 - mae: 0.5627 - rmse: 0.8108

247/269 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.6704 - mae: 0.5621 - rmse: 0.8102

248/269 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.6694 - mae: 0.5616 - rmse: 0.8095

249/269 ━━━━━━━━━━━━━━━━━━━━ 21s 1s/step - loss: 0.6684 - mae: 0.5611 - rmse: 0.8089

250/269 ━━━━━━━━━━━━━━━━━━━━ 20s 1s/step - loss: 0.6675 - mae: 0.5606 - rmse: 0.8083

251/269 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.6665 - mae: 0.5601 - rmse: 0.8076

252/269 ━━━━━━━━━━━━━━━━━━━━ 18s 1s/step - loss: 0.6655 - mae: 0.5596 - rmse: 0.8070

253/269 ━━━━━━━━━━━━━━━━━━━━ 17s 1s/step - loss: 0.6646 - mae: 0.5591 - rmse: 0.8064

254/269 ━━━━━━━━━━━━━━━━━━━━ 16s 1s/step - loss: 0.6636 - mae: 0.5586 - rmse: 0.8057

255/269 ━━━━━━━━━━━━━━━━━━━━ 15s 1s/step - loss: 0.6627 - mae: 0.5581 - rmse: 0.8051

256/269 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step - loss: 0.6617 - mae: 0.5576 - rmse: 0.8045

257/269 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.6608 - mae: 0.5571 - rmse: 0.8038

258/269 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.6598 - mae: 0.5566 - rmse: 0.8032

259/269 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.6589 - mae: 0.5561 - rmse: 0.8026

260/269 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.6579 - mae: 0.5556 - rmse: 0.8020

261/269 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.6570 - mae: 0.5551 - rmse: 0.8013

262/269 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.6560 - mae: 0.5547 - rmse: 0.8007

263/269 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.6551 - mae: 0.5542 - rmse: 0.8001

264/269 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.6542 - mae: 0.5537 - rmse: 0.7995

265/269 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - loss: 0.6532 - mae: 0.5532 - rmse: 0.7989

266/269 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - loss: 0.6523 - mae: 0.5527 - rmse: 0.7982

267/269 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step - loss: 0.6514 - mae: 0.5522 - rmse: 0.7976

268/269 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.6505 - mae: 0.5517 - rmse: 0.7970

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.6496 - mae: 0.5513 - rmse: 0.7964

269/269 ━━━━━━━━━━━━━━━━━━━━ 313s 1s/step - loss: 0.4053 - mae: 0.4227 - rmse: 0.6334 - val_loss: 0.7249 - val_mae: 0.5185 - val_rmse: 0.8491 - learning_rate: 0.0010

Epoch 14/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 7:51 2s/step - loss: 0.8204 - mae: 0.6380 - rmse: 0.9035

  2/269 ━━━━━━━━━━━━━━━━━━━━ 5:47 1s/step - loss: 0.7385 - mae: 0.6113 - rmse: 0.8557

  3/269 ━━━━━━━━━━━━━━━━━━━━ 6:10 1s/step - loss: 0.7250 - mae: 0.6116 - rmse: 0.8481

  4/269 ━━━━━━━━━━━━━━━━━━━━ 6:55 2s/step - loss: 0.7108 - mae: 0.6092 - rmse: 0.8398

  5/269 ━━━━━━━━━━━━━━━━━━━━ 6:36 2s/step - loss: 0.6880 - mae: 0.6007 - rmse: 0.8258

  6/269 ━━━━━━━━━━━━━━━━━━━━ 6:17 1s/step - loss: 0.6722 - mae: 0.5951 - rmse: 0.8162

  7/269 ━━━━━━━━━━━━━━━━━━━━ 6:06 1s/step - loss: 0.6666 - mae: 0.5933 - rmse: 0.8128

  8/269 ━━━━━━━━━━━━━━━━━━━━ 5:53 1s/step - loss: 0.6748 - mae: 0.5968 - rmse: 0.8179

  9/269 ━━━━━━━━━━━━━━━━━━━━ 5:42 1s/step - loss: 0.6797 - mae: 0.5987 - rmse: 0.8210

 10/269 ━━━━━━━━━━━━━━━━━━━━ 5:34 1s/step - loss: 0.6799 - mae: 0.5986 - rmse: 0.8212

 11/269 ━━━━━━━━━━━━━━━━━━━━ 5:32 1s/step - loss: 0.6782 - mae: 0.5976 - rmse: 0.8202

 12/269 ━━━━━━━━━━━━━━━━━━━━ 5:21 1s/step - loss: 0.6843 - mae: 0.5995 - rmse: 0.8239

 13/269 ━━━━━━━━━━━━━━━━━━━━ 5:11 1s/step - loss: 0.6953 - mae: 0.6026 - rmse: 0.8304

 14/269 ━━━━━━━━━━━━━━━━━━━━ 5:04 1s/step - loss: 0.7120 - mae: 0.6079 - rmse: 0.8398

 15/269 ━━━━━━━━━━━━━━━━━━━━ 4:59 1s/step - loss: 0.7270 - mae: 0.6127 - rmse: 0.8481

 16/269 ━━━━━━━━━━━━━━━━━━━━ 5:05 1s/step - loss: 0.7427 - mae: 0.6179 - rmse: 0.8568

 17/269 ━━━━━━━━━━━━━━━━━━━━ 5:17 1s/step - loss: 0.7585 - mae: 0.6227 - rmse: 0.8654

 18/269 ━━━━━━━━━━━━━━━━━━━━ 5:23 1s/step - loss: 0.7718 - mae: 0.6268 - rmse: 0.8728

 19/269 ━━━━━━━━━━━━━━━━━━━━ 5:36 1s/step - loss: 0.7855 - mae: 0.6308 - rmse: 0.8802

 20/269 ━━━━━━━━━━━━━━━━━━━━ 5:50 1s/step - loss: 0.7976 - mae: 0.6344 - rmse: 0.8868

 21/269 ━━━━━━━━━━━━━━━━━━━━ 5:55 1s/step - loss: 0.8073 - mae: 0.6372 - rmse: 0.8921

 22/269 ━━━━━━━━━━━━━━━━━━━━ 5:53 1s/step - loss: 0.8162 - mae: 0.6399 - rmse: 0.8970

 23/269 ━━━━━━━━━━━━━━━━━━━━ 5:48 1s/step - loss: 0.8253 - mae: 0.6428 - rmse: 0.9019

 24/269 ━━━━━━━━━━━━━━━━━━━━ 5:40 1s/step - loss: 0.8332 - mae: 0.6453 - rmse: 0.9062

 25/269 ━━━━━━━━━━━━━━━━━━━━ 5:32 1s/step - loss: 0.8397 - mae: 0.6474 - rmse: 0.9099

 26/269 ━━━━━━━━━━━━━━━━━━━━ 5:28 1s/step - loss: 0.8462 - mae: 0.6494 - rmse: 0.9134

 27/269 ━━━━━━━━━━━━━━━━━━━━ 5:22 1s/step - loss: 0.8513 - mae: 0.6510 - rmse: 0.9162

 28/269 ━━━━━━━━━━━━━━━━━━━━ 5:17 1s/step - loss: 0.8554 - mae: 0.6522 - rmse: 0.9185

 29/269 ━━━━━━━━━━━━━━━━━━━━ 5:13 1s/step - loss: 0.8589 - mae: 0.6533 - rmse: 0.9205

 30/269 ━━━━━━━━━━━━━━━━━━━━ 5:16 1s/step - loss: 0.8615 - mae: 0.6541 - rmse: 0.9220

 31/269 ━━━━━━━━━━━━━━━━━━━━ 5:19 1s/step - loss: 0.8634 - mae: 0.6546 - rmse: 0.9232

 32/269 ━━━━━━━━━━━━━━━━━━━━ 5:24 1s/step - loss: 0.8649 - mae: 0.6549 - rmse: 0.9241

 33/269 ━━━━━━━━━━━━━━━━━━━━ 5:27 1s/step - loss: 0.8660 - mae: 0.6551 - rmse: 0.9248

 34/269 ━━━━━━━━━━━━━━━━━━━━ 5:27 1s/step - loss: 0.8667 - mae: 0.6553 - rmse: 0.9253

 35/269 ━━━━━━━━━━━━━━━━━━━━ 5:26 1s/step - loss: 0.8673 - mae: 0.6555 - rmse: 0.9257

 36/269 ━━━━━━━━━━━━━━━━━━━━ 5:27 1s/step - loss: 0.8676 - mae: 0.6555 - rmse: 0.9259

 37/269 ━━━━━━━━━━━━━━━━━━━━ 5:23 1s/step - loss: 0.8678 - mae: 0.6556 - rmse: 0.9261

 38/269 ━━━━━━━━━━━━━━━━━━━━ 5:21 1s/step - loss: 0.8675 - mae: 0.6554 - rmse: 0.9261

 39/269 ━━━━━━━━━━━━━━━━━━━━ 5:21 1s/step - loss: 0.8671 - mae: 0.6552 - rmse: 0.9259

 40/269 ━━━━━━━━━━━━━━━━━━━━ 5:21 1s/step - loss: 0.8663 - mae: 0.6549 - rmse: 0.9256

 41/269 ━━━━━━━━━━━━━━━━━━━━ 5:21 1s/step - loss: 0.8658 - mae: 0.6547 - rmse: 0.9254

 42/269 ━━━━━━━━━━━━━━━━━━━━ 5:17 1s/step - loss: 0.8650 - mae: 0.6543 - rmse: 0.9250

 43/269 ━━━━━━━━━━━━━━━━━━━━ 5:14 1s/step - loss: 0.8640 - mae: 0.6540 - rmse: 0.9246

 44/269 ━━━━━━━━━━━━━━━━━━━━ 5:12 1s/step - loss: 0.8632 - mae: 0.6536 - rmse: 0.9242

 45/269 ━━━━━━━━━━━━━━━━━━━━ 5:11 1s/step - loss: 0.8623 - mae: 0.6533 - rmse: 0.9238

 46/269 ━━━━━━━━━━━━━━━━━━━━ 5:13 1s/step - loss: 0.8612 - mae: 0.6529 - rmse: 0.9232

 47/269 ━━━━━━━━━━━━━━━━━━━━ 5:12 1s/step - loss: 0.8602 - mae: 0.6525 - rmse: 0.9227

 48/269 ━━━━━━━━━━━━━━━━━━━━ 5:11 1s/step - loss: 0.8591 - mae: 0.6521 - rmse: 0.9221

 49/269 ━━━━━━━━━━━━━━━━━━━━ 5:09 1s/step - loss: 0.8577 - mae: 0.6516 - rmse: 0.9214

 50/269 ━━━━━━━━━━━━━━━━━━━━ 5:06 1s/step - loss: 0.8563 - mae: 0.6511 - rmse: 0.9207

 51/269 ━━━━━━━━━━━━━━━━━━━━ 5:03 1s/step - loss: 0.8547 - mae: 0.6505 - rmse: 0.9199

 52/269 ━━━━━━━━━━━━━━━━━━━━ 5:00 1s/step - loss: 0.8531 - mae: 0.6499 - rmse: 0.9190

 53/269 ━━━━━━━━━━━━━━━━━━━━ 4:57 1s/step - loss: 0.8514 - mae: 0.6492 - rmse: 0.9181

 54/269 ━━━━━━━━━━━━━━━━━━━━ 4:54 1s/step - loss: 0.8499 - mae: 0.6487 - rmse: 0.9174

 55/269 ━━━━━━━━━━━━━━━━━━━━ 4:51 1s/step - loss: 0.8484 - mae: 0.6481 - rmse: 0.9165

 56/269 ━━━━━━━━━━━━━━━━━━━━ 4:47 1s/step - loss: 0.8468 - mae: 0.6475 - rmse: 0.9157

 57/269 ━━━━━━━━━━━━━━━━━━━━ 4:42 1s/step - loss: 0.8453 - mae: 0.6469 - rmse: 0.9149

 58/269 ━━━━━━━━━━━━━━━━━━━━ 4:38 1s/step - loss: 0.8437 - mae: 0.6463 - rmse: 0.9140

 59/269 ━━━━━━━━━━━━━━━━━━━━ 4:34 1s/step - loss: 0.8423 - mae: 0.6458 - rmse: 0.9133

 60/269 ━━━━━━━━━━━━━━━━━━━━ 4:29 1s/step - loss: 0.8408 - mae: 0.6453 - rmse: 0.9125

 61/269 ━━━━━━━━━━━━━━━━━━━━ 4:25 1s/step - loss: 0.8394 - mae: 0.6448 - rmse: 0.9117

 62/269 ━━━━━━━━━━━━━━━━━━━━ 4:21 1s/step - loss: 0.8380 - mae: 0.6443 - rmse: 0.9110

 63/269 ━━━━━━━━━━━━━━━━━━━━ 4:17 1s/step - loss: 0.8367 - mae: 0.6438 - rmse: 0.9103

 64/269 ━━━━━━━━━━━━━━━━━━━━ 4:14 1s/step - loss: 0.8352 - mae: 0.6433 - rmse: 0.9095

 65/269 ━━━━━━━━━━━━━━━━━━━━ 4:10 1s/step - loss: 0.8337 - mae: 0.6428 - rmse: 0.9086

 66/269 ━━━━━━━━━━━━━━━━━━━━ 4:07 1s/step - loss: 0.8320 - mae: 0.6422 - rmse: 0.9078

 67/269 ━━━━━━━━━━━━━━━━━━━━ 4:05 1s/step - loss: 0.8304 - mae: 0.6416 - rmse: 0.9069

 68/269 ━━━━━━━━━━━━━━━━━━━━ 4:03 1s/step - loss: 0.8287 - mae: 0.6410 - rmse: 0.9059

 69/269 ━━━━━━━━━━━━━━━━━━━━ 4:01 1s/step - loss: 0.8272 - mae: 0.6404 - rmse: 0.9051

 70/269 ━━━━━━━━━━━━━━━━━━━━ 3:59 1s/step - loss: 0.8256 - mae: 0.6398 - rmse: 0.9042

 71/269 ━━━━━━━━━━━━━━━━━━━━ 3:56 1s/step - loss: 0.8242 - mae: 0.6393 - rmse: 0.9035

 72/269 ━━━━━━━━━━━━━━━━━━━━ 3:54 1s/step - loss: 0.8228 - mae: 0.6388 - rmse: 0.9027

 73/269 ━━━━━━━━━━━━━━━━━━━━ 3:51 1s/step - loss: 0.8215 - mae: 0.6383 - rmse: 0.9020

 74/269 ━━━━━━━━━━━━━━━━━━━━ 3:48 1s/step - loss: 0.8202 - mae: 0.6378 - rmse: 0.9013

 75/269 ━━━━━━━━━━━━━━━━━━━━ 3:46 1s/step - loss: 0.8190 - mae: 0.6374 - rmse: 0.9006

 76/269 ━━━━━━━━━━━━━━━━━━━━ 3:43 1s/step - loss: 0.8178 - mae: 0.6369 - rmse: 0.9000

 77/269 ━━━━━━━━━━━━━━━━━━━━ 3:42 1s/step - loss: 0.8168 - mae: 0.6365 - rmse: 0.8994

 78/269 ━━━━━━━━━━━━━━━━━━━━ 3:40 1s/step - loss: 0.8157 - mae: 0.6362 - rmse: 0.8988

 79/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 1s/step - loss: 0.8148 - mae: 0.6358 - rmse: 0.8983

 80/269 ━━━━━━━━━━━━━━━━━━━━ 3:37 1s/step - loss: 0.8138 - mae: 0.6355 - rmse: 0.8978

 81/269 ━━━━━━━━━━━━━━━━━━━━ 3:35 1s/step - loss: 0.8131 - mae: 0.6352 - rmse: 0.8974

 82/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 1s/step - loss: 0.8128 - mae: 0.6351 - rmse: 0.8973

 83/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 1s/step - loss: 0.8126 - mae: 0.6350 - rmse: 0.8972

 84/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 1s/step - loss: 0.8125 - mae: 0.6350 - rmse: 0.8971

 85/269 ━━━━━━━━━━━━━━━━━━━━ 3:30 1s/step - loss: 0.8124 - mae: 0.6349 - rmse: 0.8971

 86/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 1s/step - loss: 0.8125 - mae: 0.6349 - rmse: 0.8972

 87/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 1s/step - loss: 0.8125 - mae: 0.6349 - rmse: 0.8972

 88/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 1s/step - loss: 0.8126 - mae: 0.6349 - rmse: 0.8973

 89/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 1s/step - loss: 0.8126 - mae: 0.6350 - rmse: 0.8973

 90/269 ━━━━━━━━━━━━━━━━━━━━ 3:23 1s/step - loss: 0.8127 - mae: 0.6350 - rmse: 0.8974

 91/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 1s/step - loss: 0.8126 - mae: 0.6350 - rmse: 0.8974

 92/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 1s/step - loss: 0.8126 - mae: 0.6349 - rmse: 0.8974

 93/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 1s/step - loss: 0.8124 - mae: 0.6349 - rmse: 0.8973

 94/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 1s/step - loss: 0.8123 - mae: 0.6348 - rmse: 0.8972

 95/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 1s/step - loss: 0.8120 - mae: 0.6347 - rmse: 0.8971

 96/269 ━━━━━━━━━━━━━━━━━━━━ 3:16 1s/step - loss: 0.8117 - mae: 0.6346 - rmse: 0.8970

 97/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 1s/step - loss: 0.8114 - mae: 0.6344 - rmse: 0.8968

 98/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 1s/step - loss: 0.8110 - mae: 0.6343 - rmse: 0.8966

 99/269 ━━━━━━━━━━━━━━━━━━━━ 3:11 1s/step - loss: 0.8106 - mae: 0.6341 - rmse: 0.8964

100/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 1s/step - loss: 0.8102 - mae: 0.6340 - rmse: 0.8962

101/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 1s/step - loss: 0.8097 - mae: 0.6338 - rmse: 0.8959

102/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 1s/step - loss: 0.8093 - mae: 0.6336 - rmse: 0.8957

103/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 1s/step - loss: 0.8088 - mae: 0.6334 - rmse: 0.8955

104/269 ━━━━━━━━━━━━━━━━━━━━ 3:07 1s/step - loss: 0.8083 - mae: 0.6333 - rmse: 0.8952

105/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step - loss: 0.8078 - mae: 0.6331 - rmse: 0.8949

106/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 1s/step - loss: 0.8073 - mae: 0.6328 - rmse: 0.8946

107/269 ━━━━━━━━━━━━━━━━━━━━ 3:04 1s/step - loss: 0.8067 - mae: 0.6326 - rmse: 0.8943

108/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 1s/step - loss: 0.8061 - mae: 0.6324 - rmse: 0.8940

109/269 ━━━━━━━━━━━━━━━━━━━━ 3:01 1s/step - loss: 0.8054 - mae: 0.6321 - rmse: 0.8936

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 1s/step - loss: 0.8047 - mae: 0.6318 - rmse: 0.8932

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:58 1s/step - loss: 0.8040 - mae: 0.6315 - rmse: 0.8928

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 1s/step - loss: 0.8032 - mae: 0.6311 - rmse: 0.8924

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 1s/step - loss: 0.8024 - mae: 0.6308 - rmse: 0.8919

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 1s/step - loss: 0.8016 - mae: 0.6304 - rmse: 0.8915

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:52 1s/step - loss: 0.8007 - mae: 0.6300 - rmse: 0.8910

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 1s/step - loss: 0.7999 - mae: 0.6296 - rmse: 0.8905

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 1s/step - loss: 0.7990 - mae: 0.6292 - rmse: 0.8900

118/269 ━━━━━━━━━━━━━━━━━━━━ 2:48 1s/step - loss: 0.7980 - mae: 0.6288 - rmse: 0.8895

119/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 1s/step - loss: 0.7971 - mae: 0.6283 - rmse: 0.8889

120/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 1s/step - loss: 0.7962 - mae: 0.6279 - rmse: 0.8884

121/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 1s/step - loss: 0.7952 - mae: 0.6274 - rmse: 0.8879

122/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 1s/step - loss: 0.7942 - mae: 0.6270 - rmse: 0.8873

123/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 1s/step - loss: 0.7932 - mae: 0.6265 - rmse: 0.8867

124/269 ━━━━━━━━━━━━━━━━━━━━ 2:43 1s/step - loss: 0.7921 - mae: 0.6260 - rmse: 0.8861

125/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 1s/step - loss: 0.7911 - mae: 0.6255 - rmse: 0.8855

126/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 1s/step - loss: 0.7900 - mae: 0.6250 - rmse: 0.8849

127/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 1s/step - loss: 0.7889 - mae: 0.6244 - rmse: 0.8842

128/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 1s/step - loss: 0.7878 - mae: 0.6239 - rmse: 0.8836

129/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 1s/step - loss: 0.7867 - mae: 0.6234 - rmse: 0.8830

130/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 1s/step - loss: 0.7856 - mae: 0.6228 - rmse: 0.8823

131/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 1s/step - loss: 0.7845 - mae: 0.6223 - rmse: 0.8817

132/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 1s/step - loss: 0.7833 - mae: 0.6218 - rmse: 0.8810

133/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.7822 - mae: 0.6212 - rmse: 0.8803

134/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 1s/step - loss: 0.7811 - mae: 0.6207 - rmse: 0.8797

135/269 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step - loss: 0.7800 - mae: 0.6201 - rmse: 0.8790

136/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 1s/step - loss: 0.7788 - mae: 0.6196 - rmse: 0.8784

137/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 1s/step - loss: 0.7777 - mae: 0.6191 - rmse: 0.8777

138/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 1s/step - loss: 0.7766 - mae: 0.6185 - rmse: 0.8770

139/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 1s/step - loss: 0.7754 - mae: 0.6180 - rmse: 0.8764

140/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 1s/step - loss: 0.7743 - mae: 0.6174 - rmse: 0.8757

141/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 1s/step - loss: 0.7731 - mae: 0.6169 - rmse: 0.8750

142/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 1s/step - loss: 0.7719 - mae: 0.6163 - rmse: 0.8743

143/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 1s/step - loss: 0.7708 - mae: 0.6157 - rmse: 0.8736

144/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 1s/step - loss: 0.7696 - mae: 0.6152 - rmse: 0.8729

145/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 1s/step - loss: 0.7684 - mae: 0.6146 - rmse: 0.8722

146/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 1s/step - loss: 0.7672 - mae: 0.6140 - rmse: 0.8714

147/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 1s/step - loss: 0.7659 - mae: 0.6134 - rmse: 0.8707

148/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 1s/step - loss: 0.7647 - mae: 0.6128 - rmse: 0.8700

149/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 1s/step - loss: 0.7635 - mae: 0.6122 - rmse: 0.8692

150/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 1s/step - loss: 0.7623 - mae: 0.6115 - rmse: 0.8685

151/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 1s/step - loss: 0.7610 - mae: 0.6109 - rmse: 0.8678

152/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 1s/step - loss: 0.7598 - mae: 0.6103 - rmse: 0.8670

153/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 1s/step - loss: 0.7586 - mae: 0.6097 - rmse: 0.8663

154/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 1s/step - loss: 0.7573 - mae: 0.6091 - rmse: 0.8655

155/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 1s/step - loss: 0.7561 - mae: 0.6085 - rmse: 0.8648

156/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 1s/step - loss: 0.7549 - mae: 0.6078 - rmse: 0.8640

157/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 1s/step - loss: 0.7536 - mae: 0.6072 - rmse: 0.8633

158/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 1s/step - loss: 0.7524 - mae: 0.6066 - rmse: 0.8625

159/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 1s/step - loss: 0.7511 - mae: 0.6060 - rmse: 0.8618

160/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 1s/step - loss: 0.7499 - mae: 0.6053 - rmse: 0.8610

161/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 1s/step - loss: 0.7486 - mae: 0.6047 - rmse: 0.8602

162/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 1s/step - loss: 0.7474 - mae: 0.6041 - rmse: 0.8595

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 1s/step - loss: 0.7461 - mae: 0.6034 - rmse: 0.8587

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 1s/step - loss: 0.7449 - mae: 0.6028 - rmse: 0.8580

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 1s/step - loss: 0.7437 - mae: 0.6022 - rmse: 0.8572

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 1s/step - loss: 0.7424 - mae: 0.6016 - rmse: 0.8564

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 1s/step - loss: 0.7412 - mae: 0.6009 - rmse: 0.8557

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 1s/step - loss: 0.7400 - mae: 0.6003 - rmse: 0.8549

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 1s/step - loss: 0.7388 - mae: 0.5997 - rmse: 0.8542

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 1s/step - loss: 0.7376 - mae: 0.5991 - rmse: 0.8535

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 1s/step - loss: 0.7364 - mae: 0.5986 - rmse: 0.8527

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 1s/step - loss: 0.7353 - mae: 0.5980 - rmse: 0.8520

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 1s/step - loss: 0.7341 - mae: 0.5974 - rmse: 0.8513

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 1s/step - loss: 0.7330 - mae: 0.5968 - rmse: 0.8506

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 1s/step - loss: 0.7318 - mae: 0.5963 - rmse: 0.8499

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 1s/step - loss: 0.7307 - mae: 0.5957 - rmse: 0.8492

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 1s/step - loss: 0.7296 - mae: 0.5952 - rmse: 0.8485

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 1s/step - loss: 0.7284 - mae: 0.5946 - rmse: 0.8478

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 1s/step - loss: 0.7273 - mae: 0.5940 - rmse: 0.8471

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 1s/step - loss: 0.7262 - mae: 0.5935 - rmse: 0.8464

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 1s/step - loss: 0.7251 - mae: 0.5929 - rmse: 0.8457

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 1s/step - loss: 0.7239 - mae: 0.5924 - rmse: 0.8450

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 1s/step - loss: 0.7228 - mae: 0.5918 - rmse: 0.8443

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 1s/step - loss: 0.7217 - mae: 0.5912 - rmse: 0.8436

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 1s/step - loss: 0.7205 - mae: 0.5907 - rmse: 0.8429

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 1s/step - loss: 0.7194 - mae: 0.5901 - rmse: 0.8422

187/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 1s/step - loss: 0.7183 - mae: 0.5895 - rmse: 0.8415

188/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 1s/step - loss: 0.7171 - mae: 0.5890 - rmse: 0.8408

189/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 1s/step - loss: 0.7160 - mae: 0.5884 - rmse: 0.8401

190/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 1s/step - loss: 0.7149 - mae: 0.5878 - rmse: 0.8394

191/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 1s/step - loss: 0.7138 - mae: 0.5873 - rmse: 0.8387

192/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 1s/step - loss: 0.7126 - mae: 0.5867 - rmse: 0.8380

193/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 1s/step - loss: 0.7115 - mae: 0.5861 - rmse: 0.8372

194/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 1s/step - loss: 0.7104 - mae: 0.5855 - rmse: 0.8365

195/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 1s/step - loss: 0.7093 - mae: 0.5850 - rmse: 0.8358

196/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 1s/step - loss: 0.7082 - mae: 0.5844 - rmse: 0.8351

197/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 1s/step - loss: 0.7070 - mae: 0.5838 - rmse: 0.8344

198/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 1s/step - loss: 0.7059 - mae: 0.5833 - rmse: 0.8337

199/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 1s/step - loss: 0.7048 - mae: 0.5827 - rmse: 0.8330

200/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 1s/step - loss: 0.7037 - mae: 0.5821 - rmse: 0.8323

201/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 1s/step - loss: 0.7026 - mae: 0.5816 - rmse: 0.8316

202/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 1s/step - loss: 0.7015 - mae: 0.5810 - rmse: 0.8309

203/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 1s/step - loss: 0.7005 - mae: 0.5805 - rmse: 0.8302

204/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 1s/step - loss: 0.6994 - mae: 0.5799 - rmse: 0.8296

205/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 1s/step - loss: 0.6983 - mae: 0.5794 - rmse: 0.8289

206/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 1s/step - loss: 0.6973 - mae: 0.5788 - rmse: 0.8282

207/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 1s/step - loss: 0.6962 - mae: 0.5783 - rmse: 0.8276

208/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 1s/step - loss: 0.6952 - mae: 0.5777 - rmse: 0.8269

209/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 1s/step - loss: 0.6941 - mae: 0.5772 - rmse: 0.8262

210/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 1s/step - loss: 0.6931 - mae: 0.5767 - rmse: 0.8255

211/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 1s/step - loss: 0.6920 - mae: 0.5761 - rmse: 0.8249

212/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 1s/step - loss: 0.6910 - mae: 0.5756 - rmse: 0.8242

213/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 1s/step - loss: 0.6900 - mae: 0.5751 - rmse: 0.8235

214/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 1s/step - loss: 0.6889 - mae: 0.5745 - rmse: 0.8229

215/269 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - loss: 0.6879 - mae: 0.5740 - rmse: 0.8222

216/269 ━━━━━━━━━━━━━━━━━━━━ 57s 1s/step - loss: 0.6868 - mae: 0.5735 - rmse: 0.8215

217/269 ━━━━━━━━━━━━━━━━━━━━ 56s 1s/step - loss: 0.6858 - mae: 0.5729 - rmse: 0.8209

218/269 ━━━━━━━━━━━━━━━━━━━━ 55s 1s/step - loss: 0.6848 - mae: 0.5724 - rmse: 0.8202

219/269 ━━━━━━━━━━━━━━━━━━━━ 54s 1s/step - loss: 0.6838 - mae: 0.5719 - rmse: 0.8196

220/269 ━━━━━━━━━━━━━━━━━━━━ 53s 1s/step - loss: 0.6827 - mae: 0.5714 - rmse: 0.8189

221/269 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - loss: 0.6817 - mae: 0.5708 - rmse: 0.8182

222/269 ━━━━━━━━━━━━━━━━━━━━ 51s 1s/step - loss: 0.6807 - mae: 0.5703 - rmse: 0.8176

223/269 ━━━━━━━━━━━━━━━━━━━━ 50s 1s/step - loss: 0.6797 - mae: 0.5698 - rmse: 0.8169

224/269 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - loss: 0.6787 - mae: 0.5692 - rmse: 0.8163

225/269 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - loss: 0.6776 - mae: 0.5687 - rmse: 0.8156

226/269 ━━━━━━━━━━━━━━━━━━━━ 47s 1s/step - loss: 0.6766 - mae: 0.5682 - rmse: 0.8149

227/269 ━━━━━━━━━━━━━━━━━━━━ 46s 1s/step - loss: 0.6756 - mae: 0.5677 - rmse: 0.8143

228/269 ━━━━━━━━━━━━━━━━━━━━ 45s 1s/step - loss: 0.6746 - mae: 0.5671 - rmse: 0.8136

229/269 ━━━━━━━━━━━━━━━━━━━━ 44s 1s/step - loss: 0.6736 - mae: 0.5666 - rmse: 0.8130

230/269 ━━━━━━━━━━━━━━━━━━━━ 43s 1s/step - loss: 0.6726 - mae: 0.5661 - rmse: 0.8123

231/269 ━━━━━━━━━━━━━━━━━━━━ 41s 1s/step - loss: 0.6716 - mae: 0.5655 - rmse: 0.8116

232/269 ━━━━━━━━━━━━━━━━━━━━ 40s 1s/step - loss: 0.6706 - mae: 0.5650 - rmse: 0.8110

233/269 ━━━━━━━━━━━━━━━━━━━━ 39s 1s/step - loss: 0.6696 - mae: 0.5645 - rmse: 0.8103

234/269 ━━━━━━━━━━━━━━━━━━━━ 38s 1s/step - loss: 0.6686 - mae: 0.5639 - rmse: 0.8097

235/269 ━━━━━━━━━━━━━━━━━━━━ 37s 1s/step - loss: 0.6676 - mae: 0.5634 - rmse: 0.8090

236/269 ━━━━━━━━━━━━━━━━━━━━ 36s 1s/step - loss: 0.6666 - mae: 0.5629 - rmse: 0.8084

237/269 ━━━━━━━━━━━━━━━━━━━━ 35s 1s/step - loss: 0.6656 - mae: 0.5624 - rmse: 0.8077

238/269 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - loss: 0.6646 - mae: 0.5618 - rmse: 0.8071

239/269 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - loss: 0.6636 - mae: 0.5613 - rmse: 0.8064

240/269 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - loss: 0.6626 - mae: 0.5608 - rmse: 0.8058

241/269 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - loss: 0.6616 - mae: 0.5603 - rmse: 0.8051

242/269 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - loss: 0.6607 - mae: 0.5598 - rmse: 0.8045

243/269 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - loss: 0.6597 - mae: 0.5592 - rmse: 0.8038

244/269 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - loss: 0.6587 - mae: 0.5587 - rmse: 0.8032

245/269 ━━━━━━━━━━━━━━━━━━━━ 26s 1s/step - loss: 0.6578 - mae: 0.5582 - rmse: 0.8025

246/269 ━━━━━━━━━━━━━━━━━━━━ 24s 1s/step - loss: 0.6568 - mae: 0.5577 - rmse: 0.8019

247/269 ━━━━━━━━━━━━━━━━━━━━ 23s 1s/step - loss: 0.6558 - mae: 0.5572 - rmse: 0.8013

248/269 ━━━━━━━━━━━━━━━━━━━━ 22s 1s/step - loss: 0.6549 - mae: 0.5567 - rmse: 0.8006

249/269 ━━━━━━━━━━━━━━━━━━━━ 21s 1s/step - loss: 0.6539 - mae: 0.5562 - rmse: 0.8000

250/269 ━━━━━━━━━━━━━━━━━━━━ 20s 1s/step - loss: 0.6530 - mae: 0.5557 - rmse: 0.7994

251/269 ━━━━━━━━━━━━━━━━━━━━ 19s 1s/step - loss: 0.6520 - mae: 0.5552 - rmse: 0.7988

252/269 ━━━━━━━━━━━━━━━━━━━━ 18s 1s/step - loss: 0.6511 - mae: 0.5547 - rmse: 0.7981

253/269 ━━━━━━━━━━━━━━━━━━━━ 17s 1s/step - loss: 0.6501 - mae: 0.5542 - rmse: 0.7975

254/269 ━━━━━━━━━━━━━━━━━━━━ 16s 1s/step - loss: 0.6492 - mae: 0.5537 - rmse: 0.7969

255/269 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step - loss: 0.6483 - mae: 0.5532 - rmse: 0.7962

256/269 ━━━━━━━━━━━━━━━━━━━━ 13s 1s/step - loss: 0.6473 - mae: 0.5527 - rmse: 0.7956

257/269 ━━━━━━━━━━━━━━━━━━━━ 12s 1s/step - loss: 0.6464 - mae: 0.5522 - rmse: 0.7950

258/269 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.6455 - mae: 0.5517 - rmse: 0.7944

259/269 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.6445 - mae: 0.5512 - rmse: 0.7938

260/269 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - loss: 0.6436 - mae: 0.5507 - rmse: 0.7931

261/269 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.6427 - mae: 0.5503 - rmse: 0.7925

262/269 ━━━━━━━━━━━━━━━━━━━━ 7s 1s/step - loss: 0.6418 - mae: 0.5498 - rmse: 0.7919

263/269 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - loss: 0.6409 - mae: 0.5493 - rmse: 0.7913

264/269 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.6400 - mae: 0.5488 - rmse: 0.7907

265/269 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - loss: 0.6391 - mae: 0.5483 - rmse: 0.7901

266/269 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - loss: 0.6381 - mae: 0.5478 - rmse: 0.7895

267/269 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step - loss: 0.6372 - mae: 0.5473 - rmse: 0.7888

268/269 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.6363 - mae: 0.5469 - rmse: 0.7882

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.6355 - mae: 0.5464 - rmse: 0.7876

269/269 ━━━━━━━━━━━━━━━━━━━━ 305s 1s/step - loss: 0.3963 - mae: 0.4190 - rmse: 0.6264 - val_loss: 0.7174 - val_mae: 0.5261 - val_rmse: 0.8447 - learning_rate: 0.0010

Epoch 15/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 1:25:27 19s/step - loss: 0.8679 - mae: 0.6705 - rmse: 0.9295

  2/269 ━━━━━━━━━━━━━━━━━━━━ 3:35 806ms/step - loss: 0.7792 - mae: 0.6395 - rmse: 0.8790

  3/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 763ms/step - loss: 0.7549 - mae: 0.6348 - rmse: 0.8654

  4/269 ━━━━━━━━━━━━━━━━━━━━ 3:28 787ms/step - loss: 0.7344 - mae: 0.6296 - rmse: 0.8535

  5/269 ━━━━━━━━━━━━━━━━━━━━ 3:26 783ms/step - loss: 0.7071 - mae: 0.6184 - rmse: 0.8369

  6/269 ━━━━━━━━━━━━━━━━━━━━ 3:25 783ms/step - loss: 0.6905 - mae: 0.6120 - rmse: 0.8270

  7/269 ━━━━━━━━━━━━━━━━━━━━ 3:35 821ms/step - loss: 0.6826 - mae: 0.6088 - rmse: 0.8223

  8/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 883ms/step - loss: 0.6881 - mae: 0.6107 - rmse: 0.8258

  9/269 ━━━━━━━━━━━━━━━━━━━━ 4:06 950ms/step - loss: 0.6890 - mae: 0.6107 - rmse: 0.8265

 10/269 ━━━━━━━━━━━━━━━━━━━━ 4:02 938ms/step - loss: 0.6861 - mae: 0.6087 - rmse: 0.8248

 11/269 ━━━━━━━━━━━━━━━━━━━━ 3:56 917ms/step - loss: 0.6818 - mae: 0.6062 - rmse: 0.8223

 12/269 ━━━━━━━━━━━━━━━━━━━━ 3:50 897ms/step - loss: 0.6865 - mae: 0.6071 - rmse: 0.8251

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:47 888ms/step - loss: 0.6960 - mae: 0.6091 - rmse: 0.8307

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:45 884ms/step - loss: 0.7121 - mae: 0.6135 - rmse: 0.8398

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:39 864ms/step - loss: 0.7267 - mae: 0.6176 - rmse: 0.8481

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:36 854ms/step - loss: 0.7419 - mae: 0.6222 - rmse: 0.8565

 17/269 ━━━━━━━━━━━━━━━━━━━━ 3:31 841ms/step - loss: 0.7575 - mae: 0.6265 - rmse: 0.8650

 18/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 825ms/step - loss: 0.7705 - mae: 0.6301 - rmse: 0.8722

 19/269 ━━━━━━━━━━━━━━━━━━━━ 3:23 814ms/step - loss: 0.7838 - mae: 0.6336 - rmse: 0.8794

 20/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 802ms/step - loss: 0.7956 - mae: 0.6368 - rmse: 0.8858

 21/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 798ms/step - loss: 0.8049 - mae: 0.6392 - rmse: 0.8909

 22/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 786ms/step - loss: 0.8134 - mae: 0.6415 - rmse: 0.8956

 23/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 786ms/step - loss: 0.8220 - mae: 0.6439 - rmse: 0.9003

 24/269 ━━━━━━━━━━━━━━━━━━━━ 3:11 781ms/step - loss: 0.8295 - mae: 0.6462 - rmse: 0.9044

 25/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 798ms/step - loss: 0.8356 - mae: 0.6479 - rmse: 0.9078

 26/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 818ms/step - loss: 0.8417 - mae: 0.6496 - rmse: 0.9112

 27/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 816ms/step - loss: 0.8464 - mae: 0.6507 - rmse: 0.9138

 28/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 819ms/step - loss: 0.8501 - mae: 0.6517 - rmse: 0.9159

 29/269 ━━━━━━━━━━━━━━━━━━━━ 3:15 814ms/step - loss: 0.8533 - mae: 0.6524 - rmse: 0.9177

 30/269 ━━━━━━━━━━━━━━━━━━━━ 3:13 812ms/step - loss: 0.8555 - mae: 0.6529 - rmse: 0.9191

 31/269 ━━━━━━━━━━━━━━━━━━━━ 3:12 807ms/step - loss: 0.8571 - mae: 0.6531 - rmse: 0.9200

 32/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 803ms/step - loss: 0.8583 - mae: 0.6532 - rmse: 0.9208

 33/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 798ms/step - loss: 0.8591 - mae: 0.6533 - rmse: 0.9213

 34/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 790ms/step - loss: 0.8597 - mae: 0.6532 - rmse: 0.9217

 35/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 780ms/step - loss: 0.8601 - mae: 0.6532 - rmse: 0.9220

 36/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 769ms/step - loss: 0.8602 - mae: 0.6531 - rmse: 0.9222

 37/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 759ms/step - loss: 0.8602 - mae: 0.6530 - rmse: 0.9223

 38/269 ━━━━━━━━━━━━━━━━━━━━ 2:52 748ms/step - loss: 0.8597 - mae: 0.6527 - rmse: 0.9221

 39/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 739ms/step - loss: 0.8592 - mae: 0.6524 - rmse: 0.9219

 40/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 729ms/step - loss: 0.8584 - mae: 0.6520 - rmse: 0.9215

 41/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 722ms/step - loss: 0.8577 - mae: 0.6517 - rmse: 0.9212

 42/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 713ms/step - loss: 0.8568 - mae: 0.6512 - rmse: 0.9208

 43/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 704ms/step - loss: 0.8558 - mae: 0.6508 - rmse: 0.9203

 44/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 697ms/step - loss: 0.8549 - mae: 0.6504 - rmse: 0.9199

 45/269 ━━━━━━━━━━━━━━━━━━━━ 2:34 688ms/step - loss: 0.8539 - mae: 0.6500 - rmse: 0.9194

 46/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 679ms/step - loss: 0.8527 - mae: 0.6495 - rmse: 0.9188

 47/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 672ms/step - loss: 0.8516 - mae: 0.6491 - rmse: 0.9182

 48/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 665ms/step - loss: 0.8503 - mae: 0.6486 - rmse: 0.9176

 49/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 662ms/step - loss: 0.8489 - mae: 0.6480 - rmse: 0.9168

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 662ms/step - loss: 0.8474 - mae: 0.6474 - rmse: 0.9160

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 661ms/step - loss: 0.8458 - mae: 0.6468 - rmse: 0.9152

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 659ms/step - loss: 0.8441 - mae: 0.6461 - rmse: 0.9143

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 658ms/step - loss: 0.8424 - mae: 0.6454 - rmse: 0.9134

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 662ms/step - loss: 0.8408 - mae: 0.6448 - rmse: 0.9125

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 664ms/step - loss: 0.8392 - mae: 0.6442 - rmse: 0.9116

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 662ms/step - loss: 0.8375 - mae: 0.6436 - rmse: 0.9108

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 663ms/step - loss: 0.8359 - mae: 0.6430 - rmse: 0.9099

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 666ms/step - loss: 0.8342 - mae: 0.6423 - rmse: 0.9090

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 667ms/step - loss: 0.8327 - mae: 0.6417 - rmse: 0.9082

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 674ms/step - loss: 0.8311 - mae: 0.6412 - rmse: 0.9073

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 677ms/step - loss: 0.8297 - mae: 0.6406 - rmse: 0.9065

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 681ms/step - loss: 0.8282 - mae: 0.6401 - rmse: 0.9057

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 695ms/step - loss: 0.8268 - mae: 0.6396 - rmse: 0.9049

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 700ms/step - loss: 0.8253 - mae: 0.6391 - rmse: 0.9041

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 704ms/step - loss: 0.8236 - mae: 0.6385 - rmse: 0.9032

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 707ms/step - loss: 0.8220 - mae: 0.6378 - rmse: 0.9023

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 713ms/step - loss: 0.8203 - mae: 0.6372 - rmse: 0.9014

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 715ms/step - loss: 0.8186 - mae: 0.6366 - rmse: 0.9004

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 717ms/step - loss: 0.8170 - mae: 0.6360 - rmse: 0.8995

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 718ms/step - loss: 0.8153 - mae: 0.6354 - rmse: 0.8986

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 718ms/step - loss: 0.8139 - mae: 0.6348 - rmse: 0.8978

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 719ms/step - loss: 0.8125 - mae: 0.6343 - rmse: 0.8970

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 716ms/step - loss: 0.8111 - mae: 0.6337 - rmse: 0.8963

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 716ms/step - loss: 0.8098 - mae: 0.6332 - rmse: 0.8955

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 717ms/step - loss: 0.8085 - mae: 0.6328 - rmse: 0.8949

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 715ms/step - loss: 0.8073 - mae: 0.6323 - rmse: 0.8942

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 714ms/step - loss: 0.8062 - mae: 0.6319 - rmse: 0.8936

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 713ms/step - loss: 0.8052 - mae: 0.6315 - rmse: 0.8930

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 713ms/step - loss: 0.8042 - mae: 0.6311 - rmse: 0.8925

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 712ms/step - loss: 0.8032 - mae: 0.6308 - rmse: 0.8919

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 712ms/step - loss: 0.8024 - mae: 0.6305 - rmse: 0.8915

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 715ms/step - loss: 0.8019 - mae: 0.6303 - rmse: 0.8913

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 721ms/step - loss: 0.8016 - mae: 0.6302 - rmse: 0.8911

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 725ms/step - loss: 0.8014 - mae: 0.6301 - rmse: 0.8910

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 727ms/step - loss: 0.8013 - mae: 0.6300 - rmse: 0.8910

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 730ms/step - loss: 0.8013 - mae: 0.6300 - rmse: 0.8910

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 733ms/step - loss: 0.8012 - mae: 0.6300 - rmse: 0.8910

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 736ms/step - loss: 0.8012 - mae: 0.6299 - rmse: 0.8910

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 738ms/step - loss: 0.8012 - mae: 0.6299 - rmse: 0.8910

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 739ms/step - loss: 0.8012 - mae: 0.6299 - rmse: 0.8910

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 740ms/step - loss: 0.8011 - mae: 0.6299 - rmse: 0.8910

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 741ms/step - loss: 0.8010 - mae: 0.6299 - rmse: 0.8910

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 742ms/step - loss: 0.8008 - mae: 0.6298 - rmse: 0.8909

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 743ms/step - loss: 0.8006 - mae: 0.6297 - rmse: 0.8908

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 743ms/step - loss: 0.8003 - mae: 0.6296 - rmse: 0.8906

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 742ms/step - loss: 0.8000 - mae: 0.6294 - rmse: 0.8905

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 743ms/step - loss: 0.7996 - mae: 0.6293 - rmse: 0.8903

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 742ms/step - loss: 0.7992 - mae: 0.6291 - rmse: 0.8901

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 741ms/step - loss: 0.7988 - mae: 0.6290 - rmse: 0.8898

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 742ms/step - loss: 0.7983 - mae: 0.6288 - rmse: 0.8896

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 742ms/step - loss: 0.7978 - mae: 0.6286 - rmse: 0.8893

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 742ms/step - loss: 0.7973 - mae: 0.6284 - rmse: 0.8891

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 742ms/step - loss: 0.7968 - mae: 0.6282 - rmse: 0.8888

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 742ms/step - loss: 0.7963 - mae: 0.6280 - rmse: 0.8885

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 742ms/step - loss: 0.7958 - mae: 0.6278 - rmse: 0.8882

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 744ms/step - loss: 0.7952 - mae: 0.6275 - rmse: 0.8879

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 746ms/step - loss: 0.7946 - mae: 0.6273 - rmse: 0.8876

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 749ms/step - loss: 0.7940 - mae: 0.6270 - rmse: 0.8872

109/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 748ms/step - loss: 0.7933 - mae: 0.6267 - rmse: 0.8869

110/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 748ms/step - loss: 0.7926 - mae: 0.6264 - rmse: 0.8865

111/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 748ms/step - loss: 0.7918 - mae: 0.6261 - rmse: 0.8860

112/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 748ms/step - loss: 0.7910 - mae: 0.6257 - rmse: 0.8856

113/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 749ms/step - loss: 0.7902 - mae: 0.6253 - rmse: 0.8851

114/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 748ms/step - loss: 0.7894 - mae: 0.6249 - rmse: 0.8847

115/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 747ms/step - loss: 0.7885 - mae: 0.6245 - rmse: 0.8842

116/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 748ms/step - loss: 0.7876 - mae: 0.6241 - rmse: 0.8837

117/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 748ms/step - loss: 0.7867 - mae: 0.6237 - rmse: 0.8831

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 747ms/step - loss: 0.7858 - mae: 0.6233 - rmse: 0.8826

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 747ms/step - loss: 0.7848 - mae: 0.6228 - rmse: 0.8821

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 747ms/step - loss: 0.7839 - mae: 0.6224 - rmse: 0.8815

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 749ms/step - loss: 0.7829 - mae: 0.6219 - rmse: 0.8809

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 752ms/step - loss: 0.7819 - mae: 0.6214 - rmse: 0.8804

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 754ms/step - loss: 0.7809 - mae: 0.6209 - rmse: 0.8798

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 756ms/step - loss: 0.7798 - mae: 0.6204 - rmse: 0.8792

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 757ms/step - loss: 0.7788 - mae: 0.6199 - rmse: 0.8786

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 756ms/step - loss: 0.7777 - mae: 0.6194 - rmse: 0.8779

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 755ms/step - loss: 0.7766 - mae: 0.6189 - rmse: 0.8773

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 756ms/step - loss: 0.7755 - mae: 0.6184 - rmse: 0.8766

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 755ms/step - loss: 0.7744 - mae: 0.6178 - rmse: 0.8760

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 755ms/step - loss: 0.7733 - mae: 0.6173 - rmse: 0.8753

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 754ms/step - loss: 0.7721 - mae: 0.6167 - rmse: 0.8747

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 753ms/step - loss: 0.7710 - mae: 0.6162 - rmse: 0.8740

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 751ms/step - loss: 0.7699 - mae: 0.6156 - rmse: 0.8734

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 751ms/step - loss: 0.7688 - mae: 0.6151 - rmse: 0.8727

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 751ms/step - loss: 0.7676 - mae: 0.6146 - rmse: 0.8720

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 750ms/step - loss: 0.7665 - mae: 0.6140 - rmse: 0.8714

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 749ms/step - loss: 0.7654 - mae: 0.6135 - rmse: 0.8707

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 753ms/step - loss: 0.7643 - mae: 0.6129 - rmse: 0.8700

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 753ms/step - loss: 0.7631 - mae: 0.6124 - rmse: 0.8693

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 754ms/step - loss: 0.7620 - mae: 0.6118 - rmse: 0.8686

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 756ms/step - loss: 0.7608 - mae: 0.6113 - rmse: 0.8680

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 756ms/step - loss: 0.7596 - mae: 0.6107 - rmse: 0.8673

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 756ms/step - loss: 0.7584 - mae: 0.6101 - rmse: 0.8665

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 757ms/step - loss: 0.7573 - mae: 0.6095 - rmse: 0.8658

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 758ms/step - loss: 0.7561 - mae: 0.6089 - rmse: 0.8651

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 758ms/step - loss: 0.7549 - mae: 0.6083 - rmse: 0.8644

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 759ms/step - loss: 0.7536 - mae: 0.6077 - rmse: 0.8637

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 760ms/step - loss: 0.7524 - mae: 0.6071 - rmse: 0.8629

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 761ms/step - loss: 0.7512 - mae: 0.6065 - rmse: 0.8622

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 761ms/step - loss: 0.7500 - mae: 0.6059 - rmse: 0.8614

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 761ms/step - loss: 0.7487 - mae: 0.6052 - rmse: 0.8607

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 760ms/step - loss: 0.7475 - mae: 0.6046 - rmse: 0.8599

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 759ms/step - loss: 0.7463 - mae: 0.6040 - rmse: 0.8592

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 757ms/step - loss: 0.7451 - mae: 0.6034 - rmse: 0.8584

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 756ms/step - loss: 0.7438 - mae: 0.6027 - rmse: 0.8577

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 755ms/step - loss: 0.7426 - mae: 0.6021 - rmse: 0.8569

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 756ms/step - loss: 0.7414 - mae: 0.6015 - rmse: 0.8562

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 757ms/step - loss: 0.7401 - mae: 0.6009 - rmse: 0.8554

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 755ms/step - loss: 0.7389 - mae: 0.6002 - rmse: 0.8547

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 754ms/step - loss: 0.7376 - mae: 0.5996 - rmse: 0.8539

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 753ms/step - loss: 0.7364 - mae: 0.5990 - rmse: 0.8531

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 751ms/step - loss: 0.7352 - mae: 0.5983 - rmse: 0.8524

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 749ms/step - loss: 0.7339 - mae: 0.5977 - rmse: 0.8516

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 747ms/step - loss: 0.7327 - mae: 0.5970 - rmse: 0.8508

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 745ms/step - loss: 0.7315 - mae: 0.5964 - rmse: 0.8501

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 743ms/step - loss: 0.7302 - mae: 0.5958 - rmse: 0.8493

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 741ms/step - loss: 0.7290 - mae: 0.5952 - rmse: 0.8486

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 738ms/step - loss: 0.7278 - mae: 0.5946 - rmse: 0.8478

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 736ms/step - loss: 0.7266 - mae: 0.5940 - rmse: 0.8471

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 734ms/step - loss: 0.7254 - mae: 0.5934 - rmse: 0.8463

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 733ms/step - loss: 0.7243 - mae: 0.5928 - rmse: 0.8456

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 731ms/step - loss: 0.7231 - mae: 0.5922 - rmse: 0.8449

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 729ms/step - loss: 0.7220 - mae: 0.5916 - rmse: 0.8442

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 728ms/step - loss: 0.7208 - mae: 0.5911 - rmse: 0.8435

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 727ms/step - loss: 0.7197 - mae: 0.5905 - rmse: 0.8428

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 726ms/step - loss: 0.7186 - mae: 0.5899 - rmse: 0.8421

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 724ms/step - loss: 0.7175 - mae: 0.5894 - rmse: 0.8414

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 725ms/step - loss: 0.7163 - mae: 0.5888 - rmse: 0.8407

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 725ms/step - loss: 0.7152 - mae: 0.5882 - rmse: 0.8400

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 724ms/step - loss: 0.7141 - mae: 0.5877 - rmse: 0.8393

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 724ms/step - loss: 0.7130 - mae: 0.5871 - rmse: 0.8386

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 724ms/step - loss: 0.7119 - mae: 0.5866 - rmse: 0.8379

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 724ms/step - loss: 0.7107 - mae: 0.5860 - rmse: 0.8372

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 724ms/step - loss: 0.7096 - mae: 0.5854 - rmse: 0.8365

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 724ms/step - loss: 0.7085 - mae: 0.5849 - rmse: 0.8358

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 723ms/step - loss: 0.7074 - mae: 0.5843 - rmse: 0.8351

187/269 ━━━━━━━━━━━━━━━━━━━━ 59s 723ms/step - loss: 0.7062 - mae: 0.5837 - rmse: 0.8343

188/269 ━━━━━━━━━━━━━━━━━━━━ 58s 722ms/step - loss: 0.7051 - mae: 0.5832 - rmse: 0.8336

189/269 ━━━━━━━━━━━━━━━━━━━━ 57s 722ms/step - loss: 0.7040 - mae: 0.5826 - rmse: 0.8329

190/269 ━━━━━━━━━━━━━━━━━━━━ 56s 721ms/step - loss: 0.7029 - mae: 0.5820 - rmse: 0.8322

191/269 ━━━━━━━━━━━━━━━━━━━━ 56s 720ms/step - loss: 0.7018 - mae: 0.5814 - rmse: 0.8315

192/269 ━━━━━━━━━━━━━━━━━━━━ 55s 720ms/step - loss: 0.7006 - mae: 0.5809 - rmse: 0.8308

193/269 ━━━━━━━━━━━━━━━━━━━━ 54s 719ms/step - loss: 0.6995 - mae: 0.5803 - rmse: 0.8301

194/269 ━━━━━━━━━━━━━━━━━━━━ 53s 720ms/step - loss: 0.6984 - mae: 0.5797 - rmse: 0.8294

195/269 ━━━━━━━━━━━━━━━━━━━━ 53s 719ms/step - loss: 0.6973 - mae: 0.5791 - rmse: 0.8287

196/269 ━━━━━━━━━━━━━━━━━━━━ 52s 721ms/step - loss: 0.6962 - mae: 0.5786 - rmse: 0.8280

197/269 ━━━━━━━━━━━━━━━━━━━━ 51s 721ms/step - loss: 0.6951 - mae: 0.5780 - rmse: 0.8273

198/269 ━━━━━━━━━━━━━━━━━━━━ 51s 721ms/step - loss: 0.6940 - mae: 0.5774 - rmse: 0.8266

199/269 ━━━━━━━━━━━━━━━━━━━━ 50s 722ms/step - loss: 0.6929 - mae: 0.5769 - rmse: 0.8259

200/269 ━━━━━━━━━━━━━━━━━━━━ 49s 722ms/step - loss: 0.6918 - mae: 0.5763 - rmse: 0.8252

201/269 ━━━━━━━━━━━━━━━━━━━━ 49s 723ms/step - loss: 0.6907 - mae: 0.5757 - rmse: 0.8245

202/269 ━━━━━━━━━━━━━━━━━━━━ 48s 722ms/step - loss: 0.6897 - mae: 0.5752 - rmse: 0.8238

203/269 ━━━━━━━━━━━━━━━━━━━━ 47s 722ms/step - loss: 0.6886 - mae: 0.5746 - rmse: 0.8231

204/269 ━━━━━━━━━━━━━━━━━━━━ 46s 722ms/step - loss: 0.6875 - mae: 0.5741 - rmse: 0.8224

205/269 ━━━━━━━━━━━━━━━━━━━━ 46s 722ms/step - loss: 0.6865 - mae: 0.5735 - rmse: 0.8217

206/269 ━━━━━━━━━━━━━━━━━━━━ 45s 723ms/step - loss: 0.6854 - mae: 0.5730 - rmse: 0.8211

207/269 ━━━━━━━━━━━━━━━━━━━━ 44s 723ms/step - loss: 0.6844 - mae: 0.5725 - rmse: 0.8204

208/269 ━━━━━━━━━━━━━━━━━━━━ 44s 724ms/step - loss: 0.6834 - mae: 0.5719 - rmse: 0.8197

209/269 ━━━━━━━━━━━━━━━━━━━━ 43s 724ms/step - loss: 0.6823 - mae: 0.5714 - rmse: 0.8191

210/269 ━━━━━━━━━━━━━━━━━━━━ 42s 725ms/step - loss: 0.6813 - mae: 0.5708 - rmse: 0.8184

211/269 ━━━━━━━━━━━━━━━━━━━━ 42s 725ms/step - loss: 0.6802 - mae: 0.5703 - rmse: 0.8177

212/269 ━━━━━━━━━━━━━━━━━━━━ 41s 726ms/step - loss: 0.6792 - mae: 0.5698 - rmse: 0.8171

213/269 ━━━━━━━━━━━━━━━━━━━━ 40s 727ms/step - loss: 0.6782 - mae: 0.5692 - rmse: 0.8164

214/269 ━━━━━━━━━━━━━━━━━━━━ 39s 727ms/step - loss: 0.6771 - mae: 0.5687 - rmse: 0.8157

215/269 ━━━━━━━━━━━━━━━━━━━━ 39s 727ms/step - loss: 0.6761 - mae: 0.5682 - rmse: 0.8151

216/269 ━━━━━━━━━━━━━━━━━━━━ 38s 727ms/step - loss: 0.6751 - mae: 0.5676 - rmse: 0.8144

217/269 ━━━━━━━━━━━━━━━━━━━━ 37s 729ms/step - loss: 0.6741 - mae: 0.5671 - rmse: 0.8137

218/269 ━━━━━━━━━━━━━━━━━━━━ 37s 731ms/step - loss: 0.6731 - mae: 0.5666 - rmse: 0.8131

219/269 ━━━━━━━━━━━━━━━━━━━━ 36s 733ms/step - loss: 0.6721 - mae: 0.5660 - rmse: 0.8124

220/269 ━━━━━━━━━━━━━━━━━━━━ 36s 735ms/step - loss: 0.6710 - mae: 0.5655 - rmse: 0.8118

221/269 ━━━━━━━━━━━━━━━━━━━━ 35s 737ms/step - loss: 0.6700 - mae: 0.5650 - rmse: 0.8111

222/269 ━━━━━━━━━━━━━━━━━━━━ 34s 740ms/step - loss: 0.6690 - mae: 0.5645 - rmse: 0.8104

223/269 ━━━━━━━━━━━━━━━━━━━━ 34s 742ms/step - loss: 0.6680 - mae: 0.5639 - rmse: 0.8098

224/269 ━━━━━━━━━━━━━━━━━━━━ 33s 741ms/step - loss: 0.6670 - mae: 0.5634 - rmse: 0.8091

225/269 ━━━━━━━━━━━━━━━━━━━━ 32s 742ms/step - loss: 0.6660 - mae: 0.5629 - rmse: 0.8085

226/269 ━━━━━━━━━━━━━━━━━━━━ 31s 743ms/step - loss: 0.6650 - mae: 0.5624 - rmse: 0.8078

227/269 ━━━━━━━━━━━━━━━━━━━━ 31s 742ms/step - loss: 0.6640 - mae: 0.5618 - rmse: 0.8071

228/269 ━━━━━━━━━━━━━━━━━━━━ 30s 742ms/step - loss: 0.6630 - mae: 0.5613 - rmse: 0.8065

229/269 ━━━━━━━━━━━━━━━━━━━━ 29s 742ms/step - loss: 0.6620 - mae: 0.5608 - rmse: 0.8058

230/269 ━━━━━━━━━━━━━━━━━━━━ 28s 743ms/step - loss: 0.6610 - mae: 0.5602 - rmse: 0.8052

231/269 ━━━━━━━━━━━━━━━━━━━━ 28s 743ms/step - loss: 0.6600 - mae: 0.5597 - rmse: 0.8045

232/269 ━━━━━━━━━━━━━━━━━━━━ 27s 744ms/step - loss: 0.6590 - mae: 0.5592 - rmse: 0.8039

233/269 ━━━━━━━━━━━━━━━━━━━━ 26s 744ms/step - loss: 0.6580 - mae: 0.5587 - rmse: 0.8032

234/269 ━━━━━━━━━━━━━━━━━━━━ 26s 744ms/step - loss: 0.6570 - mae: 0.5581 - rmse: 0.8025

235/269 ━━━━━━━━━━━━━━━━━━━━ 25s 744ms/step - loss: 0.6560 - mae: 0.5576 - rmse: 0.8019

236/269 ━━━━━━━━━━━━━━━━━━━━ 24s 743ms/step - loss: 0.6551 - mae: 0.5571 - rmse: 0.8012

237/269 ━━━━━━━━━━━━━━━━━━━━ 23s 743ms/step - loss: 0.6541 - mae: 0.5565 - rmse: 0.8006

238/269 ━━━━━━━━━━━━━━━━━━━━ 23s 743ms/step - loss: 0.6531 - mae: 0.5560 - rmse: 0.7999

239/269 ━━━━━━━━━━━━━━━━━━━━ 22s 744ms/step - loss: 0.6521 - mae: 0.5555 - rmse: 0.7993

240/269 ━━━━━━━━━━━━━━━━━━━━ 21s 745ms/step - loss: 0.6512 - mae: 0.5550 - rmse: 0.7987

241/269 ━━━━━━━━━━━━━━━━━━━━ 20s 745ms/step - loss: 0.6502 - mae: 0.5545 - rmse: 0.7980

242/269 ━━━━━━━━━━━━━━━━━━━━ 20s 746ms/step - loss: 0.6492 - mae: 0.5540 - rmse: 0.7974

243/269 ━━━━━━━━━━━━━━━━━━━━ 19s 747ms/step - loss: 0.6483 - mae: 0.5534 - rmse: 0.7967

244/269 ━━━━━━━━━━━━━━━━━━━━ 18s 747ms/step - loss: 0.6473 - mae: 0.5529 - rmse: 0.7961

245/269 ━━━━━━━━━━━━━━━━━━━━ 17s 747ms/step - loss: 0.6464 - mae: 0.5524 - rmse: 0.7955

246/269 ━━━━━━━━━━━━━━━━━━━━ 17s 747ms/step - loss: 0.6454 - mae: 0.5519 - rmse: 0.7948

247/269 ━━━━━━━━━━━━━━━━━━━━ 16s 747ms/step - loss: 0.6445 - mae: 0.5514 - rmse: 0.7942

248/269 ━━━━━━━━━━━━━━━━━━━━ 15s 748ms/step - loss: 0.6435 - mae: 0.5509 - rmse: 0.7936

249/269 ━━━━━━━━━━━━━━━━━━━━ 14s 749ms/step - loss: 0.6426 - mae: 0.5504 - rmse: 0.7929

250/269 ━━━━━━━━━━━━━━━━━━━━ 14s 749ms/step - loss: 0.6416 - mae: 0.5499 - rmse: 0.7923

251/269 ━━━━━━━━━━━━━━━━━━━━ 13s 749ms/step - loss: 0.6407 - mae: 0.5494 - rmse: 0.7917

252/269 ━━━━━━━━━━━━━━━━━━━━ 12s 750ms/step - loss: 0.6398 - mae: 0.5489 - rmse: 0.7911

253/269 ━━━━━━━━━━━━━━━━━━━━ 12s 751ms/step - loss: 0.6389 - mae: 0.5484 - rmse: 0.7904

254/269 ━━━━━━━━━━━━━━━━━━━━ 11s 750ms/step - loss: 0.6379 - mae: 0.5479 - rmse: 0.7898

255/269 ━━━━━━━━━━━━━━━━━━━━ 10s 750ms/step - loss: 0.6370 - mae: 0.5474 - rmse: 0.7892

256/269 ━━━━━━━━━━━━━━━━━━━━ 9s 751ms/step - loss: 0.6361 - mae: 0.5469 - rmse: 0.7886

257/269 ━━━━━━━━━━━━━━━━━━━━ 9s 751ms/step - loss: 0.6352 - mae: 0.5465 - rmse: 0.7879

258/269 ━━━━━━━━━━━━━━━━━━━━ 8s 752ms/step - loss: 0.6342 - mae: 0.5460 - rmse: 0.7873

259/269 ━━━━━━━━━━━━━━━━━━━━ 7s 752ms/step - loss: 0.6333 - mae: 0.5455 - rmse: 0.7867

260/269 ━━━━━━━━━━━━━━━━━━━━ 6s 753ms/step - loss: 0.6324 - mae: 0.5450 - rmse: 0.7861

261/269 ━━━━━━━━━━━━━━━━━━━━ 6s 753ms/step - loss: 0.6315 - mae: 0.5445 - rmse: 0.7855

262/269 ━━━━━━━━━━━━━━━━━━━━ 5s 753ms/step - loss: 0.6306 - mae: 0.5440 - rmse: 0.7849

263/269 ━━━━━━━━━━━━━━━━━━━━ 4s 753ms/step - loss: 0.6297 - mae: 0.5435 - rmse: 0.7843

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 754ms/step - loss: 0.6288 - mae: 0.5430 - rmse: 0.7836

265/269 ━━━━━━━━━━━━━━━━━━━━ 3s 754ms/step - loss: 0.6279 - mae: 0.5426 - rmse: 0.7830

266/269 ━━━━━━━━━━━━━━━━━━━━ 2s 755ms/step - loss: 0.6270 - mae: 0.5421 - rmse: 0.7824

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 755ms/step - loss: 0.6261 - mae: 0.5416 - rmse: 0.7818

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 756ms/step - loss: 0.6252 - mae: 0.5411 - rmse: 0.7812

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 754ms/step - loss: 0.6244 - mae: 0.5407 - rmse: 0.7806

269/269 ━━━━━━━━━━━━━━━━━━━━ 242s 831ms/step - loss: 0.3886 - mae: 0.4139 - rmse: 0.6202 - val_loss: 0.7359 - val_mae: 0.5246 - val_rmse: 0.8556 - learning_rate: 0.0010

Epoch 16/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 472ms/step - loss: 0.8078 - mae: 0.6346 - rmse: 0.8967

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 383ms/step - loss: 0.7153 - mae: 0.6029 - rmse: 0.8416

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 381ms/step - loss: 0.7021 - mae: 0.6037 - rmse: 0.8343

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 390ms/step - loss: 0.6874 - mae: 0.6012 - rmse: 0.8256

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 379ms/step - loss: 0.6645 - mae: 0.5925 - rmse: 0.8114

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 381ms/step - loss: 0.6469 - mae: 0.5860 - rmse: 0.8003

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 380ms/step - loss: 0.6382 - mae: 0.5830 - rmse: 0.7950

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 377ms/step - loss: 0.6430 - mae: 0.5853 - rmse: 0.7981

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 377ms/step - loss: 0.6459 - mae: 0.5868 - rmse: 0.8001

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 376ms/step - loss: 0.6450 - mae: 0.5863 - rmse: 0.7996

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 378ms/step - loss: 0.6432 - mae: 0.5853 - rmse: 0.7986

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 378ms/step - loss: 0.6493 - mae: 0.5872 - rmse: 0.8024

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 387ms/step - loss: 0.6599 - mae: 0.5902 - rmse: 0.8088

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 431ms/step - loss: 0.6762 - mae: 0.5953 - rmse: 0.8182

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 470ms/step - loss: 0.6909 - mae: 0.6000 - rmse: 0.8266

 16/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 489ms/step - loss: 0.7064 - mae: 0.6051 - rmse: 0.8354

 17/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 517ms/step - loss: 0.7218 - mae: 0.6098 - rmse: 0.8440

 18/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 524ms/step - loss: 0.7347 - mae: 0.6137 - rmse: 0.8513

 19/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 528ms/step - loss: 0.7479 - mae: 0.6176 - rmse: 0.8586

 20/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 543ms/step - loss: 0.7597 - mae: 0.6211 - rmse: 0.8652

 21/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 547ms/step - loss: 0.7692 - mae: 0.6238 - rmse: 0.8705

 22/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 551ms/step - loss: 0.7778 - mae: 0.6264 - rmse: 0.8754

 23/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 554ms/step - loss: 0.7867 - mae: 0.6292 - rmse: 0.8803

 24/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 554ms/step - loss: 0.7944 - mae: 0.6318 - rmse: 0.8846

 25/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 554ms/step - loss: 0.8008 - mae: 0.6338 - rmse: 0.8883

 26/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 560ms/step - loss: 0.8073 - mae: 0.6358 - rmse: 0.8919

 27/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 559ms/step - loss: 0.8124 - mae: 0.6373 - rmse: 0.8948

 28/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 559ms/step - loss: 0.8167 - mae: 0.6386 - rmse: 0.8972

 29/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 562ms/step - loss: 0.8204 - mae: 0.6397 - rmse: 0.8994

 30/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 565ms/step - loss: 0.8231 - mae: 0.6404 - rmse: 0.9010

 31/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 574ms/step - loss: 0.8252 - mae: 0.6409 - rmse: 0.9023

 32/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 579ms/step - loss: 0.8268 - mae: 0.6413 - rmse: 0.9032

 33/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 591ms/step - loss: 0.8280 - mae: 0.6416 - rmse: 0.9040

 34/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 594ms/step - loss: 0.8289 - mae: 0.6417 - rmse: 0.9046

 35/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 597ms/step - loss: 0.8296 - mae: 0.6419 - rmse: 0.9051

 36/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 605ms/step - loss: 0.8300 - mae: 0.6420 - rmse: 0.9055

 37/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 611ms/step - loss: 0.8303 - mae: 0.6421 - rmse: 0.9057

 38/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 619ms/step - loss: 0.8302 - mae: 0.6419 - rmse: 0.9057

 39/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 627ms/step - loss: 0.8299 - mae: 0.6418 - rmse: 0.9056

 40/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 634ms/step - loss: 0.8293 - mae: 0.6415 - rmse: 0.9054

 41/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 639ms/step - loss: 0.8288 - mae: 0.6413 - rmse: 0.9052

 42/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 646ms/step - loss: 0.8281 - mae: 0.6410 - rmse: 0.9049

 43/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 651ms/step - loss: 0.8273 - mae: 0.6406 - rmse: 0.9045

 44/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 656ms/step - loss: 0.8266 - mae: 0.6403 - rmse: 0.9042

 45/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 664ms/step - loss: 0.8258 - mae: 0.6400 - rmse: 0.9038

 46/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 667ms/step - loss: 0.8249 - mae: 0.6397 - rmse: 0.9033

 47/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 668ms/step - loss: 0.8240 - mae: 0.6393 - rmse: 0.9029

 48/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 673ms/step - loss: 0.8230 - mae: 0.6389 - rmse: 0.9024

 49/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 672ms/step - loss: 0.8217 - mae: 0.6384 - rmse: 0.9017

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 671ms/step - loss: 0.8204 - mae: 0.6379 - rmse: 0.9011

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 669ms/step - loss: 0.8190 - mae: 0.6373 - rmse: 0.9003

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 667ms/step - loss: 0.8175 - mae: 0.6367 - rmse: 0.8995

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 663ms/step - loss: 0.8159 - mae: 0.6361 - rmse: 0.8987

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 664ms/step - loss: 0.8145 - mae: 0.6355 - rmse: 0.8979

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 663ms/step - loss: 0.8130 - mae: 0.6350 - rmse: 0.8971

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 663ms/step - loss: 0.8116 - mae: 0.6344 - rmse: 0.8963

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 664ms/step - loss: 0.8101 - mae: 0.6338 - rmse: 0.8955

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 667ms/step - loss: 0.8086 - mae: 0.6332 - rmse: 0.8947

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 671ms/step - loss: 0.8072 - mae: 0.6327 - rmse: 0.8940

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 676ms/step - loss: 0.8058 - mae: 0.6322 - rmse: 0.8932

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 683ms/step - loss: 0.8045 - mae: 0.6317 - rmse: 0.8925

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 686ms/step - loss: 0.8032 - mae: 0.6312 - rmse: 0.8918

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 697ms/step - loss: 0.8019 - mae: 0.6308 - rmse: 0.8911

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 708ms/step - loss: 0.8006 - mae: 0.6303 - rmse: 0.8903

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 716ms/step - loss: 0.7991 - mae: 0.6297 - rmse: 0.8895

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 722ms/step - loss: 0.7976 - mae: 0.6291 - rmse: 0.8887

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 727ms/step - loss: 0.7960 - mae: 0.6285 - rmse: 0.8878

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 726ms/step - loss: 0.7945 - mae: 0.6279 - rmse: 0.8869

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 730ms/step - loss: 0.7930 - mae: 0.6274 - rmse: 0.8861

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 730ms/step - loss: 0.7915 - mae: 0.6268 - rmse: 0.8853

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 731ms/step - loss: 0.7902 - mae: 0.6263 - rmse: 0.8846

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 736ms/step - loss: 0.7889 - mae: 0.6258 - rmse: 0.8838

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 737ms/step - loss: 0.7877 - mae: 0.6253 - rmse: 0.8831

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 737ms/step - loss: 0.7865 - mae: 0.6249 - rmse: 0.8825

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 737ms/step - loss: 0.7854 - mae: 0.6244 - rmse: 0.8819

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 737ms/step - loss: 0.7843 - mae: 0.6240 - rmse: 0.8812

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 736ms/step - loss: 0.7833 - mae: 0.6236 - rmse: 0.8807

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 733ms/step - loss: 0.7823 - mae: 0.6233 - rmse: 0.8802

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 733ms/step - loss: 0.7814 - mae: 0.6229 - rmse: 0.8797

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 739ms/step - loss: 0.7805 - mae: 0.6226 - rmse: 0.8792

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 748ms/step - loss: 0.7799 - mae: 0.6224 - rmse: 0.8788

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 754ms/step - loss: 0.7795 - mae: 0.6222 - rmse: 0.8786

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 757ms/step - loss: 0.7793 - mae: 0.6221 - rmse: 0.8785

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 759ms/step - loss: 0.7792 - mae: 0.6221 - rmse: 0.8785

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 761ms/step - loss: 0.7792 - mae: 0.6221 - rmse: 0.8785

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 761ms/step - loss: 0.7792 - mae: 0.6221 - rmse: 0.8786

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 764ms/step - loss: 0.7793 - mae: 0.6221 - rmse: 0.8786

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 766ms/step - loss: 0.7793 - mae: 0.6221 - rmse: 0.8787

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 769ms/step - loss: 0.7794 - mae: 0.6221 - rmse: 0.8787

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 769ms/step - loss: 0.7795 - mae: 0.6221 - rmse: 0.8788

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 768ms/step - loss: 0.7795 - mae: 0.6221 - rmse: 0.8788

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 766ms/step - loss: 0.7794 - mae: 0.6220 - rmse: 0.8788

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 765ms/step - loss: 0.7793 - mae: 0.6220 - rmse: 0.8788

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 767ms/step - loss: 0.7791 - mae: 0.6219 - rmse: 0.8787

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 765ms/step - loss: 0.7789 - mae: 0.6218 - rmse: 0.8786

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 766ms/step - loss: 0.7787 - mae: 0.6217 - rmse: 0.8785

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 767ms/step - loss: 0.7784 - mae: 0.6215 - rmse: 0.8783

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 766ms/step - loss: 0.7780 - mae: 0.6214 - rmse: 0.8781

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 765ms/step - loss: 0.7776 - mae: 0.6212 - rmse: 0.8779

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 764ms/step - loss: 0.7772 - mae: 0.6210 - rmse: 0.8777

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 763ms/step - loss: 0.7768 - mae: 0.6208 - rmse: 0.8775

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 763ms/step - loss: 0.7764 - mae: 0.6207 - rmse: 0.8773

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 764ms/step - loss: 0.7760 - mae: 0.6205 - rmse: 0.8770

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 766ms/step - loss: 0.7755 - mae: 0.6203 - rmse: 0.8768

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 769ms/step - loss: 0.7750 - mae: 0.6201 - rmse: 0.8765

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 770ms/step - loss: 0.7745 - mae: 0.6199 - rmse: 0.8763

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 770ms/step - loss: 0.7740 - mae: 0.6196 - rmse: 0.8760

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 770ms/step - loss: 0.7734 - mae: 0.6194 - rmse: 0.8756

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 772ms/step - loss: 0.7728 - mae: 0.6191 - rmse: 0.8753

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 771ms/step - loss: 0.7721 - mae: 0.6188 - rmse: 0.8749

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 770ms/step - loss: 0.7714 - mae: 0.6185 - rmse: 0.8745

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 769ms/step - loss: 0.7707 - mae: 0.6181 - rmse: 0.8741

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 770ms/step - loss: 0.7700 - mae: 0.6178 - rmse: 0.8737

114/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 772ms/step - loss: 0.7692 - mae: 0.6174 - rmse: 0.8732

115/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 772ms/step - loss: 0.7684 - mae: 0.6170 - rmse: 0.8728

116/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 773ms/step - loss: 0.7675 - mae: 0.6166 - rmse: 0.8723

117/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 772ms/step - loss: 0.7667 - mae: 0.6162 - rmse: 0.8718

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 772ms/step - loss: 0.7658 - mae: 0.6158 - rmse: 0.8713

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 772ms/step - loss: 0.7649 - mae: 0.6154 - rmse: 0.8708

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 771ms/step - loss: 0.7640 - mae: 0.6149 - rmse: 0.8703

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 771ms/step - loss: 0.7631 - mae: 0.6145 - rmse: 0.8697

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 770ms/step - loss: 0.7622 - mae: 0.6140 - rmse: 0.8692

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 770ms/step - loss: 0.7612 - mae: 0.6136 - rmse: 0.8686

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 770ms/step - loss: 0.7602 - mae: 0.6131 - rmse: 0.8680

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 770ms/step - loss: 0.7592 - mae: 0.6126 - rmse: 0.8675

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 769ms/step - loss: 0.7582 - mae: 0.6121 - rmse: 0.8669

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 769ms/step - loss: 0.7572 - mae: 0.6116 - rmse: 0.8662

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 770ms/step - loss: 0.7561 - mae: 0.6110 - rmse: 0.8656

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 771ms/step - loss: 0.7551 - mae: 0.6105 - rmse: 0.8650

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 770ms/step - loss: 0.7540 - mae: 0.6100 - rmse: 0.8644

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 770ms/step - loss: 0.7530 - mae: 0.6095 - rmse: 0.8637

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 768ms/step - loss: 0.7519 - mae: 0.6089 - rmse: 0.8631

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 767ms/step - loss: 0.7508 - mae: 0.6084 - rmse: 0.8625

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 765ms/step - loss: 0.7498 - mae: 0.6079 - rmse: 0.8618

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 762ms/step - loss: 0.7487 - mae: 0.6074 - rmse: 0.8612

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 760ms/step - loss: 0.7476 - mae: 0.6068 - rmse: 0.8606

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 757ms/step - loss: 0.7465 - mae: 0.6063 - rmse: 0.8599

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 754ms/step - loss: 0.7455 - mae: 0.6058 - rmse: 0.8593

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 751ms/step - loss: 0.7444 - mae: 0.6052 - rmse: 0.8586

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 748ms/step - loss: 0.7433 - mae: 0.6047 - rmse: 0.8579

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 744ms/step - loss: 0.7422 - mae: 0.6041 - rmse: 0.8573

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 741ms/step - loss: 0.7410 - mae: 0.6036 - rmse: 0.8566

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 738ms/step - loss: 0.7399 - mae: 0.6030 - rmse: 0.8559

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 735ms/step - loss: 0.7388 - mae: 0.6025 - rmse: 0.8552

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 732ms/step - loss: 0.7376 - mae: 0.6019 - rmse: 0.8545

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 730ms/step - loss: 0.7365 - mae: 0.6013 - rmse: 0.8538

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 727ms/step - loss: 0.7353 - mae: 0.6007 - rmse: 0.8531

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 725ms/step - loss: 0.7341 - mae: 0.6001 - rmse: 0.8524

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 723ms/step - loss: 0.7330 - mae: 0.5995 - rmse: 0.8517

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 722ms/step - loss: 0.7318 - mae: 0.5989 - rmse: 0.8510

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 721ms/step - loss: 0.7306 - mae: 0.5983 - rmse: 0.8502

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 720ms/step - loss: 0.7295 - mae: 0.5977 - rmse: 0.8495

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 719ms/step - loss: 0.7283 - mae: 0.5971 - rmse: 0.8488

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 718ms/step - loss: 0.7271 - mae: 0.5965 - rmse: 0.8481

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 717ms/step - loss: 0.7259 - mae: 0.5959 - rmse: 0.8473

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 719ms/step - loss: 0.7247 - mae: 0.5953 - rmse: 0.8466

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 719ms/step - loss: 0.7236 - mae: 0.5946 - rmse: 0.8459

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 719ms/step - loss: 0.7224 - mae: 0.5940 - rmse: 0.8451

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 719ms/step - loss: 0.7212 - mae: 0.5934 - rmse: 0.8444

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 720ms/step - loss: 0.7200 - mae: 0.5928 - rmse: 0.8437

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 721ms/step - loss: 0.7188 - mae: 0.5922 - rmse: 0.8429

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 722ms/step - loss: 0.7176 - mae: 0.5916 - rmse: 0.8422

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 723ms/step - loss: 0.7164 - mae: 0.5910 - rmse: 0.8414

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 725ms/step - loss: 0.7152 - mae: 0.5903 - rmse: 0.8407

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 727ms/step - loss: 0.7141 - mae: 0.5897 - rmse: 0.8400

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 727ms/step - loss: 0.7129 - mae: 0.5891 - rmse: 0.8392

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 726ms/step - loss: 0.7117 - mae: 0.5885 - rmse: 0.8385

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 727ms/step - loss: 0.7106 - mae: 0.5879 - rmse: 0.8378

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 726ms/step - loss: 0.7094 - mae: 0.5873 - rmse: 0.8370

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 725ms/step - loss: 0.7083 - mae: 0.5867 - rmse: 0.8363

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 725ms/step - loss: 0.7072 - mae: 0.5862 - rmse: 0.8356

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 725ms/step - loss: 0.7060 - mae: 0.5856 - rmse: 0.8349

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 724ms/step - loss: 0.7050 - mae: 0.5851 - rmse: 0.8342

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 723ms/step - loss: 0.7039 - mae: 0.5845 - rmse: 0.8336

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 721ms/step - loss: 0.7028 - mae: 0.5840 - rmse: 0.8329

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 720ms/step - loss: 0.7017 - mae: 0.5834 - rmse: 0.8322

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 720ms/step - loss: 0.7006 - mae: 0.5829 - rmse: 0.8315

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 720ms/step - loss: 0.6995 - mae: 0.5823 - rmse: 0.8308

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 720ms/step - loss: 0.6985 - mae: 0.5818 - rmse: 0.8302

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 719ms/step - loss: 0.6974 - mae: 0.5812 - rmse: 0.8295

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 721ms/step - loss: 0.6963 - mae: 0.5807 - rmse: 0.8288

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 722ms/step - loss: 0.6952 - mae: 0.5801 - rmse: 0.8281

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 722ms/step - loss: 0.6942 - mae: 0.5796 - rmse: 0.8274

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 722ms/step - loss: 0.6931 - mae: 0.5790 - rmse: 0.8268

185/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 723ms/step - loss: 0.6920 - mae: 0.5785 - rmse: 0.8261

186/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 723ms/step - loss: 0.6909 - mae: 0.5779 - rmse: 0.8254

187/269 ━━━━━━━━━━━━━━━━━━━━ 59s 723ms/step - loss: 0.6898 - mae: 0.5774 - rmse: 0.8247

188/269 ━━━━━━━━━━━━━━━━━━━━ 58s 722ms/step - loss: 0.6888 - mae: 0.5768 - rmse: 0.8240

189/269 ━━━━━━━━━━━━━━━━━━━━ 57s 722ms/step - loss: 0.6877 - mae: 0.5763 - rmse: 0.8233

190/269 ━━━━━━━━━━━━━━━━━━━━ 56s 721ms/step - loss: 0.6866 - mae: 0.5757 - rmse: 0.8226

191/269 ━━━━━━━━━━━━━━━━━━━━ 56s 720ms/step - loss: 0.6855 - mae: 0.5752 - rmse: 0.8219

192/269 ━━━━━━━━━━━━━━━━━━━━ 55s 721ms/step - loss: 0.6845 - mae: 0.5746 - rmse: 0.8212

193/269 ━━━━━━━━━━━━━━━━━━━━ 54s 720ms/step - loss: 0.6834 - mae: 0.5740 - rmse: 0.8206

194/269 ━━━━━━━━━━━━━━━━━━━━ 54s 721ms/step - loss: 0.6823 - mae: 0.5735 - rmse: 0.8199

195/269 ━━━━━━━━━━━━━━━━━━━━ 53s 721ms/step - loss: 0.6813 - mae: 0.5729 - rmse: 0.8192

196/269 ━━━━━━━━━━━━━━━━━━━━ 52s 722ms/step - loss: 0.6802 - mae: 0.5724 - rmse: 0.8185

197/269 ━━━━━━━━━━━━━━━━━━━━ 52s 722ms/step - loss: 0.6791 - mae: 0.5718 - rmse: 0.8178

198/269 ━━━━━━━━━━━━━━━━━━━━ 51s 723ms/step - loss: 0.6781 - mae: 0.5713 - rmse: 0.8171

199/269 ━━━━━━━━━━━━━━━━━━━━ 50s 722ms/step - loss: 0.6770 - mae: 0.5707 - rmse: 0.8164

200/269 ━━━━━━━━━━━━━━━━━━━━ 49s 724ms/step - loss: 0.6760 - mae: 0.5701 - rmse: 0.8158

201/269 ━━━━━━━━━━━━━━━━━━━━ 49s 724ms/step - loss: 0.6749 - mae: 0.5696 - rmse: 0.8151

202/269 ━━━━━━━━━━━━━━━━━━━━ 48s 724ms/step - loss: 0.6739 - mae: 0.5691 - rmse: 0.8144

203/269 ━━━━━━━━━━━━━━━━━━━━ 47s 726ms/step - loss: 0.6729 - mae: 0.5685 - rmse: 0.8137

204/269 ━━━━━━━━━━━━━━━━━━━━ 47s 727ms/step - loss: 0.6718 - mae: 0.5680 - rmse: 0.8131

205/269 ━━━━━━━━━━━━━━━━━━━━ 46s 727ms/step - loss: 0.6708 - mae: 0.5675 - rmse: 0.8124

206/269 ━━━━━━━━━━━━━━━━━━━━ 45s 727ms/step - loss: 0.6698 - mae: 0.5669 - rmse: 0.8118

207/269 ━━━━━━━━━━━━━━━━━━━━ 45s 727ms/step - loss: 0.6688 - mae: 0.5664 - rmse: 0.8111

208/269 ━━━━━━━━━━━━━━━━━━━━ 44s 727ms/step - loss: 0.6678 - mae: 0.5659 - rmse: 0.8105

209/269 ━━━━━━━━━━━━━━━━━━━━ 43s 728ms/step - loss: 0.6668 - mae: 0.5653 - rmse: 0.8098

210/269 ━━━━━━━━━━━━━━━━━━━━ 42s 728ms/step - loss: 0.6658 - mae: 0.5648 - rmse: 0.8092

211/269 ━━━━━━━━━━━━━━━━━━━━ 42s 729ms/step - loss: 0.6648 - mae: 0.5643 - rmse: 0.8085

212/269 ━━━━━━━━━━━━━━━━━━━━ 41s 729ms/step - loss: 0.6638 - mae: 0.5638 - rmse: 0.8079

213/269 ━━━━━━━━━━━━━━━━━━━━ 40s 728ms/step - loss: 0.6628 - mae: 0.5633 - rmse: 0.8072

214/269 ━━━━━━━━━━━━━━━━━━━━ 40s 728ms/step - loss: 0.6618 - mae: 0.5627 - rmse: 0.8066

215/269 ━━━━━━━━━━━━━━━━━━━━ 39s 727ms/step - loss: 0.6608 - mae: 0.5622 - rmse: 0.8059

216/269 ━━━━━━━━━━━━━━━━━━━━ 38s 727ms/step - loss: 0.6599 - mae: 0.5617 - rmse: 0.8053

217/269 ━━━━━━━━━━━━━━━━━━━━ 37s 728ms/step - loss: 0.6589 - mae: 0.5612 - rmse: 0.8046

218/269 ━━━━━━━━━━━━━━━━━━━━ 37s 728ms/step - loss: 0.6579 - mae: 0.5607 - rmse: 0.8040

219/269 ━━━━━━━━━━━━━━━━━━━━ 36s 731ms/step - loss: 0.6569 - mae: 0.5602 - rmse: 0.8033

220/269 ━━━━━━━━━━━━━━━━━━━━ 35s 733ms/step - loss: 0.6559 - mae: 0.5596 - rmse: 0.8027

221/269 ━━━━━━━━━━━━━━━━━━━━ 35s 734ms/step - loss: 0.6550 - mae: 0.5591 - rmse: 0.8021

222/269 ━━━━━━━━━━━━━━━━━━━━ 34s 733ms/step - loss: 0.6540 - mae: 0.5586 - rmse: 0.8014

223/269 ━━━━━━━━━━━━━━━━━━━━ 33s 733ms/step - loss: 0.6530 - mae: 0.5581 - rmse: 0.8008

224/269 ━━━━━━━━━━━━━━━━━━━━ 33s 733ms/step - loss: 0.6520 - mae: 0.5576 - rmse: 0.8001

225/269 ━━━━━━━━━━━━━━━━━━━━ 32s 734ms/step - loss: 0.6511 - mae: 0.5571 - rmse: 0.7995

226/269 ━━━━━━━━━━━━━━━━━━━━ 31s 734ms/step - loss: 0.6501 - mae: 0.5566 - rmse: 0.7988

227/269 ━━━━━━━━━━━━━━━━━━━━ 30s 735ms/step - loss: 0.6491 - mae: 0.5560 - rmse: 0.7982

228/269 ━━━━━━━━━━━━━━━━━━━━ 30s 737ms/step - loss: 0.6482 - mae: 0.5555 - rmse: 0.7976

229/269 ━━━━━━━━━━━━━━━━━━━━ 29s 738ms/step - loss: 0.6472 - mae: 0.5550 - rmse: 0.7969

230/269 ━━━━━━━━━━━━━━━━━━━━ 28s 739ms/step - loss: 0.6462 - mae: 0.5545 - rmse: 0.7963

231/269 ━━━━━━━━━━━━━━━━━━━━ 28s 739ms/step - loss: 0.6453 - mae: 0.5540 - rmse: 0.7956

232/269 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 0.6443 - mae: 0.5535 - rmse: 0.7950

233/269 ━━━━━━━━━━━━━━━━━━━━ 26s 739ms/step - loss: 0.6433 - mae: 0.5529 - rmse: 0.7944

234/269 ━━━━━━━━━━━━━━━━━━━━ 25s 740ms/step - loss: 0.6424 - mae: 0.5524 - rmse: 0.7937

235/269 ━━━━━━━━━━━━━━━━━━━━ 25s 740ms/step - loss: 0.6414 - mae: 0.5519 - rmse: 0.7931

236/269 ━━━━━━━━━━━━━━━━━━━━ 24s 740ms/step - loss: 0.6405 - mae: 0.5514 - rmse: 0.7924

237/269 ━━━━━━━━━━━━━━━━━━━━ 23s 740ms/step - loss: 0.6395 - mae: 0.5509 - rmse: 0.7918

238/269 ━━━━━━━━━━━━━━━━━━━━ 22s 740ms/step - loss: 0.6386 - mae: 0.5504 - rmse: 0.7912

239/269 ━━━━━━━━━━━━━━━━━━━━ 22s 739ms/step - loss: 0.6377 - mae: 0.5499 - rmse: 0.7905

240/269 ━━━━━━━━━━━━━━━━━━━━ 21s 738ms/step - loss: 0.6367 - mae: 0.5494 - rmse: 0.7899

241/269 ━━━━━━━━━━━━━━━━━━━━ 20s 738ms/step - loss: 0.6358 - mae: 0.5488 - rmse: 0.7893

242/269 ━━━━━━━━━━━━━━━━━━━━ 19s 738ms/step - loss: 0.6349 - mae: 0.5483 - rmse: 0.7887

243/269 ━━━━━━━━━━━━━━━━━━━━ 19s 738ms/step - loss: 0.6339 - mae: 0.5478 - rmse: 0.7880

244/269 ━━━━━━━━━━━━━━━━━━━━ 18s 740ms/step - loss: 0.6330 - mae: 0.5473 - rmse: 0.7874

245/269 ━━━━━━━━━━━━━━━━━━━━ 17s 740ms/step - loss: 0.6321 - mae: 0.5468 - rmse: 0.7868

246/269 ━━━━━━━━━━━━━━━━━━━━ 17s 740ms/step - loss: 0.6312 - mae: 0.5464 - rmse: 0.7862

247/269 ━━━━━━━━━━━━━━━━━━━━ 16s 741ms/step - loss: 0.6302 - mae: 0.5459 - rmse: 0.7856

248/269 ━━━━━━━━━━━━━━━━━━━━ 15s 741ms/step - loss: 0.6293 - mae: 0.5454 - rmse: 0.7849

249/269 ━━━━━━━━━━━━━━━━━━━━ 14s 742ms/step - loss: 0.6284 - mae: 0.5449 - rmse: 0.7843

250/269 ━━━━━━━━━━━━━━━━━━━━ 14s 743ms/step - loss: 0.6275 - mae: 0.5444 - rmse: 0.7837

251/269 ━━━━━━━━━━━━━━━━━━━━ 13s 743ms/step - loss: 0.6266 - mae: 0.5439 - rmse: 0.7831

252/269 ━━━━━━━━━━━━━━━━━━━━ 12s 743ms/step - loss: 0.6257 - mae: 0.5434 - rmse: 0.7825

253/269 ━━━━━━━━━━━━━━━━━━━━ 11s 745ms/step - loss: 0.6248 - mae: 0.5429 - rmse: 0.7819

254/269 ━━━━━━━━━━━━━━━━━━━━ 11s 745ms/step - loss: 0.6239 - mae: 0.5425 - rmse: 0.7813

255/269 ━━━━━━━━━━━━━━━━━━━━ 10s 745ms/step - loss: 0.6230 - mae: 0.5420 - rmse: 0.7807

256/269 ━━━━━━━━━━━━━━━━━━━━ 9s 745ms/step - loss: 0.6221 - mae: 0.5415 - rmse: 0.7800

257/269 ━━━━━━━━━━━━━━━━━━━━ 8s 745ms/step - loss: 0.6212 - mae: 0.5410 - rmse: 0.7794

258/269 ━━━━━━━━━━━━━━━━━━━━ 8s 744ms/step - loss: 0.6204 - mae: 0.5405 - rmse: 0.7788

259/269 ━━━━━━━━━━━━━━━━━━━━ 7s 744ms/step - loss: 0.6195 - mae: 0.5401 - rmse: 0.7782

260/269 ━━━━━━━━━━━━━━━━━━━━ 6s 743ms/step - loss: 0.6186 - mae: 0.5396 - rmse: 0.7776

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 743ms/step - loss: 0.6177 - mae: 0.5391 - rmse: 0.7770

262/269 ━━━━━━━━━━━━━━━━━━━━ 5s 742ms/step - loss: 0.6168 - mae: 0.5386 - rmse: 0.7764

263/269 ━━━━━━━━━━━━━━━━━━━━ 4s 741ms/step - loss: 0.6160 - mae: 0.5382 - rmse: 0.7758

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 741ms/step - loss: 0.6151 - mae: 0.5377 - rmse: 0.7752

265/269 ━━━━━━━━━━━━━━━━━━━━ 2s 740ms/step - loss: 0.6142 - mae: 0.5372 - rmse: 0.7746

266/269 ━━━━━━━━━━━━━━━━━━━━ 2s 740ms/step - loss: 0.6134 - mae: 0.5367 - rmse: 0.7740

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 739ms/step - loss: 0.6125 - mae: 0.5363 - rmse: 0.7735

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 738ms/step - loss: 0.6116 - mae: 0.5358 - rmse: 0.7729

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 736ms/step - loss: 0.6108 - mae: 0.5353 - rmse: 0.7723

Epoch 16: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

269/269 ━━━━━━━━━━━━━━━━━━━━ 215s 800ms/step - loss: 0.3824 - mae: 0.4113 - rmse: 0.6153 - val_loss: 0.7386 - val_mae: 0.5261 - val_rmse: 0.8572 - learning_rate: 0.0010

Epoch 17/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 680ms/step - loss: 0.8752 - mae: 0.6419 - rmse: 0.9335

  2/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 556ms/step - loss: 0.7732 - mae: 0.6089 - rmse: 0.8752

  3/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 592ms/step - loss: 0.7466 - mae: 0.6064 - rmse: 0.8603

  4/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 690ms/step - loss: 0.7236 - mae: 0.6021 - rmse: 0.8469

  5/269 ━━━━━━━━━━━━━━━━━━━━ 3:09 719ms/step - loss: 0.6953 - mae: 0.5922 - rmse: 0.8297

  6/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 756ms/step - loss: 0.6761 - mae: 0.5859 - rmse: 0.8179

  7/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 771ms/step - loss: 0.6671 - mae: 0.5835 - rmse: 0.8126

  8/269 ━━━━━━━━━━━━━━━━━━━━ 3:24 785ms/step - loss: 0.6698 - mae: 0.5856 - rmse: 0.8145

  9/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 821ms/step - loss: 0.6698 - mae: 0.5862 - rmse: 0.8146

 10/269 ━━━━━━━━━━━━━━━━━━━━ 3:33 823ms/step - loss: 0.6663 - mae: 0.5851 - rmse: 0.8126

 11/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 831ms/step - loss: 0.6624 - mae: 0.5836 - rmse: 0.8103

 12/269 ━━━━━━━━━━━━━━━━━━━━ 3:37 847ms/step - loss: 0.6661 - mae: 0.5849 - rmse: 0.8126

 13/269 ━━━━━━━━━━━━━━━━━━━━ 3:38 854ms/step - loss: 0.6750 - mae: 0.5876 - rmse: 0.8180

 14/269 ━━━━━━━━━━━━━━━━━━━━ 3:39 860ms/step - loss: 0.6886 - mae: 0.5922 - rmse: 0.8258

 15/269 ━━━━━━━━━━━━━━━━━━━━ 3:34 845ms/step - loss: 0.7013 - mae: 0.5967 - rmse: 0.8332

 16/269 ━━━━━━━━━━━━━━━━━━━━ 3:29 829ms/step - loss: 0.7151 - mae: 0.6016 - rmse: 0.8410

 17/269 ━━━━━━━━━━━━━━━━━━━━ 3:27 823ms/step - loss: 0.7289 - mae: 0.6062 - rmse: 0.8487

 18/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 804ms/step - loss: 0.7401 - mae: 0.6099 - rmse: 0.8551

 19/269 ━━━━━━━━━━━━━━━━━━━━ 3:15 781ms/step - loss: 0.7516 - mae: 0.6135 - rmse: 0.8615

 20/269 ━━━━━━━━━━━━━━━━━━━━ 3:10 766ms/step - loss: 0.7614 - mae: 0.6166 - rmse: 0.8670

 21/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 760ms/step - loss: 0.7691 - mae: 0.6189 - rmse: 0.8713

 22/269 ━━━━━━━━━━━━━━━━━━━━ 3:06 754ms/step - loss: 0.7765 - mae: 0.6213 - rmse: 0.8755

 23/269 ━━━━━━━━━━━━━━━━━━━━ 3:04 748ms/step - loss: 0.7843 - mae: 0.6240 - rmse: 0.8799

 24/269 ━━━━━━━━━━━━━━━━━━━━ 3:02 743ms/step - loss: 0.7912 - mae: 0.6264 - rmse: 0.8838

 25/269 ━━━━━━━━━━━━━━━━━━━━ 3:00 738ms/step - loss: 0.7968 - mae: 0.6283 - rmse: 0.8870

 26/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 732ms/step - loss: 0.8024 - mae: 0.6301 - rmse: 0.8901

 27/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 732ms/step - loss: 0.8067 - mae: 0.6316 - rmse: 0.8926

 28/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 736ms/step - loss: 0.8103 - mae: 0.6328 - rmse: 0.8946

 29/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 733ms/step - loss: 0.8134 - mae: 0.6338 - rmse: 0.8964

 30/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 728ms/step - loss: 0.8156 - mae: 0.6346 - rmse: 0.8977

 31/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 731ms/step - loss: 0.8172 - mae: 0.6351 - rmse: 0.8987

 32/269 ━━━━━━━━━━━━━━━━━━━━ 2:52 726ms/step - loss: 0.8184 - mae: 0.6354 - rmse: 0.8995

 33/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 727ms/step - loss: 0.8193 - mae: 0.6357 - rmse: 0.9000

 34/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 751ms/step - loss: 0.8198 - mae: 0.6359 - rmse: 0.9004

 35/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 755ms/step - loss: 0.8202 - mae: 0.6361 - rmse: 0.9007

 36/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 760ms/step - loss: 0.8202 - mae: 0.6361 - rmse: 0.9008

 37/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 764ms/step - loss: 0.8202 - mae: 0.6362 - rmse: 0.9009

 38/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 770ms/step - loss: 0.8199 - mae: 0.6361 - rmse: 0.9008

 39/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 770ms/step - loss: 0.8193 - mae: 0.6359 - rmse: 0.9005

 40/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 771ms/step - loss: 0.8185 - mae: 0.6357 - rmse: 0.9001

 41/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 771ms/step - loss: 0.8178 - mae: 0.6355 - rmse: 0.8998

 42/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 772ms/step - loss: 0.8169 - mae: 0.6351 - rmse: 0.8994

 43/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 770ms/step - loss: 0.8159 - mae: 0.6348 - rmse: 0.8988

 44/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 775ms/step - loss: 0.8150 - mae: 0.6345 - rmse: 0.8984

 45/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 775ms/step - loss: 0.8141 - mae: 0.6342 - rmse: 0.8979

 46/269 ━━━━━━━━━━━━━━━━━━━━ 2:52 772ms/step - loss: 0.8129 - mae: 0.6338 - rmse: 0.8973

 47/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 770ms/step - loss: 0.8118 - mae: 0.6335 - rmse: 0.8968

 48/269 ━━━━━━━━━━━━━━━━━━━━ 2:50 771ms/step - loss: 0.8106 - mae: 0.6330 - rmse: 0.8961

 49/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 770ms/step - loss: 0.8091 - mae: 0.6325 - rmse: 0.8953

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 773ms/step - loss: 0.8076 - mae: 0.6319 - rmse: 0.8945

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 770ms/step - loss: 0.8060 - mae: 0.6313 - rmse: 0.8936

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 770ms/step - loss: 0.8043 - mae: 0.6306 - rmse: 0.8927

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 771ms/step - loss: 0.8026 - mae: 0.6300 - rmse: 0.8918

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 774ms/step - loss: 0.8011 - mae: 0.6294 - rmse: 0.8909

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 777ms/step - loss: 0.7995 - mae: 0.6288 - rmse: 0.8900

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 780ms/step - loss: 0.7980 - mae: 0.6282 - rmse: 0.8892

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 784ms/step - loss: 0.7964 - mae: 0.6276 - rmse: 0.8883

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 791ms/step - loss: 0.7948 - mae: 0.6270 - rmse: 0.8874

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 794ms/step - loss: 0.7933 - mae: 0.6265 - rmse: 0.8866

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 798ms/step - loss: 0.7918 - mae: 0.6260 - rmse: 0.8857

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 800ms/step - loss: 0.7904 - mae: 0.6255 - rmse: 0.8850

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 801ms/step - loss: 0.7890 - mae: 0.6250 - rmse: 0.8842

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 803ms/step - loss: 0.7876 - mae: 0.6246 - rmse: 0.8834

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 805ms/step - loss: 0.7862 - mae: 0.6241 - rmse: 0.8826

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 804ms/step - loss: 0.7847 - mae: 0.6235 - rmse: 0.8817

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 801ms/step - loss: 0.7831 - mae: 0.6229 - rmse: 0.8808

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 800ms/step - loss: 0.7814 - mae: 0.6223 - rmse: 0.8799

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:40 797ms/step - loss: 0.7798 - mae: 0.6217 - rmse: 0.8790

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 795ms/step - loss: 0.7783 - mae: 0.6211 - rmse: 0.8781

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 795ms/step - loss: 0.7768 - mae: 0.6206 - rmse: 0.8772

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:37 793ms/step - loss: 0.7754 - mae: 0.6201 - rmse: 0.8765

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 790ms/step - loss: 0.7740 - mae: 0.6195 - rmse: 0.8757

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 794ms/step - loss: 0.7727 - mae: 0.6191 - rmse: 0.8749

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 797ms/step - loss: 0.7715 - mae: 0.6186 - rmse: 0.8742

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 800ms/step - loss: 0.7703 - mae: 0.6181 - rmse: 0.8736

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:34 802ms/step - loss: 0.7691 - mae: 0.6177 - rmse: 0.8729

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:34 804ms/step - loss: 0.7680 - mae: 0.6173 - rmse: 0.8723

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 805ms/step - loss: 0.7670 - mae: 0.6169 - rmse: 0.8717

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 805ms/step - loss: 0.7660 - mae: 0.6165 - rmse: 0.8712

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 807ms/step - loss: 0.7650 - mae: 0.6162 - rmse: 0.8706

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 807ms/step - loss: 0.7643 - mae: 0.6159 - rmse: 0.8702

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 809ms/step - loss: 0.7638 - mae: 0.6157 - rmse: 0.8699

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:30 808ms/step - loss: 0.7634 - mae: 0.6156 - rmse: 0.8697

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 806ms/step - loss: 0.7632 - mae: 0.6155 - rmse: 0.8696

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 804ms/step - loss: 0.7631 - mae: 0.6155 - rmse: 0.8696

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:27 803ms/step - loss: 0.7630 - mae: 0.6154 - rmse: 0.8696

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 802ms/step - loss: 0.7630 - mae: 0.6154 - rmse: 0.8696

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:24 799ms/step - loss: 0.7629 - mae: 0.6153 - rmse: 0.8695

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 798ms/step - loss: 0.7628 - mae: 0.6153 - rmse: 0.8695

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 797ms/step - loss: 0.7628 - mae: 0.6153 - rmse: 0.8695

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 797ms/step - loss: 0.7627 - mae: 0.6152 - rmse: 0.8695

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 800ms/step - loss: 0.7626 - mae: 0.6151 - rmse: 0.8694

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 799ms/step - loss: 0.7624 - mae: 0.6150 - rmse: 0.8693

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 801ms/step - loss: 0.7621 - mae: 0.6149 - rmse: 0.8692

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 805ms/step - loss: 0.7618 - mae: 0.6148 - rmse: 0.8690

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 806ms/step - loss: 0.7615 - mae: 0.6146 - rmse: 0.8689

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 808ms/step - loss: 0.7611 - mae: 0.6144 - rmse: 0.8687

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 810ms/step - loss: 0.7607 - mae: 0.6142 - rmse: 0.8684

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 809ms/step - loss: 0.7602 - mae: 0.6140 - rmse: 0.8682

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 810ms/step - loss: 0.7598 - mae: 0.6138 - rmse: 0.8679

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 807ms/step - loss: 0.7593 - mae: 0.6136 - rmse: 0.8677

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 808ms/step - loss: 0.7588 - mae: 0.6134 - rmse: 0.8674

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 807ms/step - loss: 0.7583 - mae: 0.6132 - rmse: 0.8671

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 806ms/step - loss: 0.7578 - mae: 0.6130 - rmse: 0.8669

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 813ms/step - loss: 0.7573 - mae: 0.6128 - rmse: 0.8666

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 818ms/step - loss: 0.7568 - mae: 0.6126 - rmse: 0.8663

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 818ms/step - loss: 0.7562 - mae: 0.6123 - rmse: 0.8660

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 821ms/step - loss: 0.7556 - mae: 0.6120 - rmse: 0.8656

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 824ms/step - loss: 0.7550 - mae: 0.6117 - rmse: 0.8652

110/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 827ms/step - loss: 0.7543 - mae: 0.6114 - rmse: 0.8648

111/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 829ms/step - loss: 0.7535 - mae: 0.6111 - rmse: 0.8644

112/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 829ms/step - loss: 0.7528 - mae: 0.6107 - rmse: 0.8640

113/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 828ms/step - loss: 0.7520 - mae: 0.6104 - rmse: 0.8635

114/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 829ms/step - loss: 0.7512 - mae: 0.6100 - rmse: 0.8631

115/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 829ms/step - loss: 0.7504 - mae: 0.6096 - rmse: 0.8626

116/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 826ms/step - loss: 0.7496 - mae: 0.6092 - rmse: 0.8621

117/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 823ms/step - loss: 0.7487 - mae: 0.6088 - rmse: 0.8616

118/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 820ms/step - loss: 0.7478 - mae: 0.6084 - rmse: 0.8611

119/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 817ms/step - loss: 0.7469 - mae: 0.6079 - rmse: 0.8606

120/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 814ms/step - loss: 0.7460 - mae: 0.6075 - rmse: 0.8600

121/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 811ms/step - loss: 0.7451 - mae: 0.6071 - rmse: 0.8595

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 809ms/step - loss: 0.7441 - mae: 0.6066 - rmse: 0.8589

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 806ms/step - loss: 0.7431 - mae: 0.6061 - rmse: 0.8583

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 802ms/step - loss: 0.7422 - mae: 0.6056 - rmse: 0.8577

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 799ms/step - loss: 0.7411 - mae: 0.6051 - rmse: 0.8571

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 796ms/step - loss: 0.7401 - mae: 0.6046 - rmse: 0.8565

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:52 794ms/step - loss: 0.7391 - mae: 0.6041 - rmse: 0.8559

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 791ms/step - loss: 0.7381 - mae: 0.6036 - rmse: 0.8553

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 789ms/step - loss: 0.7370 - mae: 0.6031 - rmse: 0.8547

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 794ms/step - loss: 0.7359 - mae: 0.6026 - rmse: 0.8540

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 793ms/step - loss: 0.7349 - mae: 0.6021 - rmse: 0.8534

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 790ms/step - loss: 0.7338 - mae: 0.6015 - rmse: 0.8527

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 788ms/step - loss: 0.7327 - mae: 0.6010 - rmse: 0.8521

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 787ms/step - loss: 0.7317 - mae: 0.6005 - rmse: 0.8514

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 787ms/step - loss: 0.7306 - mae: 0.6000 - rmse: 0.8508

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 786ms/step - loss: 0.7295 - mae: 0.5994 - rmse: 0.8501

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 785ms/step - loss: 0.7285 - mae: 0.5989 - rmse: 0.8495

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 785ms/step - loss: 0.7274 - mae: 0.5984 - rmse: 0.8488

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 783ms/step - loss: 0.7263 - mae: 0.5979 - rmse: 0.8482

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 781ms/step - loss: 0.7252 - mae: 0.5973 - rmse: 0.8475

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 781ms/step - loss: 0.7241 - mae: 0.5968 - rmse: 0.8468

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 779ms/step - loss: 0.7230 - mae: 0.5962 - rmse: 0.8462

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 777ms/step - loss: 0.7219 - mae: 0.5957 - rmse: 0.8455

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 776ms/step - loss: 0.7208 - mae: 0.5951 - rmse: 0.8448

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 774ms/step - loss: 0.7196 - mae: 0.5945 - rmse: 0.8441

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 772ms/step - loss: 0.7185 - mae: 0.5940 - rmse: 0.8434

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 769ms/step - loss: 0.7174 - mae: 0.5934 - rmse: 0.8427

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 766ms/step - loss: 0.7162 - mae: 0.5928 - rmse: 0.8420

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 763ms/step - loss: 0.7150 - mae: 0.5922 - rmse: 0.8412

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 760ms/step - loss: 0.7139 - mae: 0.5916 - rmse: 0.8405

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 758ms/step - loss: 0.7127 - mae: 0.5910 - rmse: 0.8398

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 755ms/step - loss: 0.7116 - mae: 0.5904 - rmse: 0.8391

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 752ms/step - loss: 0.7104 - mae: 0.5898 - rmse: 0.8383

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 749ms/step - loss: 0.7092 - mae: 0.5892 - rmse: 0.8376

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 746ms/step - loss: 0.7081 - mae: 0.5886 - rmse: 0.8369

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 744ms/step - loss: 0.7069 - mae: 0.5880 - rmse: 0.8361

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 742ms/step - loss: 0.7057 - mae: 0.5874 - rmse: 0.8354

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 741ms/step - loss: 0.7046 - mae: 0.5868 - rmse: 0.8347

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 739ms/step - loss: 0.7034 - mae: 0.5861 - rmse: 0.8339

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 738ms/step - loss: 0.7022 - mae: 0.5855 - rmse: 0.8332

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 736ms/step - loss: 0.7011 - mae: 0.5849 - rmse: 0.8325

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 734ms/step - loss: 0.6999 - mae: 0.5843 - rmse: 0.8317

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 732ms/step - loss: 0.6987 - mae: 0.5837 - rmse: 0.8310

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 730ms/step - loss: 0.6975 - mae: 0.5831 - rmse: 0.8302

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 729ms/step - loss: 0.6964 - mae: 0.5825 - rmse: 0.8295

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 726ms/step - loss: 0.6952 - mae: 0.5819 - rmse: 0.8288

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 725ms/step - loss: 0.6941 - mae: 0.5813 - rmse: 0.8280

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 724ms/step - loss: 0.6929 - mae: 0.5807 - rmse: 0.8273

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 722ms/step - loss: 0.6918 - mae: 0.5801 - rmse: 0.8266

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 720ms/step - loss: 0.6907 - mae: 0.5796 - rmse: 0.8259

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 719ms/step - loss: 0.6896 - mae: 0.5790 - rmse: 0.8252

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 717ms/step - loss: 0.6885 - mae: 0.5784 - rmse: 0.8245

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 716ms/step - loss: 0.6874 - mae: 0.5779 - rmse: 0.8238

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 715ms/step - loss: 0.6863 - mae: 0.5773 - rmse: 0.8231

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 713ms/step - loss: 0.6853 - mae: 0.5768 - rmse: 0.8224

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 712ms/step - loss: 0.6842 - mae: 0.5762 - rmse: 0.8218

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 713ms/step - loss: 0.6831 - mae: 0.5757 - rmse: 0.8211

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 714ms/step - loss: 0.6821 - mae: 0.5752 - rmse: 0.8204

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 715ms/step - loss: 0.6810 - mae: 0.5746 - rmse: 0.8197

180/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 713ms/step - loss: 0.6800 - mae: 0.5741 - rmse: 0.8190

181/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 712ms/step - loss: 0.6789 - mae: 0.5735 - rmse: 0.8184

182/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 711ms/step - loss: 0.6778 - mae: 0.5730 - rmse: 0.8177

183/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 710ms/step - loss: 0.6768 - mae: 0.5724 - rmse: 0.8170

184/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 709ms/step - loss: 0.6757 - mae: 0.5719 - rmse: 0.8163

185/269 ━━━━━━━━━━━━━━━━━━━━ 59s 708ms/step - loss: 0.6746 - mae: 0.5714 - rmse: 0.8156

186/269 ━━━━━━━━━━━━━━━━━━━━ 58s 707ms/step - loss: 0.6736 - mae: 0.5708 - rmse: 0.8149

187/269 ━━━━━━━━━━━━━━━━━━━━ 57s 707ms/step - loss: 0.6725 - mae: 0.5703 - rmse: 0.8142

188/269 ━━━━━━━━━━━━━━━━━━━━ 57s 706ms/step - loss: 0.6714 - mae: 0.5697 - rmse: 0.8135

189/269 ━━━━━━━━━━━━━━━━━━━━ 56s 704ms/step - loss: 0.6704 - mae: 0.5691 - rmse: 0.8128

190/269 ━━━━━━━━━━━━━━━━━━━━ 55s 703ms/step - loss: 0.6693 - mae: 0.5686 - rmse: 0.8122

191/269 ━━━━━━━━━━━━━━━━━━━━ 54s 701ms/step - loss: 0.6682 - mae: 0.5680 - rmse: 0.8115

192/269 ━━━━━━━━━━━━━━━━━━━━ 53s 700ms/step - loss: 0.6672 - mae: 0.5675 - rmse: 0.8108

193/269 ━━━━━━━━━━━━━━━━━━━━ 53s 699ms/step - loss: 0.6661 - mae: 0.5669 - rmse: 0.8101

194/269 ━━━━━━━━━━━━━━━━━━━━ 52s 698ms/step - loss: 0.6651 - mae: 0.5664 - rmse: 0.8094

195/269 ━━━━━━━━━━━━━━━━━━━━ 51s 697ms/step - loss: 0.6640 - mae: 0.5658 - rmse: 0.8087

196/269 ━━━━━━━━━━━━━━━━━━━━ 50s 696ms/step - loss: 0.6630 - mae: 0.5653 - rmse: 0.8080

197/269 ━━━━━━━━━━━━━━━━━━━━ 50s 695ms/step - loss: 0.6619 - mae: 0.5647 - rmse: 0.8073

198/269 ━━━━━━━━━━━━━━━━━━━━ 49s 697ms/step - loss: 0.6609 - mae: 0.5642 - rmse: 0.8067

199/269 ━━━━━━━━━━━━━━━━━━━━ 48s 699ms/step - loss: 0.6598 - mae: 0.5636 - rmse: 0.8060

200/269 ━━━━━━━━━━━━━━━━━━━━ 48s 702ms/step - loss: 0.6588 - mae: 0.5631 - rmse: 0.8053

201/269 ━━━━━━━━━━━━━━━━━━━━ 47s 702ms/step - loss: 0.6578 - mae: 0.5625 - rmse: 0.8046

202/269 ━━━━━━━━━━━━━━━━━━━━ 46s 700ms/step - loss: 0.6568 - mae: 0.5620 - rmse: 0.8040

203/269 ━━━━━━━━━━━━━━━━━━━━ 46s 699ms/step - loss: 0.6558 - mae: 0.5614 - rmse: 0.8033

204/269 ━━━━━━━━━━━━━━━━━━━━ 45s 698ms/step - loss: 0.6547 - mae: 0.5609 - rmse: 0.8026

205/269 ━━━━━━━━━━━━━━━━━━━━ 44s 697ms/step - loss: 0.6538 - mae: 0.5604 - rmse: 0.8020

206/269 ━━━━━━━━━━━━━━━━━━━━ 43s 695ms/step - loss: 0.6528 - mae: 0.5599 - rmse: 0.8013

207/269 ━━━━━━━━━━━━━━━━━━━━ 43s 695ms/step - loss: 0.6518 - mae: 0.5593 - rmse: 0.8007

208/269 ━━━━━━━━━━━━━━━━━━━━ 42s 693ms/step - loss: 0.6508 - mae: 0.5588 - rmse: 0.8000

209/269 ━━━━━━━━━━━━━━━━━━━━ 41s 693ms/step - loss: 0.6498 - mae: 0.5583 - rmse: 0.7994

210/269 ━━━━━━━━━━━━━━━━━━━━ 40s 692ms/step - loss: 0.6488 - mae: 0.5578 - rmse: 0.7987

211/269 ━━━━━━━━━━━━━━━━━━━━ 40s 691ms/step - loss: 0.6478 - mae: 0.5573 - rmse: 0.7981

212/269 ━━━━━━━━━━━━━━━━━━━━ 39s 690ms/step - loss: 0.6469 - mae: 0.5567 - rmse: 0.7974

213/269 ━━━━━━━━━━━━━━━━━━━━ 38s 690ms/step - loss: 0.6459 - mae: 0.5562 - rmse: 0.7968

214/269 ━━━━━━━━━━━━━━━━━━━━ 37s 690ms/step - loss: 0.6449 - mae: 0.5557 - rmse: 0.7961

215/269 ━━━━━━━━━━━━━━━━━━━━ 37s 689ms/step - loss: 0.6439 - mae: 0.5552 - rmse: 0.7955

216/269 ━━━━━━━━━━━━━━━━━━━━ 36s 688ms/step - loss: 0.6430 - mae: 0.5547 - rmse: 0.7949

217/269 ━━━━━━━━━━━━━━━━━━━━ 35s 688ms/step - loss: 0.6420 - mae: 0.5542 - rmse: 0.7942

218/269 ━━━━━━━━━━━━━━━━━━━━ 35s 687ms/step - loss: 0.6411 - mae: 0.5537 - rmse: 0.7936

219/269 ━━━━━━━━━━━━━━━━━━━━ 34s 686ms/step - loss: 0.6401 - mae: 0.5531 - rmse: 0.7929

220/269 ━━━━━━━━━━━━━━━━━━━━ 33s 685ms/step - loss: 0.6391 - mae: 0.5526 - rmse: 0.7923

221/269 ━━━━━━━━━━━━━━━━━━━━ 32s 684ms/step - loss: 0.6382 - mae: 0.5521 - rmse: 0.7917

222/269 ━━━━━━━━━━━━━━━━━━━━ 32s 683ms/step - loss: 0.6372 - mae: 0.5516 - rmse: 0.7910

223/269 ━━━━━━━━━━━━━━━━━━━━ 31s 681ms/step - loss: 0.6363 - mae: 0.5511 - rmse: 0.7904

224/269 ━━━━━━━━━━━━━━━━━━━━ 30s 680ms/step - loss: 0.6353 - mae: 0.5506 - rmse: 0.7897

225/269 ━━━━━━━━━━━━━━━━━━━━ 29s 679ms/step - loss: 0.6344 - mae: 0.5501 - rmse: 0.7891

226/269 ━━━━━━━━━━━━━━━━━━━━ 29s 680ms/step - loss: 0.6334 - mae: 0.5496 - rmse: 0.7885

227/269 ━━━━━━━━━━━━━━━━━━━━ 28s 679ms/step - loss: 0.6325 - mae: 0.5491 - rmse: 0.7878

228/269 ━━━━━━━━━━━━━━━━━━━━ 27s 678ms/step - loss: 0.6315 - mae: 0.5485 - rmse: 0.7872

229/269 ━━━━━━━━━━━━━━━━━━━━ 27s 678ms/step - loss: 0.6306 - mae: 0.5480 - rmse: 0.7865

230/269 ━━━━━━━━━━━━━━━━━━━━ 26s 678ms/step - loss: 0.6296 - mae: 0.5475 - rmse: 0.7859

231/269 ━━━━━━━━━━━━━━━━━━━━ 25s 677ms/step - loss: 0.6287 - mae: 0.5470 - rmse: 0.7853

232/269 ━━━━━━━━━━━━━━━━━━━━ 25s 676ms/step - loss: 0.6277 - mae: 0.5465 - rmse: 0.7846

233/269 ━━━━━━━━━━━━━━━━━━━━ 24s 675ms/step - loss: 0.6268 - mae: 0.5460 - rmse: 0.7840

234/269 ━━━━━━━━━━━━━━━━━━━━ 23s 674ms/step - loss: 0.6258 - mae: 0.5455 - rmse: 0.7834

235/269 ━━━━━━━━━━━━━━━━━━━━ 22s 673ms/step - loss: 0.6249 - mae: 0.5450 - rmse: 0.7827

236/269 ━━━━━━━━━━━━━━━━━━━━ 22s 671ms/step - loss: 0.6240 - mae: 0.5444 - rmse: 0.7821

237/269 ━━━━━━━━━━━━━━━━━━━━ 21s 669ms/step - loss: 0.6231 - mae: 0.5439 - rmse: 0.7815

238/269 ━━━━━━━━━━━━━━━━━━━━ 20s 668ms/step - loss: 0.6221 - mae: 0.5434 - rmse: 0.7808

239/269 ━━━━━━━━━━━━━━━━━━━━ 20s 667ms/step - loss: 0.6212 - mae: 0.5429 - rmse: 0.7802

240/269 ━━━━━━━━━━━━━━━━━━━━ 19s 667ms/step - loss: 0.6203 - mae: 0.5424 - rmse: 0.7796

241/269 ━━━━━━━━━━━━━━━━━━━━ 18s 666ms/step - loss: 0.6194 - mae: 0.5419 - rmse: 0.7789

242/269 ━━━━━━━━━━━━━━━━━━━━ 17s 666ms/step - loss: 0.6185 - mae: 0.5414 - rmse: 0.7783

243/269 ━━━━━━━━━━━━━━━━━━━━ 17s 665ms/step - loss: 0.6175 - mae: 0.5409 - rmse: 0.7777

244/269 ━━━━━━━━━━━━━━━━━━━━ 16s 664ms/step - loss: 0.6166 - mae: 0.5404 - rmse: 0.7771

245/269 ━━━━━━━━━━━━━━━━━━━━ 15s 663ms/step - loss: 0.6157 - mae: 0.5399 - rmse: 0.7765

246/269 ━━━━━━━━━━━━━━━━━━━━ 15s 662ms/step - loss: 0.6148 - mae: 0.5395 - rmse: 0.7758

247/269 ━━━━━━━━━━━━━━━━━━━━ 14s 661ms/step - loss: 0.6139 - mae: 0.5390 - rmse: 0.7752

248/269 ━━━━━━━━━━━━━━━━━━━━ 13s 660ms/step - loss: 0.6130 - mae: 0.5385 - rmse: 0.7746

249/269 ━━━━━━━━━━━━━━━━━━━━ 13s 659ms/step - loss: 0.6122 - mae: 0.5380 - rmse: 0.7740

250/269 ━━━━━━━━━━━━━━━━━━━━ 12s 659ms/step - loss: 0.6113 - mae: 0.5375 - rmse: 0.7734

251/269 ━━━━━━━━━━━━━━━━━━━━ 11s 658ms/step - loss: 0.6104 - mae: 0.5370 - rmse: 0.7728

252/269 ━━━━━━━━━━━━━━━━━━━━ 11s 657ms/step - loss: 0.6095 - mae: 0.5365 - rmse: 0.7722

253/269 ━━━━━━━━━━━━━━━━━━━━ 10s 656ms/step - loss: 0.6086 - mae: 0.5361 - rmse: 0.7716

254/269 ━━━━━━━━━━━━━━━━━━━━ 9s 655ms/step - loss: 0.6077 - mae: 0.5356 - rmse: 0.7710

255/269 ━━━━━━━━━━━━━━━━━━━━ 9s 654ms/step - loss: 0.6069 - mae: 0.5351 - rmse: 0.7704

256/269 ━━━━━━━━━━━━━━━━━━━━ 8s 653ms/step - loss: 0.6060 - mae: 0.5346 - rmse: 0.7698

257/269 ━━━━━━━━━━━━━━━━━━━━ 7s 652ms/step - loss: 0.6051 - mae: 0.5342 - rmse: 0.7692

258/269 ━━━━━━━━━━━━━━━━━━━━ 7s 651ms/step - loss: 0.6042 - mae: 0.5337 - rmse: 0.7686

259/269 ━━━━━━━━━━━━━━━━━━━━ 6s 651ms/step - loss: 0.6034 - mae: 0.5332 - rmse: 0.7680

260/269 ━━━━━━━━━━━━━━━━━━━━ 5s 650ms/step - loss: 0.6025 - mae: 0.5327 - rmse: 0.7674

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 649ms/step - loss: 0.6017 - mae: 0.5323 - rmse: 0.7668

262/269 ━━━━━━━━━━━━━━━━━━━━ 4s 648ms/step - loss: 0.6008 - mae: 0.5318 - rmse: 0.7662

263/269 ━━━━━━━━━━━━━━━━━━━━ 3s 647ms/step - loss: 0.5999 - mae: 0.5313 - rmse: 0.7656

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 646ms/step - loss: 0.5991 - mae: 0.5309 - rmse: 0.7650

265/269 ━━━━━━━━━━━━━━━━━━━━ 2s 646ms/step - loss: 0.5982 - mae: 0.5304 - rmse: 0.7644

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 645ms/step - loss: 0.5974 - mae: 0.5299 - rmse: 0.7638

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 644ms/step - loss: 0.5966 - mae: 0.5294 - rmse: 0.7632

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 643ms/step - loss: 0.5957 - mae: 0.5290 - rmse: 0.7626

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 641ms/step - loss: 0.5949 - mae: 0.5285 - rmse: 0.7620

269/269 ━━━━━━━━━━━━━━━━━━━━ 185s 686ms/step - loss: 0.3712 - mae: 0.4054 - rmse: 0.6061 - val_loss: 0.7311 - val_mae: 0.5282 - val_rmse: 0.8528 - learning_rate: 5.0000e-04

Epoch 18/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 613ms/step - loss: 0.7156 - mae: 0.6069 - rmse: 0.8437

  2/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 497ms/step - loss: 0.6554 - mae: 0.5816 - rmse: 0.8064

  3/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 476ms/step - loss: 0.6584 - mae: 0.5878 - rmse: 0.8085

  4/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 458ms/step - loss: 0.6486 - mae: 0.5867 - rmse: 0.8025

  5/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 474ms/step - loss: 0.6310 - mae: 0.5801 - rmse: 0.7912

  6/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 479ms/step - loss: 0.6190 - mae: 0.5760 - rmse: 0.7836

  7/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 473ms/step - loss: 0.6130 - mae: 0.5740 - rmse: 0.7798

  8/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 473ms/step - loss: 0.6190 - mae: 0.5769 - rmse: 0.7837

  9/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 476ms/step - loss: 0.6230 - mae: 0.5787 - rmse: 0.7863

 10/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 469ms/step - loss: 0.6228 - mae: 0.5784 - rmse: 0.7862

 11/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 470ms/step - loss: 0.6215 - mae: 0.5775 - rmse: 0.7854

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 464ms/step - loss: 0.6283 - mae: 0.5797 - rmse: 0.7896

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 463ms/step - loss: 0.6395 - mae: 0.5830 - rmse: 0.7964

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 460ms/step - loss: 0.6556 - mae: 0.5883 - rmse: 0.8058

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 458ms/step - loss: 0.6702 - mae: 0.5930 - rmse: 0.8143

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 459ms/step - loss: 0.6852 - mae: 0.5981 - rmse: 0.8229

 17/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 494ms/step - loss: 0.6999 - mae: 0.6028 - rmse: 0.8313

 18/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 528ms/step - loss: 0.7118 - mae: 0.6066 - rmse: 0.8381

 19/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 530ms/step - loss: 0.7242 - mae: 0.6103 - rmse: 0.8451

 20/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 553ms/step - loss: 0.7348 - mae: 0.6134 - rmse: 0.8512

 21/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 577ms/step - loss: 0.7432 - mae: 0.6158 - rmse: 0.8560

 22/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 632ms/step - loss: 0.7513 - mae: 0.6182 - rmse: 0.8606

 23/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 678ms/step - loss: 0.7598 - mae: 0.6209 - rmse: 0.8654

 24/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 674ms/step - loss: 0.7674 - mae: 0.6233 - rmse: 0.8697

 25/269 ━━━━━━━━━━━━━━━━━━━━ 2:45 680ms/step - loss: 0.7737 - mae: 0.6253 - rmse: 0.8733

 26/269 ━━━━━━━━━━━━━━━━━━━━ 2:54 717ms/step - loss: 0.7799 - mae: 0.6272 - rmse: 0.8769

 27/269 ━━━━━━━━━━━━━━━━━━━━ 3:01 750ms/step - loss: 0.7849 - mae: 0.6286 - rmse: 0.8797

 28/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 770ms/step - loss: 0.7889 - mae: 0.6298 - rmse: 0.8820

 29/269 ━━━━━━━━━━━━━━━━━━━━ 3:15 816ms/step - loss: 0.7924 - mae: 0.6308 - rmse: 0.8841

 30/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 829ms/step - loss: 0.7950 - mae: 0.6314 - rmse: 0.8857

 31/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 837ms/step - loss: 0.7969 - mae: 0.6318 - rmse: 0.8869

 32/269 ━━━━━━━━━━━━━━━━━━━━ 3:18 840ms/step - loss: 0.7984 - mae: 0.6321 - rmse: 0.8878

 33/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 846ms/step - loss: 0.7995 - mae: 0.6323 - rmse: 0.8885

 34/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 864ms/step - loss: 0.8004 - mae: 0.6324 - rmse: 0.8891

 35/269 ━━━━━━━━━━━━━━━━━━━━ 3:22 867ms/step - loss: 0.8011 - mae: 0.6325 - rmse: 0.8896

 36/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 865ms/step - loss: 0.8014 - mae: 0.6326 - rmse: 0.8899

 37/269 ━━━━━━━━━━━━━━━━━━━━ 3:21 869ms/step - loss: 0.8016 - mae: 0.6325 - rmse: 0.8901

 38/269 ━━━━━━━━━━━━━━━━━━━━ 3:20 866ms/step - loss: 0.8014 - mae: 0.6323 - rmse: 0.8900

 39/269 ━━━━━━━━━━━━━━━━━━━━ 3:19 867ms/step - loss: 0.8011 - mae: 0.6321 - rmse: 0.8899

 40/269 ━━━━━━━━━━━━━━━━━━━━ 3:17 861ms/step - loss: 0.8004 - mae: 0.6317 - rmse: 0.8897

 41/269 ━━━━━━━━━━━━━━━━━━━━ 3:15 858ms/step - loss: 0.7999 - mae: 0.6314 - rmse: 0.8894

 42/269 ━━━━━━━━━━━━━━━━━━━━ 3:14 855ms/step - loss: 0.7991 - mae: 0.6310 - rmse: 0.8890

 43/269 ━━━━━━━━━━━━━━━━━━━━ 3:11 846ms/step - loss: 0.7982 - mae: 0.6306 - rmse: 0.8886

 44/269 ━━━━━━━━━━━━━━━━━━━━ 3:08 836ms/step - loss: 0.7975 - mae: 0.6302 - rmse: 0.8882

 45/269 ━━━━━━━━━━━━━━━━━━━━ 3:05 829ms/step - loss: 0.7967 - mae: 0.6299 - rmse: 0.8878

 46/269 ━━━━━━━━━━━━━━━━━━━━ 3:04 826ms/step - loss: 0.7957 - mae: 0.6294 - rmse: 0.8873

 47/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 828ms/step - loss: 0.7947 - mae: 0.6290 - rmse: 0.8869

 48/269 ━━━━━━━━━━━━━━━━━━━━ 3:03 830ms/step - loss: 0.7936 - mae: 0.6285 - rmse: 0.8863

 49/269 ━━━━━━━━━━━━━━━━━━━━ 3:01 824ms/step - loss: 0.7923 - mae: 0.6280 - rmse: 0.8856

 50/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 820ms/step - loss: 0.7910 - mae: 0.6274 - rmse: 0.8848

 51/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 814ms/step - loss: 0.7895 - mae: 0.6267 - rmse: 0.8841

 52/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 815ms/step - loss: 0.7881 - mae: 0.6261 - rmse: 0.8833

 53/269 ━━━━━━━━━━━━━━━━━━━━ 2:56 817ms/step - loss: 0.7865 - mae: 0.6255 - rmse: 0.8824

 54/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 818ms/step - loss: 0.7851 - mae: 0.6249 - rmse: 0.8817

 55/269 ━━━━━━━━━━━━━━━━━━━━ 2:57 832ms/step - loss: 0.7837 - mae: 0.6243 - rmse: 0.8808

 56/269 ━━━━━━━━━━━━━━━━━━━━ 2:59 844ms/step - loss: 0.7822 - mae: 0.6237 - rmse: 0.8801

 57/269 ━━━━━━━━━━━━━━━━━━━━ 2:58 841ms/step - loss: 0.7808 - mae: 0.6231 - rmse: 0.8792

 58/269 ━━━━━━━━━━━━━━━━━━━━ 2:55 833ms/step - loss: 0.7793 - mae: 0.6225 - rmse: 0.8784

 59/269 ━━━━━━━━━━━━━━━━━━━━ 2:53 826ms/step - loss: 0.7779 - mae: 0.6220 - rmse: 0.8777

 60/269 ━━━━━━━━━━━━━━━━━━━━ 2:51 821ms/step - loss: 0.7765 - mae: 0.6215 - rmse: 0.8769

 61/269 ━━━━━━━━━━━━━━━━━━━━ 2:49 815ms/step - loss: 0.7752 - mae: 0.6210 - rmse: 0.8762

 62/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 811ms/step - loss: 0.7740 - mae: 0.6205 - rmse: 0.8754

 63/269 ━━━━━━━━━━━━━━━━━━━━ 2:46 807ms/step - loss: 0.7727 - mae: 0.6200 - rmse: 0.8747

 64/269 ━━━━━━━━━━━━━━━━━━━━ 2:44 802ms/step - loss: 0.7713 - mae: 0.6196 - rmse: 0.8740

 65/269 ━━━━━━━━━━━━━━━━━━━━ 2:42 798ms/step - loss: 0.7699 - mae: 0.6190 - rmse: 0.8731

 66/269 ━━━━━━━━━━━━━━━━━━━━ 2:41 793ms/step - loss: 0.7684 - mae: 0.6184 - rmse: 0.8723

 67/269 ━━━━━━━━━━━━━━━━━━━━ 2:39 791ms/step - loss: 0.7668 - mae: 0.6179 - rmse: 0.8714

 68/269 ━━━━━━━━━━━━━━━━━━━━ 2:38 787ms/step - loss: 0.7653 - mae: 0.6173 - rmse: 0.8705

 69/269 ━━━━━━━━━━━━━━━━━━━━ 2:36 784ms/step - loss: 0.7639 - mae: 0.6167 - rmse: 0.8697

 70/269 ━━━━━━━━━━━━━━━━━━━━ 2:35 780ms/step - loss: 0.7624 - mae: 0.6162 - rmse: 0.8689

 71/269 ━━━━━━━━━━━━━━━━━━━━ 2:33 777ms/step - loss: 0.7611 - mae: 0.6157 - rmse: 0.8682

 72/269 ━━━━━━━━━━━━━━━━━━━━ 2:32 774ms/step - loss: 0.7599 - mae: 0.6152 - rmse: 0.8675

 73/269 ━━━━━━━━━━━━━━━━━━━━ 2:31 771ms/step - loss: 0.7587 - mae: 0.6147 - rmse: 0.8668

 74/269 ━━━━━━━━━━━━━━━━━━━━ 2:29 768ms/step - loss: 0.7575 - mae: 0.6143 - rmse: 0.8661

 75/269 ━━━━━━━━━━━━━━━━━━━━ 2:28 764ms/step - loss: 0.7564 - mae: 0.6139 - rmse: 0.8655

 76/269 ━━━━━━━━━━━━━━━━━━━━ 2:26 760ms/step - loss: 0.7554 - mae: 0.6134 - rmse: 0.8649

 77/269 ━━━━━━━━━━━━━━━━━━━━ 2:25 756ms/step - loss: 0.7544 - mae: 0.6131 - rmse: 0.8644

 78/269 ━━━━━━━━━━━━━━━━━━━━ 2:23 753ms/step - loss: 0.7535 - mae: 0.6127 - rmse: 0.8639

 79/269 ━━━━━━━━━━━━━━━━━━━━ 2:22 749ms/step - loss: 0.7527 - mae: 0.6124 - rmse: 0.8634

 80/269 ━━━━━━━━━━━━━━━━━━━━ 2:21 748ms/step - loss: 0.7518 - mae: 0.6121 - rmse: 0.8629

 81/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 748ms/step - loss: 0.7512 - mae: 0.6118 - rmse: 0.8626

 82/269 ━━━━━━━━━━━━━━━━━━━━ 2:20 749ms/step - loss: 0.7509 - mae: 0.6117 - rmse: 0.8624

 83/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 752ms/step - loss: 0.7507 - mae: 0.6116 - rmse: 0.8623

 84/269 ━━━━━━━━━━━━━━━━━━━━ 2:19 753ms/step - loss: 0.7506 - mae: 0.6115 - rmse: 0.8623

 85/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 753ms/step - loss: 0.7506 - mae: 0.6115 - rmse: 0.8623

 86/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 756ms/step - loss: 0.7506 - mae: 0.6115 - rmse: 0.8623

 87/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 752ms/step - loss: 0.7507 - mae: 0.6115 - rmse: 0.8624

 88/269 ━━━━━━━━━━━━━━━━━━━━ 2:15 750ms/step - loss: 0.7507 - mae: 0.6114 - rmse: 0.8624

 89/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 748ms/step - loss: 0.7508 - mae: 0.6114 - rmse: 0.8625

 90/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 745ms/step - loss: 0.7508 - mae: 0.6114 - rmse: 0.8625

 91/269 ━━━━━━━━━━━━━━━━━━━━ 2:12 743ms/step - loss: 0.7508 - mae: 0.6114 - rmse: 0.8626

 92/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 740ms/step - loss: 0.7508 - mae: 0.6113 - rmse: 0.8626

 93/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 739ms/step - loss: 0.7507 - mae: 0.6113 - rmse: 0.8625

 94/269 ━━━━━━━━━━━━━━━━━━━━ 2:09 738ms/step - loss: 0.7505 - mae: 0.6111 - rmse: 0.8624

 95/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 740ms/step - loss: 0.7503 - mae: 0.6110 - rmse: 0.8623

 96/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 743ms/step - loss: 0.7500 - mae: 0.6109 - rmse: 0.8622

 97/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 746ms/step - loss: 0.7497 - mae: 0.6107 - rmse: 0.8620

 98/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 751ms/step - loss: 0.7494 - mae: 0.6105 - rmse: 0.8618

 99/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 752ms/step - loss: 0.7490 - mae: 0.6103 - rmse: 0.8616

100/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 752ms/step - loss: 0.7486 - mae: 0.6101 - rmse: 0.8614

101/269 ━━━━━━━━━━━━━━━━━━━━ 2:06 751ms/step - loss: 0.7482 - mae: 0.6099 - rmse: 0.8612

102/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 750ms/step - loss: 0.7478 - mae: 0.6097 - rmse: 0.8610

103/269 ━━━━━━━━━━━━━━━━━━━━ 2:04 749ms/step - loss: 0.7474 - mae: 0.6095 - rmse: 0.8608

104/269 ━━━━━━━━━━━━━━━━━━━━ 2:03 748ms/step - loss: 0.7470 - mae: 0.6093 - rmse: 0.8605

105/269 ━━━━━━━━━━━━━━━━━━━━ 2:02 748ms/step - loss: 0.7465 - mae: 0.6091 - rmse: 0.8603

106/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 748ms/step - loss: 0.7461 - mae: 0.6089 - rmse: 0.8600

107/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 750ms/step - loss: 0.7455 - mae: 0.6086 - rmse: 0.8597

108/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 751ms/step - loss: 0.7450 - mae: 0.6084 - rmse: 0.8594

109/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 751ms/step - loss: 0.7444 - mae: 0.6081 - rmse: 0.8591

110/269 ━━━━━━━━━━━━━━━━━━━━ 1:59 753ms/step - loss: 0.7438 - mae: 0.6078 - rmse: 0.8587

111/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 751ms/step - loss: 0.7431 - mae: 0.6074 - rmse: 0.8583

112/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 749ms/step - loss: 0.7424 - mae: 0.6071 - rmse: 0.8579

113/269 ━━━━━━━━━━━━━━━━━━━━ 1:56 746ms/step - loss: 0.7417 - mae: 0.6067 - rmse: 0.8575

114/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 743ms/step - loss: 0.7410 - mae: 0.6064 - rmse: 0.8571

115/269 ━━━━━━━━━━━━━━━━━━━━ 1:54 741ms/step - loss: 0.7402 - mae: 0.6060 - rmse: 0.8566

116/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 739ms/step - loss: 0.7394 - mae: 0.6056 - rmse: 0.8562

117/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 736ms/step - loss: 0.7386 - mae: 0.6052 - rmse: 0.8557

118/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 734ms/step - loss: 0.7378 - mae: 0.6047 - rmse: 0.8552

119/269 ━━━━━━━━━━━━━━━━━━━━ 1:49 731ms/step - loss: 0.7369 - mae: 0.6043 - rmse: 0.8547

120/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 728ms/step - loss: 0.7361 - mae: 0.6039 - rmse: 0.8542

121/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 726ms/step - loss: 0.7352 - mae: 0.6034 - rmse: 0.8537

122/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 723ms/step - loss: 0.7343 - mae: 0.6030 - rmse: 0.8532

123/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 722ms/step - loss: 0.7334 - mae: 0.6025 - rmse: 0.8526

124/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 720ms/step - loss: 0.7324 - mae: 0.6020 - rmse: 0.8521

125/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 718ms/step - loss: 0.7315 - mae: 0.6016 - rmse: 0.8515

126/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 719ms/step - loss: 0.7305 - mae: 0.6011 - rmse: 0.8509

127/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 724ms/step - loss: 0.7295 - mae: 0.6006 - rmse: 0.8503

128/269 ━━━━━━━━━━━━━━━━━━━━ 1:42 727ms/step - loss: 0.7286 - mae: 0.6001 - rmse: 0.8497

129/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 727ms/step - loss: 0.7276 - mae: 0.5996 - rmse: 0.8491

130/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 731ms/step - loss: 0.7265 - mae: 0.5990 - rmse: 0.8485

131/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 733ms/step - loss: 0.7255 - mae: 0.5985 - rmse: 0.8479

132/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 732ms/step - loss: 0.7245 - mae: 0.5980 - rmse: 0.8473

133/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 729ms/step - loss: 0.7235 - mae: 0.5975 - rmse: 0.8467

134/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 727ms/step - loss: 0.7225 - mae: 0.5970 - rmse: 0.8460

135/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 725ms/step - loss: 0.7215 - mae: 0.5965 - rmse: 0.8454

136/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 722ms/step - loss: 0.7204 - mae: 0.5959 - rmse: 0.8448

137/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 720ms/step - loss: 0.7194 - mae: 0.5954 - rmse: 0.8442

138/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 717ms/step - loss: 0.7184 - mae: 0.5949 - rmse: 0.8435

139/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 715ms/step - loss: 0.7173 - mae: 0.5944 - rmse: 0.8429

140/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 714ms/step - loss: 0.7163 - mae: 0.5939 - rmse: 0.8423

141/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 713ms/step - loss: 0.7152 - mae: 0.5933 - rmse: 0.8416

142/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 711ms/step - loss: 0.7142 - mae: 0.5928 - rmse: 0.8410

143/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 710ms/step - loss: 0.7131 - mae: 0.5922 - rmse: 0.8403

144/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 709ms/step - loss: 0.7120 - mae: 0.5917 - rmse: 0.8396

145/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 716ms/step - loss: 0.7109 - mae: 0.5911 - rmse: 0.8390

146/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 719ms/step - loss: 0.7098 - mae: 0.5905 - rmse: 0.8383

147/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 722ms/step - loss: 0.7087 - mae: 0.5900 - rmse: 0.8376

148/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 724ms/step - loss: 0.7076 - mae: 0.5894 - rmse: 0.8369

149/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 723ms/step - loss: 0.7065 - mae: 0.5888 - rmse: 0.8362

150/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 722ms/step - loss: 0.7054 - mae: 0.5882 - rmse: 0.8355

151/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 720ms/step - loss: 0.7042 - mae: 0.5876 - rmse: 0.8348

152/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 718ms/step - loss: 0.7031 - mae: 0.5870 - rmse: 0.8341

153/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 716ms/step - loss: 0.7020 - mae: 0.5864 - rmse: 0.8334

154/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 714ms/step - loss: 0.7009 - mae: 0.5858 - rmse: 0.8327

155/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 712ms/step - loss: 0.6997 - mae: 0.5852 - rmse: 0.8320

156/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 710ms/step - loss: 0.6986 - mae: 0.5846 - rmse: 0.8313

157/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 708ms/step - loss: 0.6975 - mae: 0.5840 - rmse: 0.8305

158/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 706ms/step - loss: 0.6963 - mae: 0.5834 - rmse: 0.8298

159/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 704ms/step - loss: 0.6952 - mae: 0.5828 - rmse: 0.8291

160/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 702ms/step - loss: 0.6941 - mae: 0.5822 - rmse: 0.8284

161/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 700ms/step - loss: 0.6929 - mae: 0.5816 - rmse: 0.8277

162/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 699ms/step - loss: 0.6918 - mae: 0.5810 - rmse: 0.8269

163/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 697ms/step - loss: 0.6907 - mae: 0.5804 - rmse: 0.8262

164/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 696ms/step - loss: 0.6895 - mae: 0.5798 - rmse: 0.8255

165/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 694ms/step - loss: 0.6884 - mae: 0.5792 - rmse: 0.8248

166/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 692ms/step - loss: 0.6873 - mae: 0.5786 - rmse: 0.8241

167/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 690ms/step - loss: 0.6862 - mae: 0.5781 - rmse: 0.8234

168/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 690ms/step - loss: 0.6851 - mae: 0.5775 - rmse: 0.8226

169/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 688ms/step - loss: 0.6840 - mae: 0.5769 - rmse: 0.8220

170/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 687ms/step - loss: 0.6829 - mae: 0.5763 - rmse: 0.8213

171/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 685ms/step - loss: 0.6818 - mae: 0.5758 - rmse: 0.8206

172/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 684ms/step - loss: 0.6808 - mae: 0.5752 - rmse: 0.8199

173/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 683ms/step - loss: 0.6797 - mae: 0.5747 - rmse: 0.8192

174/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 681ms/step - loss: 0.6787 - mae: 0.5741 - rmse: 0.8186

175/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 679ms/step - loss: 0.6776 - mae: 0.5736 - rmse: 0.8179

176/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 678ms/step - loss: 0.6766 - mae: 0.5731 - rmse: 0.8172

177/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 676ms/step - loss: 0.6756 - mae: 0.5725 - rmse: 0.8166

178/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 675ms/step - loss: 0.6745 - mae: 0.5720 - rmse: 0.8159

179/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 673ms/step - loss: 0.6735 - mae: 0.5715 - rmse: 0.8153

180/269 ━━━━━━━━━━━━━━━━━━━━ 59s 672ms/step - loss: 0.6725 - mae: 0.5710 - rmse: 0.8146

181/269 ━━━━━━━━━━━━━━━━━━━━ 59s 671ms/step - loss: 0.6714 - mae: 0.5704 - rmse: 0.8139

182/269 ━━━━━━━━━━━━━━━━━━━━ 58s 670ms/step - loss: 0.6704 - mae: 0.5699 - rmse: 0.8133

183/269 ━━━━━━━━━━━━━━━━━━━━ 57s 669ms/step - loss: 0.6694 - mae: 0.5694 - rmse: 0.8126

184/269 ━━━━━━━━━━━━━━━━━━━━ 56s 668ms/step - loss: 0.6684 - mae: 0.5688 - rmse: 0.8119

185/269 ━━━━━━━━━━━━━━━━━━━━ 55s 667ms/step - loss: 0.6673 - mae: 0.5683 - rmse: 0.8113

186/269 ━━━━━━━━━━━━━━━━━━━━ 55s 666ms/step - loss: 0.6663 - mae: 0.5677 - rmse: 0.8106

187/269 ━━━━━━━━━━━━━━━━━━━━ 54s 665ms/step - loss: 0.6653 - mae: 0.5672 - rmse: 0.8099

188/269 ━━━━━━━━━━━━━━━━━━━━ 53s 664ms/step - loss: 0.6642 - mae: 0.5667 - rmse: 0.8092

189/269 ━━━━━━━━━━━━━━━━━━━━ 53s 663ms/step - loss: 0.6632 - mae: 0.5661 - rmse: 0.8086

190/269 ━━━━━━━━━━━━━━━━━━━━ 52s 662ms/step - loss: 0.6622 - mae: 0.5656 - rmse: 0.8079

191/269 ━━━━━━━━━━━━━━━━━━━━ 51s 662ms/step - loss: 0.6611 - mae: 0.5650 - rmse: 0.8072

192/269 ━━━━━━━━━━━━━━━━━━━━ 50s 661ms/step - loss: 0.6601 - mae: 0.5645 - rmse: 0.8066

193/269 ━━━━━━━━━━━━━━━━━━━━ 50s 660ms/step - loss: 0.6591 - mae: 0.5639 - rmse: 0.8059

194/269 ━━━━━━━━━━━━━━━━━━━━ 49s 660ms/step - loss: 0.6580 - mae: 0.5634 - rmse: 0.8052

195/269 ━━━━━━━━━━━━━━━━━━━━ 48s 659ms/step - loss: 0.6570 - mae: 0.5628 - rmse: 0.8045

196/269 ━━━━━━━━━━━━━━━━━━━━ 48s 658ms/step - loss: 0.6560 - mae: 0.5623 - rmse: 0.8039

197/269 ━━━━━━━━━━━━━━━━━━━━ 47s 657ms/step - loss: 0.6550 - mae: 0.5618 - rmse: 0.8032

198/269 ━━━━━━━━━━━━━━━━━━━━ 46s 656ms/step - loss: 0.6540 - mae: 0.5612 - rmse: 0.8025

199/269 ━━━━━━━━━━━━━━━━━━━━ 45s 655ms/step - loss: 0.6529 - mae: 0.5607 - rmse: 0.8019

200/269 ━━━━━━━━━━━━━━━━━━━━ 45s 654ms/step - loss: 0.6519 - mae: 0.5601 - rmse: 0.8012

201/269 ━━━━━━━━━━━━━━━━━━━━ 44s 653ms/step - loss: 0.6509 - mae: 0.5596 - rmse: 0.8005

202/269 ━━━━━━━━━━━━━━━━━━━━ 43s 652ms/step - loss: 0.6499 - mae: 0.5591 - rmse: 0.7999

203/269 ━━━━━━━━━━━━━━━━━━━━ 42s 651ms/step - loss: 0.6490 - mae: 0.5585 - rmse: 0.7992

204/269 ━━━━━━━━━━━━━━━━━━━━ 42s 650ms/step - loss: 0.6480 - mae: 0.5580 - rmse: 0.7986

205/269 ━━━━━━━━━━━━━━━━━━━━ 41s 649ms/step - loss: 0.6470 - mae: 0.5575 - rmse: 0.7979

206/269 ━━━━━━━━━━━━━━━━━━━━ 40s 648ms/step - loss: 0.6460 - mae: 0.5570 - rmse: 0.7973

207/269 ━━━━━━━━━━━━━━━━━━━━ 40s 647ms/step - loss: 0.6451 - mae: 0.5565 - rmse: 0.7967

208/269 ━━━━━━━━━━━━━━━━━━━━ 39s 646ms/step - loss: 0.6441 - mae: 0.5559 - rmse: 0.7960

209/269 ━━━━━━━━━━━━━━━━━━━━ 38s 645ms/step - loss: 0.6432 - mae: 0.5554 - rmse: 0.7954

210/269 ━━━━━━━━━━━━━━━━━━━━ 37s 643ms/step - loss: 0.6422 - mae: 0.5549 - rmse: 0.7948

211/269 ━━━━━━━━━━━━━━━━━━━━ 37s 642ms/step - loss: 0.6412 - mae: 0.5544 - rmse: 0.7941

212/269 ━━━━━━━━━━━━━━━━━━━━ 36s 640ms/step - loss: 0.6403 - mae: 0.5539 - rmse: 0.7935

213/269 ━━━━━━━━━━━━━━━━━━━━ 35s 639ms/step - loss: 0.6393 - mae: 0.5534 - rmse: 0.7929

214/269 ━━━━━━━━━━━━━━━━━━━━ 35s 638ms/step - loss: 0.6384 - mae: 0.5529 - rmse: 0.7922

215/269 ━━━━━━━━━━━━━━━━━━━━ 34s 637ms/step - loss: 0.6374 - mae: 0.5524 - rmse: 0.7916

216/269 ━━━━━━━━━━━━━━━━━━━━ 33s 636ms/step - loss: 0.6365 - mae: 0.5519 - rmse: 0.7910

217/269 ━━━━━━━━━━━━━━━━━━━━ 33s 635ms/step - loss: 0.6355 - mae: 0.5514 - rmse: 0.7903

218/269 ━━━━━━━━━━━━━━━━━━━━ 32s 634ms/step - loss: 0.6346 - mae: 0.5509 - rmse: 0.7897

219/269 ━━━━━━━━━━━━━━━━━━━━ 31s 633ms/step - loss: 0.6337 - mae: 0.5504 - rmse: 0.7891

220/269 ━━━━━━━━━━━━━━━━━━━━ 30s 632ms/step - loss: 0.6327 - mae: 0.5498 - rmse: 0.7884

221/269 ━━━━━━━━━━━━━━━━━━━━ 30s 631ms/step - loss: 0.6318 - mae: 0.5493 - rmse: 0.7878

222/269 ━━━━━━━━━━━━━━━━━━━━ 29s 631ms/step - loss: 0.6309 - mae: 0.5488 - rmse: 0.7872

223/269 ━━━━━━━━━━━━━━━━━━━━ 29s 631ms/step - loss: 0.6299 - mae: 0.5483 - rmse: 0.7866

224/269 ━━━━━━━━━━━━━━━━━━━━ 28s 629ms/step - loss: 0.6290 - mae: 0.5478 - rmse: 0.7859

225/269 ━━━━━━━━━━━━━━━━━━━━ 27s 628ms/step - loss: 0.6281 - mae: 0.5473 - rmse: 0.7853

226/269 ━━━━━━━━━━━━━━━━━━━━ 26s 627ms/step - loss: 0.6271 - mae: 0.5468 - rmse: 0.7847

227/269 ━━━━━━━━━━━━━━━━━━━━ 26s 625ms/step - loss: 0.6262 - mae: 0.5463 - rmse: 0.7840

228/269 ━━━━━━━━━━━━━━━━━━━━ 25s 624ms/step - loss: 0.6253 - mae: 0.5458 - rmse: 0.7834

229/269 ━━━━━━━━━━━━━━━━━━━━ 24s 623ms/step - loss: 0.6243 - mae: 0.5453 - rmse: 0.7828

230/269 ━━━━━━━━━━━━━━━━━━━━ 24s 622ms/step - loss: 0.6234 - mae: 0.5448 - rmse: 0.7822

231/269 ━━━━━━━━━━━━━━━━━━━━ 23s 620ms/step - loss: 0.6225 - mae: 0.5443 - rmse: 0.7815

232/269 ━━━━━━━━━━━━━━━━━━━━ 22s 619ms/step - loss: 0.6216 - mae: 0.5438 - rmse: 0.7809

233/269 ━━━━━━━━━━━━━━━━━━━━ 22s 617ms/step - loss: 0.6206 - mae: 0.5433 - rmse: 0.7803

234/269 ━━━━━━━━━━━━━━━━━━━━ 21s 617ms/step - loss: 0.6197 - mae: 0.5428 - rmse: 0.7797

235/269 ━━━━━━━━━━━━━━━━━━━━ 20s 617ms/step - loss: 0.6188 - mae: 0.5423 - rmse: 0.7790

236/269 ━━━━━━━━━━━━━━━━━━━━ 20s 617ms/step - loss: 0.6179 - mae: 0.5418 - rmse: 0.7784

237/269 ━━━━━━━━━━━━━━━━━━━━ 19s 619ms/step - loss: 0.6170 - mae: 0.5413 - rmse: 0.7778

238/269 ━━━━━━━━━━━━━━━━━━━━ 19s 624ms/step - loss: 0.6161 - mae: 0.5408 - rmse: 0.7772

239/269 ━━━━━━━━━━━━━━━━━━━━ 18s 626ms/step - loss: 0.6152 - mae: 0.5403 - rmse: 0.7766

240/269 ━━━━━━━━━━━━━━━━━━━━ 18s 629ms/step - loss: 0.6143 - mae: 0.5398 - rmse: 0.7759

241/269 ━━━━━━━━━━━━━━━━━━━━ 17s 631ms/step - loss: 0.6134 - mae: 0.5393 - rmse: 0.7753

242/269 ━━━━━━━━━━━━━━━━━━━━ 17s 632ms/step - loss: 0.6125 - mae: 0.5388 - rmse: 0.7747

243/269 ━━━━━━━━━━━━━━━━━━━━ 16s 632ms/step - loss: 0.6116 - mae: 0.5383 - rmse: 0.7741

244/269 ━━━━━━━━━━━━━━━━━━━━ 15s 633ms/step - loss: 0.6107 - mae: 0.5378 - rmse: 0.7735

245/269 ━━━━━━━━━━━━━━━━━━━━ 15s 635ms/step - loss: 0.6098 - mae: 0.5373 - rmse: 0.7729

246/269 ━━━━━━━━━━━━━━━━━━━━ 14s 635ms/step - loss: 0.6089 - mae: 0.5368 - rmse: 0.7723

247/269 ━━━━━━━━━━━━━━━━━━━━ 13s 634ms/step - loss: 0.6080 - mae: 0.5363 - rmse: 0.7717

248/269 ━━━━━━━━━━━━━━━━━━━━ 13s 635ms/step - loss: 0.6072 - mae: 0.5359 - rmse: 0.7711

249/269 ━━━━━━━━━━━━━━━━━━━━ 12s 634ms/step - loss: 0.6063 - mae: 0.5354 - rmse: 0.7705

250/269 ━━━━━━━━━━━━━━━━━━━━ 12s 634ms/step - loss: 0.6054 - mae: 0.5349 - rmse: 0.7699

251/269 ━━━━━━━━━━━━━━━━━━━━ 11s 633ms/step - loss: 0.6046 - mae: 0.5344 - rmse: 0.7693

252/269 ━━━━━━━━━━━━━━━━━━━━ 10s 632ms/step - loss: 0.6037 - mae: 0.5339 - rmse: 0.7687

253/269 ━━━━━━━━━━━━━━━━━━━━ 10s 632ms/step - loss: 0.6028 - mae: 0.5335 - rmse: 0.7681

254/269 ━━━━━━━━━━━━━━━━━━━━ 9s 631ms/step - loss: 0.6020 - mae: 0.5330 - rmse: 0.7675

255/269 ━━━━━━━━━━━━━━━━━━━━ 8s 630ms/step - loss: 0.6011 - mae: 0.5325 - rmse: 0.7669

256/269 ━━━━━━━━━━━━━━━━━━━━ 8s 629ms/step - loss: 0.6003 - mae: 0.5321 - rmse: 0.7663

257/269 ━━━━━━━━━━━━━━━━━━━━ 7s 629ms/step - loss: 0.5994 - mae: 0.5316 - rmse: 0.7657

258/269 ━━━━━━━━━━━━━━━━━━━━ 6s 628ms/step - loss: 0.5985 - mae: 0.5311 - rmse: 0.7651

259/269 ━━━━━━━━━━━━━━━━━━━━ 6s 627ms/step - loss: 0.5977 - mae: 0.5306 - rmse: 0.7645

260/269 ━━━━━━━━━━━━━━━━━━━━ 5s 627ms/step - loss: 0.5968 - mae: 0.5302 - rmse: 0.7639

261/269 ━━━━━━━━━━━━━━━━━━━━ 5s 629ms/step - loss: 0.5960 - mae: 0.5297 - rmse: 0.7633

262/269 ━━━━━━━━━━━━━━━━━━━━ 4s 629ms/step - loss: 0.5952 - mae: 0.5292 - rmse: 0.7627

263/269 ━━━━━━━━━━━━━━━━━━━━ 3s 628ms/step - loss: 0.5943 - mae: 0.5288 - rmse: 0.7622

264/269 ━━━━━━━━━━━━━━━━━━━━ 3s 628ms/step - loss: 0.5935 - mae: 0.5283 - rmse: 0.7616

265/269 ━━━━━━━━━━━━━━━━━━━━ 2s 627ms/step - loss: 0.5926 - mae: 0.5279 - rmse: 0.7610

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 626ms/step - loss: 0.5918 - mae: 0.5274 - rmse: 0.7604

267/269 ━━━━━━━━━━━━━━━━━━━━ 1s 625ms/step - loss: 0.5910 - mae: 0.5269 - rmse: 0.7598

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 624ms/step - loss: 0.5902 - mae: 0.5265 - rmse: 0.7592

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 622ms/step - loss: 0.5893 - mae: 0.5260 - rmse: 0.7587

269/269 ━━━━━━━━━━━━━━━━━━━━ 176s 656ms/step - loss: 0.3697 - mae: 0.4043 - rmse: 0.6049 - val_loss: 0.7280 - val_mae: 0.5282 - val_rmse: 0.8510 - learning_rate: 5.0000e-04

Epoch 19/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:00 449ms/step - loss: 0.7440 - mae: 0.6218 - rmse: 0.8604

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 276ms/step - loss: 0.6761 - mae: 0.5956 - rmse: 0.8189

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 340ms/step - loss: 0.6681 - mae: 0.5963 - rmse: 0.8143

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 337ms/step - loss: 0.6522 - mae: 0.5921 - rmse: 0.8046

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 332ms/step - loss: 0.6335 - mae: 0.5844 - rmse: 0.7926

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 331ms/step - loss: 0.6191 - mae: 0.5787 - rmse: 0.7833

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 322ms/step - loss: 0.6117 - mae: 0.5758 - rmse: 0.7787

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 319ms/step - loss: 0.6155 - mae: 0.5775 - rmse: 0.7813

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 315ms/step - loss: 0.6192 - mae: 0.5789 - rmse: 0.7837

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 315ms/step - loss: 0.6188 - mae: 0.5782 - rmse: 0.7835

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 312ms/step - loss: 0.6172 - mae: 0.5770 - rmse: 0.7826

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 315ms/step - loss: 0.6236 - mae: 0.5788 - rmse: 0.7866

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 318ms/step - loss: 0.6338 - mae: 0.5817 - rmse: 0.7928

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 315ms/step - loss: 0.6478 - mae: 0.5863 - rmse: 0.8011

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 312ms/step - loss: 0.6607 - mae: 0.5905 - rmse: 0.8087

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 309ms/step - loss: 0.6745 - mae: 0.5951 - rmse: 0.8167

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 308ms/step - loss: 0.6876 - mae: 0.5993 - rmse: 0.8243

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 307ms/step - loss: 0.6984 - mae: 0.6027 - rmse: 0.8305

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 305ms/step - loss: 0.7099 - mae: 0.6061 - rmse: 0.8371

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 305ms/step - loss: 0.7199 - mae: 0.6091 - rmse: 0.8429

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 306ms/step - loss: 0.7278 - mae: 0.6113 - rmse: 0.8475

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 304ms/step - loss: 0.7352 - mae: 0.6136 - rmse: 0.8518

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 303ms/step - loss: 0.7433 - mae: 0.6161 - rmse: 0.8563

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 304ms/step - loss: 0.7503 - mae: 0.6184 - rmse: 0.8604

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 303ms/step - loss: 0.7561 - mae: 0.6203 - rmse: 0.8637

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 304ms/step - loss: 0.7619 - mae: 0.6220 - rmse: 0.8670

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 306ms/step - loss: 0.7663 - mae: 0.6232 - rmse: 0.8696

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 310ms/step - loss: 0.7699 - mae: 0.6242 - rmse: 0.8718

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 317ms/step - loss: 0.7731 - mae: 0.6250 - rmse: 0.8736

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 321ms/step - loss: 0.7753 - mae: 0.6256 - rmse: 0.8750

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 322ms/step - loss: 0.7770 - mae: 0.6259 - rmse: 0.8761

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 323ms/step - loss: 0.7782 - mae: 0.6260 - rmse: 0.8769

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 324ms/step - loss: 0.7792 - mae: 0.6261 - rmse: 0.8775

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 326ms/step - loss: 0.7798 - mae: 0.6261 - rmse: 0.8779

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 327ms/step - loss: 0.7803 - mae: 0.6262 - rmse: 0.8783

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 327ms/step - loss: 0.7805 - mae: 0.6261 - rmse: 0.8785

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 328ms/step - loss: 0.7806 - mae: 0.6260 - rmse: 0.8786

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 327ms/step - loss: 0.7803 - mae: 0.6257 - rmse: 0.8785

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 326ms/step - loss: 0.7799 - mae: 0.6254 - rmse: 0.8784

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 326ms/step - loss: 0.7792 - mae: 0.6250 - rmse: 0.8780

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 326ms/step - loss: 0.7787 - mae: 0.6247 - rmse: 0.8778

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 326ms/step - loss: 0.7779 - mae: 0.6243 - rmse: 0.8774

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 324ms/step - loss: 0.7771 - mae: 0.6239 - rmse: 0.8770

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 325ms/step - loss: 0.7764 - mae: 0.6235 - rmse: 0.8767

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 324ms/step - loss: 0.7757 - mae: 0.6232 - rmse: 0.8763

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 325ms/step - loss: 0.7748 - mae: 0.6227 - rmse: 0.8758

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 327ms/step - loss: 0.7739 - mae: 0.6223 - rmse: 0.8754

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 328ms/step - loss: 0.7729 - mae: 0.6218 - rmse: 0.8748

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 330ms/step - loss: 0.7716 - mae: 0.6213 - rmse: 0.8742

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 331ms/step - loss: 0.7704 - mae: 0.6207 - rmse: 0.8735

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 332ms/step - loss: 0.7690 - mae: 0.6201 - rmse: 0.8727

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 332ms/step - loss: 0.7676 - mae: 0.6194 - rmse: 0.8719

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 331ms/step - loss: 0.7662 - mae: 0.6188 - rmse: 0.8711

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 332ms/step - loss: 0.7649 - mae: 0.6182 - rmse: 0.8704

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 331ms/step - loss: 0.7635 - mae: 0.6176 - rmse: 0.8696

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 331ms/step - loss: 0.7621 - mae: 0.6171 - rmse: 0.8688

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 330ms/step - loss: 0.7607 - mae: 0.6165 - rmse: 0.8680

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 329ms/step - loss: 0.7593 - mae: 0.6159 - rmse: 0.8672

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 328ms/step - loss: 0.7580 - mae: 0.6154 - rmse: 0.8665

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 328ms/step - loss: 0.7566 - mae: 0.6148 - rmse: 0.8657

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 327ms/step - loss: 0.7554 - mae: 0.6143 - rmse: 0.8650

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 327ms/step - loss: 0.7541 - mae: 0.6139 - rmse: 0.8643

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 325ms/step - loss: 0.7529 - mae: 0.6134 - rmse: 0.8636

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 324ms/step - loss: 0.7516 - mae: 0.6129 - rmse: 0.8629

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 323ms/step - loss: 0.7502 - mae: 0.6124 - rmse: 0.8621

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 322ms/step - loss: 0.7488 - mae: 0.6118 - rmse: 0.8613

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 321ms/step - loss: 0.7473 - mae: 0.6113 - rmse: 0.8604

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 320ms/step - loss: 0.7458 - mae: 0.6107 - rmse: 0.8596

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 320ms/step - loss: 0.7444 - mae: 0.6101 - rmse: 0.8588

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 321ms/step - loss: 0.7431 - mae: 0.6096 - rmse: 0.8580

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 320ms/step - loss: 0.7419 - mae: 0.6091 - rmse: 0.8573

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 320ms/step - loss: 0.7407 - mae: 0.6087 - rmse: 0.8566

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 321ms/step - loss: 0.7395 - mae: 0.6082 - rmse: 0.8559

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 323ms/step - loss: 0.7384 - mae: 0.6078 - rmse: 0.8553

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 322ms/step - loss: 0.7374 - mae: 0.6073 - rmse: 0.8547

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 322ms/step - loss: 0.7363 - mae: 0.6069 - rmse: 0.8541

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 321ms/step - loss: 0.7354 - mae: 0.6066 - rmse: 0.8536

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 322ms/step - loss: 0.7346 - mae: 0.6062 - rmse: 0.8531

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 322ms/step - loss: 0.7337 - mae: 0.6059 - rmse: 0.8526

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 321ms/step - loss: 0.7329 - mae: 0.6056 - rmse: 0.8521

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 320ms/step - loss: 0.7323 - mae: 0.6053 - rmse: 0.8518

 82/269 ━━━━━━━━━━━━━━━━━━━━ 59s 320ms/step - loss: 0.7320 - mae: 0.6052 - rmse: 0.8516

 83/269 ━━━━━━━━━━━━━━━━━━━━ 59s 319ms/step - loss: 0.7319 - mae: 0.6051 - rmse: 0.8516

 84/269 ━━━━━━━━━━━━━━━━━━━━ 58s 318ms/step - loss: 0.7318 - mae: 0.6051 - rmse: 0.8516

 85/269 ━━━━━━━━━━━━━━━━━━━━ 58s 318ms/step - loss: 0.7318 - mae: 0.6051 - rmse: 0.8516

 86/269 ━━━━━━━━━━━━━━━━━━━━ 58s 318ms/step - loss: 0.7319 - mae: 0.6051 - rmse: 0.8517

 87/269 ━━━━━━━━━━━━━━━━━━━━ 57s 318ms/step - loss: 0.7320 - mae: 0.6051 - rmse: 0.8517

 88/269 ━━━━━━━━━━━━━━━━━━━━ 57s 318ms/step - loss: 0.7321 - mae: 0.6050 - rmse: 0.8518

 89/269 ━━━━━━━━━━━━━━━━━━━━ 57s 318ms/step - loss: 0.7323 - mae: 0.6051 - rmse: 0.8519

 90/269 ━━━━━━━━━━━━━━━━━━━━ 56s 318ms/step - loss: 0.7324 - mae: 0.6051 - rmse: 0.8520

 91/269 ━━━━━━━━━━━━━━━━━━━━ 56s 318ms/step - loss: 0.7325 - mae: 0.6051 - rmse: 0.8521

 92/269 ━━━━━━━━━━━━━━━━━━━━ 56s 317ms/step - loss: 0.7325 - mae: 0.6050 - rmse: 0.8521

 93/269 ━━━━━━━━━━━━━━━━━━━━ 55s 318ms/step - loss: 0.7324 - mae: 0.6050 - rmse: 0.8521

 94/269 ━━━━━━━━━━━━━━━━━━━━ 55s 318ms/step - loss: 0.7323 - mae: 0.6049 - rmse: 0.8520

 95/269 ━━━━━━━━━━━━━━━━━━━━ 55s 318ms/step - loss: 0.7322 - mae: 0.6047 - rmse: 0.8520

 96/269 ━━━━━━━━━━━━━━━━━━━━ 55s 318ms/step - loss: 0.7320 - mae: 0.6046 - rmse: 0.8519

 97/269 ━━━━━━━━━━━━━━━━━━━━ 54s 319ms/step - loss: 0.7317 - mae: 0.6044 - rmse: 0.8517

 98/269 ━━━━━━━━━━━━━━━━━━━━ 54s 319ms/step - loss: 0.7315 - mae: 0.6043 - rmse: 0.8516

 99/269 ━━━━━━━━━━━━━━━━━━━━ 54s 319ms/step - loss: 0.7311 - mae: 0.6041 - rmse: 0.8514

100/269 ━━━━━━━━━━━━━━━━━━━━ 53s 318ms/step - loss: 0.7308 - mae: 0.6039 - rmse: 0.8512

101/269 ━━━━━━━━━━━━━━━━━━━━ 53s 318ms/step - loss: 0.7305 - mae: 0.6037 - rmse: 0.8511

102/269 ━━━━━━━━━━━━━━━━━━━━ 53s 318ms/step - loss: 0.7301 - mae: 0.6035 - rmse: 0.8509

103/269 ━━━━━━━━━━━━━━━━━━━━ 52s 318ms/step - loss: 0.7298 - mae: 0.6033 - rmse: 0.8507

104/269 ━━━━━━━━━━━━━━━━━━━━ 52s 318ms/step - loss: 0.7294 - mae: 0.6031 - rmse: 0.8505

105/269 ━━━━━━━━━━━━━━━━━━━━ 52s 317ms/step - loss: 0.7290 - mae: 0.6030 - rmse: 0.8503

106/269 ━━━━━━━━━━━━━━━━━━━━ 51s 317ms/step - loss: 0.7286 - mae: 0.6027 - rmse: 0.8500

107/269 ━━━━━━━━━━━━━━━━━━━━ 51s 317ms/step - loss: 0.7282 - mae: 0.6025 - rmse: 0.8498

108/269 ━━━━━━━━━━━━━━━━━━━━ 50s 317ms/step - loss: 0.7277 - mae: 0.6023 - rmse: 0.8495

109/269 ━━━━━━━━━━━━━━━━━━━━ 50s 317ms/step - loss: 0.7272 - mae: 0.6020 - rmse: 0.8492

110/269 ━━━━━━━━━━━━━━━━━━━━ 50s 317ms/step - loss: 0.7266 - mae: 0.6017 - rmse: 0.8488

111/269 ━━━━━━━━━━━━━━━━━━━━ 50s 317ms/step - loss: 0.7260 - mae: 0.6014 - rmse: 0.8485

112/269 ━━━━━━━━━━━━━━━━━━━━ 49s 316ms/step - loss: 0.7253 - mae: 0.6010 - rmse: 0.8481

113/269 ━━━━━━━━━━━━━━━━━━━━ 49s 316ms/step - loss: 0.7247 - mae: 0.6007 - rmse: 0.8477

114/269 ━━━━━━━━━━━━━━━━━━━━ 48s 316ms/step - loss: 0.7240 - mae: 0.6003 - rmse: 0.8473

115/269 ━━━━━━━━━━━━━━━━━━━━ 48s 317ms/step - loss: 0.7233 - mae: 0.6000 - rmse: 0.8469

116/269 ━━━━━━━━━━━━━━━━━━━━ 48s 316ms/step - loss: 0.7226 - mae: 0.5996 - rmse: 0.8465

117/269 ━━━━━━━━━━━━━━━━━━━━ 48s 316ms/step - loss: 0.7218 - mae: 0.5992 - rmse: 0.8460

118/269 ━━━━━━━━━━━━━━━━━━━━ 47s 316ms/step - loss: 0.7210 - mae: 0.5988 - rmse: 0.8456

119/269 ━━━━━━━━━━━━━━━━━━━━ 47s 316ms/step - loss: 0.7202 - mae: 0.5984 - rmse: 0.8451

120/269 ━━━━━━━━━━━━━━━━━━━━ 47s 318ms/step - loss: 0.7194 - mae: 0.5979 - rmse: 0.8446

121/269 ━━━━━━━━━━━━━━━━━━━━ 47s 318ms/step - loss: 0.7186 - mae: 0.5975 - rmse: 0.8441

122/269 ━━━━━━━━━━━━━━━━━━━━ 46s 317ms/step - loss: 0.7178 - mae: 0.5971 - rmse: 0.8436

123/269 ━━━━━━━━━━━━━━━━━━━━ 46s 317ms/step - loss: 0.7169 - mae: 0.5966 - rmse: 0.8431

124/269 ━━━━━━━━━━━━━━━━━━━━ 46s 318ms/step - loss: 0.7160 - mae: 0.5962 - rmse: 0.8426

125/269 ━━━━━━━━━━━━━━━━━━━━ 45s 318ms/step - loss: 0.7151 - mae: 0.5957 - rmse: 0.8420

126/269 ━━━━━━━━━━━━━━━━━━━━ 45s 318ms/step - loss: 0.7142 - mae: 0.5952 - rmse: 0.8415

127/269 ━━━━━━━━━━━━━━━━━━━━ 45s 317ms/step - loss: 0.7133 - mae: 0.5947 - rmse: 0.8409

128/269 ━━━━━━━━━━━━━━━━━━━━ 44s 317ms/step - loss: 0.7124 - mae: 0.5942 - rmse: 0.8404

129/269 ━━━━━━━━━━━━━━━━━━━━ 44s 317ms/step - loss: 0.7114 - mae: 0.5937 - rmse: 0.8398

130/269 ━━━━━━━━━━━━━━━━━━━━ 43s 316ms/step - loss: 0.7105 - mae: 0.5932 - rmse: 0.8392

131/269 ━━━━━━━━━━━━━━━━━━━━ 43s 316ms/step - loss: 0.7095 - mae: 0.5927 - rmse: 0.8386

132/269 ━━━━━━━━━━━━━━━━━━━━ 43s 315ms/step - loss: 0.7085 - mae: 0.5922 - rmse: 0.8380

133/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 0.7076 - mae: 0.5917 - rmse: 0.8374

134/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 0.7066 - mae: 0.5912 - rmse: 0.8368

135/269 ━━━━━━━━━━━━━━━━━━━━ 42s 315ms/step - loss: 0.7056 - mae: 0.5907 - rmse: 0.8362

136/269 ━━━━━━━━━━━━━━━━━━━━ 41s 314ms/step - loss: 0.7047 - mae: 0.5902 - rmse: 0.8356

137/269 ━━━━━━━━━━━━━━━━━━━━ 41s 314ms/step - loss: 0.7037 - mae: 0.5897 - rmse: 0.8350

138/269 ━━━━━━━━━━━━━━━━━━━━ 41s 313ms/step - loss: 0.7027 - mae: 0.5892 - rmse: 0.8344

139/269 ━━━━━━━━━━━━━━━━━━━━ 40s 313ms/step - loss: 0.7017 - mae: 0.5887 - rmse: 0.8338

140/269 ━━━━━━━━━━━━━━━━━━━━ 40s 313ms/step - loss: 0.7007 - mae: 0.5882 - rmse: 0.8332

141/269 ━━━━━━━━━━━━━━━━━━━━ 40s 313ms/step - loss: 0.6997 - mae: 0.5877 - rmse: 0.8326

142/269 ━━━━━━━━━━━━━━━━━━━━ 39s 312ms/step - loss: 0.6987 - mae: 0.5872 - rmse: 0.8320

143/269 ━━━━━━━━━━━━━━━━━━━━ 39s 312ms/step - loss: 0.6977 - mae: 0.5866 - rmse: 0.8313

144/269 ━━━━━━━━━━━━━━━━━━━━ 39s 312ms/step - loss: 0.6967 - mae: 0.5861 - rmse: 0.8307

145/269 ━━━━━━━━━━━━━━━━━━━━ 38s 312ms/step - loss: 0.6956 - mae: 0.5856 - rmse: 0.8300

146/269 ━━━━━━━━━━━━━━━━━━━━ 38s 312ms/step - loss: 0.6946 - mae: 0.5850 - rmse: 0.8294

147/269 ━━━━━━━━━━━━━━━━━━━━ 38s 312ms/step - loss: 0.6935 - mae: 0.5844 - rmse: 0.8287

148/269 ━━━━━━━━━━━━━━━━━━━━ 37s 312ms/step - loss: 0.6925 - mae: 0.5839 - rmse: 0.8280

149/269 ━━━━━━━━━━━━━━━━━━━━ 37s 313ms/step - loss: 0.6914 - mae: 0.5833 - rmse: 0.8273

150/269 ━━━━━━━━━━━━━━━━━━━━ 37s 313ms/step - loss: 0.6903 - mae: 0.5827 - rmse: 0.8267

151/269 ━━━━━━━━━━━━━━━━━━━━ 37s 314ms/step - loss: 0.6892 - mae: 0.5821 - rmse: 0.8260

152/269 ━━━━━━━━━━━━━━━━━━━━ 36s 314ms/step - loss: 0.6882 - mae: 0.5816 - rmse: 0.8253

153/269 ━━━━━━━━━━━━━━━━━━━━ 36s 314ms/step - loss: 0.6871 - mae: 0.5810 - rmse: 0.8246

154/269 ━━━━━━━━━━━━━━━━━━━━ 36s 314ms/step - loss: 0.6860 - mae: 0.5804 - rmse: 0.8240

155/269 ━━━━━━━━━━━━━━━━━━━━ 35s 314ms/step - loss: 0.6849 - mae: 0.5798 - rmse: 0.8233

156/269 ━━━━━━━━━━━━━━━━━━━━ 35s 314ms/step - loss: 0.6838 - mae: 0.5792 - rmse: 0.8226

157/269 ━━━━━━━━━━━━━━━━━━━━ 35s 314ms/step - loss: 0.6828 - mae: 0.5786 - rmse: 0.8219

158/269 ━━━━━━━━━━━━━━━━━━━━ 34s 315ms/step - loss: 0.6817 - mae: 0.5781 - rmse: 0.8212

159/269 ━━━━━━━━━━━━━━━━━━━━ 34s 315ms/step - loss: 0.6806 - mae: 0.5775 - rmse: 0.8205

160/269 ━━━━━━━━━━━━━━━━━━━━ 34s 316ms/step - loss: 0.6795 - mae: 0.5769 - rmse: 0.8198

161/269 ━━━━━━━━━━━━━━━━━━━━ 34s 316ms/step - loss: 0.6784 - mae: 0.5763 - rmse: 0.8191

162/269 ━━━━━━━━━━━━━━━━━━━━ 33s 316ms/step - loss: 0.6773 - mae: 0.5757 - rmse: 0.8184

163/269 ━━━━━━━━━━━━━━━━━━━━ 33s 317ms/step - loss: 0.6762 - mae: 0.5751 - rmse: 0.8177

164/269 ━━━━━━━━━━━━━━━━━━━━ 33s 317ms/step - loss: 0.6751 - mae: 0.5745 - rmse: 0.8170

165/269 ━━━━━━━━━━━━━━━━━━━━ 32s 317ms/step - loss: 0.6741 - mae: 0.5740 - rmse: 0.8163

166/269 ━━━━━━━━━━━━━━━━━━━━ 32s 318ms/step - loss: 0.6730 - mae: 0.5734 - rmse: 0.8156

167/269 ━━━━━━━━━━━━━━━━━━━━ 32s 320ms/step - loss: 0.6719 - mae: 0.5728 - rmse: 0.8149

168/269 ━━━━━━━━━━━━━━━━━━━━ 32s 321ms/step - loss: 0.6708 - mae: 0.5722 - rmse: 0.8142

169/269 ━━━━━━━━━━━━━━━━━━━━ 32s 322ms/step - loss: 0.6698 - mae: 0.5717 - rmse: 0.8136

170/269 ━━━━━━━━━━━━━━━━━━━━ 31s 322ms/step - loss: 0.6688 - mae: 0.5711 - rmse: 0.8129

171/269 ━━━━━━━━━━━━━━━━━━━━ 31s 323ms/step - loss: 0.6677 - mae: 0.5706 - rmse: 0.8122

172/269 ━━━━━━━━━━━━━━━━━━━━ 31s 324ms/step - loss: 0.6667 - mae: 0.5700 - rmse: 0.8116

173/269 ━━━━━━━━━━━━━━━━━━━━ 31s 324ms/step - loss: 0.6657 - mae: 0.5695 - rmse: 0.8109

174/269 ━━━━━━━━━━━━━━━━━━━━ 30s 325ms/step - loss: 0.6647 - mae: 0.5690 - rmse: 0.8103

175/269 ━━━━━━━━━━━━━━━━━━━━ 30s 326ms/step - loss: 0.6637 - mae: 0.5685 - rmse: 0.8096

176/269 ━━━━━━━━━━━━━━━━━━━━ 30s 326ms/step - loss: 0.6627 - mae: 0.5679 - rmse: 0.8090

177/269 ━━━━━━━━━━━━━━━━━━━━ 29s 326ms/step - loss: 0.6617 - mae: 0.5674 - rmse: 0.8083

178/269 ━━━━━━━━━━━━━━━━━━━━ 29s 326ms/step - loss: 0.6607 - mae: 0.5669 - rmse: 0.8077

179/269 ━━━━━━━━━━━━━━━━━━━━ 29s 325ms/step - loss: 0.6597 - mae: 0.5664 - rmse: 0.8070

180/269 ━━━━━━━━━━━━━━━━━━━━ 28s 325ms/step - loss: 0.6587 - mae: 0.5659 - rmse: 0.8064

181/269 ━━━━━━━━━━━━━━━━━━━━ 28s 325ms/step - loss: 0.6577 - mae: 0.5653 - rmse: 0.8058

182/269 ━━━━━━━━━━━━━━━━━━━━ 28s 325ms/step - loss: 0.6568 - mae: 0.5648 - rmse: 0.8051

183/269 ━━━━━━━━━━━━━━━━━━━━ 27s 325ms/step - loss: 0.6558 - mae: 0.5643 - rmse: 0.8045

184/269 ━━━━━━━━━━━━━━━━━━━━ 27s 325ms/step - loss: 0.6548 - mae: 0.5638 - rmse: 0.8038

185/269 ━━━━━━━━━━━━━━━━━━━━ 27s 325ms/step - loss: 0.6538 - mae: 0.5632 - rmse: 0.8032

186/269 ━━━━━━━━━━━━━━━━━━━━ 26s 325ms/step - loss: 0.6528 - mae: 0.5627 - rmse: 0.8025

187/269 ━━━━━━━━━━━━━━━━━━━━ 26s 325ms/step - loss: 0.6518 - mae: 0.5622 - rmse: 0.8018

188/269 ━━━━━━━━━━━━━━━━━━━━ 26s 325ms/step - loss: 0.6508 - mae: 0.5617 - rmse: 0.8012

189/269 ━━━━━━━━━━━━━━━━━━━━ 26s 325ms/step - loss: 0.6498 - mae: 0.5611 - rmse: 0.8005

190/269 ━━━━━━━━━━━━━━━━━━━━ 25s 326ms/step - loss: 0.6488 - mae: 0.5606 - rmse: 0.7999

191/269 ━━━━━━━━━━━━━━━━━━━━ 25s 326ms/step - loss: 0.6478 - mae: 0.5601 - rmse: 0.7992

192/269 ━━━━━━━━━━━━━━━━━━━━ 25s 327ms/step - loss: 0.6468 - mae: 0.5595 - rmse: 0.7986

193/269 ━━━━━━━━━━━━━━━━━━━━ 24s 328ms/step - loss: 0.6458 - mae: 0.5590 - rmse: 0.7979

194/269 ━━━━━━━━━━━━━━━━━━━━ 24s 328ms/step - loss: 0.6448 - mae: 0.5584 - rmse: 0.7972

195/269 ━━━━━━━━━━━━━━━━━━━━ 24s 328ms/step - loss: 0.6438 - mae: 0.5579 - rmse: 0.7966

196/269 ━━━━━━━━━━━━━━━━━━━━ 24s 329ms/step - loss: 0.6428 - mae: 0.5574 - rmse: 0.7959

197/269 ━━━━━━━━━━━━━━━━━━━━ 23s 329ms/step - loss: 0.6418 - mae: 0.5568 - rmse: 0.7953

198/269 ━━━━━━━━━━━━━━━━━━━━ 23s 329ms/step - loss: 0.6409 - mae: 0.5563 - rmse: 0.7946

199/269 ━━━━━━━━━━━━━━━━━━━━ 23s 330ms/step - loss: 0.6399 - mae: 0.5558 - rmse: 0.7940

200/269 ━━━━━━━━━━━━━━━━━━━━ 22s 332ms/step - loss: 0.6389 - mae: 0.5552 - rmse: 0.7933

201/269 ━━━━━━━━━━━━━━━━━━━━ 22s 334ms/step - loss: 0.6379 - mae: 0.5547 - rmse: 0.7927

202/269 ━━━━━━━━━━━━━━━━━━━━ 22s 336ms/step - loss: 0.6370 - mae: 0.5542 - rmse: 0.7920

203/269 ━━━━━━━━━━━━━━━━━━━━ 22s 338ms/step - loss: 0.6360 - mae: 0.5537 - rmse: 0.7914

204/269 ━━━━━━━━━━━━━━━━━━━━ 22s 339ms/step - loss: 0.6351 - mae: 0.5532 - rmse: 0.7908

205/269 ━━━━━━━━━━━━━━━━━━━━ 21s 341ms/step - loss: 0.6341 - mae: 0.5527 - rmse: 0.7902

206/269 ━━━━━━━━━━━━━━━━━━━━ 21s 343ms/step - loss: 0.6332 - mae: 0.5521 - rmse: 0.7895

207/269 ━━━━━━━━━━━━━━━━━━━━ 21s 343ms/step - loss: 0.6323 - mae: 0.5516 - rmse: 0.7889

208/269 ━━━━━━━━━━━━━━━━━━━━ 21s 345ms/step - loss: 0.6313 - mae: 0.5511 - rmse: 0.7883

209/269 ━━━━━━━━━━━━━━━━━━━━ 20s 346ms/step - loss: 0.6304 - mae: 0.5506 - rmse: 0.7877

210/269 ━━━━━━━━━━━━━━━━━━━━ 20s 347ms/step - loss: 0.6295 - mae: 0.5501 - rmse: 0.7870

211/269 ━━━━━━━━━━━━━━━━━━━━ 20s 348ms/step - loss: 0.6285 - mae: 0.5496 - rmse: 0.7864

212/269 ━━━━━━━━━━━━━━━━━━━━ 19s 349ms/step - loss: 0.6276 - mae: 0.5491 - rmse: 0.7858

213/269 ━━━━━━━━━━━━━━━━━━━━ 19s 349ms/step - loss: 0.6267 - mae: 0.5486 - rmse: 0.7852

214/269 ━━━━━━━━━━━━━━━━━━━━ 19s 349ms/step - loss: 0.6258 - mae: 0.5481 - rmse: 0.7846

215/269 ━━━━━━━━━━━━━━━━━━━━ 18s 350ms/step - loss: 0.6249 - mae: 0.5476 - rmse: 0.7839

216/269 ━━━━━━━━━━━━━━━━━━━━ 18s 350ms/step - loss: 0.6239 - mae: 0.5471 - rmse: 0.7833

217/269 ━━━━━━━━━━━━━━━━━━━━ 18s 350ms/step - loss: 0.6230 - mae: 0.5466 - rmse: 0.7827

218/269 ━━━━━━━━━━━━━━━━━━━━ 17s 351ms/step - loss: 0.6221 - mae: 0.5461 - rmse: 0.7821

219/269 ━━━━━━━━━━━━━━━━━━━━ 17s 351ms/step - loss: 0.6212 - mae: 0.5456 - rmse: 0.7815

220/269 ━━━━━━━━━━━━━━━━━━━━ 17s 352ms/step - loss: 0.6203 - mae: 0.5451 - rmse: 0.7809

221/269 ━━━━━━━━━━━━━━━━━━━━ 16s 352ms/step - loss: 0.6194 - mae: 0.5446 - rmse: 0.7802

222/269 ━━━━━━━━━━━━━━━━━━━━ 16s 353ms/step - loss: 0.6185 - mae: 0.5441 - rmse: 0.7796

223/269 ━━━━━━━━━━━━━━━━━━━━ 16s 355ms/step - loss: 0.6176 - mae: 0.5436 - rmse: 0.7790

224/269 ━━━━━━━━━━━━━━━━━━━━ 16s 356ms/step - loss: 0.6167 - mae: 0.5432 - rmse: 0.7784

225/269 ━━━━━━━━━━━━━━━━━━━━ 15s 356ms/step - loss: 0.6158 - mae: 0.5427 - rmse: 0.7778

226/269 ━━━━━━━━━━━━━━━━━━━━ 15s 356ms/step - loss: 0.6149 - mae: 0.5422 - rmse: 0.7772

227/269 ━━━━━━━━━━━━━━━━━━━━ 14s 356ms/step - loss: 0.6140 - mae: 0.5417 - rmse: 0.7765

228/269 ━━━━━━━━━━━━━━━━━━━━ 14s 356ms/step - loss: 0.6131 - mae: 0.5412 - rmse: 0.7759

229/269 ━━━━━━━━━━━━━━━━━━━━ 14s 356ms/step - loss: 0.6122 - mae: 0.5407 - rmse: 0.7753

230/269 ━━━━━━━━━━━━━━━━━━━━ 13s 356ms/step - loss: 0.6113 - mae: 0.5402 - rmse: 0.7747

231/269 ━━━━━━━━━━━━━━━━━━━━ 13s 355ms/step - loss: 0.6104 - mae: 0.5397 - rmse: 0.7741

232/269 ━━━━━━━━━━━━━━━━━━━━ 13s 355ms/step - loss: 0.6095 - mae: 0.5392 - rmse: 0.7735

233/269 ━━━━━━━━━━━━━━━━━━━━ 12s 355ms/step - loss: 0.6086 - mae: 0.5387 - rmse: 0.7729

234/269 ━━━━━━━━━━━━━━━━━━━━ 12s 355ms/step - loss: 0.6077 - mae: 0.5382 - rmse: 0.7722

235/269 ━━━━━━━━━━━━━━━━━━━━ 12s 356ms/step - loss: 0.6068 - mae: 0.5377 - rmse: 0.7716

236/269 ━━━━━━━━━━━━━━━━━━━━ 11s 357ms/step - loss: 0.6059 - mae: 0.5372 - rmse: 0.7710

237/269 ━━━━━━━━━━━━━━━━━━━━ 11s 357ms/step - loss: 0.6050 - mae: 0.5367 - rmse: 0.7704

238/269 ━━━━━━━━━━━━━━━━━━━━ 11s 358ms/step - loss: 0.6041 - mae: 0.5362 - rmse: 0.7698

239/269 ━━━━━━━━━━━━━━━━━━━━ 10s 358ms/step - loss: 0.6033 - mae: 0.5357 - rmse: 0.7692

240/269 ━━━━━━━━━━━━━━━━━━━━ 10s 358ms/step - loss: 0.6024 - mae: 0.5352 - rmse: 0.7686

241/269 ━━━━━━━━━━━━━━━━━━━━ 10s 359ms/step - loss: 0.6015 - mae: 0.5347 - rmse: 0.7680

242/269 ━━━━━━━━━━━━━━━━━━━━ 9s 360ms/step - loss: 0.6006 - mae: 0.5342 - rmse: 0.7674

243/269 ━━━━━━━━━━━━━━━━━━━━ 9s 363ms/step - loss: 0.5998 - mae: 0.5338 - rmse: 0.7668

244/269 ━━━━━━━━━━━━━━━━━━━━ 9s 364ms/step - loss: 0.5989 - mae: 0.5333 - rmse: 0.7662

245/269 ━━━━━━━━━━━━━━━━━━━━ 8s 364ms/step - loss: 0.5981 - mae: 0.5328 - rmse: 0.7656

246/269 ━━━━━━━━━━━━━━━━━━━━ 8s 366ms/step - loss: 0.5972 - mae: 0.5323 - rmse: 0.7650

247/269 ━━━━━━━━━━━━━━━━━━━━ 8s 368ms/step - loss: 0.5963 - mae: 0.5318 - rmse: 0.7644

248/269 ━━━━━━━━━━━━━━━━━━━━ 7s 368ms/step - loss: 0.5955 - mae: 0.5314 - rmse: 0.7638

249/269 ━━━━━━━━━━━━━━━━━━━━ 7s 369ms/step - loss: 0.5946 - mae: 0.5309 - rmse: 0.7632

250/269 ━━━━━━━━━━━━━━━━━━━━ 7s 370ms/step - loss: 0.5938 - mae: 0.5304 - rmse: 0.7626

251/269 ━━━━━━━━━━━━━━━━━━━━ 6s 370ms/step - loss: 0.5930 - mae: 0.5300 - rmse: 0.7621

252/269 ━━━━━━━━━━━━━━━━━━━━ 6s 370ms/step - loss: 0.5921 - mae: 0.5295 - rmse: 0.7615

253/269 ━━━━━━━━━━━━━━━━━━━━ 5s 371ms/step - loss: 0.5913 - mae: 0.5290 - rmse: 0.7609

254/269 ━━━━━━━━━━━━━━━━━━━━ 5s 372ms/step - loss: 0.5904 - mae: 0.5286 - rmse: 0.7603

255/269 ━━━━━━━━━━━━━━━━━━━━ 5s 372ms/step - loss: 0.5896 - mae: 0.5281 - rmse: 0.7597

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 372ms/step - loss: 0.5888 - mae: 0.5276 - rmse: 0.7591

257/269 ━━━━━━━━━━━━━━━━━━━━ 4s 372ms/step - loss: 0.5879 - mae: 0.5272 - rmse: 0.7586

258/269 ━━━━━━━━━━━━━━━━━━━━ 4s 372ms/step - loss: 0.5871 - mae: 0.5267 - rmse: 0.7580

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 372ms/step - loss: 0.5863 - mae: 0.5262 - rmse: 0.7574

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 371ms/step - loss: 0.5855 - mae: 0.5258 - rmse: 0.7568

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 371ms/step - loss: 0.5846 - mae: 0.5253 - rmse: 0.7562

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 372ms/step - loss: 0.5838 - mae: 0.5249 - rmse: 0.7557

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 372ms/step - loss: 0.5830 - mae: 0.5244 - rmse: 0.7551

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 372ms/step - loss: 0.5822 - mae: 0.5239 - rmse: 0.7545

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 372ms/step - loss: 0.5814 - mae: 0.5235 - rmse: 0.7539

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 372ms/step - loss: 0.5806 - mae: 0.5230 - rmse: 0.7534

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 372ms/step - loss: 0.5798 - mae: 0.5226 - rmse: 0.7528

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 372ms/step - loss: 0.5790 - mae: 0.5221 - rmse: 0.7522

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 371ms/step - loss: 0.5782 - mae: 0.5217 - rmse: 0.7517

269/269 ━━━━━━━━━━━━━━━━━━━━ 112s 415ms/step - loss: 0.3648 - mae: 0.4019 - rmse: 0.6009 - val_loss: 0.7223 - val_mae: 0.5279 - val_rmse: 0.8477 - learning_rate: 5.0000e-04

Epoch 20/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:47 625ms/step - loss: 0.7825 - mae: 0.6286 - rmse: 0.8825

  2/269 ━━━━━━━━━━━━━━━━━━━━ 1:46 399ms/step - loss: 0.7000 - mae: 0.5966 - rmse: 0.8330

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 407ms/step - loss: 0.6872 - mae: 0.5982 - rmse: 0.8257

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 448ms/step - loss: 0.6715 - mae: 0.5962 - rmse: 0.8162

  5/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 499ms/step - loss: 0.6494 - mae: 0.5881 - rmse: 0.8023

  6/269 ━━━━━━━━━━━━━━━━━━━━ 2:16 518ms/step - loss: 0.6351 - mae: 0.5831 - rmse: 0.7933

  7/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 523ms/step - loss: 0.6268 - mae: 0.5804 - rmse: 0.7881

  8/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 505ms/step - loss: 0.6298 - mae: 0.5824 - rmse: 0.7901

  9/269 ━━━━━━━━━━━━━━━━━━━━ 2:13 513ms/step - loss: 0.6322 - mae: 0.5835 - rmse: 0.7918

 10/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 533ms/step - loss: 0.6307 - mae: 0.5827 - rmse: 0.7909

 11/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 535ms/step - loss: 0.6289 - mae: 0.5814 - rmse: 0.7899

 12/269 ━━━━━━━━━━━━━━━━━━━━ 2:18 540ms/step - loss: 0.6354 - mae: 0.5832 - rmse: 0.7939

 13/269 ━━━━━━━━━━━━━━━━━━━━ 2:17 538ms/step - loss: 0.6458 - mae: 0.5863 - rmse: 0.8002

 14/269 ━━━━━━━━━━━━━━━━━━━━ 2:14 527ms/step - loss: 0.6608 - mae: 0.5913 - rmse: 0.8090

 15/269 ━━━━━━━━━━━━━━━━━━━━ 2:10 514ms/step - loss: 0.6747 - mae: 0.5959 - rmse: 0.8171

 16/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 506ms/step - loss: 0.6891 - mae: 0.6008 - rmse: 0.8254

 17/269 ━━━━━━━━━━━━━━━━━━━━ 2:07 504ms/step - loss: 0.7033 - mae: 0.6054 - rmse: 0.8334

 18/269 ━━━━━━━━━━━━━━━━━━━━ 2:05 499ms/step - loss: 0.7147 - mae: 0.6090 - rmse: 0.8400

 19/269 ━━━━━━━━━━━━━━━━━━━━ 2:01 487ms/step - loss: 0.7266 - mae: 0.6125 - rmse: 0.8467

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:58 475ms/step - loss: 0.7366 - mae: 0.6154 - rmse: 0.8524

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:55 467ms/step - loss: 0.7446 - mae: 0.6176 - rmse: 0.8570

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:53 462ms/step - loss: 0.7521 - mae: 0.6199 - rmse: 0.8613

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:51 454ms/step - loss: 0.7603 - mae: 0.6225 - rmse: 0.8660

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:50 449ms/step - loss: 0.7674 - mae: 0.6248 - rmse: 0.8700

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:47 442ms/step - loss: 0.7732 - mae: 0.6266 - rmse: 0.8733

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:45 434ms/step - loss: 0.7788 - mae: 0.6283 - rmse: 0.8765

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:43 427ms/step - loss: 0.7831 - mae: 0.6295 - rmse: 0.8790

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:41 422ms/step - loss: 0.7866 - mae: 0.6305 - rmse: 0.8811

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:39 417ms/step - loss: 0.7896 - mae: 0.6313 - rmse: 0.8829

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 411ms/step - loss: 0.7917 - mae: 0.6317 - rmse: 0.8842

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 407ms/step - loss: 0.7932 - mae: 0.6320 - rmse: 0.8851

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 407ms/step - loss: 0.7943 - mae: 0.6321 - rmse: 0.8858

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 406ms/step - loss: 0.7951 - mae: 0.6322 - rmse: 0.8864

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 405ms/step - loss: 0.7955 - mae: 0.6322 - rmse: 0.8867

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 403ms/step - loss: 0.7959 - mae: 0.6322 - rmse: 0.8870

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 400ms/step - loss: 0.7959 - mae: 0.6321 - rmse: 0.8871

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 401ms/step - loss: 0.7958 - mae: 0.6320 - rmse: 0.8872

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 403ms/step - loss: 0.7954 - mae: 0.6317 - rmse: 0.8870

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 404ms/step - loss: 0.7949 - mae: 0.6314 - rmse: 0.8868

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:32 404ms/step - loss: 0.7941 - mae: 0.6310 - rmse: 0.8864

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 403ms/step - loss: 0.7935 - mae: 0.6307 - rmse: 0.8861

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 403ms/step - loss: 0.7926 - mae: 0.6302 - rmse: 0.8857

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 404ms/step - loss: 0.7916 - mae: 0.6298 - rmse: 0.8852

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 402ms/step - loss: 0.7908 - mae: 0.6294 - rmse: 0.8847

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 400ms/step - loss: 0.7899 - mae: 0.6290 - rmse: 0.8843

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 399ms/step - loss: 0.7888 - mae: 0.6285 - rmse: 0.8837

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 398ms/step - loss: 0.7878 - mae: 0.6280 - rmse: 0.8832

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 398ms/step - loss: 0.7866 - mae: 0.6275 - rmse: 0.8826

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 397ms/step - loss: 0.7852 - mae: 0.6269 - rmse: 0.8818

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 396ms/step - loss: 0.7838 - mae: 0.6263 - rmse: 0.8810

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 396ms/step - loss: 0.7823 - mae: 0.6256 - rmse: 0.8802

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 396ms/step - loss: 0.7808 - mae: 0.6249 - rmse: 0.8793

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 395ms/step - loss: 0.7792 - mae: 0.6242 - rmse: 0.8785

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 394ms/step - loss: 0.7777 - mae: 0.6236 - rmse: 0.8777

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 394ms/step - loss: 0.7762 - mae: 0.6230 - rmse: 0.8768

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 394ms/step - loss: 0.7747 - mae: 0.6224 - rmse: 0.8760

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 392ms/step - loss: 0.7732 - mae: 0.6217 - rmse: 0.8751

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 391ms/step - loss: 0.7716 - mae: 0.6211 - rmse: 0.8742

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 392ms/step - loss: 0.7702 - mae: 0.6205 - rmse: 0.8734

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 391ms/step - loss: 0.7688 - mae: 0.6199 - rmse: 0.8726

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 389ms/step - loss: 0.7674 - mae: 0.6194 - rmse: 0.8718

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 389ms/step - loss: 0.7660 - mae: 0.6189 - rmse: 0.8711

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 389ms/step - loss: 0.7647 - mae: 0.6184 - rmse: 0.8703

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 386ms/step - loss: 0.7633 - mae: 0.6178 - rmse: 0.8695

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 384ms/step - loss: 0.7618 - mae: 0.6172 - rmse: 0.8687

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 381ms/step - loss: 0.7602 - mae: 0.6166 - rmse: 0.8678

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 379ms/step - loss: 0.7587 - mae: 0.6160 - rmse: 0.8669

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 378ms/step - loss: 0.7571 - mae: 0.6153 - rmse: 0.8659

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 377ms/step - loss: 0.7556 - mae: 0.6147 - rmse: 0.8651

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 375ms/step - loss: 0.7541 - mae: 0.6142 - rmse: 0.8642

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 375ms/step - loss: 0.7528 - mae: 0.6136 - rmse: 0.8635

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 375ms/step - loss: 0.7515 - mae: 0.6131 - rmse: 0.8628

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 375ms/step - loss: 0.7503 - mae: 0.6126 - rmse: 0.8620

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 374ms/step - loss: 0.7491 - mae: 0.6121 - rmse: 0.8613

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 374ms/step - loss: 0.7480 - mae: 0.6116 - rmse: 0.8607

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 373ms/step - loss: 0.7469 - mae: 0.6112 - rmse: 0.8601

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 372ms/step - loss: 0.7459 - mae: 0.6108 - rmse: 0.8595

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 371ms/step - loss: 0.7449 - mae: 0.6104 - rmse: 0.8590

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 370ms/step - loss: 0.7440 - mae: 0.6100 - rmse: 0.8585

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 369ms/step - loss: 0.7431 - mae: 0.6096 - rmse: 0.8579

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 369ms/step - loss: 0.7425 - mae: 0.6094 - rmse: 0.8576

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 369ms/step - loss: 0.7421 - mae: 0.6092 - rmse: 0.8574

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 368ms/step - loss: 0.7420 - mae: 0.6091 - rmse: 0.8573

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 368ms/step - loss: 0.7419 - mae: 0.6090 - rmse: 0.8573

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 367ms/step - loss: 0.7419 - mae: 0.6089 - rmse: 0.8573

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 369ms/step - loss: 0.7419 - mae: 0.6089 - rmse: 0.8574

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 371ms/step - loss: 0.7420 - mae: 0.6089 - rmse: 0.8575

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 372ms/step - loss: 0.7421 - mae: 0.6088 - rmse: 0.8575

 89/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 371ms/step - loss: 0.7422 - mae: 0.6088 - rmse: 0.8576

 90/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 371ms/step - loss: 0.7423 - mae: 0.6088 - rmse: 0.8577

 91/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 371ms/step - loss: 0.7423 - mae: 0.6087 - rmse: 0.8577

 92/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 370ms/step - loss: 0.7423 - mae: 0.6087 - rmse: 0.8577

 93/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 369ms/step - loss: 0.7422 - mae: 0.6086 - rmse: 0.8577

 94/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 370ms/step - loss: 0.7421 - mae: 0.6085 - rmse: 0.8576

 95/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 369ms/step - loss: 0.7419 - mae: 0.6083 - rmse: 0.8575

 96/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 371ms/step - loss: 0.7417 - mae: 0.6081 - rmse: 0.8574

 97/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 373ms/step - loss: 0.7414 - mae: 0.6080 - rmse: 0.8573

 98/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 374ms/step - loss: 0.7411 - mae: 0.6078 - rmse: 0.8571

 99/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 374ms/step - loss: 0.7407 - mae: 0.6075 - rmse: 0.8569

100/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 374ms/step - loss: 0.7404 - mae: 0.6073 - rmse: 0.8567

101/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 373ms/step - loss: 0.7400 - mae: 0.6071 - rmse: 0.8565

102/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 373ms/step - loss: 0.7396 - mae: 0.6069 - rmse: 0.8563

103/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 372ms/step - loss: 0.7392 - mae: 0.6067 - rmse: 0.8561

104/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 372ms/step - loss: 0.7388 - mae: 0.6065 - rmse: 0.8559

105/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 372ms/step - loss: 0.7384 - mae: 0.6062 - rmse: 0.8556

106/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 373ms/step - loss: 0.7379 - mae: 0.6060 - rmse: 0.8554

107/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 372ms/step - loss: 0.7375 - mae: 0.6057 - rmse: 0.8551

108/269 ━━━━━━━━━━━━━━━━━━━━ 59s 372ms/step - loss: 0.7369 - mae: 0.6054 - rmse: 0.8548

109/269 ━━━━━━━━━━━━━━━━━━━━ 59s 373ms/step - loss: 0.7363 - mae: 0.6051 - rmse: 0.8545

110/269 ━━━━━━━━━━━━━━━━━━━━ 59s 373ms/step - loss: 0.7357 - mae: 0.6048 - rmse: 0.8541

111/269 ━━━━━━━━━━━━━━━━━━━━ 58s 373ms/step - loss: 0.7351 - mae: 0.6045 - rmse: 0.8538

112/269 ━━━━━━━━━━━━━━━━━━━━ 58s 373ms/step - loss: 0.7344 - mae: 0.6041 - rmse: 0.8534

113/269 ━━━━━━━━━━━━━━━━━━━━ 58s 373ms/step - loss: 0.7337 - mae: 0.6037 - rmse: 0.8530

114/269 ━━━━━━━━━━━━━━━━━━━━ 57s 373ms/step - loss: 0.7330 - mae: 0.6033 - rmse: 0.8525

115/269 ━━━━━━━━━━━━━━━━━━━━ 57s 373ms/step - loss: 0.7322 - mae: 0.6029 - rmse: 0.8521

116/269 ━━━━━━━━━━━━━━━━━━━━ 56s 372ms/step - loss: 0.7315 - mae: 0.6025 - rmse: 0.8516

117/269 ━━━━━━━━━━━━━━━━━━━━ 56s 373ms/step - loss: 0.7307 - mae: 0.6021 - rmse: 0.8512

118/269 ━━━━━━━━━━━━━━━━━━━━ 56s 373ms/step - loss: 0.7299 - mae: 0.6017 - rmse: 0.8507

119/269 ━━━━━━━━━━━━━━━━━━━━ 55s 372ms/step - loss: 0.7290 - mae: 0.6012 - rmse: 0.8502

120/269 ━━━━━━━━━━━━━━━━━━━━ 55s 372ms/step - loss: 0.7282 - mae: 0.6008 - rmse: 0.8497

121/269 ━━━━━━━━━━━━━━━━━━━━ 54s 371ms/step - loss: 0.7273 - mae: 0.6003 - rmse: 0.8492

122/269 ━━━━━━━━━━━━━━━━━━━━ 54s 371ms/step - loss: 0.7264 - mae: 0.5999 - rmse: 0.8486

123/269 ━━━━━━━━━━━━━━━━━━━━ 54s 371ms/step - loss: 0.7255 - mae: 0.5994 - rmse: 0.8481

124/269 ━━━━━━━━━━━━━━━━━━━━ 53s 371ms/step - loss: 0.7246 - mae: 0.5989 - rmse: 0.8476

125/269 ━━━━━━━━━━━━━━━━━━━━ 53s 370ms/step - loss: 0.7237 - mae: 0.5984 - rmse: 0.8470

126/269 ━━━━━━━━━━━━━━━━━━━━ 52s 369ms/step - loss: 0.7227 - mae: 0.5979 - rmse: 0.8464

127/269 ━━━━━━━━━━━━━━━━━━━━ 52s 369ms/step - loss: 0.7218 - mae: 0.5974 - rmse: 0.8458

128/269 ━━━━━━━━━━━━━━━━━━━━ 51s 368ms/step - loss: 0.7208 - mae: 0.5969 - rmse: 0.8452

129/269 ━━━━━━━━━━━━━━━━━━━━ 51s 368ms/step - loss: 0.7198 - mae: 0.5963 - rmse: 0.8446

130/269 ━━━━━━━━━━━━━━━━━━━━ 51s 368ms/step - loss: 0.7188 - mae: 0.5958 - rmse: 0.8440

131/269 ━━━━━━━━━━━━━━━━━━━━ 50s 367ms/step - loss: 0.7178 - mae: 0.5953 - rmse: 0.8434

132/269 ━━━━━━━━━━━━━━━━━━━━ 50s 366ms/step - loss: 0.7168 - mae: 0.5948 - rmse: 0.8428

133/269 ━━━━━━━━━━━━━━━━━━━━ 49s 366ms/step - loss: 0.7158 - mae: 0.5942 - rmse: 0.8422

134/269 ━━━━━━━━━━━━━━━━━━━━ 49s 365ms/step - loss: 0.7148 - mae: 0.5937 - rmse: 0.8416

135/269 ━━━━━━━━━━━━━━━━━━━━ 48s 364ms/step - loss: 0.7138 - mae: 0.5932 - rmse: 0.8410

136/269 ━━━━━━━━━━━━━━━━━━━━ 48s 364ms/step - loss: 0.7128 - mae: 0.5927 - rmse: 0.8404

137/269 ━━━━━━━━━━━━━━━━━━━━ 47s 363ms/step - loss: 0.7118 - mae: 0.5921 - rmse: 0.8397

138/269 ━━━━━━━━━━━━━━━━━━━━ 47s 363ms/step - loss: 0.7107 - mae: 0.5916 - rmse: 0.8391

139/269 ━━━━━━━━━━━━━━━━━━━━ 47s 363ms/step - loss: 0.7097 - mae: 0.5911 - rmse: 0.8385

140/269 ━━━━━━━━━━━━━━━━━━━━ 46s 362ms/step - loss: 0.7087 - mae: 0.5905 - rmse: 0.8378

141/269 ━━━━━━━━━━━━━━━━━━━━ 46s 362ms/step - loss: 0.7076 - mae: 0.5900 - rmse: 0.8372

142/269 ━━━━━━━━━━━━━━━━━━━━ 45s 361ms/step - loss: 0.7066 - mae: 0.5894 - rmse: 0.8365

143/269 ━━━━━━━━━━━━━━━━━━━━ 45s 361ms/step - loss: 0.7055 - mae: 0.5889 - rmse: 0.8359

144/269 ━━━━━━━━━━━━━━━━━━━━ 45s 361ms/step - loss: 0.7044 - mae: 0.5883 - rmse: 0.8352

145/269 ━━━━━━━━━━━━━━━━━━━━ 44s 361ms/step - loss: 0.7034 - mae: 0.5877 - rmse: 0.8345

146/269 ━━━━━━━━━━━━━━━━━━━━ 44s 361ms/step - loss: 0.7023 - mae: 0.5872 - rmse: 0.8339

147/269 ━━━━━━━━━━━━━━━━━━━━ 44s 361ms/step - loss: 0.7012 - mae: 0.5866 - rmse: 0.8332

148/269 ━━━━━━━━━━━━━━━━━━━━ 43s 360ms/step - loss: 0.7001 - mae: 0.5860 - rmse: 0.8325

149/269 ━━━━━━━━━━━━━━━━━━━━ 43s 361ms/step - loss: 0.6990 - mae: 0.5854 - rmse: 0.8318

150/269 ━━━━━━━━━━━━━━━━━━━━ 42s 361ms/step - loss: 0.6979 - mae: 0.5848 - rmse: 0.8311

151/269 ━━━━━━━━━━━━━━━━━━━━ 42s 361ms/step - loss: 0.6967 - mae: 0.5842 - rmse: 0.8304

152/269 ━━━━━━━━━━━━━━━━━━━━ 42s 361ms/step - loss: 0.6956 - mae: 0.5836 - rmse: 0.8297

153/269 ━━━━━━━━━━━━━━━━━━━━ 41s 362ms/step - loss: 0.6945 - mae: 0.5830 - rmse: 0.8290

154/269 ━━━━━━━━━━━━━━━━━━━━ 41s 362ms/step - loss: 0.6934 - mae: 0.5824 - rmse: 0.8283

155/269 ━━━━━━━━━━━━━━━━━━━━ 41s 362ms/step - loss: 0.6923 - mae: 0.5818 - rmse: 0.8276

156/269 ━━━━━━━━━━━━━━━━━━━━ 40s 363ms/step - loss: 0.6912 - mae: 0.5812 - rmse: 0.8269

157/269 ━━━━━━━━━━━━━━━━━━━━ 40s 363ms/step - loss: 0.6901 - mae: 0.5806 - rmse: 0.8262

158/269 ━━━━━━━━━━━━━━━━━━━━ 40s 363ms/step - loss: 0.6889 - mae: 0.5800 - rmse: 0.8255

159/269 ━━━━━━━━━━━━━━━━━━━━ 39s 363ms/step - loss: 0.6878 - mae: 0.5794 - rmse: 0.8247

160/269 ━━━━━━━━━━━━━━━━━━━━ 39s 364ms/step - loss: 0.6867 - mae: 0.5788 - rmse: 0.8240

161/269 ━━━━━━━━━━━━━━━━━━━━ 39s 364ms/step - loss: 0.6856 - mae: 0.5782 - rmse: 0.8233

162/269 ━━━━━━━━━━━━━━━━━━━━ 38s 364ms/step - loss: 0.6845 - mae: 0.5775 - rmse: 0.8226

163/269 ━━━━━━━━━━━━━━━━━━━━ 38s 364ms/step - loss: 0.6833 - mae: 0.5769 - rmse: 0.8219

164/269 ━━━━━━━━━━━━━━━━━━━━ 38s 363ms/step - loss: 0.6822 - mae: 0.5763 - rmse: 0.8212

165/269 ━━━━━━━━━━━━━━━━━━━━ 37s 363ms/step - loss: 0.6811 - mae: 0.5757 - rmse: 0.8204

166/269 ━━━━━━━━━━━━━━━━━━━━ 37s 362ms/step - loss: 0.6800 - mae: 0.5751 - rmse: 0.8197

167/269 ━━━━━━━━━━━━━━━━━━━━ 36s 362ms/step - loss: 0.6789 - mae: 0.5745 - rmse: 0.8190

168/269 ━━━━━━━━━━━━━━━━━━━━ 36s 362ms/step - loss: 0.6778 - mae: 0.5740 - rmse: 0.8183

169/269 ━━━━━━━━━━━━━━━━━━━━ 36s 362ms/step - loss: 0.6767 - mae: 0.5734 - rmse: 0.8176

170/269 ━━━━━━━━━━━━━━━━━━━━ 35s 362ms/step - loss: 0.6756 - mae: 0.5728 - rmse: 0.8169

171/269 ━━━━━━━━━━━━━━━━━━━━ 35s 362ms/step - loss: 0.6746 - mae: 0.5722 - rmse: 0.8163

172/269 ━━━━━━━━━━━━━━━━━━━━ 35s 362ms/step - loss: 0.6735 - mae: 0.5717 - rmse: 0.8156

173/269 ━━━━━━━━━━━━━━━━━━━━ 34s 361ms/step - loss: 0.6725 - mae: 0.5711 - rmse: 0.8149

174/269 ━━━━━━━━━━━━━━━━━━━━ 34s 361ms/step - loss: 0.6715 - mae: 0.5706 - rmse: 0.8143

175/269 ━━━━━━━━━━━━━━━━━━━━ 33s 360ms/step - loss: 0.6704 - mae: 0.5701 - rmse: 0.8136

176/269 ━━━━━━━━━━━━━━━━━━━━ 33s 359ms/step - loss: 0.6694 - mae: 0.5695 - rmse: 0.8129

177/269 ━━━━━━━━━━━━━━━━━━━━ 33s 359ms/step - loss: 0.6684 - mae: 0.5690 - rmse: 0.8123

178/269 ━━━━━━━━━━━━━━━━━━━━ 32s 360ms/step - loss: 0.6674 - mae: 0.5685 - rmse: 0.8116

179/269 ━━━━━━━━━━━━━━━━━━━━ 32s 360ms/step - loss: 0.6663 - mae: 0.5679 - rmse: 0.8109

180/269 ━━━━━━━━━━━━━━━━━━━━ 32s 360ms/step - loss: 0.6653 - mae: 0.5674 - rmse: 0.8103

181/269 ━━━━━━━━━━━━━━━━━━━━ 31s 360ms/step - loss: 0.6643 - mae: 0.5669 - rmse: 0.8096

182/269 ━━━━━━━━━━━━━━━━━━━━ 31s 360ms/step - loss: 0.6633 - mae: 0.5663 - rmse: 0.8090

183/269 ━━━━━━━━━━━━━━━━━━━━ 30s 360ms/step - loss: 0.6622 - mae: 0.5658 - rmse: 0.8083

184/269 ━━━━━━━━━━━━━━━━━━━━ 30s 359ms/step - loss: 0.6612 - mae: 0.5652 - rmse: 0.8076

185/269 ━━━━━━━━━━━━━━━━━━━━ 30s 359ms/step - loss: 0.6602 - mae: 0.5647 - rmse: 0.8070

186/269 ━━━━━━━━━━━━━━━━━━━━ 29s 359ms/step - loss: 0.6592 - mae: 0.5642 - rmse: 0.8063

187/269 ━━━━━━━━━━━━━━━━━━━━ 29s 358ms/step - loss: 0.6581 - mae: 0.5636 - rmse: 0.8056

188/269 ━━━━━━━━━━━━━━━━━━━━ 29s 358ms/step - loss: 0.6571 - mae: 0.5631 - rmse: 0.8049

189/269 ━━━━━━━━━━━━━━━━━━━━ 28s 358ms/step - loss: 0.6561 - mae: 0.5625 - rmse: 0.8043

190/269 ━━━━━━━━━━━━━━━━━━━━ 28s 357ms/step - loss: 0.6551 - mae: 0.5620 - rmse: 0.8036

191/269 ━━━━━━━━━━━━━━━━━━━━ 27s 357ms/step - loss: 0.6540 - mae: 0.5614 - rmse: 0.8029

192/269 ━━━━━━━━━━━━━━━━━━━━ 27s 356ms/step - loss: 0.6530 - mae: 0.5609 - rmse: 0.8023

193/269 ━━━━━━━━━━━━━━━━━━━━ 27s 356ms/step - loss: 0.6520 - mae: 0.5603 - rmse: 0.8016

194/269 ━━━━━━━━━━━━━━━━━━━━ 26s 356ms/step - loss: 0.6510 - mae: 0.5598 - rmse: 0.8009

195/269 ━━━━━━━━━━━━━━━━━━━━ 26s 355ms/step - loss: 0.6500 - mae: 0.5592 - rmse: 0.8002

196/269 ━━━━━━━━━━━━━━━━━━━━ 25s 355ms/step - loss: 0.6490 - mae: 0.5587 - rmse: 0.7996

197/269 ━━━━━━━━━━━━━━━━━━━━ 25s 355ms/step - loss: 0.6480 - mae: 0.5581 - rmse: 0.7989

198/269 ━━━━━━━━━━━━━━━━━━━━ 25s 355ms/step - loss: 0.6469 - mae: 0.5576 - rmse: 0.7982

199/269 ━━━━━━━━━━━━━━━━━━━━ 24s 354ms/step - loss: 0.6459 - mae: 0.5570 - rmse: 0.7976

200/269 ━━━━━━━━━━━━━━━━━━━━ 24s 354ms/step - loss: 0.6449 - mae: 0.5565 - rmse: 0.7969

201/269 ━━━━━━━━━━━━━━━━━━━━ 24s 353ms/step - loss: 0.6439 - mae: 0.5560 - rmse: 0.7963

202/269 ━━━━━━━━━━━━━━━━━━━━ 23s 353ms/step - loss: 0.6430 - mae: 0.5554 - rmse: 0.7956

203/269 ━━━━━━━━━━━━━━━━━━━━ 23s 353ms/step - loss: 0.6420 - mae: 0.5549 - rmse: 0.7950

204/269 ━━━━━━━━━━━━━━━━━━━━ 22s 353ms/step - loss: 0.6410 - mae: 0.5544 - rmse: 0.7943

205/269 ━━━━━━━━━━━━━━━━━━━━ 22s 352ms/step - loss: 0.6401 - mae: 0.5539 - rmse: 0.7937

206/269 ━━━━━━━━━━━━━━━━━━━━ 22s 352ms/step - loss: 0.6391 - mae: 0.5533 - rmse: 0.7930

207/269 ━━━━━━━━━━━━━━━━━━━━ 21s 352ms/step - loss: 0.6381 - mae: 0.5528 - rmse: 0.7924

208/269 ━━━━━━━━━━━━━━━━━━━━ 21s 351ms/step - loss: 0.6372 - mae: 0.5523 - rmse: 0.7918

209/269 ━━━━━━━━━━━━━━━━━━━━ 21s 351ms/step - loss: 0.6362 - mae: 0.5518 - rmse: 0.7911

210/269 ━━━━━━━━━━━━━━━━━━━━ 20s 351ms/step - loss: 0.6353 - mae: 0.5513 - rmse: 0.7905

211/269 ━━━━━━━━━━━━━━━━━━━━ 20s 351ms/step - loss: 0.6343 - mae: 0.5508 - rmse: 0.7899

212/269 ━━━━━━━━━━━━━━━━━━━━ 19s 350ms/step - loss: 0.6334 - mae: 0.5503 - rmse: 0.7892

213/269 ━━━━━━━━━━━━━━━━━━━━ 19s 350ms/step - loss: 0.6324 - mae: 0.5497 - rmse: 0.7886

214/269 ━━━━━━━━━━━━━━━━━━━━ 19s 350ms/step - loss: 0.6315 - mae: 0.5492 - rmse: 0.7880

215/269 ━━━━━━━━━━━━━━━━━━━━ 18s 350ms/step - loss: 0.6306 - mae: 0.5487 - rmse: 0.7873

216/269 ━━━━━━━━━━━━━━━━━━━━ 18s 349ms/step - loss: 0.6296 - mae: 0.5482 - rmse: 0.7867

217/269 ━━━━━━━━━━━━━━━━━━━━ 18s 349ms/step - loss: 0.6287 - mae: 0.5477 - rmse: 0.7861

218/269 ━━━━━━━━━━━━━━━━━━━━ 17s 349ms/step - loss: 0.6277 - mae: 0.5472 - rmse: 0.7854

219/269 ━━━━━━━━━━━━━━━━━━━━ 17s 348ms/step - loss: 0.6268 - mae: 0.5467 - rmse: 0.7848

220/269 ━━━━━━━━━━━━━━━━━━━━ 17s 348ms/step - loss: 0.6259 - mae: 0.5462 - rmse: 0.7842

221/269 ━━━━━━━━━━━━━━━━━━━━ 16s 348ms/step - loss: 0.6250 - mae: 0.5457 - rmse: 0.7836

222/269 ━━━━━━━━━━━━━━━━━━━━ 16s 347ms/step - loss: 0.6240 - mae: 0.5452 - rmse: 0.7829

223/269 ━━━━━━━━━━━━━━━━━━━━ 15s 347ms/step - loss: 0.6231 - mae: 0.5447 - rmse: 0.7823

224/269 ━━━━━━━━━━━━━━━━━━━━ 15s 346ms/step - loss: 0.6222 - mae: 0.5442 - rmse: 0.7817

225/269 ━━━━━━━━━━━━━━━━━━━━ 15s 346ms/step - loss: 0.6212 - mae: 0.5437 - rmse: 0.7811

226/269 ━━━━━━━━━━━━━━━━━━━━ 14s 346ms/step - loss: 0.6203 - mae: 0.5432 - rmse: 0.7804

227/269 ━━━━━━━━━━━━━━━━━━━━ 14s 346ms/step - loss: 0.6194 - mae: 0.5427 - rmse: 0.7798

228/269 ━━━━━━━━━━━━━━━━━━━━ 14s 345ms/step - loss: 0.6185 - mae: 0.5422 - rmse: 0.7792

229/269 ━━━━━━━━━━━━━━━━━━━━ 13s 345ms/step - loss: 0.6176 - mae: 0.5417 - rmse: 0.7785

230/269 ━━━━━━━━━━━━━━━━━━━━ 13s 345ms/step - loss: 0.6166 - mae: 0.5412 - rmse: 0.7779

231/269 ━━━━━━━━━━━━━━━━━━━━ 13s 345ms/step - loss: 0.6157 - mae: 0.5406 - rmse: 0.7773

232/269 ━━━━━━━━━━━━━━━━━━━━ 12s 345ms/step - loss: 0.6148 - mae: 0.5401 - rmse: 0.7767

233/269 ━━━━━━━━━━━━━━━━━━━━ 12s 345ms/step - loss: 0.6139 - mae: 0.5396 - rmse: 0.7760

234/269 ━━━━━━━━━━━━━━━━━━━━ 12s 345ms/step - loss: 0.6130 - mae: 0.5391 - rmse: 0.7754

235/269 ━━━━━━━━━━━━━━━━━━━━ 11s 345ms/step - loss: 0.6121 - mae: 0.5386 - rmse: 0.7748

236/269 ━━━━━━━━━━━━━━━━━━━━ 11s 345ms/step - loss: 0.6112 - mae: 0.5381 - rmse: 0.7742

237/269 ━━━━━━━━━━━━━━━━━━━━ 11s 345ms/step - loss: 0.6103 - mae: 0.5376 - rmse: 0.7736

238/269 ━━━━━━━━━━━━━━━━━━━━ 10s 344ms/step - loss: 0.6094 - mae: 0.5371 - rmse: 0.7729

239/269 ━━━━━━━━━━━━━━━━━━━━ 10s 344ms/step - loss: 0.6085 - mae: 0.5366 - rmse: 0.7723

240/269 ━━━━━━━━━━━━━━━━━━━━ 9s 344ms/step - loss: 0.6076 - mae: 0.5361 - rmse: 0.7717

241/269 ━━━━━━━━━━━━━━━━━━━━ 9s 344ms/step - loss: 0.6067 - mae: 0.5356 - rmse: 0.7711

242/269 ━━━━━━━━━━━━━━━━━━━━ 9s 344ms/step - loss: 0.6058 - mae: 0.5351 - rmse: 0.7705

243/269 ━━━━━━━━━━━━━━━━━━━━ 8s 344ms/step - loss: 0.6049 - mae: 0.5346 - rmse: 0.7699

244/269 ━━━━━━━━━━━━━━━━━━━━ 8s 344ms/step - loss: 0.6040 - mae: 0.5342 - rmse: 0.7693

245/269 ━━━━━━━━━━━━━━━━━━━━ 8s 344ms/step - loss: 0.6032 - mae: 0.5337 - rmse: 0.7687

246/269 ━━━━━━━━━━━━━━━━━━━━ 7s 343ms/step - loss: 0.6023 - mae: 0.5332 - rmse: 0.7681

247/269 ━━━━━━━━━━━━━━━━━━━━ 7s 343ms/step - loss: 0.6014 - mae: 0.5327 - rmse: 0.7675

248/269 ━━━━━━━━━━━━━━━━━━━━ 7s 343ms/step - loss: 0.6005 - mae: 0.5322 - rmse: 0.7669

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 343ms/step - loss: 0.5997 - mae: 0.5317 - rmse: 0.7663

250/269 ━━━━━━━━━━━━━━━━━━━━ 6s 344ms/step - loss: 0.5988 - mae: 0.5313 - rmse: 0.7657

251/269 ━━━━━━━━━━━━━━━━━━━━ 6s 344ms/step - loss: 0.5980 - mae: 0.5308 - rmse: 0.7651

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 344ms/step - loss: 0.5971 - mae: 0.5303 - rmse: 0.7645

253/269 ━━━━━━━━━━━━━━━━━━━━ 5s 344ms/step - loss: 0.5962 - mae: 0.5298 - rmse: 0.7639

254/269 ━━━━━━━━━━━━━━━━━━━━ 5s 344ms/step - loss: 0.5954 - mae: 0.5294 - rmse: 0.7633

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 344ms/step - loss: 0.5945 - mae: 0.5289 - rmse: 0.7627

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 344ms/step - loss: 0.5937 - mae: 0.5284 - rmse: 0.7621

257/269 ━━━━━━━━━━━━━━━━━━━━ 4s 344ms/step - loss: 0.5928 - mae: 0.5280 - rmse: 0.7615

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 344ms/step - loss: 0.5920 - mae: 0.5275 - rmse: 0.7609

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 344ms/step - loss: 0.5911 - mae: 0.5270 - rmse: 0.7603

260/269 ━━━━━━━━━━━━━━━━━━━━ 3s 344ms/step - loss: 0.5903 - mae: 0.5265 - rmse: 0.7597

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 343ms/step - loss: 0.5895 - mae: 0.5261 - rmse: 0.7591

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 343ms/step - loss: 0.5886 - mae: 0.5256 - rmse: 0.7586

263/269 ━━━━━━━━━━━━━━━━━━━━ 2s 343ms/step - loss: 0.5878 - mae: 0.5252 - rmse: 0.7580

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 343ms/step - loss: 0.5870 - mae: 0.5247 - rmse: 0.7574

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 343ms/step - loss: 0.5861 - mae: 0.5242 - rmse: 0.7568

266/269 ━━━━━━━━━━━━━━━━━━━━ 1s 343ms/step - loss: 0.5853 - mae: 0.5238 - rmse: 0.7562

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - loss: 0.5845 - mae: 0.5233 - rmse: 0.7556

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - loss: 0.5837 - mae: 0.5228 - rmse: 0.7551

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - loss: 0.5829 - mae: 0.5224 - rmse: 0.7545

269/269 ━━━━━━━━━━━━━━━━━━━━ 101s 374ms/step - loss: 0.3651 - mae: 0.4008 - rmse: 0.6012 - val_loss: 0.7254 - val_mae: 0.5325 - val_rmse: 0.8495 - learning_rate: 5.0000e-04

Epoch 21/60

  1/269 ━━━━━━━━━━━━━━━━━━━━ 2:11 491ms/step - loss: 0.8483 - mae: 0.6645 - rmse: 0.9190

  2/269 ━━━━━━━━━━━━━━━━━━━━ 2:08 482ms/step - loss: 0.7633 - mae: 0.6307 - rmse: 0.8702

  3/269 ━━━━━━━━━━━━━━━━━━━━ 1:57 443ms/step - loss: 0.7508 - mae: 0.6294 - rmse: 0.8633

  4/269 ━━━━━━━━━━━━━━━━━━━━ 1:48 410ms/step - loss: 0.7275 - mae: 0.6218 - rmse: 0.8497

  5/269 ━━━━━━━━━━━━━━━━━━━━ 1:44 397ms/step - loss: 0.7014 - mae: 0.6107 - rmse: 0.8338

  6/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 381ms/step - loss: 0.6836 - mae: 0.6036 - rmse: 0.8230

  7/269 ━━━━━━━━━━━━━━━━━━━━ 1:40 382ms/step - loss: 0.6740 - mae: 0.6002 - rmse: 0.8172

  8/269 ━━━━━━━━━━━━━━━━━━━━ 1:37 375ms/step - loss: 0.6751 - mae: 0.6014 - rmse: 0.8181

  9/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 377ms/step - loss: 0.6758 - mae: 0.6017 - rmse: 0.8186

 10/269 ━━━━━━━━━━━━━━━━━━━━ 1:38 379ms/step - loss: 0.6725 - mae: 0.6000 - rmse: 0.8167

 11/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 375ms/step - loss: 0.6684 - mae: 0.5978 - rmse: 0.8143

 12/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 376ms/step - loss: 0.6725 - mae: 0.5986 - rmse: 0.8169

 13/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 376ms/step - loss: 0.6813 - mae: 0.6008 - rmse: 0.8220

 14/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 374ms/step - loss: 0.6929 - mae: 0.6045 - rmse: 0.8288

 15/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 375ms/step - loss: 0.7037 - mae: 0.6079 - rmse: 0.8351

 16/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 380ms/step - loss: 0.7160 - mae: 0.6120 - rmse: 0.8421

 17/269 ━━━━━━━━━━━━━━━━━━━━ 1:36 383ms/step - loss: 0.7282 - mae: 0.6157 - rmse: 0.8489

 18/269 ━━━━━━━━━━━━━━━━━━━━ 1:35 381ms/step - loss: 0.7380 - mae: 0.6187 - rmse: 0.8545

 19/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 378ms/step - loss: 0.7482 - mae: 0.6216 - rmse: 0.8603

 20/269 ━━━━━━━━━━━━━━━━━━━━ 1:34 378ms/step - loss: 0.7570 - mae: 0.6240 - rmse: 0.8652

 21/269 ━━━━━━━━━━━━━━━━━━━━ 1:33 376ms/step - loss: 0.7639 - mae: 0.6258 - rmse: 0.8691

 22/269 ━━━━━━━━━━━━━━━━━━━━ 1:31 372ms/step - loss: 0.7704 - mae: 0.6277 - rmse: 0.8728

 23/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 368ms/step - loss: 0.7773 - mae: 0.6298 - rmse: 0.8767

 24/269 ━━━━━━━━━━━━━━━━━━━━ 1:30 367ms/step - loss: 0.7833 - mae: 0.6317 - rmse: 0.8801

 25/269 ━━━━━━━━━━━━━━━━━━━━ 1:29 366ms/step - loss: 0.7881 - mae: 0.6331 - rmse: 0.8828

 26/269 ━━━━━━━━━━━━━━━━━━━━ 1:28 363ms/step - loss: 0.7927 - mae: 0.6343 - rmse: 0.8855

 27/269 ━━━━━━━━━━━━━━━━━━━━ 1:27 361ms/step - loss: 0.7962 - mae: 0.6352 - rmse: 0.8875

 28/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 360ms/step - loss: 0.7988 - mae: 0.6357 - rmse: 0.8890

 29/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 360ms/step - loss: 0.8010 - mae: 0.6362 - rmse: 0.8903

 30/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 361ms/step - loss: 0.8024 - mae: 0.6364 - rmse: 0.8912

 31/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 361ms/step - loss: 0.8033 - mae: 0.6364 - rmse: 0.8917

 32/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 363ms/step - loss: 0.8038 - mae: 0.6362 - rmse: 0.8921

 33/269 ━━━━━━━━━━━━━━━━━━━━ 1:26 366ms/step - loss: 0.8040 - mae: 0.6360 - rmse: 0.8923

 34/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 364ms/step - loss: 0.8039 - mae: 0.6357 - rmse: 0.8923

 35/269 ━━━━━━━━━━━━━━━━━━━━ 1:25 364ms/step - loss: 0.8038 - mae: 0.6355 - rmse: 0.8923

 36/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 365ms/step - loss: 0.8034 - mae: 0.6351 - rmse: 0.8921

 37/269 ━━━━━━━━━━━━━━━━━━━━ 1:24 364ms/step - loss: 0.8029 - mae: 0.6348 - rmse: 0.8919

 38/269 ━━━━━━━━━━━━━━━━━━━━ 1:23 363ms/step - loss: 0.8021 - mae: 0.6343 - rmse: 0.8915

 39/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 361ms/step - loss: 0.8011 - mae: 0.6338 - rmse: 0.8910

 40/269 ━━━━━━━━━━━━━━━━━━━━ 1:22 359ms/step - loss: 0.7999 - mae: 0.6332 - rmse: 0.8904

 41/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 358ms/step - loss: 0.7989 - mae: 0.6327 - rmse: 0.8899

 42/269 ━━━━━━━━━━━━━━━━━━━━ 1:21 358ms/step - loss: 0.7977 - mae: 0.6321 - rmse: 0.8892

 43/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 357ms/step - loss: 0.7965 - mae: 0.6315 - rmse: 0.8886

 44/269 ━━━━━━━━━━━━━━━━━━━━ 1:20 356ms/step - loss: 0.7954 - mae: 0.6309 - rmse: 0.8880

 45/269 ━━━━━━━━━━━━━━━━━━━━ 1:19 354ms/step - loss: 0.7942 - mae: 0.6304 - rmse: 0.8873

 46/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 353ms/step - loss: 0.7928 - mae: 0.6298 - rmse: 0.8866

 47/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 353ms/step - loss: 0.7915 - mae: 0.6292 - rmse: 0.8859

 48/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 354ms/step - loss: 0.7901 - mae: 0.6285 - rmse: 0.8851

 49/269 ━━━━━━━━━━━━━━━━━━━━ 1:18 355ms/step - loss: 0.7885 - mae: 0.6278 - rmse: 0.8842

 50/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 355ms/step - loss: 0.7868 - mae: 0.6271 - rmse: 0.8833

 51/269 ━━━━━━━━━━━━━━━━━━━━ 1:17 355ms/step - loss: 0.7851 - mae: 0.6263 - rmse: 0.8823

 52/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 355ms/step - loss: 0.7834 - mae: 0.6255 - rmse: 0.8813

 53/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 355ms/step - loss: 0.7815 - mae: 0.6247 - rmse: 0.8803

 54/269 ━━━━━━━━━━━━━━━━━━━━ 1:16 355ms/step - loss: 0.7799 - mae: 0.6240 - rmse: 0.8794

 55/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 354ms/step - loss: 0.7782 - mae: 0.6233 - rmse: 0.8784

 56/269 ━━━━━━━━━━━━━━━━━━━━ 1:15 352ms/step - loss: 0.7766 - mae: 0.6226 - rmse: 0.8775

 57/269 ━━━━━━━━━━━━━━━━━━━━ 1:14 350ms/step - loss: 0.7749 - mae: 0.6219 - rmse: 0.8765

 58/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 350ms/step - loss: 0.7732 - mae: 0.6212 - rmse: 0.8756

 59/269 ━━━━━━━━━━━━━━━━━━━━ 1:13 349ms/step - loss: 0.7716 - mae: 0.6206 - rmse: 0.8747

 60/269 ━━━━━━━━━━━━━━━━━━━━ 1:12 347ms/step - loss: 0.7700 - mae: 0.6199 - rmse: 0.8737

 61/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 346ms/step - loss: 0.7685 - mae: 0.6193 - rmse: 0.8729

 62/269 ━━━━━━━━━━━━━━━━━━━━ 1:11 345ms/step - loss: 0.7671 - mae: 0.6188 - rmse: 0.8720

 63/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 344ms/step - loss: 0.7656 - mae: 0.6182 - rmse: 0.8712

 64/269 ━━━━━━━━━━━━━━━━━━━━ 1:10 343ms/step - loss: 0.7640 - mae: 0.6176 - rmse: 0.8703

 65/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 343ms/step - loss: 0.7624 - mae: 0.6170 - rmse: 0.8694

 66/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 343ms/step - loss: 0.7608 - mae: 0.6163 - rmse: 0.8684

 67/269 ━━━━━━━━━━━━━━━━━━━━ 1:09 342ms/step - loss: 0.7591 - mae: 0.6157 - rmse: 0.8675

 68/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 341ms/step - loss: 0.7574 - mae: 0.6150 - rmse: 0.8665

 69/269 ━━━━━━━━━━━━━━━━━━━━ 1:08 340ms/step - loss: 0.7558 - mae: 0.6144 - rmse: 0.8655

 70/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 340ms/step - loss: 0.7543 - mae: 0.6137 - rmse: 0.8646

 71/269 ━━━━━━━━━━━━━━━━━━━━ 1:07 339ms/step - loss: 0.7528 - mae: 0.6132 - rmse: 0.8638

 72/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 338ms/step - loss: 0.7514 - mae: 0.6126 - rmse: 0.8630

 73/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 338ms/step - loss: 0.7501 - mae: 0.6121 - rmse: 0.8622

 74/269 ━━━━━━━━━━━━━━━━━━━━ 1:06 338ms/step - loss: 0.7488 - mae: 0.6115 - rmse: 0.8615

 75/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 338ms/step - loss: 0.7476 - mae: 0.6110 - rmse: 0.8607

 76/269 ━━━━━━━━━━━━━━━━━━━━ 1:05 337ms/step - loss: 0.7464 - mae: 0.6106 - rmse: 0.8601

 77/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 337ms/step - loss: 0.7453 - mae: 0.6101 - rmse: 0.8594

 78/269 ━━━━━━━━━━━━━━━━━━━━ 1:04 337ms/step - loss: 0.7443 - mae: 0.6097 - rmse: 0.8589

 79/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 337ms/step - loss: 0.7433 - mae: 0.6093 - rmse: 0.8583

 80/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 336ms/step - loss: 0.7423 - mae: 0.6089 - rmse: 0.8577

 81/269 ━━━━━━━━━━━━━━━━━━━━ 1:03 336ms/step - loss: 0.7415 - mae: 0.6086 - rmse: 0.8573

 82/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 336ms/step - loss: 0.7410 - mae: 0.6084 - rmse: 0.8570

 83/269 ━━━━━━━━━━━━━━━━━━━━ 1:02 335ms/step - loss: 0.7407 - mae: 0.6082 - rmse: 0.8568

 84/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 335ms/step - loss: 0.7404 - mae: 0.6081 - rmse: 0.8567

 85/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 334ms/step - loss: 0.7402 - mae: 0.6080 - rmse: 0.8566

 86/269 ━━━━━━━━━━━━━━━━━━━━ 1:01 334ms/step - loss: 0.7402 - mae: 0.6079 - rmse: 0.8566

 87/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 334ms/step - loss: 0.7401 - mae: 0.6079 - rmse: 0.8566

 88/269 ━━━━━━━━━━━━━━━━━━━━ 1:00 333ms/step - loss: 0.7400 - mae: 0.6078 - rmse: 0.8565

 89/269 ━━━━━━━━━━━━━━━━━━━━ 59s 333ms/step - loss: 0.7400 - mae: 0.6077 - rmse: 0.8565

 90/269 ━━━━━━━━━━━━━━━━━━━━ 59s 333ms/step - loss: 0.7399 - mae: 0.6076 - rmse: 0.8565

 91/269 ━━━━━━━━━━━━━━━━━━━━ 59s 333ms/step - loss: 0.7398 - mae: 0.6076 - rmse: 0.8564

 92/269 ━━━━━━━━━━━━━━━━━━━━ 58s 332ms/step - loss: 0.7396 - mae: 0.6074 - rmse: 0.8564

 93/269 ━━━━━━━━━━━━━━━━━━━━ 58s 332ms/step - loss: 0.7394 - mae: 0.6073 - rmse: 0.8562

 94/269 ━━━━━━━━━━━━━━━━━━━━ 57s 331ms/step - loss: 0.7391 - mae: 0.6071 - rmse: 0.8561

 95/269 ━━━━━━━━━━━━━━━━━━━━ 57s 330ms/step - loss: 0.7388 - mae: 0.6070 - rmse: 0.8559

 96/269 ━━━━━━━━━━━━━━━━━━━━ 57s 330ms/step - loss: 0.7384 - mae: 0.6067 - rmse: 0.8557

 97/269 ━━━━━━━━━━━━━━━━━━━━ 56s 330ms/step - loss: 0.7380 - mae: 0.6065 - rmse: 0.8555

 98/269 ━━━━━━━━━━━━━━━━━━━━ 56s 330ms/step - loss: 0.7376 - mae: 0.6063 - rmse: 0.8553

 99/269 ━━━━━━━━━━━━━━━━━━━━ 55s 329ms/step - loss: 0.7372 - mae: 0.6061 - rmse: 0.8550

100/269 ━━━━━━━━━━━━━━━━━━━━ 55s 329ms/step - loss: 0.7367 - mae: 0.6058 - rmse: 0.8547

101/269 ━━━━━━━━━━━━━━━━━━━━ 55s 329ms/step - loss: 0.7362 - mae: 0.6055 - rmse: 0.8545

102/269 ━━━━━━━━━━━━━━━━━━━━ 54s 329ms/step - loss: 0.7357 - mae: 0.6053 - rmse: 0.8542

103/269 ━━━━━━━━━━━━━━━━━━━━ 55s 331ms/step - loss: 0.7352 - mae: 0.6051 - rmse: 0.8539

104/269 ━━━━━━━━━━━━━━━━━━━━ 54s 333ms/step - loss: 0.7347 - mae: 0.6048 - rmse: 0.8536

105/269 ━━━━━━━━━━━━━━━━━━━━ 54s 334ms/step - loss: 0.7342 - mae: 0.6045 - rmse: 0.8533

106/269 ━━━━━━━━━━━━━━━━━━━━ 54s 335ms/step - loss: 0.7336 - mae: 0.6043 - rmse: 0.8530

107/269 ━━━━━━━━━━━━━━━━━━━━ 54s 337ms/step - loss: 0.7330 - mae: 0.6040 - rmse: 0.8527

108/269 ━━━━━━━━━━━━━━━━━━━━ 54s 338ms/step - loss: 0.7324 - mae: 0.6037 - rmse: 0.8523

109/269 ━━━━━━━━━━━━━━━━━━━━ 54s 339ms/step - loss: 0.7318 - mae: 0.6034 - rmse: 0.8519

110/269 ━━━━━━━━━━━━━━━━━━━━ 53s 339ms/step - loss: 0.7311 - mae: 0.6030 - rmse: 0.8515

111/269 ━━━━━━━━━━━━━━━━━━━━ 53s 339ms/step - loss: 0.7303 - mae: 0.6026 - rmse: 0.8511

112/269 ━━━━━━━━━━━━━━━━━━━━ 53s 340ms/step - loss: 0.7296 - mae: 0.6022 - rmse: 0.8507

113/269 ━━━━━━━━━━━━━━━━━━━━ 53s 341ms/step - loss: 0.7288 - mae: 0.6019 - rmse: 0.8502

114/269 ━━━━━━━━━━━━━━━━━━━━ 52s 342ms/step - loss: 0.7280 - mae: 0.6014 - rmse: 0.8497

115/269 ━━━━━━━━━━━━━━━━━━━━ 52s 342ms/step - loss: 0.7272 - mae: 0.6010 - rmse: 0.8492

116/269 ━━━━━━━━━━━━━━━━━━━━ 52s 342ms/step - loss: 0.7264 - mae: 0.6006 - rmse: 0.8487

117/269 ━━━━━━━━━━━━━━━━━━━━ 51s 342ms/step - loss: 0.7255 - mae: 0.6001 - rmse: 0.8482

118/269 ━━━━━━━━━━━━━━━━━━━━ 51s 341ms/step - loss: 0.7246 - mae: 0.5997 - rmse: 0.8477

119/269 ━━━━━━━━━━━━━━━━━━━━ 51s 341ms/step - loss: 0.7237 - mae: 0.5992 - rmse: 0.8472

120/269 ━━━━━━━━━━━━━━━━━━━━ 50s 341ms/step - loss: 0.7228 - mae: 0.5988 - rmse: 0.8466

121/269 ━━━━━━━━━━━━━━━━━━━━ 50s 341ms/step - loss: 0.7219 - mae: 0.5983 - rmse: 0.8461

122/269 ━━━━━━━━━━━━━━━━━━━━ 50s 341ms/step - loss: 0.7210 - mae: 0.5978 - rmse: 0.8455

123/269 ━━━━━━━━━━━━━━━━━━━━ 49s 340ms/step - loss: 0.7200 - mae: 0.5973 - rmse: 0.8449

124/269 ━━━━━━━━━━━━━━━━━━━━ 49s 340ms/step - loss: 0.7190 - mae: 0.5968 - rmse: 0.8443

125/269 ━━━━━━━━━━━━━━━━━━━━ 48s 340ms/step - loss: 0.7180 - mae: 0.5963 - rmse: 0.8437

126/269 ━━━━━━━━━━━━━━━━━━━━ 48s 339ms/step - loss: 0.7170 - mae: 0.5958 - rmse: 0.8431

127/269 ━━━━━━━━━━━━━━━━━━━━ 48s 339ms/step - loss: 0.7160 - mae: 0.5953 - rmse: 0.8425

128/269 ━━━━━━━━━━━━━━━━━━━━ 47s 339ms/step - loss: 0.7150 - mae: 0.5947 - rmse: 0.8419

129/269 ━━━━━━━━━━━━━━━━━━━━ 47s 339ms/step - loss: 0.7140 - mae: 0.5942 - rmse: 0.8413

130/269 ━━━━━━━━━━━━━━━━━━━━ 47s 338ms/step - loss: 0.7129 - mae: 0.5937 - rmse: 0.8406

131/269 ━━━━━━━━━━━━━━━━━━━━ 46s 338ms/step - loss: 0.7119 - mae: 0.5931 - rmse: 0.8400

132/269 ━━━━━━━━━━━━━━━━━━━━ 46s 339ms/step - loss: 0.7108 - mae: 0.5926 - rmse: 0.8393

133/269 ━━━━━━━━━━━━━━━━━━━━ 46s 339ms/step - loss: 0.7098 - mae: 0.5920 - rmse: 0.8387

134/269 ━━━━━━━━━━━━━━━━━━━━ 45s 339ms/step - loss: 0.7088 - mae: 0.5915 - rmse: 0.8381

135/269 ━━━━━━━━━━━━━━━━━━━━ 45s 339ms/step - loss: 0.7077 - mae: 0.5910 - rmse: 0.8374

136/269 ━━━━━━━━━━━━━━━━━━━━ 45s 339ms/step - loss: 0.7067 - mae: 0.5904 - rmse: 0.8368

137/269 ━━━━━━━━━━━━━━━━━━━━ 44s 338ms/step - loss: 0.7056 - mae: 0.5899 - rmse: 0.8361

138/269 ━━━━━━━━━━━━━━━━━━━━ 44s 339ms/step - loss: 0.7046 - mae: 0.5894 - rmse: 0.8355

139/269 ━━━━━━━━━━━━━━━━━━━━ 44s 339ms/step - loss: 0.7035 - mae: 0.5888 - rmse: 0.8348

140/269 ━━━━━━━━━━━━━━━━━━━━ 43s 339ms/step - loss: 0.7025 - mae: 0.5883 - rmse: 0.8341

141/269 ━━━━━━━━━━━━━━━━━━━━ 43s 340ms/step - loss: 0.7014 - mae: 0.5878 - rmse: 0.8335

142/269 ━━━━━━━━━━━━━━━━━━━━ 43s 339ms/step - loss: 0.7003 - mae: 0.5872 - rmse: 0.8328

143/269 ━━━━━━━━━━━━━━━━━━━━ 42s 339ms/step - loss: 0.6992 - mae: 0.5866 - rmse: 0.8321

144/269 ━━━━━━━━━━━━━━━━━━━━ 42s 338ms/step - loss: 0.6981 - mae: 0.5861 - rmse: 0.8314

145/269 ━━━━━━━━━━━━━━━━━━━━ 42s 339ms/step - loss: 0.6970 - mae: 0.5855 - rmse: 0.8307

146/269 ━━━━━━━━━━━━━━━━━━━━ 41s 339ms/step - loss: 0.6959 - mae: 0.5849 - rmse: 0.8300

147/269 ━━━━━━━━━━━━━━━━━━━━ 41s 339ms/step - loss: 0.6948 - mae: 0.5843 - rmse: 0.8293

148/269 ━━━━━━━━━━━━━━━━━━━━ 41s 339ms/step - loss: 0.6936 - mae: 0.5837 - rmse: 0.8286

149/269 ━━━━━━━━━━━━━━━━━━━━ 40s 339ms/step - loss: 0.6925 - mae: 0.5831 - rmse: 0.8279

150/269 ━━━━━━━━━━━━━━━━━━━━ 40s 340ms/step - loss: 0.6914 - mae: 0.5825 - rmse: 0.8272

151/269 ━━━━━━━━━━━━━━━━━━━━ 40s 339ms/step - loss: 0.6902 - mae: 0.5819 - rmse: 0.8265

152/269 ━━━━━━━━━━━━━━━━━━━━ 39s 339ms/step - loss: 0.6891 - mae: 0.5813 - rmse: 0.8258

153/269 ━━━━━━━━━━━━━━━━━━━━ 39s 339ms/step - loss: 0.6880 - mae: 0.5807 - rmse: 0.8250

154/269 ━━━━━━━━━━━━━━━━━━━━ 38s 339ms/step - loss: 0.6869 - mae: 0.5801 - rmse: 0.8243

155/269 ━━━━━━━━━━━━━━━━━━━━ 38s 340ms/step - loss: 0.6857 - mae: 0.5795 - rmse: 0.8236

156/269 ━━━━━━━━━━━━━━━━━━━━ 38s 339ms/step - loss: 0.6846 - mae: 0.5789 - rmse: 0.8229

157/269 ━━━━━━━━━━━━━━━━━━━━ 37s 338ms/step - loss: 0.6834 - mae: 0.5783 - rmse: 0.8221

158/269 ━━━━━━━━━━━━━━━━━━━━ 37s 337ms/step - loss: 0.6823 - mae: 0.5776 - rmse: 0.8214

159/269 ━━━━━━━━━━━━━━━━━━━━ 37s 336ms/step - loss: 0.6812 - mae: 0.5770 - rmse: 0.8207

160/269 ━━━━━━━━━━━━━━━━━━━━ 36s 335ms/step - loss: 0.6800 - mae: 0.5764 - rmse: 0.8200

161/269 ━━━━━━━━━━━━━━━━━━━━ 36s 335ms/step - loss: 0.6789 - mae: 0.5758 - rmse: 0.8192

162/269 ━━━━━━━━━━━━━━━━━━━━ 35s 335ms/step - loss: 0.6778 - mae: 0.5752 - rmse: 0.8185

163/269 ━━━━━━━━━━━━━━━━━━━━ 35s 336ms/step - loss: 0.6766 - mae: 0.5746 - rmse: 0.8178

164/269 ━━━━━━━━━━━━━━━━━━━━ 35s 335ms/step - loss: 0.6755 - mae: 0.5740 - rmse: 0.8170

165/269 ━━━━━━━━━━━━━━━━━━━━ 34s 335ms/step - loss: 0.6744 - mae: 0.5734 - rmse: 0.8163

166/269 ━━━━━━━━━━━━━━━━━━━━ 34s 334ms/step - loss: 0.6732 - mae: 0.5728 - rmse: 0.8156

167/269 ━━━━━━━━━━━━━━━━━━━━ 34s 334ms/step - loss: 0.6721 - mae: 0.5722 - rmse: 0.8149

168/269 ━━━━━━━━━━━━━━━━━━━━ 33s 334ms/step - loss: 0.6710 - mae: 0.5716 - rmse: 0.8141

169/269 ━━━━━━━━━━━━━━━━━━━━ 33s 333ms/step - loss: 0.6699 - mae: 0.5710 - rmse: 0.8134

170/269 ━━━━━━━━━━━━━━━━━━━━ 32s 333ms/step - loss: 0.6688 - mae: 0.5704 - rmse: 0.8127

171/269 ━━━━━━━━━━━━━━━━━━━━ 32s 333ms/step - loss: 0.6678 - mae: 0.5699 - rmse: 0.8120

172/269 ━━━━━━━━━━━━━━━━━━━━ 32s 333ms/step - loss: 0.6667 - mae: 0.5693 - rmse: 0.8114

173/269 ━━━━━━━━━━━━━━━━━━━━ 31s 332ms/step - loss: 0.6657 - mae: 0.5688 - rmse: 0.8107

174/269 ━━━━━━━━━━━━━━━━━━━━ 31s 332ms/step - loss: 0.6646 - mae: 0.5682 - rmse: 0.8100

175/269 ━━━━━━━━━━━━━━━━━━━━ 31s 331ms/step - loss: 0.6636 - mae: 0.5677 - rmse: 0.8093

176/269 ━━━━━━━━━━━━━━━━━━━━ 30s 331ms/step - loss: 0.6626 - mae: 0.5672 - rmse: 0.8087

177/269 ━━━━━━━━━━━━━━━━━━━━ 30s 330ms/step - loss: 0.6615 - mae: 0.5666 - rmse: 0.8080

178/269 ━━━━━━━━━━━━━━━━━━━━ 30s 330ms/step - loss: 0.6605 - mae: 0.5661 - rmse: 0.8073

179/269 ━━━━━━━━━━━━━━━━━━━━ 29s 330ms/step - loss: 0.6595 - mae: 0.5656 - rmse: 0.8067

180/269 ━━━━━━━━━━━━━━━━━━━━ 29s 330ms/step - loss: 0.6584 - mae: 0.5650 - rmse: 0.8060

181/269 ━━━━━━━━━━━━━━━━━━━━ 28s 329ms/step - loss: 0.6574 - mae: 0.5645 - rmse: 0.8053

182/269 ━━━━━━━━━━━━━━━━━━━━ 28s 329ms/step - loss: 0.6564 - mae: 0.5639 - rmse: 0.8047

183/269 ━━━━━━━━━━━━━━━━━━━━ 28s 329ms/step - loss: 0.6554 - mae: 0.5634 - rmse: 0.8040

184/269 ━━━━━━━━━━━━━━━━━━━━ 27s 328ms/step - loss: 0.6543 - mae: 0.5629 - rmse: 0.8033

185/269 ━━━━━━━━━━━━━━━━━━━━ 27s 328ms/step - loss: 0.6533 - mae: 0.5623 - rmse: 0.8026

186/269 ━━━━━━━━━━━━━━━━━━━━ 27s 327ms/step - loss: 0.6523 - mae: 0.5618 - rmse: 0.8020

187/269 ━━━━━━━━━━━━━━━━━━━━ 26s 327ms/step - loss: 0.6512 - mae: 0.5612 - rmse: 0.8013

188/269 ━━━━━━━━━━━━━━━━━━━━ 26s 327ms/step - loss: 0.6502 - mae: 0.5607 - rmse: 0.8006

189/269 ━━━━━━━━━━━━━━━━━━━━ 26s 327ms/step - loss: 0.6492 - mae: 0.5601 - rmse: 0.7999

190/269 ━━━━━━━━━━━━━━━━━━━━ 25s 326ms/step - loss: 0.6481 - mae: 0.5596 - rmse: 0.7992

191/269 ━━━━━━━━━━━━━━━━━━━━ 25s 326ms/step - loss: 0.6471 - mae: 0.5590 - rmse: 0.7986

192/269 ━━━━━━━━━━━━━━━━━━━━ 25s 326ms/step - loss: 0.6461 - mae: 0.5585 - rmse: 0.7979

193/269 ━━━━━━━━━━━━━━━━━━━━ 24s 326ms/step - loss: 0.6451 - mae: 0.5579 - rmse: 0.7972

194/269 ━━━━━━━━━━━━━━━━━━━━ 24s 325ms/step - loss: 0.6441 - mae: 0.5574 - rmse: 0.7965

195/269 ━━━━━━━━━━━━━━━━━━━━ 24s 325ms/step - loss: 0.6430 - mae: 0.5568 - rmse: 0.7959

196/269 ━━━━━━━━━━━━━━━━━━━━ 23s 324ms/step - loss: 0.6420 - mae: 0.5563 - rmse: 0.7952

197/269 ━━━━━━━━━━━━━━━━━━━━ 23s 324ms/step - loss: 0.6410 - mae: 0.5558 - rmse: 0.7945

198/269 ━━━━━━━━━━━━━━━━━━━━ 22s 324ms/step - loss: 0.6400 - mae: 0.5552 - rmse: 0.7938

199/269 ━━━━━━━━━━━━━━━━━━━━ 22s 324ms/step - loss: 0.6390 - mae: 0.5547 - rmse: 0.7932

200/269 ━━━━━━━━━━━━━━━━━━━━ 22s 323ms/step - loss: 0.6380 - mae: 0.5541 - rmse: 0.7925

201/269 ━━━━━━━━━━━━━━━━━━━━ 21s 323ms/step - loss: 0.6370 - mae: 0.5536 - rmse: 0.7918

202/269 ━━━━━━━━━━━━━━━━━━━━ 21s 323ms/step - loss: 0.6360 - mae: 0.5531 - rmse: 0.7912

203/269 ━━━━━━━━━━━━━━━━━━━━ 21s 323ms/step - loss: 0.6350 - mae: 0.5525 - rmse: 0.7905

204/269 ━━━━━━━━━━━━━━━━━━━━ 20s 323ms/step - loss: 0.6341 - mae: 0.5520 - rmse: 0.7899

205/269 ━━━━━━━━━━━━━━━━━━━━ 20s 323ms/step - loss: 0.6331 - mae: 0.5515 - rmse: 0.7892

206/269 ━━━━━━━━━━━━━━━━━━━━ 20s 323ms/step - loss: 0.6322 - mae: 0.5510 - rmse: 0.7886

207/269 ━━━━━━━━━━━━━━━━━━━━ 20s 323ms/step - loss: 0.6312 - mae: 0.5505 - rmse: 0.7880

208/269 ━━━━━━━━━━━━━━━━━━━━ 19s 323ms/step - loss: 0.6302 - mae: 0.5499 - rmse: 0.7873

209/269 ━━━━━━━━━━━━━━━━━━━━ 19s 323ms/step - loss: 0.6293 - mae: 0.5494 - rmse: 0.7867

210/269 ━━━━━━━━━━━━━━━━━━━━ 19s 322ms/step - loss: 0.6283 - mae: 0.5489 - rmse: 0.7860

211/269 ━━━━━━━━━━━━━━━━━━━━ 18s 322ms/step - loss: 0.6274 - mae: 0.5484 - rmse: 0.7854

212/269 ━━━━━━━━━━━━━━━━━━━━ 18s 322ms/step - loss: 0.6264 - mae: 0.5479 - rmse: 0.7848

213/269 ━━━━━━━━━━━━━━━━━━━━ 18s 322ms/step - loss: 0.6255 - mae: 0.5474 - rmse: 0.7841

214/269 ━━━━━━━━━━━━━━━━━━━━ 17s 322ms/step - loss: 0.6246 - mae: 0.5469 - rmse: 0.7835

215/269 ━━━━━━━━━━━━━━━━━━━━ 17s 321ms/step - loss: 0.6236 - mae: 0.5464 - rmse: 0.7829

216/269 ━━━━━━━━━━━━━━━━━━━━ 17s 321ms/step - loss: 0.6227 - mae: 0.5459 - rmse: 0.7822

217/269 ━━━━━━━━━━━━━━━━━━━━ 16s 321ms/step - loss: 0.6218 - mae: 0.5454 - rmse: 0.7816

218/269 ━━━━━━━━━━━━━━━━━━━━ 16s 321ms/step - loss: 0.6208 - mae: 0.5448 - rmse: 0.7810

219/269 ━━━━━━━━━━━━━━━━━━━━ 16s 321ms/step - loss: 0.6199 - mae: 0.5443 - rmse: 0.7803

220/269 ━━━━━━━━━━━━━━━━━━━━ 15s 321ms/step - loss: 0.6190 - mae: 0.5438 - rmse: 0.7797

221/269 ━━━━━━━━━━━━━━━━━━━━ 15s 321ms/step - loss: 0.6180 - mae: 0.5433 - rmse: 0.7791

222/269 ━━━━━━━━━━━━━━━━━━━━ 15s 320ms/step - loss: 0.6171 - mae: 0.5428 - rmse: 0.7785

223/269 ━━━━━━━━━━━━━━━━━━━━ 14s 320ms/step - loss: 0.6162 - mae: 0.5423 - rmse: 0.7778

224/269 ━━━━━━━━━━━━━━━━━━━━ 14s 320ms/step - loss: 0.6153 - mae: 0.5418 - rmse: 0.7772

225/269 ━━━━━━━━━━━━━━━━━━━━ 14s 319ms/step - loss: 0.6144 - mae: 0.5413 - rmse: 0.7766

226/269 ━━━━━━━━━━━━━━━━━━━━ 13s 319ms/step - loss: 0.6134 - mae: 0.5408 - rmse: 0.7760

227/269 ━━━━━━━━━━━━━━━━━━━━ 13s 319ms/step - loss: 0.6125 - mae: 0.5403 - rmse: 0.7753

228/269 ━━━━━━━━━━━━━━━━━━━━ 13s 319ms/step - loss: 0.6116 - mae: 0.5398 - rmse: 0.7747

229/269 ━━━━━━━━━━━━━━━━━━━━ 12s 319ms/step - loss: 0.6107 - mae: 0.5393 - rmse: 0.7741

230/269 ━━━━━━━━━━━━━━━━━━━━ 12s 319ms/step - loss: 0.6098 - mae: 0.5388 - rmse: 0.7734

231/269 ━━━━━━━━━━━━━━━━━━━━ 12s 318ms/step - loss: 0.6088 - mae: 0.5383 - rmse: 0.7728

232/269 ━━━━━━━━━━━━━━━━━━━━ 11s 318ms/step - loss: 0.6079 - mae: 0.5378 - rmse: 0.7722

233/269 ━━━━━━━━━━━━━━━━━━━━ 11s 318ms/step - loss: 0.6070 - mae: 0.5373 - rmse: 0.7716

234/269 ━━━━━━━━━━━━━━━━━━━━ 11s 318ms/step - loss: 0.6061 - mae: 0.5368 - rmse: 0.7709

235/269 ━━━━━━━━━━━━━━━━━━━━ 10s 318ms/step - loss: 0.6052 - mae: 0.5363 - rmse: 0.7703

236/269 ━━━━━━━━━━━━━━━━━━━━ 10s 318ms/step - loss: 0.6043 - mae: 0.5358 - rmse: 0.7697

237/269 ━━━━━━━━━━━━━━━━━━━━ 10s 318ms/step - loss: 0.6034 - mae: 0.5353 - rmse: 0.7691

238/269 ━━━━━━━━━━━━━━━━━━━━ 9s 318ms/step - loss: 0.6025 - mae: 0.5348 - rmse: 0.7685

239/269 ━━━━━━━━━━━━━━━━━━━━ 9s 318ms/step - loss: 0.6016 - mae: 0.5343 - rmse: 0.7678

240/269 ━━━━━━━━━━━━━━━━━━━━ 9s 319ms/step - loss: 0.6007 - mae: 0.5338 - rmse: 0.7672

241/269 ━━━━━━━━━━━━━━━━━━━━ 8s 320ms/step - loss: 0.5999 - mae: 0.5333 - rmse: 0.7666

242/269 ━━━━━━━━━━━━━━━━━━━━ 8s 320ms/step - loss: 0.5990 - mae: 0.5328 - rmse: 0.7660

243/269 ━━━━━━━━━━━━━━━━━━━━ 8s 320ms/step - loss: 0.5981 - mae: 0.5323 - rmse: 0.7654

244/269 ━━━━━━━━━━━━━━━━━━━━ 8s 320ms/step - loss: 0.5972 - mae: 0.5318 - rmse: 0.7648

245/269 ━━━━━━━━━━━━━━━━━━━━ 7s 320ms/step - loss: 0.5964 - mae: 0.5314 - rmse: 0.7642

246/269 ━━━━━━━━━━━━━━━━━━━━ 7s 320ms/step - loss: 0.5955 - mae: 0.5309 - rmse: 0.7636

247/269 ━━━━━━━━━━━━━━━━━━━━ 7s 321ms/step - loss: 0.5946 - mae: 0.5304 - rmse: 0.7630

248/269 ━━━━━━━━━━━━━━━━━━━━ 6s 321ms/step - loss: 0.5938 - mae: 0.5299 - rmse: 0.7624

249/269 ━━━━━━━━━━━━━━━━━━━━ 6s 322ms/step - loss: 0.5929 - mae: 0.5294 - rmse: 0.7618

250/269 ━━━━━━━━━━━━━━━━━━━━ 6s 322ms/step - loss: 0.5920 - mae: 0.5290 - rmse: 0.7612

251/269 ━━━━━━━━━━━━━━━━━━━━ 5s 323ms/step - loss: 0.5912 - mae: 0.5285 - rmse: 0.7606

252/269 ━━━━━━━━━━━━━━━━━━━━ 5s 324ms/step - loss: 0.5903 - mae: 0.5280 - rmse: 0.7600

253/269 ━━━━━━━━━━━━━━━━━━━━ 5s 324ms/step - loss: 0.5895 - mae: 0.5276 - rmse: 0.7594

254/269 ━━━━━━━━━━━━━━━━━━━━ 4s 324ms/step - loss: 0.5886 - mae: 0.5271 - rmse: 0.7588

255/269 ━━━━━━━━━━━━━━━━━━━━ 4s 324ms/step - loss: 0.5878 - mae: 0.5266 - rmse: 0.7582

256/269 ━━━━━━━━━━━━━━━━━━━━ 4s 325ms/step - loss: 0.5869 - mae: 0.5261 - rmse: 0.7576

257/269 ━━━━━━━━━━━━━━━━━━━━ 3s 324ms/step - loss: 0.5861 - mae: 0.5257 - rmse: 0.7570

258/269 ━━━━━━━━━━━━━━━━━━━━ 3s 324ms/step - loss: 0.5853 - mae: 0.5252 - rmse: 0.7564

259/269 ━━━━━━━━━━━━━━━━━━━━ 3s 324ms/step - loss: 0.5844 - mae: 0.5247 - rmse: 0.7558

260/269 ━━━━━━━━━━━━━━━━━━━━ 2s 324ms/step - loss: 0.5836 - mae: 0.5243 - rmse: 0.7552

261/269 ━━━━━━━━━━━━━━━━━━━━ 2s 324ms/step - loss: 0.5828 - mae: 0.5238 - rmse: 0.7547

262/269 ━━━━━━━━━━━━━━━━━━━━ 2s 324ms/step - loss: 0.5819 - mae: 0.5234 - rmse: 0.7541

263/269 ━━━━━━━━━━━━━━━━━━━━ 1s 324ms/step - loss: 0.5811 - mae: 0.5229 - rmse: 0.7535

264/269 ━━━━━━━━━━━━━━━━━━━━ 1s 323ms/step - loss: 0.5803 - mae: 0.5224 - rmse: 0.7529

265/269 ━━━━━━━━━━━━━━━━━━━━ 1s 323ms/step - loss: 0.5795 - mae: 0.5220 - rmse: 0.7523

266/269 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - loss: 0.5786 - mae: 0.5215 - rmse: 0.7518

267/269 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - loss: 0.5778 - mae: 0.5211 - rmse: 0.7512

268/269 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - loss: 0.5770 - mae: 0.5206 - rmse: 0.7506

269/269 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - loss: 0.5762 - mae: 0.5202 - rmse: 0.7500

Epoch 21: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

269/269 ━━━━━━━━━━━━━━━━━━━━ 94s 349ms/step - loss: 0.3601 - mae: 0.3993 - rmse: 0.5971 - val_loss: 0.7156 - val_mae: 0.5247 - val_rmse: 0.8438 - learning_rate: 5.0000e-04

In [8]:
def inverse_target_scale(values: np.ndarray) -> np.ndarray:
    return target_scaler.inverse_transform(values.reshape(-1, 1)).reshape(values.shape)

validation_predictions = np.clip(
    inverse_target_scale(model.predict(x_validation, batch_size=BATCH_SIZE, verbose=0)),
    0.0,
    None,
)
test_predictions = np.clip(
    inverse_target_scale(model.predict(x_test, batch_size=BATCH_SIZE, verbose=0)),
    0.0,
    None,
)

endpoint_frame = model_frame.iloc[endpoint_positions].copy()
endpoint_frame.index = np.arange(len(endpoint_frame))
endpoint_split = {
    name: pd.Series(mask, index=endpoint_frame.index)
    for name, mask in endpoint_split_masks.items()
}
predictions = pd.concat([
    prediction_frame(
        endpoint_frame, endpoint_split["validation"], validation_predictions,
        MODEL_NAME, "validation"
    ),
    prediction_frame(
        endpoint_frame, endpoint_split["test"], test_predictions,
        MODEL_NAME, "test"
    ),
], ignore_index=True)

joblib.dump(
    {
        "feature_scaler": feature_scaler,
        "target_scaler": target_scaler,
        "feature_columns": lstm_feature_columns,
        "sequence_length": SEQUENCE_LENGTH,
        "horizons": HORIZONS.tolist(),
    },
    CANDIDATES_DIR / "lstm_multihorizon_preprocessing.joblib",
)
by_horizon, by_city, summary = save_evaluation(MODEL_SLUG, predictions)
display(summary)
display(by_city)

,model,split,rows,mean_horizon_rmse_ug_m3,mean_horizon_mae_ug_m3,global_rmse_ug_m3,global_mae_ug_m3,global_r2,global_bias_ug_m3
0,LSTM,test,352296,15.259917,9.893819,15.336945,9.893819,0.619100,0.075982
1,LSTM,validation,352296,16.901673,10.503458,17.036844,10.503458,0.540826,-2.458232

,model,split,city,rows,rmse_ug_m3,mae_ug_m3,r2,bias_ug_m3
0,LSTM,test,Hà Nội,117432,23.280297,16.440091,0.459872,-5.091752
1,LSTM,test,TP.HCM,117432,10.799167,8.419504,0.260154,4.292298
2,LSTM,test,Đà Nẵng,117432,6.860860,4.821862,0.540253,1.027400
3,LSTM,validation,Hà Nội,117432,23.848374,15.331742,0.357905,-6.456247
4,LSTM,validation,TP.HCM,117432,14.492655,10.113979,0.355242,-1.556157
5,LSTM,validation,Đà Nẵng,117432,9.590631,6.064654,0.474401,0.637707

In [9]:
fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))
curve_pairs = [
    ("loss", "val_loss", "MSE loss"),
    ("rmse", "val_rmse", "RMSE chuẩn hóa"),
    ("mae", "val_mae", "MAE chuẩn hóa"),
]
for axis, (train_column, val_column, title) in zip(axes, curve_pairs):
    axis.plot(history_frame["epoch"], history_frame[train_column], label="Train")
    axis.plot(history_frame["epoch"], history_frame[val_column], label="Validation")
    axis.set_title(title)
    axis.set_xlabel("Epoch")
    axis.grid(alpha=0.2)
axes[0].legend()
plt.tight_layout()
plt.show()

C:\Users\nguyen\AppData\Local\Temp\ipykernel_25936\1675078938.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [10]:
test_curve = by_horizon.loc[by_horizon["split"].eq("test")]
axis = test_curve.plot(
    x="horizon", y=["rmse_ug_m3", "mae_ug_m3"], marker="o", figsize=(9, 4.5)
)
axis.set_xlabel("Chân trời dự báo (giờ)")
axis.set_ylabel("Sai số (µg/m³)")
axis.set_title("LSTM: sai số Test theo chân trời")
axis.grid(alpha=0.25)
plt.tight_layout()
plt.show()

C:\Users\nguyen\AppData\Local\Temp\ipykernel_25936\851945057.py:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [11]:
best_epoch = int(history_frame["val_loss"].idxmin() + 1)
val_summary = summary.loc[summary["split"].eq("validation")].iloc[0]
test_summary = summary.loc[summary["split"].eq("test")].iloc[0]
display(Markdown(
    f"**Nhận xét.** Validation loss nhỏ nhất tại epoch **{best_epoch}**. Validation "
    f"RMSE trung bình theo horizon là **{val_summary['mean_horizon_rmse_ug_m3']:.2f} "
    f"µg/m³**, còn Test RMSE là **{test_summary['mean_horizon_rmse_ug_m3']:.2f} "
    "µg/m³**. Khoảng cách giữa đường Train và Validation cho biết mức overfitting; "
    "Early Stopping giữ lại trọng số tại epoch có Validation loss tốt nhất."
))

**Nhận xét.** Validation loss nhỏ nhất tại epoch **11**. Validation RMSE trung bình theo horizon là **16.90 µg/m³**, còn Test RMSE là **15.26 µg/m³**. Khoảng cách giữa đường Train và Validation cho biết mức overfitting; Early Stopping giữ lại trọng số tại epoch có Validation loss tốt nhất.